### ISSUE TITLE
Переименовать репозиторий и сделать отсылку к лицензии

### ISSUE THREAD

**Issue by allustin** [Pr-Mex/vanessa-automation#1]
Если решил отделится

* переименуй репозиторий пожалуйста
* измени чат Гитера на свой
* сделай отсылку к основному продукту https://github.com/silverbulleters/add 
* на новый код добавь свою персональную лицензию

Тогда все будет прозрачно и спокойно

**Comment by artbear** [comment]
- [ ] Еще ссылки на наши лицензии, пожалуйста, не забудь

**Comment by kuzyara** [comment]
- Зачем переименовывать то, что является той же vb, но только c не оставленной поддержкой?
- Все проблемы "старой" vb обсуждались в одном месте. Хочешь избавиться от старой части сообщества? Тогда и чат гиттер подпиши deprecated.
- А "ваши" лицензии вообще никому не сдались.

**Comment by Pr-Mex** [comment]
Готово.

**Comment by Pr-Mex** [comment]
В исходной лицензии ничего не написано про использование слов Vanessa, Automation, Behavior (и т.п.) по отдельности.
https://github.com/silverbulleters/vanessa-behavior/blob/develop/license/LICENSE.txt

**Comment by allustin** [comment]
Дальше по репозиторию - наименование используется не только в названии репозитория, но и в наименовании обработки: их также следует переименовать

Нужно переименовать - https://github.com/Pr-Mex/vanessa-automation/tree/develop/VanessaBehavior

А также https://github.com/Pr-Mex/vanessa-automation/blob/develop/VanessaBehavior.xml

В документации убрать https://github.com/Pr-Mex/vanessa-automation/blob/develop/F.A.Q.MD

**Comment by allustin** [comment]
```
Ни название продукта "Vanessa Behavior", ни имена его разработчиков не могут быть использованы
в качестве поддержки или продвижения продуктов, основанных на этом ПО без предварительного письменного разрешения.
```

> в качестве поддержки или продвижения продуктов, основанных на этом ПО без предварительного письменного разрешения.

У тебя нет такого письменного разрешения ни от меня, ни от silverbulleters - даже в рамках твоей активности в СППР. Поэтому у тебя варианта два - переименовываться до конца либо договариваться до письменного разрешения.

Буква лицензии она такова... Я уже однажды это проходил с Артуром - пройдем еще раз. Схитрить не получится - придется договариваться или дело дойдет до арбитража github.

**Comment by nixel2007** [comment]
> Схитрить не получится - придется договариваться или дело дойдет до арбитража github.

то-то я смотрю в add появился NOTICE с vanessa-automation.license.txt
хотя о чем это я, там даже нет NOTICE на саму vanessa-behavior.

**Comment by kuzyara** [comment]
А с Артуром что там за история?

**Comment by artbear** [comment]
NOTICE на саму vanessa-behavior забыли.я добавлю, конечно

**Comment by freddy121** [comment]
@Pr-Mex судом гитхабовым будешь прикован навечно на поселение в хранилище
кодеревью сильвербаллетеру делать 7 лет без права пуллреквестов ;)

**Comment by Pr-Mex** [comment]
"Схитрить не получится" ))))))))
Парни. @allustin  @artbear 
Вы бы хоть когда копируете мои изменения из VA - указывали это )))
Вот, пример, когда вы копируете из VA. В VB1 - этого нет.
https://github.com/silverbulleters/add/commit/92e4ea0766edd869c188289887e4edc64b731e24

А то, как-то с лицензионной чистотой не очень получается )))

**Comment by Pr-Mex** [comment]
Вот эти же изменения в VA
https://github.com/Pr-Mex/vanessa-automation/commit/f867270deea80cafb0722c1ca31133d8443e13e1#diff-66a5f88da67c445c3237bacb184a96d4

**Comment by nixel2007** [comment]
прям вижу, как мозговые волны Лёни и Артура синхронизировались и даже переводы строки в фича файлах сделали в одинаковых местах. И название коммита, конечно же, абсолютная случайность.

**Comment by artbear** [comment]
Чтобы вы не съезжали с темы, я откачу эти изменения. Не проблема.

**Comment by artbear** [comment]
Откатил.

**Comment by Pr-Mex** [comment]
> @Pr-Mex я решаю конкретные проблемы, которые выявлены еще в исходной VB и в add.

Я понимаю, какую ты проблему решаешь )))
Просто при копипасте надо указывать источник.
Причём лицензия VA не запрещает тебе копировать. В ней прямо указано, что это можно делать.
Соблюдая лицензию, конечно.

**Comment by artbear** [comment]
Давай последовательно решать с изменением наименования твоего репозитория и имени обработки.

**Comment by Pr-Mex** [comment]
>@Pr-Mex ты не имеешь права использовать vanessa в наименовании - этот репозиторий не входит в Vanessa Stack это первое

Не понятна связь. 
Лицензия VB1 не требует проверки чего-либо на вхождение в Vanessa Stack, Vanessa Pack, Vanessa конгломерат и т.п.

> Второе сводный продукт называется vanessa-automation-driven-development - наименование которое придумали в Пуле во время архитектутурных разборов в рамках репозитория vanessa-stack. - поэтому твое наименование это плагиат.

Тогда вы можете переименовать проект ADD в VADD )))
Также даже лучше звучит )))))))))))))))))))))))

**Comment by Pr-Mex** [comment]
>Дальше по репозиторию - наименование используется не только в названии репозитория, но и в наименовании обработки: их также следует переименовать

С этим согласен. Epf я переименую.

**Comment by Pr-Mex** [comment]
>У тебя нет такого письменного разрешения ни от меня, ни от silverbulleters - даже в рамках твоей активности в СППР. Поэтому у тебя варианта два - переименовываться до конца либо договариваться до письменного разрешения.

О каком письменном разрешении идёт речь? На что? 
Лицензия у VB1 и у VA уже очень сильно разрешительная.

**Comment by artbear** [comment]
Леня, если уж решил отделиться, сделай все по-честному.

от зря ты хочешь использовать уже устоявшийся термин "Ванесса/Vanessa" :(

Он придуман не тобой, а Валерой Агеевым (светлая ему память) и от него для Пули получено разрешение на использование. Лет 5 назад примерно.

этот термин уже жестко привязан к разным продуктам от Пули.
Термин максимально продвинут различными средствами - продукты, конференции, обучение, хакатоны и т.п.
Есть различные макеты для обозначения логотипов Ванессы.
И т.п. и т.д.

Пожалуйста, если решил отделиться, начни с собственного наименования, а не используй для продвижения своего продукта чужие, честно заработанные !

**Comment by Pr-Mex** [comment]
Артур, я три года вложил в развитие Vanessa-Behavior.
Это продукт по большей части написан мной. Что хорошо видно тут.
https://github.com/silverbulleters/vanessa-behavior/graphs/contributors

Меня бы устроил вариант - просто сохранить старое название Vanessa-Behavior.
Вы же выступаете против этого.

Логотип с бабочками мне не интересен.
Также меня не интересуют всякие Ванесса тфс, Ванесса аджалер и прочее. Я эти проекты не разрабатывал.

На мой взгляд, термин Ванесса жёстче всего привязан именно к VB и в меньшей степени к другим проектам.
Это ИМХО.

Итого, мне видится, что я в праве использовать слово Ванесса, т.к. я тоже много в него вложил и продвигал.
Я не могу сказать, что для меня этот термин - "чужой".

**Comment by artbear** [comment]
Твои мысли понятны.
Конечно, термин Ванесса для тебя не "чужой" и никто твоего участия ни в коей мере не умоляет.

Но, к сожалению, термин Ванесса привязан не только к ВБ, а и к другим, упомянутой тобой продуктам - `ванесса-раннер, ванесса-бутстрап, ванесса-сервисы, ванесса-бдд-едитор и еще нескольким`.

И термин `Ванесса` продвигался не только как отдельная ВБ, но и как остальные сервисы за авторством Пули и в ее организации.

Сейчас попытка использования тобой термина "Ванесса" все-таки выглядит как желание продвижения за чужой счет и желание максимально сохранить аудиторию продукта подобным образом.

Некрасиво и не очень честно :(

Напоминаю, что ты сам выбрал путь разделения/отделения и а у этого действия есть свои последствия :(

**Comment by alehinsasha** [comment]
> Сейчас попытка использования тобой термина "Ванесса" все-таки выглядит как желание продвижения за чужой счет и желание максимально сохранить аудиторию продукта подобным образом.

Выглядит <> Является

> Некрасиво и не очень честно :(
> 
> Напоминаю, что ты сам выбрал путь разделения/отделения и а у этого действия есть свои последствия :(

Это как раз и умаляет участие Леонида(

Думаю обсуждение не имеет смысла продолжать без скриншотов на текст доказывающий нарушение.

@artbear дай, пожалуйста, скриншоты)

**Comment by artbear** [comment]
> Это как раз и умаляет участие Леонида(

Верну тебе твои же слова -`Выглядит <> Является`. 
Я все уже написал выше.

**Comment by Pr-Mex** [comment]
>Сейчас попытка использования тобой термина "Ванесса" все-таки выглядит как желание продвижения за чужой счет и желание максимально сохранить аудиторию продукта подобным образом.

Мне это "видится" по-другому.

**Comment by Pr-Mex** [comment]
@allustin @artbear 
Если вы считаете, что где-то нарушена лицензия - приводите, пожалуйста, ссылки, скриншоты и т.д. на конкретные, как вы считаете, нарушения.
Буду смотреть.

Иначе разговор не предметный.

**Comment by hawk911** [comment]
![Как я это вижу ](https://cs.pikabu.ru/images/big_size_comm/2013-03_3/13629724119866.jpg)

**Comment by kuzyara** [comment]
![images](https://user-images.githubusercontent.com/2604430/40724777-72af734a-6454-11e8-9724-4c5e5c698e3b.jpg)

**Comment by Pr-Mex** [comment]
Ну а теперь меня удалили из истории коммитов репо VB1.
https://github.com/silverbulleters/vanessa-behavior/graphs/contributors

Прозрачность опенсорса вышла на новую высоту )))

![image](https://user-images.githubusercontent.com/8627416/40873173-3113cfc8-6664-11e8-9833-d8c0893a851f.png)

**Comment by allustin** [comment]
> Это продукт по большей части написан мной

где-то я уже подобную формулировку слышал - @Pr-Mex помнишь где ? 

> Меня бы устроил вариант

нас бы устроил вариант если бы ты не динамил 4-рех человек с сентября прошлого года. Но теперь ты нам потерянное время не возместишь и даже как-то не видно даже желания.

> На мой взгляд, термин Ванесса жёстче всего привязан именно

Твой взгляд тут не важен. Изобретал я на основе идеи Валеры Агеева. Я тебе разрешение **НЕ ДАЮ** на использование. Хочешь использовать - напомню что ты в курсе моего телефона и телефона @yasplush: позвонить всегда можно. 

> что я в праве использовать слово Ванесса, т.к. я тоже много в него вложил и продвигал.

Нет - ты не в праве. В лицензии указана компания "Серебряная Пуля" - права принадлежат ей, а не каким то там персоналиям Алексею, Артуру, Васе, Пете и Коле, Леониду.

Подытожим для всехКоманда "Серебряная Пуля" будет и дальше следовать принципу что архитекурные обсуждения будут проводится в горизонтальной стру публично (причем я сделаю это именно публично).

----

На данный момент команда "Серебряная Пуля" воспринимает сложившуюся ситуация как попытку мягкого давления со стороны компании в которой работает @Pr-Mex 
Блокировка развития продуктов для тестирования в нужном направлении длилась с сентября 2017 года.

Команда "Серебряная Пуля" будет и дальше защищать продукты созданные сообществом авторов от попытки присвоить их себе персонально или заблокировать развитие.

**Comment by allustin** [comment]
> Прозрачность опенсорса вышла на новую высоту )))

@Pr-Mex так ведет себя Github Server после отключения участника от организации - к нему все претензии. Я не являюсь автором сервера gitHub и не могу на это влиять. 

----

@Pr-Mex я повторюсь еще раз - ты решил идти дальше один в угоду двухбуквенной компании, должен был предусматривать последствия. Ты думал будет как-то по другому ? 

---

Я тебе напомню - ADD репозиторий для тебя открыт: на правах администратора если пожелаешь. Единственное что тебе нужно это принять тот факт, что ты не один главный - а нас несколько людей. 

Из изменений в ADD

* объединение кодовой базы BDD&TDD по заветам Валеры Агеева (RIP)
* порядок разработки git-flow и полностью на исходниках по процессу придуманному Евгением Сосна
* разделение на плагины кодовой базы - то есть общего модуля на 25000 строк больше не будет никогда.

Лично я считаю что не все еще потеряно и конфликт можно убрать - но мы действий со своей стороны предпринимать в этом направлении уже не будем: @Pr-Mex решение за тобой

если собираешься делать все сам и один все также:

* переименовывайся - префикс vanessa ит.д.

если все таки в тебе не совсем победил "кровавый ынтырпрайз" с их мутной политикой

* добро пожаловать в add как равноправный администратор

**Comment by freddy121** [comment]
Основатели крафтовой шотландской пивоварни «BrewDog» Джеймс Уотт и Мартин Дикки заявили, что меняют свои имена на Элвис Уотт и Элвис Дикки, а фото с соответствующими бумагами в адрес Центрального офиса Главного Суда Англии и Уэльса опубликовали в блоге компании.
С очередным юродством «панки» выступили в ответ на послания адвокатов Elvis Presley Estate с запретом использования имени Элвис в названии сорта Elvis Jiuce.
Сделали они это в ответ на требование наследников Элвиса Пресли прекратить использовать имя короля рок-н-ролла в названии пива – «Elvis Juice» IPA с грейпфрутами и кровавыми апельсинами.
"Теперь мы сами можем засудить мистера Пресли за использование наших имен на всех его пластинках без нашего письменного разрешения" — заявил Элвис Уотт.
![image](https://user-images.githubusercontent.com/11014844/40878252-e56bf02c-6696-11e8-827a-a3ba0debfa66.png)

**Comment by Pr-Mex** [comment]
@freddy121 
Зачёт!

**Comment by Pr-Mex** [comment]
>@Pr-Mex так ведет себя Github Server после отключения участника от организации - к нему все претензии. Я не являюсь автором сервера gitHub и не могу на это влиять.

Так уже было с @alehinsasha и с @nixel2007 
![image](https://user-images.githubusercontent.com/8627416/40878928-20184888-66a1-11e8-8784-25da72984765.png)

**Comment by Pr-Mex** [comment]
>@Pr-Mex я повторюсь еще раз - ты решил идти дальше один в угоду двухбуквенной компании, должен был предусматривать последствия. Ты думал будет как-то по другому ?

Я представляю только себя и говорю только от своего имени.

**Comment by Pr-Mex** [comment]
>где-то я уже подобную формулировку слышал - @Pr-Mex помнишь где ?

@allustin 
Я не понял о чём ты.  Я его реально написал по большей части. Что не так?
Тут это всё ещё видно не смотря на затирание истории )))
https://github.com/kuzyara/vanessa-behavior/graphs/contributors
З.Ы. I love github!

**Comment by Pr-Mex** [comment]
>нас бы устроил вариант если бы ты не динамил 4-рех человек с сентября прошлого года. Но теперь ты нам потерянное время не возместишь и даже как-то не видно даже желания.

@allustin 
Это может показаться странным, но я сам принимаю решения.
То что вы предлагали - мне не нравилось. Сори конечно, но я не обязан принимать чужие решения и реализации, если они мне не нравятся, не устраивают, не актуальны для меня и т.д.

**Comment by Pr-Mex** [comment]
@allustin 
Интересно, этот проект тоже что-то нарушает?
http://www.vanessa-sharp.ru/quickstart.html

**Comment by Pr-Mex** [comment]
>На данный момент команда "Серебряная Пуля" воспринимает сложившуюся ситуация как попытку мягкого давления со стороны компании в которой работает @Pr-Mex
Блокировка развития продуктов для тестирования в нужном направлении длилась с сентября 2017 года.

@allustin 
Я представляю себя. На мой взгляд, с сентября 2017 года проект отлично развивался.
Я решал те задачи, которые считал перевоочередными.
Я не понимаю как кто-то может заблокировать развитие opensource продукта в каком-либо направлении.
Есть же механизм форков.
Например, @allustin не нравится как я развиваю проект - и он создаёт ADD.
Или можно как я, когда мне не понравилось в каком направлении пуля решила развивать проект, я создал свой форк и его развиваю.

Вот, кстати, краткий перечень того что было сделано только с февраля 2018 по май 2018
https://github.com/kuzyara/vanessa-behavior/blob/develop/history.MD

**Comment by Pr-Mex** [comment]
>Команда "Серебряная Пуля" будет и дальше защищать продукты созданные сообществом авторов от попытки присвоить их себе персонально или заблокировать развитие.

@allustin 
Ну да. Для этого надо против "автора" использовать баны, затыкание ртов, угрозы.
Грустно всё это...

**Comment by Pr-Mex** [comment]
>Я тебе напомню - ADD репозиторий для тебя открыт: на правах администратора если пожелаешь. Единственное что тебе нужно это принять тот факт, что ты не один главный - а нас несколько людей.

@allustin 
Именно из-за того как был создан проект ADD - я в нём не захотел участвовать.

**Comment by Pr-Mex** [comment]
>Лично я считаю что не все еще потеряно и конфликт можно убрать - но мы действий со своей стороны предпринимать в этом направлении уже не будем: @Pr-Mex решение за тобой

>если собираешься делать все сам и один все также:

>переименовывайся - префикс vanessa ит.д.
если все таки в тебе не совсем победил "кровавый ынтырпрайз" с их мутной политикой

Решение использовать слово ванесса - моё. Оно мне нравится.
Слово automation взято, т.к. продукт может использоваться более широко. Например для автоматизации своей собственной деятельности.
Если кто-то считает что слово "Ванесса" именно "принадлежит" кому-то, тогда для этого надо привести хоть какие-то основания.

>добро пожаловать в add как равноправный администратор


Вряд ли я впредь захочу отдать права на администрирование проекта, в который я хочу вкладывать свои силы, людям, которые банят тех, кто имеет другое мнение.

**Comment by Pr-Mex** [comment]
@allustin 
Мне интересно, если кто-то захочет назвать свою дочь Vanessa - ему надо будет присылать письменное  уведомление?

**Comment by Pr-Mex** [comment]
@allustin @artbear 
Парни. Дружеский совет.
Вы учтите, что вы создаёте опасный прецедент.
Когда активного участника проекта, банят, удаляют из истории, и т.д.

Вы ведь не только от своего имени говорите. Вы для большинства - это и есть "Серебряная пуля" как организация.
Многие ли захотят участвовать в проектах пули после такого?

**Comment by allustin** [comment]
@Pr-Mex еще раз повторюсь - твое поведение полностью повторяет поведение другого человека 2 года назад, собственно последствия одинаковые в данном случае и в том. Так что не обманывай ни себя ни других - это не прецедент. https://github.com/silverbulleters/vanessa-behavior/issues/239

Что касается использования имён - то по указанному issue уже было обсуддение

https://github.com/silverbulleters/vanessa-behavior/blob/e89c1f01beb824dd9ee4fede8c88ecf98ea922c4/CONTRIBUTING.md#bsd-v3-license

```
BSD v3 License

наша лицензия поощеряет коллективное участие в разработке 
всего стэка продуктов Vanessa Stack, 
однако не поощеряет использовать брендов (с) SilverBulleters, 
vanessa-stack, vanessa-behavior и остальных 
для развития своих неофициальных имлементаций поэтому:

используйте, дорабатывайте через концепцию fork и pull request 
если вы хотите создать свой продукт на основе это разрешено 
и не противоречит лицензии BSD v3
однако если вы хотите использовать для рекламирования 
и продвижения своего продукта бренды "SilverBulleters" или "Vanessa Behavior" 
вам необходимо получить у нас разрешение на это написав на адрес team@silverbulleters.org или создать Issue на GitHub

```

и самое важно 

```
поэтому интернет маркетологов просим быть осторожней при использовании символики Vanessa и SilverBulleters
```

Публичную дискуссию предлагаю закончить - скайпы и телефоны у всех есть.

**Comment by Pr-Mex** [comment]
>@Pr-Mex еще раз повторюсь - твое поведение полностью повторяет поведение другого человека 2 года назад, собственно последствия одинаковые в данном случае и в том. Так что не обманывай ни себя ни других - это не прецедент. silverbulleters/vanessa-behavior#239

@allustin
Там вообще не про это.
Там нет банов, удаления истории коммитов, угроз арбитража github и подобного.

**Comment by Pr-Mex** [comment]
>Что касается использования имён - то по указанному issue уже было обсуддение

>https://github.com/silverbulleters/vanessa-behavior/blob/e89c1f01beb824dd9ee4fede8c88ecf98ea922c4/CONTRIBUTING.md#bsd-v3-license

>BSD v3 License

>наша лицензия поощеряет коллективное участие в разработке 
>всего стэка продуктов Vanessa Stack, 
>однако не поощеряет использовать брендов (с) SilverBulleters, 
>vanessa-stack, vanessa-behavior и остальных 
>для развития своих неофициальных имлементаций поэтому:

>используйте, дорабатывайте через концепцию fork и pull request 
>если вы хотите создать свой продукт на основе это разрешено 
>и не противоречит лицензии BSD v3
>однако если вы хотите использовать для рекламирования 
>и продвижения своего продукта бренды "SilverBulleters" или "Vanessa Behavior" 
>вам необходимо получить у нас разрешение на это написав на адрес team@silverbulleters.org или >создать Issue на GitHub

>и самое важно

>поэтому интернет маркетологов просим быть осторожней при использовании символики >Vanessa и SilverBulleters

@allustin
Обрати внимание.
>если вы хотите создать свой продукт на основе это разрешено 
>и не противоречит лицензии BSD v3

Лицензии BSD v3 противоречия нет.

"SilverBulleters" - не используется.
"Vanessa Behavior" - тоже.

**Comment by kuzyara** [comment]
> _- традиционно, к созданию веток разработчики проектов с открытым исходным кодом относятся негативно - (c) wiki_

[Why Open Source Software / Free Software (OSS/FS, FLOSS, or FOSS)? Look at the Numbers!](https://www.dwheeler.com/oss_fs_why.html#forking)

> Форк (англ. fork — развилка, вилка) или ответвление — использование кодовой базы программного проекта в качестве старта для другого. 

> Причины форкинга могут быть различны: от реализации чего-то экспериментального; портирования на новые ниши и платформы; вплоть до __**спасения проекта, если основной проект по разным причинам **заморожен****__, и его развитие под текущими условиями невозможно или представляется невозможным, а также если разработчик не хочет развивать основной проект.
