### ISSUE TITLE
Ошибка в шаге И таблица "" содержит строки

### ISSUE THREAD

**Issue by astrizhachuk** [Pr-Mex/vanessa-automation#1000]
1. Получено состояние формы через VA
2. Удалена колонка "Дата"
2. Шаг `И таблица "EventsHistory" стала равной`
3. Замена его на `И таблица "EventsHistory" содержит строки` приводит к ошибке
https://github.com/astrizhachuk/gitlab-services/commit/44497e662d39188bd89ece2b9bd142af507ca3db
![image](https://user-images.githubusercontent.com/25724999/96869550-47502d80-1478-11eb-8967-f44d675d6555.png)

**Comment by astrizhachuk** [comment]
P.S. Шаг И таблица "EventsHistory" стала равной работает не стабильно: то все хорошо, то не может найти таблицу. При запуске шага из редактора F11 шаг проходит.

**Comment by Pr-Mex** [comment]
@astrizhachuk 
Проверь, плиз, на VA из develop. Мне кажется я это уже решал.

**Comment by astrizhachuk** [comment]
> @astrizhachuk
> Проверь, плиз, на VA из develop. Мне кажется я это уже решал.

Проверил на последнем develop, проблема повторяется.

**Comment by Pr-Mex** [comment]
@astrizhachuk 
Где взять сценарий и базу для воспроизведения?

**Comment by astrizhachuk** [comment]
@Pr-Mex 
Все можно получить прям из репы, т.к. все в докере. Полное описание девелоперской среды в readme проекта. Тут кратко шаги, т.к. до автодеплоя еще руки не дошли:

1. Переходим в последний commit65d4436 https://github.com/astrizhachuk/gitlab-services/tree/65d44367f590f88b6adeac43d20d602d8662df61
2. Заполняем ENV и hosts (см. https://github.com/astrizhachuk/gitlab-services/tree/65d44367f590f88b6adeac43d20d602d8662df61)
3. В корне проекта `docker-compose up -d --build`
4. Подрубаемся через VNC View к localhost:5900 к поднятому клиенту в контейнере и регаем новую базу (или с хостовой машины если есть оснастка)
![image](https://user-images.githubusercontent.com/25724999/96961757-01de3f80-150e-11eb-9e2e-4630023b1601.png)
5. Загружаем эталон для текущего commit выполнив команду  `docker exec gitlab-services_client_1 bash -c "/opt/1C/v8.3/x86_64/1cv8 DESIGNER /S 'srv\gitlabServices' /RestoreIB /home/usr1cv8/empty.dt /DisableStartupDialogs"`
6. Гасим лишние службы, так как для тестов они не нужны `docker-compose stop gitlab gitlab-services_client_1 gitlab-services_receiver_1`
7. Все. Должно работать. Srvr="srv";Ref="gitlabServices";

**Comment by Pr-Mex** [comment]
А, понял )
Но лучше упростить сценарий для того, кто будет воспроизводить ошибку )
Дай, плиз, dt и фичу.

**Comment by astrizhachuk** [comment]
https://github.com/astrizhachuk/gitlab-services/blob/patch-6/features/Обработчики%20событий/История%20событий.feature
https://github.com/astrizhachuk/gitlab-services/blob/patch-6/test/empty.dt

Куда еще проще)
В сценарии используются мок сервер и всякие технологии, так что без поднятой среды повторить точь-в-точь не получится, а в докере прям как на моей машине будет.

**Comment by Pr-Mex** [comment]
@astrizhachuk 
При регистрации ошибки лучше передавать набор артефактов, который будет максимально просто воспроизвести проверяющему. Причём, желательно, чтобы было как можно меньше зависимостей от особенностей окружения.
Я когда регистрирую ошибки стараюсь с нуля создать простой пример, который за пару шагов воспроизводит проблему.

**Comment by astrizhachuk** [comment]
@Pr-Mex 
Так, поумничать с докером не удалось, поэтому вот новый dt  и простой тест с повторением проблемы:
https://github.com/astrizhachuk/gitlab-services/blob/f8790d9a32e81d3a738bfdba88e0e7a05bc077b7/features/Обработчики%20событий/PrMex.feature
https://github.com/astrizhachuk/gitlab-services/blob/f8790d9a32e81d3a738bfdba88e0e7a05bc077b7/test/empty.dt

**Comment by Pr-Mex** [comment]
@astrizhachuk 
Исправлено. Просьба проверить на версии 1.2.034.36.

**Comment by astrizhachuk** [comment]
@Pr-Mex Спецсимвол "\n" по прежнему не работает.

**Comment by Pr-Mex** [comment]
@astrizhachuk 
Не понял.
Я проверял на приложенном DT и приложенной фиче. На ней ошибки не было.
Ты на чём проверяешь?

**Comment by Pr-Mex** [comment]
> @Pr-Mex
> Так, поумничать с докером не удалось, поэтому вот новый dt и простой тест с повторением проблемы:
> [https://github.com/astrizhachuk/gitlab-services/blob/f8790d9a32e81d3a738bfdba88e0e7a05bc077b7/features/Обработчики%20событий/PrMex.feature](https://github.com/astrizhachuk/gitlab-services/blob/f8790d9a32e81d3a738bfdba88e0e7a05bc077b7/features/%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%B8%20%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9/PrMex.feature)
> https://github.com/astrizhachuk/gitlab-services/blob/f8790d9a32e81d3a738bfdba88e0e7a05bc077b7/test/empty.dt

@astrizhachuk 
Вот на этом должно работать.

**Comment by astrizhachuk** [comment]
@Pr-Mex проверял на последней сборке ветке sonar-fix. Взял состояние всей формы и проверил полученную таблицу через этот шаг. По прежнему на двух строках, где \n не отрабатывает.

**Comment by Pr-Mex** [comment]
@astrizhachuk 
Можешь проверить на том dt и сценарии что ты дал мне?

**Comment by astrizhachuk** [comment]
@Pr-Mex пересобрал версию VA на другой машине и все заработало, спасибо!

**Comment by Pr-Mex** [comment]
@astrizhachuk 
Отлично!

**Comment by Pr-Mex** [comment]
Решено в 1.2.035
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.035
