### ISSUE TITLE
Поддержка основных команд работы с git

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1001]
Поддержка основных команд работы с git.

**Comment by Pr-Mex** [comment]
Commit, pull, push, checkout.

**Comment by Pr-Mex** [comment]
Работа с ветками.

**Comment by Pr-Mex** [comment]
Решено в 1.2.035
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.035

**Comment by dentaky** [comment]
Можно еще добавить команду set-upstream в работу с git? Сейчас если в ванессе подключил удаленный репо и создал новую ветку в локальном репо, создал тесты в ней, то запушить её без открытия командной строки нельзя. Хотелось бы всё через Ванессу делать, раз туда добавлен этот функционал.

**Comment by Pr-Mex** [comment]
> Можно еще добавить команду set-upstream в работу с git? Сейчас если в ванессе подключил удаленный репо и создал новую ветку в локальном репо, создал тесты в ней, то запушить её без открытия командной строки нельзя. Хотелось бы всё через Ванессу делать, раз туда добавлен этот функционал.

@dentaky 
Думаю да, можно.

@lintest 
Подскажи, пожалуйста, компонента может сделать set-upstream?

**Comment by lintest** [comment]
@Pr-Mex сейчас не умеет, но можно добавить https://libgit2.org/libgit2/#v0.27.0/group/branch/git_branch_set_upstream

**Comment by Pr-Mex** [comment]
@lintest 
Давай добавим.

**Comment by dentaky** [comment]
> @lintest Давай добавим.

Мне новую заявку создать?

**Comment by Pr-Mex** [comment]
@dentaky 
Можно сюда продублировать
https://github.com/lintest/VanessaExt
