### ISSUE TITLE
Не удаётся ввести значение в поле по имени (в веб-интерфейсе)

### ISSUE THREAD

**Issue by sergey-dubinin-work** [Pr-Mex/vanessa-automation#1002]
```Gherkin
Функционал: Ввести значение в поле по имени поля
   Как Тестировщик
   Я хочу Я хочу ввести значение в поле по имени поля

Контекст:
  Дано: Vanessa Automation 1.2.034
  И 1С:Предприятие 8.3.15.1869
  и 1C: Drive

Сценарий: Я открываю Исследователь формы и получаю состояние формы и имена полей
  Допустим: Приложенная база публикуется на веб-сервере apache
В качестве клиента тестирования используется веб-клиент (браузер Chrome)
  Когда: Я захожу в справочник Campaigns (CRM -> Campaings)
Создаю новый элемент справочника, в табличной части Activities нажимаю кнопку Add, в добавленной строке нажимаю кнопку выбора у поля Highlight color
  Тогда: Открывается форма Select color, в поля которой я не могу ввести значения с помощью шагов:
And I input "135" text in the field named "RedEdit"
```

![image](https://user-images.githubusercontent.com/57937645/96996689-f81e0180-1538-11eb-9ce4-10bb1946254f.png)

```Gherkin

Однако в файловом варианте это шаг отрабатывает корректно, и исследователь формы видит поле с таким именем

```
![image](https://user-images.githubusercontent.com/57937645/96996804-2e5b8100-1539-11eb-8b36-64663f919d72.png)

База:
https://drive.google.com/file/d/1y0CRKGYM_fgk5KzsLxC2VY9laaRelhrr/view?usp=sharing
доступ открою по запросу

**Comment by Pr-Mex** [comment]
@sergey-dubinin-work 
Исследователь формы показывает, что имена полей в web клиенте другие
![image](https://user-images.githubusercontent.com/8627416/98436583-8ffd1d00-20ed-11eb-8540-972f111d8920.png)

**Comment by Pr-Mex** [comment]
@sergey-dubinin-work 
Если вы хотите написать универсальный сценарий, который работает и в тонком клиенте и в web используйте условие
``` Gherkin
If it is Web client Then
```

Так можно разделить разницу в поведении тонкого и web клиента.

**Comment by sergey-dubinin-work** [comment]
@Pr-Mex Благодарю, работает
