### ISSUE TITLE
Новый шаг: "И я закрываю все вкладки браузера"

### ISSUE THREAD

**Issue by lintest** [Pr-Mex/vanessa-automation#1004]
Новый шаг для закрытия браузера
```gherkin
И я закрываю все вкладки браузера
```

**Comment by lintest** [comment]
Для закрытия вкладок используется HTTP Endpoints:
https://chromedevtools.github.io/devtools-protocol/#get-jsonclosetargetid

![image](https://user-images.githubusercontent.com/92895/97091507-022d2680-1645-11eb-8b22-0af9766565ec.png)

**Comment by Pr-Mex** [comment]
Решено в 1.2.035
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.035
