### ISSUE TITLE
При сверке табличного документа - сохранять его как вложение

### ISSUE THREAD

**Issue by KrapivinAndrey** [Pr-Mex/vanessa-automation#1007]
```Gherkin
Функционал: Создание артефакта сверяемый Табличный документ
   Как разработчик тестов
   Я хочу получить сравниваемый документ
   Чтобы быстрее разобраться почему упал тест

Контекст:
  Дано: VA 1.2.034
  и Собственная

Сценарий: Проверка строк табличного документ
  Допустим сформирован табличный документ
  Когда проверяю наличие строк в этом табличном документе
  И некоторых строк не хватает
  Тогда тест падает
  И в отчете аллюр я могу посмотреть сформированный табдок
```

Сейчас если проверять табдок и тест падает:
1. Скриншоты не снимаются
2. Состояния форм не показывают состав табдок

![image](https://user-images.githubusercontent.com/586025/97405760-faf26b00-1919-11eb-8de6-771ff507df5f.png)

**Comment by Pr-Mex** [comment]
@KrapivinAndrey 
Скрины вроде снимаются при возникновении каждой ошибки.
В состоянии форм табдока нет, это да.

**Comment by KrapivinAndrey** [comment]
@Pr-Mex кто брался уже?
А то сегодня опять подгорело) Тест упал, даже скрины есть. Но вот... табдок оказался со свернутыми группами - так что скрин бесполезен.

**Comment by Pr-Mex** [comment]
@KrapivinAndrey 
Я планировал в скором времени сделать.

**Comment by Pr-Mex** [comment]
@KrapivinAndrey 
Сделано

**Comment by Pr-Mex** [comment]
Решено.
