### ISSUE TITLE
При выполнении шага "И я удаляю переменные текущего сценария" ошибка.

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#1008]
![Screenshot_19](https://user-images.githubusercontent.com/68432407/97413359-bfed3900-1913-11eb-8b39-d5eafa6ccc66.png)

VA 1.2.0.34. Платформа 8.3.16.1063. При выполнении шага "И я удаляю переменные текущего сценария" возникает ошибка: "Итератор для значения не определён" (см. скриншот).

**Comment by Pr-Mex** [comment]
@unichkin
Можешь посмотреть, плиз?

**Comment by Pr-Mex** [comment]
Решено в 1.2.035
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.035
