### ISSUE TITLE
И в таблице "List" текущая строка помечена на удаление

### ISSUE THREAD

**Issue by astrizhachuk** [Pr-Mex/vanessa-automation#1012]
Для англоязычной конфигурации возникает ошибка:

{ExternalDataProcessor.VanessaAutomationsingle.Form.Тест_РаботаСИнтерфейсом.Form(14385)}: Кнопка с именем <СписокКонтекстноеМенюУстановитьПометкуУдаления> не найдена.

Технические данные:
        ЗаголовокАктивногоОкна: ****
        ИмяАктивнойФормы: Catalog.****.ListForm
        ИмяФичи: ****
        ИмяСценария: ****
        НомерСтрокиДерева: 37
        НомерСтрокиФичи: 116
        ПолнйПутьКФиче: ****
        ИмяФайла: ВнешняяОбработка.VanessaAutomationsingle.Форма.Тест_РаботаСИнтерфейсом
        ИмяПроцедуры: ВТаблицеТекущаяСтрокаПомеченаНаУдаление
        ИмяРаннера: ****
        ТипКлиентаТестирования: Тонкий
        СтрокаСоединения: ***
        PIDКлиентаТестирования: 8264
        ВерсияVA: ver 1.2.033
        ВерсияПлатформы: 8.3.17.1549
        РежимСовместимостиTestManager: DontUse
        ДатаВремяОшибки: 30.10.2020 12:42:01

**Comment by Pr-Mex** [comment]
@astrizhachuk 
У меня это не воспроизводится. Дай пример для воспроизведения или скажи как у тебя эта кнопка называется. плиз.

**Comment by astrizhachuk** [comment]
@Pr-Mex 
ListContextMenuSetDeletionMark

**Comment by Pr-Mex** [comment]
@astrizhachuk 
Исправлено. Просьба проверить на версии 1.2.034.36.

**Comment by astrizhachuk** [comment]
@Pr-Mex работает.

**Comment by Pr-Mex** [comment]
Решено в 1.2.035
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.035
