### ISSUE TITLE
При выполнении шага "И Я очищаю фильтр на форме списка"

### ISSUE THREAD

**Issue by astrizhachuk** [Pr-Mex/vanessa-automation#1013]
Для англоязычной конфигурации возникает ошибка:

{ExternalDataProcessor.VanessaAutomationsingle.Form.Тест_РаботаСИнтерфейсом.Form(3572)}: Кнопка с именем <*НастройкаСписка> не найдена. ТекущееОкно=****

Технические данные:
        ЗаголовокАктивногоОкна: ****
        ИмяАктивнойФормы: Catalog.****.ListForm
        ИмяФичи: ****
        ИмяСценария: ****
        НомерСтрокиДерева: 12
        НомерСтрокиФичи: 73
        ПолнйПутьКФиче: ****
        ИмяФайла: ВнешняяОбработка.VanessaAutomationsingle.Форма.Тест_РаботаСИнтерфейсом
        ИмяПроцедуры: ЯНажимаюНаКнопкуСИменем
        ИмяРаннера: ****
        ТипКлиентаТестирования: Тонкий
        СтрокаСоединения: ****
        PIDКлиентаТестирования: 8264
        ВерсияVA: ver 1.2.033
        ВерсияПлатформы: 8.3.17.1549
        РежимСовместимостиTestManager: DontUse
        ДатаВремяОшибки: 30.10.2020 12:59:12

**Comment by Pr-Mex** [comment]
@astrizhachuk
У меня это не воспроизводится. Дай пример для воспроизведения или скажи как у тебя эта кнопка называется. плиз.

**Comment by astrizhachuk** [comment]
@Pr-Mex 
FormDynamicListStandardSettings

Для воспроизведения внутренний язык основным должен быть Английский, а интерфейс Русский (в моем кейсе было так)

**Comment by Pr-Mex** [comment]
@astrizhachuk 
Исправлено. Просьба проверить на версии 1.2.034.36.

**Comment by astrizhachuk** [comment]
@Pr-Mex Работает.

**Comment by Pr-Mex** [comment]
Решено в 1.2.035
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.035
