### ISSUE TITLE
Не выполняются шаги проверки пометки на удаление

### ISSUE THREAD

**Issue by tav-git** [Pr-Mex/vanessa-automation#1015]
VA ver 1.2.034
  1С:Предприятие 8.3 (8.3.15.1958)
  Конфигурации в которых замечена проблема: Бухгалтерия предприятия (базовая) расширенная, редакция 3.0 (3.0.83.40), Зарплата и управление персоналом, редакция 3.1 (3.1.15.97), Управление фирмой аутсорсером, редакция 2.0 (2.0.40.179)

В рамках сценария для 1С-Отчетности проверяется недоступность пометки на удаление. При ручном нажатии на пометку на удаление не возникает никаких сообщений, т.е. нажатие на кнопку происходит успешно, но пометка не устанавливается.

При попытке выполнения шагов проверки пометки на удаление они падают с ошибкой:
{ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(14416)}: Кнопка с именем <СписокКонтекстноеМенюУстановитьПометкуУдаления> не найдена.

Технические данные:
        ЗаголовокАктивногоОкна: 1С-Отчетность
        ИмяАктивнойФормы: ОбщаяФорма.РегламентированнаяОтчетность
        ИмяФичи: Проверка запрета редактирования деклараций
        ИмяСценария: Проверка недоступности удаления декларации
        НомерСтрокиДерева: 21
        НомерСтрокиФичи: 26
        ПолнйПутьКФиче: D:\1cbo\Jenkins\workspace\Запрет редактирования деклараций\runner\features\test.feature
        ИмяФайла: D:\1cbo\Jenkins\tools\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf
        ИмяПроцедуры: ВТаблицеТекущаяСтрокаПомеченаНаУдаление
        ИмяРаннера: 
        ТипКлиентаТестирования: Тонкий
        PIDКлиентаТестирования: 0
        ВерсияVA: ver 1.2.034
        ВерсияПлатформы: 8.3.15.1958
        РежимСовместимостиTestManager: НеИспользовать

На форме 1С-Отчетности пункт "пометить на удаление" в контекстном меню имеет имя 'ОтчетыКонтекстноеМенюУдалить'.

[Пример сценария.zip](https://github.com/Pr-Mex/vanessa-automation/files/5475011/default.zip)

База и учетные данные: https://docs.google.com/document/d/1aCwWOovK91e5cZLs3wWwq0uEdwOHVbSgwE9LiRUkOKA/edit?usp=sharing
Доступ открою по запросу

![image](https://user-images.githubusercontent.com/72562610/97868412-b0f5f480-1d20-11eb-9c21-e4b30c68a710.png)
![image](https://user-images.githubusercontent.com/72562610/97868555-f6b2bd00-1d20-11eb-9117-f0c747e81546.png)

**Comment by Pr-Mex** [comment]
Воспроизвести на указанной базе не удалось, т.к. для воспроизведения нужен dt базы, а по ссылке открывается гугл док с данными для подключения к web клиенту.

**Comment by Pr-Mex** [comment]
@tav-git 
Внёс правки по месту, просьба проверить на VA из develop на версии 1.2.034.36.

**Comment by tav-git** [comment]
> Воспроизвести на указанной базе не удалось, т.к. для воспроизведения нужен dt базы, а по ссылке открывается гугл док с данными для подключения к web клиенту.

Предоставить dt базы, увы, не могу.
Но ошибка воспроизводится в типовой БП, редакция 3.0 (3.0.84.42) в Регламентированных отчетах.

**Comment by Pr-Mex** [comment]
Решено в 1.2.035
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.035
