### ISSUE TITLE
Если прерывать шагом "Тогда я прерываю цикл" цикл в цикле, то этот шаг прерывает выполнение обоих циклов.

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#1029]
VA: 1.2.034. ERP 2.4.12.102. Платформа: 8.3.16.1063.
После прерывания первого цикла прервётся так же цикл по параметру "РеквизитыНоменклатуры" и заполнения второго реквизита "Вид номенклатуры" значением "Холодильники, морозильники" не выполнится.
Для примера сценарий вернего уровня и подсценарий

1. Сценарий верхнего уровня

И Заполнение полей реквизитов номенклатуры
   РеквизитыНоменклатуры = 
     | 'ЗаголовокРеквизита' | 'ЗначениеРеквизита' |
	 | 'Обособленная закупка/продажа' | 'Да' |
	 | 'Вид номенклатуры' | 'Холодильники, морозильники' |

2. Подсценарий:

//И Заполнение полей реквизитов номенклатуры

Дано Я открываю навигационную ссылку "e1cib/list/Справочник.Номенклатура"
Тогда открылось окно "Номенклатура"
И я нажимаю на кнопку с имененм "СписокРасширенныйПоискНоменклатураСоздать"
Тогда открылось окно "Номенклатура (создание)"
И я запоминаю значение выражения "Обособленная закупка/продажа" в переменную "РеквизитыВключениеВыключениеФлага"
И я запоминаю значение выражения "Вид номенклатуры" в переменную "РеквизитыВыборПоСтроке"

Цикл и для каждой строки таблицы я выполняю
  [РеквизитыНоменклатуры]
  
  И я активизирую поле "$ЗаголовокРеквизита$"
  И я запоминаю имя текущего поля как "ИмяПоляЗаголовокРеквизита"
  И я активизирую поле с именем "$ИмяПоляЗаголовокРеквизита$"
  
  Цикл И для каждого значения "ЭлементМассива" из масссива "РеквизитыВключениеВыключениеФлага"
  
     Если переменная "ЭлементМассива" имеет значение "$ЗаголовокРеквизита$" Тогда
	 
	      Тогда я прерываю цикл
		  
		  Если переменная "ЗначениеРеквизита" имеет значение "Да" Тогда
		  
		     И я устанавливаю флаг с имененм "$ИмяПоляЗаголовокРеквизита$"
			 
		  КонецЕсли	 
	 
	 КонецЕсли
  
  КонецЦикла  
  
  Цикл И для каждого значения "ЭлементМассива" из масссива "РеквизитыВыборПоСтроке"
  
     Если переменная "ЭлементМассива" имеет значение "$ЗаголовокРеквизита$" Тогда
	 
	      Тогда я прерываю цикл
		  И из выпадающего списка с именем "$ИмяПоляЗаголовокРеквизита$" я выбираю по строке "$ЗначениеРеквизита$"
		  И я перехожу к следующему реквизиту
	 
	 КонецЕсли
  
  КонецЦикла    

КонецЦикла

И я нажимаю на кнопку "Записать и закрыть"
И я жду закрытия окна "Номенклатура (создание)*" в течение 20 секунд

**Comment by Pr-Mex** [comment]
Решено.
