### ISSUE TITLE
По ходу выполнения сценария с первого раза  не выполняется заход в условие "Если".

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#1031]
[Для отладки123.zip](https://github.com/Pr-Mex/vanessa-automation/files/5529493/123.zip)
![Screenshot_1](https://user-images.githubusercontent.com/68432407/98921777-bb637b80-24e2-11eb-9543-2c93e3c044f4.png)

1. Загрузить в СППР сценарии "Для отладки1", "Для отладки2" и "Для отладки3" (одноимённые файлы приложены к данному обращению).
2. Запустить сценарий "Для отладки1" (в группе шагов "Заполнение полей реквизитов" не выполнится заход в условие "Если". Если вручную выполнять эту группу шагов, то заход в условие выполняется - см. приложенный скриншот).

Обнаружено в VA 1.2.034 в СППР 2.0.1.58, платформа 8.3.16.1063, конфигурация "ERP 2.4.12.102".
Воспроизвести можно на демо ERP 2.0, КА 2,0 или УТ 11.

**Comment by Pr-Mex** [comment]
Не воспроизводится на текущей VA.
