### ISSUE TITLE
Интеграция с контуром CI

### ISSUE THREAD

**Issue by DitriXNew** [Pr-Mex/vanessa-automation#1048]
Решаю сейчас задачу вывода информации по тестам в контур. Это связано с тем, что я хочу отслеживать на уровне контура значения тестов, которые иначе не отследить. Например:
1. Время выполнения теста в зависимости от агента
2. Увеличение времени теста более чем на 50%, хочу видеть предупреждение
3. Хочу сделать автомерж, т.е. если пул принят, в нем нет ошибок, то я хочу автомержиться
4. Хочу наблюдать за текущим билдом, и видеть скорость выполнения, и какие тесты прошли и\или УЖЕ упали.

Что я делаю сейчас:
1. Запускаю ванес у в несколько потоков
2. Ожидаю файлы логов, куда пишет инфа по тестам
3. Считываю тесты - отправляю в контур.

Проблемы:
1. Я не знаю сколько времени ванеса готовится к выполнению тестов.
Т.е. я запустил ванесу, и никакой информации до момента первого теста я не получаю.
Что я хочу - я запустил ванесу, мне сразу влог упало, что ванеса запустилась.
Потом упало - что началось чтение данных тестов.
Если при чтении возникли ошибки - я хочу их видеть в этом логе, например, снипеты не найдены и т.д.
И собственно попмент старта тестов, что типо тесты начались.

2. Я не могу рассчитать нормально время выполнения тестов, особенно, если ванеса упала в самом начале, так как лог будет пустым.
В идеале, я хочу получать строки:
Start script: S1
Finish script: S1
Start script: S2
Finish script: S2
и т.д., это мне позволит понять - сколько времени реально, валеса тратит на выполнение сценария.
Дополнительно, в строке финиша - я бы хотел видеть время в мс - сколько времени этот скрипт выполнялся.

3. Хотел бы иметь возможность указать настройку - каждый скрипт в отдельный файл, чтобы ванеса туда складировала скрипты, т.е. лог каждого скрипта в отдельный файл, желательно в json, и тогда я смогу считывать файлы, и удалять их, сразу почле того как я из догрузил. Тогда мне не надо будет делать кривых тейлов и сидеть в попытках распарсить лог на разные скрипты.

4. Ну это прям вообще идеал, если бы ванеса могла собрать простой html файл, в случае фейла скрипта, разместить его в отдельную папку, туда закинуть картинки и привязать к этому html. Тогда я бы в контуре мог этот html привязать к этому сценарию, и пока идут тесты, не дожидаясь аллюра - начать уже исправлять ошибки.

**Comment by Pr-Mex** [comment]
Создал
https://github.com/Pr-Mex/vanessa-automation/issues/1063

**Comment by Pr-Mex** [comment]
Создал: Запись в лог VA начало запуска сценария и окончания запуска сценария
https://github.com/Pr-Mex/vanessa-automation/issues/1064

**Comment by Pr-Mex** [comment]
> 3. Хотел бы иметь возможность указать настройку - каждый скрипт в отдельный файл, чтобы ванеса туда складировала скрипты, т.е. лог каждого скрипта в отдельный файл, желательно в json, и тогда я смогу считывать файлы, и удалять их, сразу почле того как я из догрузил. Тогда мне не надо будет делать кривых тейлов и сидеть в попытках распарсить лог на разные скрипты.

@DitriXNew 
Не понял этот момент. Расшифруй плиз. Ведь в логе уже будет нужная инфа.

**Comment by Pr-Mex** [comment]
> 4. Ну это прям вообще идеал, если бы ванеса могла собрать простой html файл, в случае фейла скрипта, разместить его в отдельную папку, туда закинуть картинки и привязать к этому html. Тогда я бы в контуре мог этот html привязать к этому сценарию, и пока идут тесты, не дожидаясь аллюра - начать уже исправлять ошибки.

@DitriXNew 
Ты хочешь получить быструю нотификацию - что тест упал?
Но разве не лучше сделать это с помощью e-mail, телеграммбота или чего-то такого?

**Comment by DitriXNew** [comment]
> 
> 
> > 1. Хотел бы иметь возможность указать настройку - каждый скрипт в отдельный файл, чтобы ванеса туда складировала скрипты, т.е. лог каждого скрипта в отдельный файл, желательно в json, и тогда я смогу считывать файлы, и удалять их, сразу почле того как я из догрузил. Тогда мне не надо будет делать кривых тейлов и сидеть в попытках распарсить лог на разные скрипты.
> 
> @DitriXNew
> Не понял этот момент. Расшифруй плиз. Ведь в логе уже будет нужная инфа.

Тут идея в том, что в файле оно таки не структуризированно, и если полезет бог знает что - парсер сломается. А так - каждый файл - отдельный тест. Грубо говоря, и тогда получается нет проблем с парсингом

**Comment by DitriXNew** [comment]
> 
> 
> > 1. Ну это прям вообще идеал, если бы ванеса могла собрать простой html файл, в случае фейла скрипта, разместить его в отдельную папку, туда закинуть картинки и привязать к этому html. Тогда я бы в контуре мог этот html привязать к этому сценарию, и пока идут тесты, не дожидаясь аллюра - начать уже исправлять ошибки.
> 
> @DitriXNew
> Ты хочешь получить быструю нотификацию - что тест упал?
> Но разве не лучше сделать это с помощью e-mail, телеграммбота или чего-то такого?

нет, то что тест упал - я и так знаю, я не знаю причин - почему он упал, т.е. мне всеравно надо ждать аллюра, чтобы понять причину падения. А я не хочу ждать аллюра, я хочу прям вот как только тест упал - зарегать его в контуре как фейл, и сразу выдать всю инфу о его фейле.

Например, есть места, когда баг сделали одиночный, ну типо тупо лажанули в каком то одном справочнике - то я пошел фиксить баг, а остальные тесты себе идут и идут.
А бывает, что лажа в какой то подписке при записи, тогда мне нет смысла ждать выполнения тестов, я их сразу всех остановлю.

**Comment by Pr-Mex** [comment]
> > > 1. Хотел бы иметь возможность указать настройку - каждый скрипт в отдельный файл, чтобы ванеса туда складировала скрипты, т.е. лог каждого скрипта в отдельный файл, желательно в json, и тогда я смогу считывать файлы, и удалять их, сразу почле того как я из догрузил. Тогда мне не надо будет делать кривых тейлов и сидеть в попытках распарсить лог на разные скрипты.
> > 
> > 
> > @DitriXNew
> > Не понял этот момент. Расшифруй плиз. Ведь в логе уже будет нужная инфа.
> 
> Тут идея в том, что в файле оно таки не структуризированно, и если полезет бог знает что - парсер сломается. А так - каждый файл - отдельный тест. Грубо говоря, и тогда получается нет проблем с парсингом

Создал задачу
Записывать данные по ошибке в json файл по мере выполнения сценария. #1065
