### ISSUE TITLE
Поддержка в синтаксисе Gherkin Попытки/Исключение (Try/Except)

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1050]
Поддержка в синтаксисе Gherkin Попытки/Исключение (Try/Except)

В секции исключение добавлять шаги необязательно.

**Comment by Pr-Mex** [comment]
Решено.

**Comment by galexkcx** [comment]
А где пример правильного использования Попытки? У меня все равно валится тест.

**Comment by Pr-Mex** [comment]
@galexkcx 
Посмотрите тут
https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/MainHelp/index.MD

![image](https://github.com/Pr-Mex/vanessa-automation/assets/8627416/c5f57043-3032-4ff6-8b96-e5b973259e25)
