### ISSUE TITLE
Прикрепление файлов в формате xlsx заменено на mxl, т.к. не всегда гарантируется конвертация данных в формат xlsx

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1052]
Нужно для гарантированного формирования отчетов.

**Comment by nixel2007** [comment]
Воу, воу, а можно и то и то? Аналитикам, пырящим аллюр, намного удобнее смотреть эксельки, чем развлекаться с открываемым только в 1С мокселем.

**Comment by Pr-Mex** [comment]
Оки. Пусть будет и то и то.
