### ISSUE TITLE
Нет шага, который бы определял тип реквизита.

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#1056]
Задача: нужно на форме, например, документа найти и активизировать таблицу.
При создании нового документа и перехода к нужной закладке табличной части этого документа, зачастую поле этой табличной части не становится активным. Варианта два: 1. нужно активизировать эту табличную часть документа кликом курсора мыши. 2.  организовать цикл, в котором анализируется тип поля реквизита документа (если тип реквизита не "Таблица", то выполняется переход к следующему реквизиту, если "Таблица", то цикл прерывается и выполняется шаг "И я запоминаю имя текущей таблицы как "ИмяПеременной""). В ходе реализации тестовых сценариев первый способ не подходит. Для второго способа нужен шаг в VA, который бы получал тип реквизита.

**Comment by Pr-Mex** [comment]
Решено.
