### ISSUE TITLE
Не работает шаг "Если в таблице "ИмяТаблицы" поле "Заголовок поля" имеет значение "ЗначениеПоля" тогда"

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#1060]
Не работает шаг "Если в таблице "ИмяТаблицы" поле "Заголовок поля" имеет значение "ЗначениеПоля" тогда" - появляется ошибка: "Ошибка при вызове метода контекста (ПолучитьТекстЯчейки): В элементе управления отсутствует указанное значение" (см. приложенный скриншот
<img width="911" alt="Screenshot_1" src="https://user-images.githubusercontent.com/68432407/100986517-5be71180-355e-11eb-8202-94d5cd56fa07.png">
)

Причём шаг "Если в таблице "ИмяТаблицы" поле с именем "ИмяПоля" имеет значение "ЗначениеПоля" тогда" с теми же данными отрабатывает корректно.

Файл со сценарием "ДляОтладки" приложен.
[ДляОтладки.txt](https://github.com/Pr-Mex/vanessa-automation/files/5634840/default.txt)

Обнаружено на VA 1.2.035.1. Платформа 8.3.18.1206.
Воспроизвести можно на демо УТ 11.4, ERP 2.4 или КА 2.4.

**Comment by Pr-Mex** [comment]
Не воспроизводится на УТ 11.4.13.148.
Появляется окно
![image](https://user-images.githubusercontent.com/8627416/112714406-4a4dbf00-8eeb-11eb-9191-faff8e194d03.png)
