### ISSUE TITLE
Файлы сценариев в Windows записываются с переводом строки LF, а не CRLF

### ISSUE THREAD

**Issue by andrewzola** [Pr-Mex/vanessa-automation#1068]
Функционал: Запись текста сценария в файл
   Как пользователь git
   Я хочу не иметь проблем с переводами строк CRLF и LF

Контекст:
  Дано: VA 1.2.0.35.1

Сценарий: Запись текста сценария в файл
  Допустим: Есть сценарий с несколькими строками
  Когда: Я записываю текст сценария
  Тогда: текст сценария записывается в файл с переводом строки, который используется в операционной системе по умолчанию

```
привнесено в https://github.com/Pr-Mex/vanessa-automation/commit/91e92db2cea9dd3026a231ea876e7190e0cd6a2b

Проблема в Новый ЗаписьТекста, в последнем параметре:
<КонвертируемыйРазделительСтрок> (необязательный)
Тип: Строка. 
Определяет разделение строк в файле для конвертации в стандартный перевод строк ПС.
Значение по умолчанию: ВК + ПС.

// Сохраняет текст из редактора в файл.
&НаКлиенте
Процедура СохранитьТекстИзVanessaEditorВФайл() Экспорт
	
	....
	ЗТ = Новый ЗаписьТекста(Ванесса.VanessaTabs.current.filename, "UTF-8", , Ложь, Символы.ПС); 
	... 
	
КонецПроцедуры

**Comment by Pr-Mex** [comment]
@andrewzola 
Подскажите, пожалуйста, в каком окружении вы работаете. В частности ОС.

**Comment by andrewzola** [comment]
Win 10 20H2
1С:Предприятие 8.3 (8.3.17.1549)

поведение воспроизвел след. образом:
1. Сохранил файл сценария из редактора VA
2. Открыл файл в Notepad++, убедился, что переносы строк LF
3. Заменил
ЗТ = Новый ЗаписьТекста(Ванесса.VanessaTabs.current.filename, "UTF-8", , Ложь, Символы.ПС); 
на 
ЗТ = Новый ЗаписьТекста(Ванесса.VanessaTabs.current.filename, "UTF-8", , Ложь); 
4. Сохранил файл сценария из редактора VA
2. Открыл файл в Notepad++, убедился, что переносы строк CRLF

**Comment by Pr-Mex** [comment]
@andrewzola 
E меня что-то не работало при сохранении в win переносов строк, можно ли оставить как есть?
Критична ли проблема? По идее настройки гита должны решать это.

**Comment by andrewzola** [comment]
@Pr-Mex вообще, не особо критично
вы правы, вопрос скорее в области настроек гита

**Comment by Pr-Mex** [comment]
Ок, тогда закрываю.
