### ISSUE TITLE
При автозапуске на удаленном компьютере некорректно передается таблица Gherkin в экспортный сценарий

### ISSUE THREAD

**Issue by sashareisler95** [Pr-Mex/vanessa-automation#1069]
При автозапуске на удаленном компьютере некорректно передается таблица Gherkin в экспортный сценарий
При локальном запуске всё работает корректно.

![image](https://user-images.githubusercontent.com/53227249/101874742-a8ac9700-3bb3-11eb-99fb-0fdf88311efa.png)
![image](https://user-images.githubusercontent.com/53227249/101874785-b6fab300-3bb3-11eb-82d5-971a5c6ad721.png)
[Экспортный сценарий.txt](https://github.com/Pr-Mex/vanessa-automation/files/5677611/default.txt)
[Фича.txt](https://github.com/Pr-Mex/vanessa-automation/files/5677613/default.txt)

**Comment by Pr-Mex** [comment]
@sashareisler95 
Опишите, пожалуйста, про передачу подсценариев.
Какое поведение вы считается правильным и какое наблюдаете.

**Comment by sashareisler95** [comment]
@Pr-Mex 
Правильным считаю поведение, когда таблица передается в экспортный сценарий туда, где она упоминается (если можно так сказать).
В текущей ситуации во время запуска на локальном компе таблица передается корректно, как видно на скрине.
При запуске на удаленной машине же таблица почему-то передается ниже, в шаг, который работает с таблицей на клиенте, а не с таблице Gherkin, что видно на скрине отчёта. Ожидалось, что таблица будет передана в шаг, который отмечен проваленным. (Исходя из работы сценария на локальном компе)

**Comment by sashareisler95** [comment]
@Pr-Mex 
Как быть в такой ситуации? Вроде находила подобную проблему, но вроде в 33 релизе правили...
https://github.com/Pr-Mex/vanessa-automation/issues/859

**Comment by Pr-Mex** [comment]
@sashareisler95 
Опишите подробно, пожалуйста, как воспроизвести проблему. Как вы  делаете запуск на удалённой машине.

**Comment by sashareisler95** [comment]
@Pr-Mex 
Автозапуск происходит с помощью Jenkins.
Jenkins стягивает все файлы из репозиториев и запускает.(На Windows)
Версия VA Single 1.2.035.1
Возможно, предоставила не всю нужную информацию, не знаю, что ещё нужно)

**Comment by sashareisler95** [comment]
Нашли проблему - проблема у нас)

**Comment by Pr-Mex** [comment]
@sashareisler95 
Ок, принято. А в чём была проблема?
