### ISSUE TITLE
Порты тест клиента

### ISSUE THREAD

**Issue by DitriXNew** [Pr-Mex/vanessa-automation#1076]
Очень не удобно указывать диапазоны портов, если на одном сервере работают несколько людей  с ванессой.
Что хотелось бы - указать путь к некоему общему файлу, и чтобы туда ванеса писала те порты, которые заняла, а другая ванеса - смотрела и не пыталась их занять.
Т.е. я хочу указать диапазон, типо от 48000 - 48100, и все ванессы которые запускаются - пусть смотрят в этот файл и пишут туда что заняли, и удаляют, что освободили.
А то временами доходит до абсурдов.

**Comment by Pr-Mex** [comment]
@DitriXNew 
Объясни, плиз, что именно неудобно?
Ведь это вроде бы разовая настройка.

**Comment by asosnoviy** [comment]
Там гдето, примерно для этого запилено чтение переменных окружения  из консула

**Comment by DitriXNew** [comment]
Кейс - сидят 3 программиста, у них какие то косяки по коду, они запускают билд, который им разворачивает базы, запускает ванесу, по нужным тегам, и с разными флагами, типо остановка по ошибке, не закрывать ванесу и т.д.
Все программисты работают на одном сервере.
В момент запуска, так как билды идентичные, то старт портов идет с 48000, и вот если этот порт занят - система берет следующий, а может и не взять, так как на этом порту висит другая ванеса, то платформа просто падает в крит, что не удалось подключить клиента.
Плюс иногда две ванесы начинают ссорится по портам, т.е. я указал для одно тега 10 портов, но если там есть несколько переподключений, то ванесы сорятся, занимают по одному порту выше, и выходят за диапазон.

Идея какая - все ванесы работают на одной машине, у них ограниченый пул портов, на деплойке я не могу порты делить явно по агентам, ибо агенты динамические, и могут запускаться на компе разраба, а могут на сервере.
Поэтому мне надо, чтобы я выделил пул в 100 портов ВСЕМ ванесам, которые запускаются на сервере.

Как то так..

**Comment by Pr-Mex** [comment]
@DitriXNew 
Тут напрашивается простое решение добавить в билд параметр - диапазон портов. Если он не задан, то брать 48000-48100.
И тоже решает вопрос.
Диапазон в 10 портов - это мало. Попробуйте выделять диапазоны большего размера, например по 100.

Записывать что-то в общий файл на терминальном сервере тоже может создать проблем и с одновременным доступом и с правами - что делать, если у кого-то не окажется прав на запись?

**Comment by DitriXNew** [comment]
это я понимаю тоже, но вешать на девопс контроль портов - сложно, с учетом того, что агенты могут не закрываться, или использоваться для других целей.
Поэтому пока не знаю как лучше разрулить этот кейс

**Comment by Pr-Mex** [comment]
@DitriXNew 
Я сомневаюсь, что на этой машине есть дефицит свободных портов.
Роботам можно выделить один набор диапазонам.
Людям - другой.
