### ISSUE TITLE
Значение не является значением объектного типа (Имя) в УстановитьЗначениеТекущейФормыVanessaEditor

### ISSUE THREAD

**Issue by Stepa86** [Pr-Mex/vanessa-automation#1081]
VA 1.2.035.8

Проигрываю фичи при включенном редакторе VanessaEditor с остановкой по ошибке.
Если останавливается на ошибке со сравнением таблиц (шаг `И таблица "Таблица" содержит строки`), то выпадает исключение. После закрытия выпадает постоянно снова, что приходится закрывать VA.

```
Значение не является значением объектного типа (Имя)
{ВнешняяОбработка.VanessaAutomation.Форма.РедакторТекста.Форма(459)}:		УстановитьЗначениеТекущейФормыVanessaEditor(ТекущиеЗначения, "ИмяКолонки", Данные.ТекЭлемент.Имя, БылиИзменения);
{ВнешняяОбработка.VanessaAutomation.Форма.РедакторТекста.Форма(1430)}:	ЗапомнитьДанныеТекущейФормыVanessaEditor(Данные, Ванесса.ЗначенияЭлементовТекущегоОкнаVanessaEditor);
```

**Comment by Pr-Mex** [comment]
Спасибо. Буду смотреть.

**Comment by Pr-Mex** [comment]
@Stepa86 
Проверь на 1.2.035.9, пожалуйста.

**Comment by Stepa86** [comment]
У меня даже на старой версии далеко не всегда повторяется, поэтому не могу сказать ушел баг или нет. Предлагаю ишуз закрыть, а если повторится - открыть или создать новый.

**Comment by Pr-Mex** [comment]
@Stepa86 
Насколько я понял ошибка проявлялась, когда в таблице не было активной колонки.

**Comment by Pr-Mex** [comment]
Решено.
