### ISSUE TITLE
Отсутствует возможность поиска таблицы по заголовку

### ISSUE THREAD

**Issue by shcherbakov-vadim** [Pr-Mex/vanessa-automation#1096]
Неожиданно обнаружил, что в VA отсутствует возможность поиска таблицы по заголовоку, например для шага "я заполняю таблицу 'Таблица' данными". Это при том, что получить заголовок таблицы можно с помощью "Изменить форму...", а вот имя либо через конфигуратор, а в худшем случае только через отладчик.
Очень напрашивается, чтобы по умолчанию во всех действиях поиск выполнялся по заголовку, при этом если имя начинается со спецсимвола, система интерпретировала это как поиск по имени. Тогда можно было бы вообще избавиться от отдельных шагов для заголовков. Спецсимвол можно устанавливать в качестве опции для файла. Если спецсимвол не задан, считать что поиск выполняется всегда по имени (для обратной совместимости)

UPD:
Обнаружил функцию ОпределитьРежимПоискаЭлементаНаФорме, которая делает что-то подобное, если режим поиска не указан. Но вариантов вызова с таким параметром обнаружить не удалось.

**Comment by Pr-Mex** [comment]
@shcherbakov-vadim 
Таблицы специально ищутся по своему имени, т.к. их заголовок редко выводится на форму.
Чтобы узнать имя элемента достаточно открыть исследователь формы (alt+E) или включить в редакторе опцию:
![image](https://user-images.githubusercontent.com/8627416/104051653-83826700-51f9-11eb-97ba-6ff474851833.png)

**Comment by Pr-Mex** [comment]
> Очень напрашивается, чтобы по умолчанию во всех действиях поиск выполнялся по заголовку, при этом если имя начинается со спецсимвола, система интерпретировала это как поиск по имени.

Да, на это есть задача
https://github.com/Pr-Mex/vanessa-automation/issues/135
Хочешь реализовать?

**Comment by shcherbakov-vadim** [comment]
> > Очень напрашивается, чтобы по умолчанию во всех действиях поиск выполнялся по заголовку, при этом если имя начинается со спецсимвола, система интерпретировала это как поиск по имени.
> 
> Да, на это есть задача
> #135
> Хочешь реализовать?
Я добавил pull-request, но там бот спрашивает про запуск тестов. Что мне нужно ответить?

**Comment by Pr-Mex** [comment]
Бот спрашивает про запуск тестов. Я запущу их.
