### ISSUE TITLE
Некорректно определяется причина падения шага.

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#1103]
VA не видит элемент на форме, хотя он есть и видим и пользователь с ним работает. В сообщении сказано что интерактивные действия невозможно выполнять с невидимым пользователю элементом, а не о том что обнаружено несколько элементов с одним заголовком (см. приложенный скриншот
![Screenshot_22](https://user-images.githubusercontent.com/68432407/104619510-0181ba80-569f-11eb-9384-7196281aac1c.png)
).

Воспроизвести можно на демо УТ 11.4.13. Платформа 8.3.18.1208. 

Сценарий для воспроизведения:

Дано Я открываю навигационную ссылку "e1cib/data/Документ.ЗаказКлиента?ref=92f10050568b35ac11e5296e0227135d"
Тогда открылось окно "Заказ клиента*"
И я включаю проверку доступности элементов с учётом доступности групп элементов
И я включаю проверку видимости элементов с учётом видимости групп элементов
И я перехожу к закладке "Товары"
И я нажимаю на кнопку "Добавить"
И я выключаю проверку видимости элементов с учётом видимости групп элементов
И я выключаю проверку доступности элементов с учётом доступности групп элементов

**Comment by Pr-Mex** [comment]
Не воспроизводится на 11.4.13.148.
