### ISSUE TITLE
Описать шаг двойного клика на строчке

### ISSUE THREAD

**Issue by Hupmu** [Pr-Mex/vanessa-automation#1116]
Есть в документе табличная часть. Нужно по текущей строке сделать двойной клик, что бы выбранная строка перенеслась во вторую табличную часть. При попытке сделать так:
```
И в таблице "Объекты" я выбираю текущую строку
И в таблице "Объекты" я делаю двойной клик на текущей строке
```
данный шаг отрабатывается, но после его выполнения сценарий прекращается с описанием:
27.01.2021 18:28:13 Пустой адрес снипета у шага: И в таблице "Объекты" я делаю двойной клик на текущей строке
27.01.2021 18:28:15 Выполнение сценариев закончено. Ошибок не было.

Хотя после этого шага еще много этапов.

**Comment by nixel2007** [comment]
Так шаг выбора текущей строки делает тоже самое, что и двойной клик. Разве вам его не хватает?

**Comment by Hupmu** [comment]
> Так шаг выбора текущей строки делает тоже самое, что и двойной клик. Разве вам его не хватает?

Нет не хватает, потому что открывается окно с двумя табличными частями. В первой таблице список объектов, что бы перенести выборочно объекты в другую таблицу, нужно дважды кликнуть по объекту. Выбор текущей строки это просто выделение, а не перенос ее во вторую табличную часть.

**Comment by nixel2007** [comment]
А список не в режиме выбора открыт?

**Comment by Pr-Mex** [comment]
> Есть в документе табличная часть. Нужно по текущей строке сделать двойной клик, что бы выбранная строка перенеслась во вторую табличную часть. При попытке сделать так:
> 
> ```
> И в таблице "Объекты" я выбираю текущую строку
> И в таблице "Объекты" я делаю двойной клик на текущей строке
> ```
> 
> данный шаг отрабатывается, но после его выполнения сценарий прекращается с описанием:
> 27.01.2021 18:28:13 Пустой адрес снипета у шага: И в таблице "Объекты" я делаю двойной клик на текущей строке
> 27.01.2021 18:28:15 Выполнение сценариев закончено. Ошибок не было.
> 
> Хотя после этого шага еще много этапов.

1.Редактор подчёркивает этот шаг, т.к. его нет в списке шагов поставляемой библиотеки.
![image](https://user-images.githubusercontent.com/8627416/106026549-ff761d80-60da-11eb-9fd0-c66ef1a6e50b.png)

2. Как правильно пишет @nixel2007 - Шаг
```Gherkin
И в таблице "Объекты" я выбираю текущую строку
```
как раз делает двойной клик по строке.

**Comment by nixel2007** [comment]
> Выбор текущей строки это просто выделение, а не перенос ее во вторую табличную часть.

просто выделение - это шаг с активизацией строки, насколько я помню. либо переход к строке по отборам (активизация там сработает сама).

**Comment by Hupmu** [comment]
Да, сработало, но пришлось после выбора текущей строки ставить паузу 3сек, иначе на следующем шаге нажатия на кнопку Выбор, на основное окно не переноситься выбранная строчка.

**Comment by Hupmu** [comment]
А подскажите, пожалуйста, еще, как выбрать 2 строку вне зависимости, какие в ней данные? То есть мне надо помимо самой первой строки, которую я выбираю как текущую, выбрать и вторую. Но во второй строке могут быть каждый раз разные данные.

**Comment by Pr-Mex** [comment]
> Да, сработало, но пришлось после выбора текущей строки ставить паузу 3сек, иначе на следующем шаге нажатия на кнопку Выбор, на основное окно не переноситься выбранная строчка.

Используйте шаг
Тогда открылось окно
чтобы разделить смену окон

**Comment by Pr-Mex** [comment]
> А подскажите, пожалуйста, еще, как выбрать 2 строку вне зависимости, какие в ней данные? То есть мне надо помимо самой первой строки, которую я выбираю как текущую, выбрать и вторую. Но во второй строке могут быть каждый раз разные данные.

Делайте переход к первой строке, затем переход на одну строку вниз.
Если в таблице есть нумерация строк, то делайте переход к строке по значению номера строки.

**Comment by Hupmu** [comment]
Спасибо за советы. Тему можно закрывать.
