### ISSUE TITLE
Одновременный запуск сценариев

### ISSUE THREAD

**Issue by Hupmu** [Pr-Mex/vanessa-automation#1122]
Добрый день.
Подскажите, пожалуйста, есть ли возможность в ванессе запуска одного и того же сценария сразу несколько раз от разных пользователей, что бы он выполнялся одновременно? Если да. то как запустить, к примеру, 10 сеансов.

**Comment by Pr-Mex** [comment]
> Добрый день.
> Подскажите, пожалуйста, есть ли возможность в ванессе запуска одного и того же сценария сразу несколько раз от разных пользователей, что бы он выполнялся одновременно? Если да. то как запустить, к примеру, 10 сеансов.

В данном случае, я думаю, подойдёт структура сценария. Посмотрите здесь.
https://wellbehaved.readthedocs.io/Gherkin.html
