### ISSUE TITLE
Создать специальный реквизит объекта ЗначениеНаСервере, чтобы в него можно было сохранять значение, вычисленное в серверном коде, чтобы потом его можно было прочитать на клиенте.

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1126]
Создать специальный реквизит объекта "ЗначениеНаСервере", чтобы в него можно было сохранять значение, вычисленное в серверном коде, чтобы потом его можно было прочитать на клиенте.

**Comment by nixel2007** [comment]
А чем не подходит сохранение в контекст?...

**Comment by Pr-Mex** [comment]
> А чем не подходит сохранение в контекст?...

Контекст не  ездит на сервер

**Comment by nixel2007** [comment]
Но ведь можно сделать шаг, который вызовет функцию на сервере и сохранит результат в контекст, не?

**Comment by Pr-Mex** [comment]
> Но ведь можно сделать шаг, который вызовет функцию на сервере и сохранит результат в контекст, не?

Да. Можно. Но постоянно идут обращения,  что надо сохранить значение в переменную на сервере и затем передавать её на клиент.  Видимо в каких-то случаях так проще.

**Comment by nixel2007** [comment]
я скорее про то, что можно просто сделать отдельный шаг прямо в поставке VA. что-то типа "Я вычисляю значение выражения "1+1" на сервере и сохраняю его в переменную "МояПеременная".
И этот шаг можно реализовать и без доп реквизита.

**Comment by Pr-Mex** [comment]
> я скорее про то, что можно просто сделать отдельный шаг прямо в поставке VA. что-то типа "Я вычисляю значение выражения "1+1" на сервере и сохраняю его в переменную "МояПеременная".
> И этот шаг можно реализовать и без доп реквизита.

Да. Это тоже можно. Реквизит нужен скорее для случая, когда используется шаг выполнения кода на сервере. И надо сохранить результат для передачи на клиент.

**Comment by nixel2007** [comment]
Так я же именно про это и говорю :)

**Comment by Pr-Mex** [comment]
> Так я же именно про это и говорю :)

Я пока не понял противоречия ) Ты за то, чтобы не добавлять реквизит?

**Comment by nixel2007** [comment]
Ну да. Зачем его добавлять, если можно просто вызвать функцию и вернуть результат?

**Comment by Pr-Mex** [comment]
> Ну да. Зачем его добавлять, если можно просто вызвать функцию и вернуть результат?

У меня на практике были случаи, когда нельзя вызвать код с клиента. Для этих случаев реквизит пригодится.

**Comment by Pr-Mex** [comment]
Решено.
