### ISSUE TITLE
Добавить обработку по генерации тестовых данных

### ISSUE THREAD

**Issue by DitriXNew** [Pr-Mex/vanessa-automation#1127]
Поддерживаемые типы данных:
Константы
Справочники
Документы
Планы видов характеристик
Регистры накоплений
Регистры сведений

При загрузке доп реквизитов - не учитывается типо дынных, поэтому доп реквизиты не примитивных типов - лучше не грузить.

**Comment by mors1eska** [comment]
круто, а где почитать как это работает?

**Comment by Pr-Mex** [comment]
@DitriXNew 
где это про это можно почитать посмотреть?

**Comment by Pr-Mex** [comment]
Решено.
