### ISSUE TITLE
После редактировании таблицы Gherkin тест выполняется с ошибкой

### ISSUE THREAD

**Issue by BProg-Gladkov** [Pr-Mex/vanessa-automation#1129]
Контекст:
  Дано: <версия инструментария> = 1.2.035.16
  И <полная версия 1С> = 1С:Предприятие 8.3 (8.3.18.1208)
  И Конфигурация запуска = v83ServiceBase8318

Сценарий: <ожидаемое поведение>
  Допустим: я редактирую тест "БиблиотекаШаговИнициаторДанных"
  Когда: я копирую шаг "И я заполняю табличную часть "Товары" объекта "ДокПТУ1" по таблице"
  Тогда: шаги заполнения табличной части по таблице выполняются
![image](https://user-images.githubusercontent.com/33430119/106424980-2d10ed00-6474-11eb-8edf-cefa78e12662.png)
  Когда: я добавляю в заголовке таблицы кавычки
  Тогда: шаги заполнения табличной части по таблице выполняются
![image](https://user-images.githubusercontent.com/33430119/106425592-220a8c80-6475-11eb-9670-7b5c887df64b.png)
  Когда: я нажимаю "редактировать таблицу"
          И окне редактирования таблицы нажимаю "ОК"
  Тогда: тест выполняется с ошибкой
![image](https://user-images.githubusercontent.com/33430119/106425756-6eee6300-6475-11eb-90f1-f70b7c6bdc40.png)
  Когда: добавляю "1" в описание шага
  Тогда: тест выполняется пропускает шаг как неизвестный
![image](https://user-images.githubusercontent.com/33430119/106425912-b4ab2b80-6475-11eb-80da-4e8c18ee88db.png)
  Когда: удаляю "1" в описание шага
  Тогда: шаги заполнения табличной части по таблице выполняются
![image](https://user-images.githubusercontent.com/33430119/106426006-e15f4300-6475-11eb-9a58-329df4e776d4.png)

ИТОГ:
Ошибка возникает при изменении таблицы без перестроения дерева шагов (используется оптимизация загрузки фичи).
см код:
![image](https://user-images.githubusercontent.com/33430119/106426138-208d9400-6476-11eb-925c-0a2e961bac08.png)
![image](https://user-images.githubusercontent.com/33430119/106426154-284d3880-6476-11eb-9291-c3916c5e41fe.png)

**Comment by Pr-Mex** [comment]
Решено.
