### ISSUE TITLE
Контекстная команда Озвучить шаг

### ISSUE THREAD

**Issue by KrapivinAndrey** [Pr-Mex/vanessa-automation#1134]
По мотивам телеграмм.
https://t.me/testspro1c/36069

1. Озвучить текущий шаг
2. Озвучить текущий шаг с учетом тегов голоса
3. Прочитать весь сценарий(очень сомнительно)...

**Comment by Pr-Mex** [comment]
@KrapivinAndrey 
Хочешь сделать?

**Comment by KrapivinAndrey** [comment]
@Pr-Mex да. идея интересная.

**Comment by Pr-Mex** [comment]
@KrapivinAndrey 
Крутяк, давай!

**Comment by Pr-Mex** [comment]
Решено.
