### ISSUE TITLE
Быстрый парсер языка Gherkin из компоненты VanessaExt.

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1144]
1. Добавить опцию использовать новый парсер.
2. Встроить новый парсер.

**Comment by Stepa86** [comment]
На CI с новым парсером проблема на шаге

`И Я запоминаю значение выражения 'Строка(ТекущаяДата())' в переменную "НачалоБлокаТестов" глобально`

```
Недостаточно фактических параметров
{(1)}:
Технические данные:
        ИмяФайла: C:/Program Files (x86)/OneScript/lib/vanessa-automation/features/libraries/ВстроенныйЯзык/ВстроенныйЯзык.epf
        ИмяПроцедуры: ЯВыполняюКодВстроенногоЯзыкаНаСервереБезКонтекста
        ТипКлиентаТестирования: Тонкий
        ВерсияVA: ver 1.2.035.29
        ВерсияПлатформы: 8.3.17.1851
        РежимСовместимостиTestManager: Версия8_3_14
        ДатаВремяОшибки: 11.03.2021 17:50:49
```

**Comment by Pr-Mex** [comment]
@Stepa86 
Попробуй обновиться до 1.2.035.30
У меня не воспроизводится.

**Comment by Stepa86** [comment]
> @Stepa86
> Попробуй обновиться до 1.2.035.30
> У меня не воспроизводится.

Ошибка осталась, но падает только на CI. Повторить локально не получается

**Comment by Stepa86** [comment]
В 1.2.035.32 не воспроизвелось. Ошибки связанными оказались

**Comment by Stepa86** [comment]
Еще нашел баг с новым парсером. Он крашит платформу, если в фиче есть "№".

Вот такая фича новым парсером не открывается:

```gherkin
#language: ru

Функционал: ИмяФункционала

Сценарий: Создание рабочего центра Маркировка №1

	Когда В командном интерфейсе я выбираю 'Нормативно-справочная информация' 'Рабочие центры'
```

А если убрать из имени сценария номер, то парсится:

```gherkin
#language: ru

Функционал: ИмяФункционала

Сценарий: Создание рабочего центра Маркировка 1

	Когда В командном интерфейсе я выбираю 'Нормативно-справочная информация' 'Рабочие центры'
```

При старом парсере все норм

**Comment by Pr-Mex** [comment]
@Stepa86 
Проверь на 1.2.035.36, пожалуйста.

**Comment by Stepa86** [comment]
> @Stepa86
> Проверь на 1.2.035.36, пожалуйста.

@Pr-Mex На 1.2.035.36 не воспроизводится. Спасибо

**Comment by Pr-Mex** [comment]
> > @Stepa86
> > Проверь на 1.2.035.36, пожалуйста.
> 
> @Pr-Mex На 1.2.035.36 не воспроизводится. Спасибо

Тебе спасибо!

**Comment by Pr-Mex** [comment]
Решено.
