### ISSUE TITLE
Пропадает водяной знак на видеоинструкции при использовании шага видеовставки.

### ISSUE THREAD

**Issue by DragunY** [Pr-Mex/vanessa-automation#1147]
Генерация видеоинструкции происходит на платформе 8.3.18.1334. Используемая версия vanessa - 35
При использовании шага: 
И видеовставка картинки "ИмяКартинки" "ТекстДиктора"
	|'FadeIn' |'Да'|
	|'FadeOut'|'Да'|
В сгенерированной видеоинструкции пропадает водяной знак на данном шаге и не появляется после показа скринов на видео.
Сценарий:

#language: ru
@tree
Функциональность: Видеоролик

Контекст:
	И Я закрыл все окна клиентского приложения

@КодСценария=000000328
Сценарий: Адресный классификатор.
И текст субтитров "Использование адресного классификатора - это наиболее удобный способ заполнять адресную информацию быстро и без ошибок, а также обеспечить единство ее структуры и состава в программе"
И видеовставка картинки "СкринАдресныйКлассификатор" "Список программ, для которых доступен адресный классификатор вы можете найти на портале 1эс"
	|'FadeIn' |'Да'|
	|'FadeOut'|'Нет'|
И видеовставка картинки "Скрин1АдресныйКлассификатор" "Там же есть ссылки на инструкции по подключению для всех программ"
	|'FadeIn' |'Нет'|
	|'FadeOut'|'Да'|
И видеовставка картинки "Скрин2АдресныйКлассификатор" "Данные в адресный классификатор загружаются из классификатора СОАТО, который ведёт Национальное кадастровое агенство Республики Беларусь. Сервис требует дополнительной оплаты и не распостраняется без действующего договора информационно технологического сопровождения. Он активируется с момента оплаты до окончания действия договора. Ознакомиться с актуальной стоимостью сервиса и заказать его можно на сайте фирмы 1эсМинск. Пользователям сервиса предоставляется возможность просмотра месторасположения на картах Яндекс и Google."
	|'FadeIn' |'Да'|
	|'FadeOut'|'Да'|
*Рассмотрим работу с адресным классификатором в Комплексной автоматизации для Беларуси.
	И Пауза 2
*Для загрузки адресного классификатора в подсистеме нормативно-справочная информация и администрирование нужно перейти по ссылке Интернет поддержка и сервисы.
	И В командном интерфейсе я выбираю 'НСИ и администрирование' 'Интернет-поддержка и сервисы'
	Тогда открылось окно 'Интернет-поддержка и сервисы'
И текст субтитров "Данный видеоролик создан службой технической поддержки 1эсМинск с использованием инструмента ванэсса аутомэйшн. Спасибо за внимание."

Скрины и пример видео прилагаю.

https://user-images.githubusercontent.com/65770546/109113639-9b805c80-774d-11eb-82e5-972219b3c038.mp4
![Скрин1АдресныйКлассификатор](https://user-images.githubusercontent.com/65770546/109113668-a6d38800-774d-11eb-9f37-60423e8d5b23.png)
![Скрин2АдресныйКлассификатор](https://user-images.githubusercontent.com/65770546/109113672-a76c1e80-774d-11eb-93f5-199e1d51293f.png)
![СкринАдресныйКлассификатор](https://user-images.githubusercontent.com/65770546/109113675-a804b500-774d-11eb-9d05-a0b100e520b3.png)

**Comment by DragunY** [comment]
Дополнительно высылаю водяной знак, скрины, feature-файл и настройки.
[Params_Feature_Screenshots.zip](https://github.com/Pr-Mex/vanessa-automation/files/6189264/Params_Feature_Screenshots.zip)

**Comment by DragunY** [comment]
@Pr-Mex  Дополнительно отправляю архив с фичей, скринами, настройками и намеренно большим водяным знаком, чтобы было четко видно, как он пропадает.
[Params_Feature_Screenshots.zip](https://github.com/Pr-Mex/vanessa-automation/files/6190644/Params_Feature_Screenshots.zip)

**Comment by Pr-Mex** [comment]
@DragunY 
Проблема в том, что вы записываете видео в одном разрешении, а вставку картинок делаете в другом разрешении.
![image](https://user-images.githubusercontent.com/8627416/112589438-24082080-8e12-11eb-8038-d93de33965b7.png)

![image](https://user-images.githubusercontent.com/8627416/112589515-4863fd00-8e12-11eb-810c-b0c6b258c636.png)
