### ISSUE TITLE
Скриншоты в junit

### ISSUE THREAD

**Issue by KrapivinAndrey** [Pr-Mex/vanessa-automation#1162]
Не уверен что любой JUnit переварит, но в GitLab добавили поддержку вывода скриншотов ошибки
https://docs.gitlab.com/ee/ci/unit_test_reports.html#viewing-junit-screenshots-on-gitlab

Таким образом можно обойтись без костылоного Allure.

**Comment by Pr-Mex** [comment]
@KrapivinAndrey 
Расшифруй, плиз.
В каких случаях это может быть полезным и почему Аллюр костыльный )

**Comment by nixel2007** [comment]
Во всех тех же, что и скриншоты в аллюре. В случае если аллюр не используется. Во многих alm есть родные средства просмотра отчётов junit, в отличие от внешнего сайта с аллюром

**Comment by KrapivinAndrey** [comment]
@Pr-Mex Аллюр прекрасен и удобен. Только очень хорошо работает в Jenkins. В GitLab он формируется очень костыльно. Но там удобный junit и теперь вроде поддерживает скрины.

**Comment by Pr-Mex** [comment]
@KrapivinAndrey 
Ты хочешь запилить эту фичу?

**Comment by KrapivinAndrey** [comment]
@Pr-Mex 
Поговорю с админами - надеюсь эту фичу мне включат. А то тестировать не удобно будет.
Если заработает - это сильно упростит переезд на gitlab. Так что - да, я готов ее сделать.

**Comment by Pr-Mex** [comment]
> @Pr-Mex
> Поговорю с админами - надеюсь эту фичу мне включат. А то тестировать не удобно будет.
> Если заработает - это сильно упростит переезд на gitlab. Так что - да, я готов ее сделать.

Ок, держи в курсе, пожалуйста.

**Comment by KrapivinAndrey** [comment]
![image](https://user-images.githubusercontent.com/586025/121340907-8ebcf880-c939-11eb-980e-618f07e439a7.png)
Так. В Gitlab 13.12 заработало. Так что теперь можно и реализовывать

ps. Выглядит ужасно... аллюр приятнее намного

**Comment by KrapivinAndrey** [comment]
Важная поправка. Можно сохранять только один скриншот

**Comment by Pr-Mex** [comment]
@KrapivinAndrey 
Есть движение по задаче?

**Comment by KrapivinAndrey** [comment]
@Pr-Mex Ну вот только только скрины заработали. В Gitlab 13.12.

Теперь можно попробовать код писать.

**Comment by Pr-Mex** [comment]
Решено.
