### ISSUE TITLE
Исправить шаги перезаполнения констант и табличных частей в модуле генерации и заполнении тестовых данных

### ISSUE THREAD

**Issue by Teomit** [Pr-Mex/vanessa-automation#1166]
Необходимо исправить некоторые ошибки в модуле генерации и заполнении тестовых данных:

- [x] - не виден сниппет перезаполнения константы;
- [x] - в описании шага перезаполнения табличной части некорректный текст.

**Comment by Pr-Mex** [comment]
Решено.
