### ISSUE TITLE
При добавлении тега @screenshot в сценарий в СППР, в отчет Аллюр не попадает скриншот.

### ISSUE THREAD

**Issue by ViktorErmakov** [Pr-Mex/vanessa-automation#1173]
Сценарий: получить дополнительный скрин для отладки сценарий на сборочной линии.
  Допустим: добавляем тег @screenshot  перед любым шагом.
  Когда: проверка тестов на Ci CD выполнена
  Тогда: открываю отчет Аллюр, скриншот лежит в артифактах.

```

**Comment by Pr-Mex** [comment]
Решено.
