### ISSUE TITLE
В строке таблицы 2 колонки со списком выбора, при выборе второго списка ошибка отображения

### ISSUE THREAD

**Issue by MaxS-777** [Pr-Mex/vanessa-automation#1178]
Функционал:  подготовка видеоинструкции
   Как разработчик
   Я хочу показать пользователю как заполнить настройки в обработке...

Контекст:
Дано: <версия инструментария> = 1.2.035.1
И <полная версия 1С> = 1С:Предприятие 8.3 (8.3.18.1363)
И <конфигурация запуска> = файловая база

Сценарий: 
  Допустим: я добавил строку в таблицу и заполняю две колонки, выбирая данные из списка значений
  Когда:  заполняю вторую колонку, список значений неправильный - он из первой колонки
  Тогда:  невозможно выбрать корректное значение из списка и тест падает с ошибкой

И В командном интерфейсе я выбираю 'НСИ и администрирование' 'Загрузка номенклатуры из Excel файла'
И Пауза 1
Тогда открылось окно 'Загрузка номенклатуры из Excel файла'

// >> Реквизиты номенклатуры
// И я нажимаю на гиперссылку с именем "ДекорацияОткрытьРеквизитыНоменклатуры"  // не работает в web
И я активизирую поле с именем "ДекорацияОткрытьРеквизитыНоменклатуры"
И я нажимаю сочетание клавиш <ENTER>

// колонка 1

И в таблице "СоответствиеКолонокИРеквизитовСправочника" я добавляю строку
И в таблице "СоответствиеКолонокИРеквизит/овСправочника" я активизирую поле с именем "СоответствиеКолонокИРеквизитовСправочникаНомерКолонкиExcel"
//	И я нажимаю сочетание клавиш <ENTER>
И В таблице "СоответствиеКолонокИРеквизитовСправочника" я нажимаю кнопку выбора у реквизита с именем "СоответствиеКолонокИРеквизитовСправочникаНомерКолонкиExcel"
И Пауза 1
И я выбираю из списка "К1 Наименование"

// колонка 2

И в таблице "СоответствиеКолонокИРеквизитовСправочника" я активизирую поле с именем "СоответствиеКолонокИРеквизитовСправочникаРеквизитНоменклатуры"
И в таблице "СоответствиеКолонокИРеквизитовСправочника" из выпадающего списка с именем "СоответствиеКолонокИРеквизитовСправочникаРеквизитНоменклатуры" я выбираю точное значение 'Наименование'
И в таблице "СоответствиеКолонокИРеквизитовСправочника" я завершаю редактирование строки
// список во второй колонке делается как в первой и происходит ошибка выбора.

![photo_2021-03-28_17-02-36](https://user-images.githubusercontent.com/69005295/112748694-ac8bea00-8fe7-11eb-80d8-a66c0c4308c8.jpg)
![photo_2021-03-28_17-02-52](https://user-images.githubusercontent.com/69005295/112748698-b281cb00-8fe7-11eb-812c-441beb9a316f.jpg)
![photo_2021-03-28_17-03-02](https://user-images.githubusercontent.com/69005295/112748704-b877ac00-8fe7-11eb-8b75-b98ef38af4b3.jpg)

Конфигурация, на которой воспроизводится ошибка.
[1Cv8_TectVA.zip](https://github.com/Pr-Mex/vanessa-automation/files/6217117/1Cv8_TectVA.zip)
[feature_testVA.zip](https://github.com/Pr-Mex/vanessa-automation/files/6217122/feature_testVA.zip)

**Comment by Pr-Mex** [comment]
@MaxS-777 
1. Нужно скрыть панель функций текущего раздела

![image](https://user-images.githubusercontent.com/8627416/113491653-1f5efe80-94db-11eb-9f10-2f31c7bb20cf.png)

**Comment by Pr-Mex** [comment]
@MaxS-777 
2. Не нужно использовать шаг
И я нажимаю сочетание клавиш <ENTER>. Это попытка сэмулировать посыл клавиш активному окну. Этот шаг применяется только там, где не работает АПИ платформы.
Вместо него надо использовать шаги, которые делают соответствующие действия.

**Comment by Pr-Mex** [comment]
@MaxS-777 
3.
Вот пример рабочего сценария
```Gherkin
	И я закрыл все окна клиентского приложения
	
	И В командном интерфейсе я выбираю 'НСИ и администрирование' 'Загрузка номенклатуры из Excel файла'
	Тогда открылось окно 'Загрузка номенклатуры из Excel файла'

	И я активизирую поле с именем "ДекорацияОткрытьРеквизитыНоменклатуры"
	И я нажимаю на гиперссылку с именем "ДекорацияОткрытьРеквизитыНоменклатуры"
		
	И в таблице "СоответствиеКолонокИРеквизитовСправочника" я добавляю строку
	И В таблице "СоответствиеКолонокИРеквизитовСправочника" я нажимаю кнопку выбора у реквизита с именем "СоответствиеКолонокИРеквизитовСправочникаНомерКолонкиExcel"	
	И я выбираю из списка 'К1 Наименование'
	И Пауза 1
	
	И В таблице "СоответствиеКолонокИРеквизитовСправочника" я нажимаю кнопку выбора у реквизита с именем "СоответствиеКолонокИРеквизитовСправочникаРеквизитНоменклатуры"	
	И я выбираю из списка 'К2 Артикул'	

	И в таблице "СоответствиеКолонокИРеквизитовСправочника" я завершаю редактирование строки
	
```

**Comment by MaxS-777** [comment]
Предварительно проверял все варианты. Это ещё раз посмотрю. Но есть неточность в примере.
В таблице "СоответствиеКолонокИРеквизитовСправочника" никак не должно быть списка выбора 'К2 Артикул' Может быть только 'Артикул'.  Проблема как раз в том, что при тестировании ванессой второй список отображается как первый, а при интерактивном выборе руками второй список содержит правильные значения.

**Comment by Pr-Mex** [comment]
> Предварительно проверял все варианты. Это ещё раз посмотрю. Но есть неточность в примере.
> В таблице "СоответствиеКолонокИРеквизитовСправочника" никак не должно быть списка выбора 'К2 Артикул' Может быть только 'Артикул'. Проблема как раз в том, что при тестировании ванессой второй список отображается как первый, а при интерактивном выборе руками второй список содержит правильные значения.

Посмотрите в отладке какие события вызываются в конфигурации в режиме тестирования и при нажатии кнопок мышкой.  Тогда станет понятно почему разное поведение.

**Comment by MaxS-777** [comment]
Посмотрел в режиме отладки. Причина не прояснилась. В режиме тестирования всегда срабатывают события первой колонки. При интерактивном нажатии мышкой срабатывает все корректно - для каждой колонки своё событие.
Это баг платформы такой? Не пойму как это обойти.
В отладке ванессы ПолеРеквизит = Ванесса.НайтиРеквизитТаблицы(  всегда корректное - либо первая, либо вторая колонка.

**Comment by Pr-Mex** [comment]
> Посмотрел в режиме отладки. Причина не прояснилась. В режиме тестирования всегда срабатывают события первой колонки. При интерактивном нажатии мышкой срабатывает все корректно - для каждой колонки своё событие.
> Это баг платформы такой? Не пойму как это обойти.

Не готов сказать почему события отрабатывают по разному.
Возможно у вас особый случай и нужно попробовать написать свой шаг/шаги используя апи платформы по автотестированию.
Либо попробовать зарегистрировать ошибку платформы.
