### ISSUE TITLE
Ошибка подключения менеджера тестирования к клиенту тестирования (веб-клиент) 

### ISSUE THREAD

**Issue by Aleksandrk12** [Pr-Mex/vanessa-automation#1180]
Добрый день.

Проблема с подключением клиента тестирования (веб).
При вызове метода "УстановитьСоединение" возвращается ошибка:
Ошибка подключения к клиенту тестирования. Отсутствует подходящий клиент тестирования.

Хотя клиент тестирования запущен (веб-клиент).
Сервер и порт указывается вручную (не локалхост).

Не подскажите, в какую сторону копать ?

**Comment by Pr-Mex** [comment]
@Aleksandrk12 
Добрый день.
Покажите скриншот настроек клиентов тестирования в VA.

**Comment by Aleksandrk12** [comment]
> @ Aleksandrk12
> Добрый день.
> Покажите скриншот настроек тестирования в VA.


![vanessa](https://user-images.githubusercontent.com/81692281/113245037-96c04280-92cf-11eb-91fb-abfdd3160f92.JPG)
![vanessa2](https://user-images.githubusercontent.com/81692281/113245038-9758d900-92cf-11eb-9550-efb1f15d4c35.JPG)
![vanessa3](https://user-images.githubusercontent.com/81692281/113245039-97f16f80-92cf-11eb-956d-f11eb4ae72fe.JPG)

**Comment by Pr-Mex** [comment]
@Aleksandrk12 
1. Убедитесь что версия платформы менеджера и клиента одинаковые.
2. Что с ПК, где запускается менеджер доступен по сети менеджер кластера.

**Comment by Aleksandrk12** [comment]
> @Aleksandrk12
> 
> 1. Убедитесь что версия платформы менеджера и клиента одинаковые.
> 2. Что с ПК, где запускается менеджер доступен по сети менеджер кластера.

1. Одинаковые 8.3.17.1549
2. Расскажите, пожалуйста, чуть подробней, как это можно проверить

**Comment by Pr-Mex** [comment]
> > @Aleksandrk12
> > 
> > 1. Убедитесь что версия платформы менеджера и клиента одинаковые.
> > 2. Что с ПК, где запускается менеджер доступен по сети менеджер кластера.
> 
> 1. Одинаковые 8.3.17.1549
> 2. Расскажите, пожалуйста, чуть подробней, как это можно проверить

С вашего ПК менеджер кластера как минимум должен пинговаться.
Плюс также, по-моему должно работать подключение через telnet.

Для чистоты эксперимента можете попробовать поднять локально файловую базу и попробовать запустить web клиент на ней. Порт в этом случае обычно будет 1538.

**Comment by Aleksandrk12** [comment]
> > > @Aleksandrk12
> > > 
> > > 1. Убедитесь что версия платформы менеджера и клиента одинаковые.
> > > 2. Что с ПК, где запускается менеджер доступен по сети менеджер кластера.
> > 
> > 
> > 
> > 1. Одинаковые 8.3.17.1549
> > 2. Расскажите, пожалуйста, чуть подробней, как это можно проверить
> 
> С вашего ПК менеджер кластера как минимум должен пинговаться.
> Плюс также, по-моему должно работать подключение через telnet.
> 
> Для чистоты эксперимента можете попробовать поднять локально файловую базу и попробовать запустить web клиент на ней. Порт в этом случае обычно будет 1538.

Сервер пингуется успешно. Так же, проверил соединение с помощью команды tnc и telnet. В обоих случаях успешно
![проверка соединения сервера и порта](https://user-images.githubusercontent.com/81692281/113513364-cf3b7700-9582-11eb-8867-19d0b2576de5.JPG)
Так же, запускал ванессу на самом сервере, где менеджер кластера. Результат не поменялся. Клиент тестирования так и не находит.

Может быть есть ещё какие-либо варианты ?

**Comment by Pr-Mex** [comment]
> > > > @Aleksandrk12
> > > > 
> > > > 1. Убедитесь что версия платформы менеджера и клиента одинаковые.
> > > > 2. Что с ПК, где запускается менеджер доступен по сети менеджер кластера.
> > > 
> > > 
> > > 
> > > 1. Одинаковые 8.3.17.1549
> > > 2. Расскажите, пожалуйста, чуть подробней, как это можно проверить
> > 
> > 
> > С вашего ПК менеджер кластера как минимум должен пинговаться.
> > Плюс также, по-моему должно работать подключение через telnet.
> > Для чистоты эксперимента можете попробовать поднять локально файловую базу и попробовать запустить web клиент на ней. Порт в этом случае обычно будет 1538.
> 
> Сервер пингуется успешно. Так же, проверил соединение с помощью команды tnc и telnet. В обоих случаях успешно
> ![проверка соединения сервера и порта](https://user-images.githubusercontent.com/81692281/113513364-cf3b7700-9582-11eb-8867-19d0b2576de5.JPG)
> Так же, запускал ванессу на самом сервере, где менеджер кластера. Результат не поменялся. Клиент тестирования так и не находит.
> 
> Может быть есть ещё какие-либо варианты ?

Ещё есть вариант,  что на сервере застряло имя подключения. Такое может быть, например, если закрыли в браузере вкладку с 1С крестиком. 
Попробуйте заменить webkis на webkis1,  например. Также можно перезапустить сервер.

**Comment by Aleksandrk12** [comment]
Имя поменял, результат тот же.
![Смена имени](https://user-images.githubusercontent.com/81692281/113538216-1746b200-95f4-11eb-8fef-c1603ce5e74b.JPG)

А перезагрузить попробовать веб-сервер или сервер 1с ?

**Comment by Pr-Mex** [comment]
> Имя поменял, результат тот же.
> ![Смена имени](https://user-images.githubusercontent.com/81692281/113538269-3c3b2500-95f4-11eb-9b42-15e25a117071.JPG)
> 
> А перезагрузить попробовать веб-сервер или сервер 1с ?

Да, стоит попробовать

**Comment by Pr-Mex** [comment]
Решено.
