### ISSUE TITLE
При записи ошибок в формате СППР, к имени файла с ошибкой дописывается абсолютный путь

### ISSUE THREAD

**Issue by DoublesunRUS** [Pr-Mex/vanessa-automation#1181]
Включена запись ошибок в формате СППР. Указан каталог куда помещать ошибки.
После окончания тестирования в каталог попадают как xml файлы с ошибками, так и скриншоты к ним.
Но при этом вместе с файлом скриншота указывается абсолютный путь. Причем не тот, который указан в качестве пути для сохранения ошибок СППР, а путь указанный в настройках КаталогВыгрузкиСкриншотов.
```
	<Property name="ИменаФайлов">
		<Value xsi:type="Array">
			<Value xsi:type="xs:string">F:\screenShots\74784c63-1b3a-4dda-a9fb-ca4c0c6015aa-attachment.png</Value>
			<Value xsi:type="xs:string">F:\screenShots\24f11c13-98c4-46b3-81f6-960d4ccb1dc3-attachment.png</Value>
		</Value>
	</Property>
```

**Comment by Pr-Mex** [comment]
Решено.
