### ISSUE TITLE
Добавить обновление таблиц во время работы шагов типы "я жду что в таблице...."

### ISSUE THREAD

**Issue by WizaXxX** [Pr-Mex/vanessa-automation#1182]
Доработать шаги типа "я жду что в таблице ...." таким образом, что бы они сами выполняли обновление таблицы если это возможно

**Comment by Pr-Mex** [comment]
@WizaXxX 
Привет! Интересная доработка!
Я правильно понимаю, что это касается только шагов, которые проверяют таблицы (формы списка, табличные части и т.п.)?

**Comment by Pr-Mex** [comment]
@WizaXxX 
Ещё вопрос - это будет работать, если конфигурация запущена на английском инетрфейсе?

**Comment by WizaXxX** [comment]
@Pr-Mex 
> @WizaXxX
> Привет! Интересная доработка!
> Я правильно понимаю, что это касается только шагов, которые проверяют таблицы (формы списка, табличные части и т.п.)?

Да, все верно.


> @WizaXxX
> Ещё вопрос - это будет работать, если конфигурация запущена на английском инетрфейсе?

Исправлю.

**Comment by Pr-Mex** [comment]
Решено.
