### ISSUE TITLE
Ошибка при загрузке фичи файлов : Поле объекта не обнаружено (Тип)

### ISSUE THREAD

**Issue by Wadus16** [Pr-Mex/vanessa-automation#1215]
Версия платформы : 8.3.18.1208
Версия VA : single 1.2.036.1
OC : windows 10

Сценарий воспроизведения :
1. Создаем пустую файловую базу и прописываем ключ запуска TESTMANAGER;
2. Скачиваем фичи из архива распаковываем в папке, в этой же папке ложим VA single - https://disk.yandex.ru/d/aTigGp5nvpxxtg ;
3. Отрываем сначала в VA фичи-файл "Базовая функциональность" - он открывается без ошибок, следом в этом же окне VA открываем фичи-файл "Сопровождение" и видим ошибку "ВнешняяОбработка.VanessaAutomationsingle.МодульОбъекта(6752)}: Поле объекта не обнаружено (Тип)"

> Прикладывайте файлы скриншотов
![Screenshot_1](https://user-images.githubusercontent.com/39588109/117957846-1efc2380-b323-11eb-85f7-641f28b21f5d.png)

**Comment by Pr-Mex** [comment]
@Wadus16 
Спасибо, посмотрю.

**Comment by Pr-Mex** [comment]
Решено.
