### ISSUE TITLE
Ошибка при подборе шагов

### ISSUE THREAD

**Issue by shcherbakov-vadim** [Pr-Mex/vanessa-automation#1231]
Контекст:
  Дано: VA 1.2.036.11
  И 1C 8.3.18.1483 (x64)
  и пустая файловая ИБ

Сценарий: Открытие формы подбора шагов
  Допустим: Открываем обработку vanessa-automation.epf в пустой ИБ
  Когда: Нажимаем на кнопку создания нового сценария
  И нажимаем кнопку контекстного меню "Подбор шагов"
  Тогда: выводится ошибка Неправильный путь к файлу 'memory:85c0d5dd-49eb-4212-8799-69506410ff6c'. Схема не зарегистрирована
![2021-05-26_23-19-04](https://user-images.githubusercontent.com/52153345/119726298-a85e3a80-be79-11eb-9369-949ce1f11147.png)

**Comment by Pr-Mex** [comment]
Решено.
