### ISSUE TITLE
Возможность показать отчет Allure по результату локального выполнения тестов.

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1233]
Возможность показать отчет Allure по результату локального выполнения тестов.

**Comment by DitriXNew** [comment]
Только стоит добавить путь к allure, а то иначе - если нет переменной среды, то кнопка не открывает ничего, а у QA нет прав админа, зачастую, та и не знают они - где это прописывать.
Это раз уж тема про локальные отчеты.

**Comment by Pr-Mex** [comment]
> Только стоит добавить путь к allure, а то иначе - если нет переменной среды, то кнопка не открывает ничего, а у QA нет прав админа, зачастую, та и не знают они - где это прописывать.
> Это раз уж тема про локальные отчеты.

Путь задаётся в настройках формирования отчетов.

**Comment by DitriXNew** [comment]
я не смог найти это место.

**Comment by Pr-Mex** [comment]
@DitriXNew Сервис/Отчёты о выполнении/Allure

**Comment by DitriXNew** [comment]
Я не вижу даже по коду - где прописывается путь к утилитам аллюра
![image](https://user-images.githubusercontent.com/11927866/125676053-e2bca974-6e05-45be-a4e1-0f8389631a7b.png)

**Comment by DitriXNew** [comment]
просто идет вызов комманды allure, а если у меня аллюр не прописан в переменных среды винды, т.е. при выполнении команды allure в cmd - я получу ошибку

**Comment by asosnoviy** [comment]
@DitriXNew https://docs.qameta.io/allure/#_manual_installation

**Comment by asosnoviy** [comment]
> Только стоит добавить путь к allure, а то иначе - если нет переменной среды, то кнопка не открывает ничего, а у QA нет прав админа, зачастую, та и не знают они - где это прописывать.
> Это раз уж тема про локальные отчеты.

Если QA не знает про свои инсnрументы и настройку среды это не QA

**Comment by Pr-Mex** [comment]
> @DitriXNew https://docs.qameta.io/allure/#_manual_installation
> Аллюр должен быть в путях. Как и гит и оскрипт и жаба и много что еще.

Аааа, так вот про что была речь. @asosnoviy Спасибо )

@DitriXNew Да, нужно сначала Allure корректно установить на комп прежде чем его использовать.

**Comment by DitriXNew** [comment]
Вначале хотел поспорить, но решил, что не буду.
Просто отбивайтесь от народа, который видит тупо "не работающую" кнопку, и которые не бывают джунами, а сразу становятся синьорами, с админскими правами, с навыками программирования, чтобы найти, что эта кнопка не работает изза того, что не указан аллюр в переменных среды :)

**Comment by Pr-Mex** [comment]
> Вначале хотел поспорить, но решил, что не буду.
> Просто отбивайтесь от народа, который видит тупо "не работающую" кнопку, и которые не бывают джунами, а сразу становятся синьорами, с админскими правами, с навыками программирования, чтобы найти, что эта кнопка не работает изза того, что не указан аллюр в переменных среды :)

Я думаю надо просто добавить сообщение, что Allure не установлен.

**Comment by asosnoviy** [comment]
Помню где то были магические кнопки по установке всякого под видео инструкции, можно что то подобное и под аллюр сделать.

**Comment by Pr-Mex** [comment]
> Помню где то были магические кнопки по установке всякого под видео инструкции, можно что то подобное и под аллюр сделать.

@asosnoviy 
Да, в автоинструкциях есть такое. Можно и сюда добавить.

**Comment by asosnoviy** [comment]
Ну или просто отразить в доке, что аллюр тоже надо "ставить", а не просто качать +)
Там кстати есть пункт:

"To run commandline application, Java Runtime Environment must be installed."

**Comment by Pr-Mex** [comment]
Решено.
