### ISSUE TITLE
Значение не является значением объектного типа (Свойство)

### ISSUE THREAD

**Issue by hawk911** [Pr-Mex/vanessa-automation#1239]
```Gherkin
Контекст:
  Дано: 1.2.036
  И 8.3.17.1549
```

`Значение не является значением объектного типа (Свойство)
{ExternalDataProcessor.VanessaAutomationsingle.Form.УправляемаяФорма.Form(37060)}:	Если НЕ СтрокаСценария.ПроизвольныеЗначения.Свойство("МассивСкриншотов") Тогда
{ExternalDataProcessor.VanessaAutomationsingle.Form.УправляемаяФорма.Form(10993)}:			ДобавитьИмяФайлаСкриншотаКСтрокеТекущегоСценария(ДанныеФайла);
`

**Comment by Pr-Mex** [comment]
Решено.
