### ISSUE TITLE
Нужен шаг, который позволяет активизировать колонку таблицы в нужной группе шагов

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#124]
Когда в таблице есть много колонок с одинаковым заголовком и с именем, которое содержит UID, возникает проблема с активизацией нужной колонки.
Поэтому нужны шаги:

```Gherkin
	И в таблице "ИмяТаблицы" я активизирую колонку "ИмяКолонки" в группе "ИмяГруппы"
	И в таблице "ИмяТаблицы" я активизирую колонку с именем "ИмяКолонки" в группе "ИмяГруппы"
```

**Comment by Pr-Mex** [comment]
Решено.

**Comment by JaneGlass73** [comment]
@Pr-Mex , здравствуйте я же правильно понимаю, что если у меня структура групп колонки такова что уникальность отслеживается только на втором или более от последнего уровня то это мне не поможет, другими словами у меня есть поле с синонимом 
"Σ" входящее в группу "Новый" которое входит в состав группы "Июнь 2025" имена полей все с гуидами которые генерируются на лету к ним не привязаться. Можно как то указывать верхнестоящие группы в параметре? Например так 
**И в таблице "КроссТаблица" я активизирую колонку "Σ" в группе "Новый|Июнь 2025"** или так
**И в таблице "КроссТаблица" я активизирую колонку "Σ" в группе "Июнь 2025"** (опустив не уникальную колонку)

**Comment by Pr-Mex** [comment]
@JaneGlass73 
По-моему вы это же спрашивали в телеграмме.
В этом случае проще сделать расширение для этой формы, которое вернёт вам уникальное имя колонки.

**Comment by JaneGlass73** [comment]
> По-моему вы это же спрашивали в телеграмме.

Все верно, я сразу во все двери стучусь. 

> проще сделать расширение для этой формы

Проще, но не лучше, в итоге в телеграмм решили что лучше все таки сделать шаг. Я посмотрела логику кода Вашего шага, как мне кажется, его можно легко адаптировать к моему кейсу. Вот пока не решила как лучше сделать - "прокачать" Ваши шаги, ну чтобы можно было список колонок передавать в строке через разделитель, или написать новые. Пока склоняюсь прокачать ваши. Нам будет проще - один файл подменить у всех. И, кажется, проще будет зареквестить изменения потом, так как ничего кроме модуля шага не придётся изменять. Совместимость сохранится, на быстродействие не повлияет.

**Comment by Pr-Mex** [comment]
@JaneGlass73 
Да, давайте попробуем.
