### ISSUE TITLE
Ошибка при загрузка полей неограниченной длины с многострочным текстом

### ISSUE THREAD

**Issue by KalyakinAG** [Pr-Mex/vanessa-automation#1242]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Заполнение тестовых данных
   Как Разработчик
   Я хочу Загрузить тестовые данные из таблицы Геркен

Контекст:
  Дано: 1.2.036
  И 1С:Предприятие 8.3 (8.3.18.1483)
  и БСП 3.1.3.417


Сценарий: загрузка данных из полей неограниченной длины с многострочным текстом
  Допустим: есть справочник с полем Описание типа строка с неограниченной длиной и с многострочным текстом
  Когда: происходит выгрузка в таблицу Геркен
  Тогда: многострочный текст нарушает формат таблицы

```
![image](https://user-images.githubusercontent.com/6729749/120520425-72223d00-c3dc-11eb-9be7-668efcad8e49.png)

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
@DitriXNew 
Посмотри. пожалуйста.

**Comment by DitriXNew** [comment]
переносы строк не поддерживаются, или их можно попробовать экранировать. Тут используется десериализация самой ванесы. Так что если конвертатор поддерживает такое - то тогда должно работать.
@Pr-Mex поддерживает ли конвертатор экранирование переноса?

**Comment by Pr-Mex** [comment]
> переносы строк не поддерживаются, или их можно попробовать экранировать. Тут используется десериализация самой ванесы. Так что если конвертатор поддерживает такое - то тогда должно работать.
> @Pr-Mex поддерживает ли конвертатор экранирование переноса?

@DitriXNew 
Да, с помощью \n нужно экранировать перенос строк.

**Comment by Pr-Mex** [comment]
Решено.
