### ISSUE TITLE
Возможность запустить сеанс клиента тестирования повторно, если процесс не клиента тестирования не запустился.

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1245]
Возможность запустить сеанс клиента тестирования повторно, если процесс не клиента тестирования не запустился.
Нужна возможность включить опцию и надо задать интервал, с которым будет происходить попытка запуска клиента тестирования.

**Comment by nixel2007** [comment]
Звучит здорово!

**Comment by Pr-Mex** [comment]
Решено.
