### ISSUE TITLE
Уважение к параметрам из файла VAParams.

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1254]
1. Должна быть возможность любой параметр из https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/CommandSetting.md передавать в VAParams.
2. Закешировать чтение переменных среды, данных из командной строки и файла VAParams.json.

**Comment by Pr-Mex** [comment]
@nixel2007 
Теперь параметры командной строки https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/CommandSetting.md можно передавать через VAParams.json.

**Comment by nixel2007** [comment]
Супер!

**Comment by Pr-Mex** [comment]
Решено.
