### ISSUE TITLE
Если возникает ошибка вычисления значения переменной, то не выполняется конструкция "Попытка ... Исключение"

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#1259]
Если возникает ошибка вычисления значения переменной, например, "Преобразование значения к типу Число не может быть выполнено", то после конструкции "Попытка ... Исключение ... КонецПопытки" код сценария не выполняется.

Описание воспроизведения:

Выполнить код сценария, который ниже. После падения в группе "Попытка 1", код в группе "Попытка 2" не выполнится.

*Попытка 1
         
        Попытка
                 
                И Я запоминаю значение выражения 'Число($Test1$)' в переменную "Test1"
                И Я запоминаю значение выражения 'Число($Test1$ + 1)' в переменную "Test1"
                 
                Если "Число($Test1$) = 1" Тогда
                         
                        И Я запоминаю в переменную "Test1" значение "01"
                         
                КонецЕсли
                 
        Исключение
                 
                И я регистрирую ошибку "Описание ошибки" по данным исключения
                 
        КонецПопытки
         
*Попытка 2
         
        Попытка
                 
                И я вывожу значение переменной "Test2"
                 
        Исключение
                 
                 
                И я регистрирую ошибку "Описание ошибки" по данным исключения
                 
        КонецПопытки

Версия VA для СППР:  1.2.036.1
Платформа: 8.3.18.1433

**Comment by Pr-Mex** [comment]
Решено.
