### ISSUE TITLE
При вставке значения переменной в поле обработки возникает ошибка.

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#1260]
Если возникает ошибка вычисления значения переменной, например, "Преобразование значения к типу Число не может быть выполнено", то после конструкции "Попытка ... Исключение ... КонецПопытки" код сценария не выполняется.

Описание воспроизведения:

![-636919586](https://user-images.githubusercontent.com/68432407/122062820-6c732100-cdf8-11eb-98d4-288395917843.png)

Нужно что бы по ходу выполнения ниже приведенного сценария была доступна для выбора косоль запросов.
Далее нужно выполнить сценарий:

И я запоминаю значение выражения "Test" в переменную "ВыражениеУсловия"
И я активизирую окно текущего клиента тестирования
И я выбираю файл "КонсольЗапросов.epf" ВК
Тогда открылось окно "Консоль запросов*"
И в поле с именем "ТекстЗапроса" я ввожу значение переменной "ВыражениеУсловия"

Версия VA для СППР: 1.2.036.1
Платформа: 8.3.18.1433

**Comment by Pr-Mex** [comment]
@egorovsergio 
Нужен полный пример для воспроизведения проблемы.

**Comment by Pr-Mex** [comment]
Решено.
