### ISSUE TITLE
При использовании шага "И в таблице "ИмяТаблицы" я перехожу к строке по шаблону" поиск в ТЧ всегда выполняется с начала ТЧ.

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#1266]
При использовании шага "И в таблице "ИмяТаблицы" я перехожу к строке по шаблону" поиск в ТЧ всегда выполняется с начала ТЧ. Если использовать шаг "И в таблице "ИмяТаблицы" я перехожу к строке", в то время когда курсором выделена последняя строка в списке, то переход выполнится к последней строке в ТЧ, в которой присутствуют нужные символы.

Для воспроизведения нужно запустить сценарий на любой демо базе ERP 2, УТ или КА:

Дано Я открываю навигационную ссылку "e1cib/list/Справочник.ВидыНоменклатуры"
Тогда открылось окно "Виды номенклатуры"
И я нажимаю на кнопку с именем 'ФормаСписок'

Цикл И я делаю 2 раз
        
        И в таблице "Список" я перехожу к последней строке
        И я нажимаю на кнопку с именем 'Скопировать'
        И я жду открытия окна отличного от "Виды номенклатуры" в течение 20 секунд
        И в поле с именем 'Наименование' я ввожу текст 'Test'
        И я перехожу к следующему реквизиту
        И я нажимаю на кнопку с именем 'ФормаЗаписатьИЗакрыть'
        И я жду закрытия окна 'Вид номенклатуры*' в течение 20 секунд
        Тогда открылось окно 'Виды номенклатуры'
        
КонецЦикла
И в таблице "Список" я перехожу к последней строке
И в таблице "Список" я перехожу к строке по шаблону
        | 'Наименование' |
        | 'Test*'        |
//Произойдёт переход с первой строке "Test" группы строк "Test"
И пауза 5
И в таблице "Список" я перехожу к последней строке
И в таблице "Список" я перехожу к строке
        | 'Наименование' |
        | 'Test'         |
//Произойдёт переход с последней строке "Test" группы строк "Test"

Версия VA: 1.2.036.1
Версия платформы: 8.3.18.1483

**Comment by Pr-Mex** [comment]
Это особенность алгоритма перехода к строкам.
