### ISSUE TITLE
Некорректно отрабатывает условие "Если...ИначеЕсли...Иначе..." в конструкции "Попытка...Исключение...КонецПопытки"

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#1270]
Если в конструкции "Попытка...Исключение...КонецПопытки" использовать условие "Если...ИначеЕсли...Иначе...", то   выполняться будет часть "Если" и часть "Иначе". Если выполнять условие без конструкции "Попытка...Исключение...КонецПопытки", то условие отработает корректно - выполнится только в части "Если".

Для воспроизведения в VA в СППР нужно выполнить сценарий:

И я запоминаю значение выражения '\"\"' в переменную "ВыполнитьПО"

Попытка

   Если переменная "ВыполнитьПО" имеет значение "" Тогда

      И я перехожу к следующему реквизиту

   ИначеЕсли переменная "ВыполнитьПО" имеет значение "ТекущаяДата" Тогда

      И я активизирую поле с имененм "ДатаНачала"
      И я запоминаю значение текущего поля как "ДатаИВремяНачала"
      И в поле с именем 'ДатаЗавершения' я ввожу текст '$ДатаИВремяНачала$'
      И я перехожу к следующему реквизиту

   Иначе

      И в поле с именем 'ДатаЗавершения' я ввожу текст '$ВыполнитьПО$'
      И я перехожу к следующему реквизиту

   КонецЕсли

Исключение

   И я регистрирую ошибку "Описание ошибки" по данным исключения

КонецПопытки
![Безымянный](https://user-images.githubusercontent.com/68432407/124743042-fdd04180-df25-11eb-81a6-78b62455bd82.png)

Версия VA: 1.2.036.1
Платформа: 8.3.18.1483

**Comment by Pr-Mex** [comment]
@egorovsergio это уже исправляюсь. Проверь на версии из develop, пожалуйста.

**Comment by Pr-Mex** [comment]
Решено.
