### ISSUE TITLE
Расширение синтаксиса языка Gherkin. Новая секция в фиче - Переменные

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1278]
Новая секция в фиче - Переменные.

Нужна, чтобы описывать:
1. Простые строковые переменные
2.  Вычисляемые переменные ( выражение пишется в фигурных скобках {} )
3. Таблицы переменных

Позволяет упростить жизнь в тех случаях, когда нужно объявлять либо много констант, либо нужно в одном месте объявить набор констант. Например - при задачах выполнения теста в интерфейсах на многих языках.

**Comment by Pr-Mex** [comment]
Пример как это может выглядеть
![image](https://user-images.githubusercontent.com/8627416/125486471-5469a8c4-6daf-47f0-836f-8a6d72907ec4.png)

**Comment by Pr-Mex** [comment]
Данные в секции Переменные вычисляются перед началом выполнения сценария.

**Comment by Pr-Mex** [comment]
Если объявлена таблица переменных то можно в шаг передавать значение через точку. Пример
![image](https://user-images.githubusercontent.com/8627416/125487907-318ca108-7ffa-4aad-964e-595c7891ff59.png)

**Comment by Pr-Mex** [comment]
При наведении мышки на имя такой явно объявленной переменной в тексте сценария появляется дополнительное описание, которое берётся из второй колонки таблицы.
![image](https://user-images.githubusercontent.com/8627416/125488459-28681ecb-5059-4a0b-95f2-ac00d13c06ff.png)

**Comment by DitriXNew** [comment]
Собственно идея в том, чтобы дать QA инженерам немного больше свободы.
И делать более универсальные тесты.

Условно, у меня есть шаг, где я ищу контрагента по имени, а имя у него может быть разным, в зависимости от языка данных пользователя. Тогда я могу просто определить переменную ```Контрагент1``` и дальше выполнять поиск этой переменной.

Аналогично и с общими интерфейсами.
Есть тест, где система ругается при записи, что реквизит не заполнен.
Теперь берем 2 ситуации:
1. Реквизит переименовали (был синоним ```контрагент```, а стал ```покупатель```)
2. Я запускаю тест на пользователе с английским языком.

В класической ситуации, для первого случая - мне надо изменить тест. Так сообщение об ошибке будет другим. Что не очень удобно, так как вначале я прогоню тест, подожду пару часов, а потом вылезет вот такой не значительный косяк данных внутри теста.
А для второго случая - вообще адекватного решения нет.

Однако, если я изначально сделаю такую конструкцию:
```ОшибкаКонтрагента = "Не заполнен реквизит: {!Метаданные.Документы.Заказ.Контрагент.Синоним}"```

И дальше буду делать проверку именно на эту переменную ```$ОшибкаКонтрагента$```
То я тогда вообще исключу появление первой ситуации, и решу автоматом проблему мультиязычных тестов, так как просто буду брать синонимы на лету.

Помимо этого не редко в тестах возникают случаи когда надо где то храть длинные строки, и строки, которые складываются из каких то данных на форме.
Сейчас это сложно, так как надо делать шаги вычиследния и помещения в переменную, а теперь - это всего лишь добавляется два символа ```{}```
И, точно также - я теперь могу сразу задавать нужные мне типы и форматы данных.
Условно:
```Булево = {Истина}```
```СтрокаНачаласьСHTTP = {СтрНачинаетсяС($СтрокаПодключения$, "http"}```
```НачалоТкущегоМесяца = {НачалоМесяца(ТекущаяДата())}```
И т.д. 

Этот механизм не призван тотально заменить существующие, но он позволит, по сути, в любом месте где есть строка - подставить переменную, которую можно вычислить в том числе и динамически.

Например:
```Переменные:
Остаток = {!РегистрыНакопления.РегистрНакопления1.Остатки()}

Сценарий:
Бла бла бла, я провожу документ
Тогда Если {$Остаток$ = {Остаток}} // т.е. сравниваем текущее значения остатка, с новым расчетным
...
```

Основная цель - насыпать сахара, чтобы немного облегчить жизнь разработчикам и тестировщикам. А то текущий вариант использования переменных и выполнения кода - слишком уж не удобен для работы.

**Comment by DitriXNew** [comment]
Вторая часть на счет таблиц.
Ее область применения проста - я не хочу писать в самом тесте эти огромные таблицы, тест становится не читабельным.
И если надо одни и те же данные подставлять, то это вообще превращается в ужас.

А так - вынесли в одно место, в одном месте изменили, и на все автоматом применилось.

**Comment by nixel2007** [comment]
а чем для переменных секция "Контекст" не угодила? она вычисляется перед каждым сценарием, в VA уже есть шаги по работе с переменными, по вычислению значений, по использованию переменных в шагах. Да, inline-вычисление значения без промежуточного сохранения в переменную - это удобно, согласен. Но вот остальные предложения смущают.

**Comment by DitriXNew** [comment]
тем что так удобнее настраивать парсер и поиск по редактору кода, подсветки ссылок и прочее.
По факту - все это можно и в область контекста засунуть, а можно вообще отдельными шагами сделать.
Так что это скорее просто сахар и удобство для редактора.

Плюс, там будут формировать таблицы данных для загрузки, а значит компоненте которая будет формировать эту секцию и перезаписывать - будет проще найти, распарсить, подрузить и заменить.

Ну и то, что ты верно написал - контекст высчитывается перед каждым сценарием, а тут в этом может не быть необходимости, но если надо, то переменные можно переопределить действительно в контексте, и тогда они будут обновляться.

**Comment by Pr-Mex** [comment]
> а чем для переменных секция "Контекст" не угодила? она вычисляется перед каждым сценарием, в VA уже есть шаги по работе с переменными, по вычислению значений, по использованию переменных в шагах. Да, inline-вычисление значения без промежуточного сохранения в переменную (из #1279) - это удобно, согласен. Но вот остальные предложения смущают.

Спасибо за коммент.
Думаю да, можно было бы всё положить в секцию Контекст, но хочется, наверное, обособить новую фичу от обычного Gherkin, если это возможно.
Она не всем нужна.

**Comment by lintest** [comment]
Поддержка новой секции "Паременные" реализована в редакторе VAEditor  https://github.com/Pr-Mex/vanessa-automation/pull/1281

**Comment by lintest** [comment]
![image](https://user-images.githubusercontent.com/92895/126002278-c9ccb4d5-27b0-493f-9e05-6ff612f6c36c.png)

**Comment by Pr-Mex** [comment]
Добавлена возможность импортировать переменные из другой фичи.
Синтаксис:
import "FileName.feature"

**Comment by Pr-Mex** [comment]
Решено.
