### ISSUE TITLE
Поправьте формат даты при разных вариантах её "прочтения"

### ISSUE THREAD

**Issue by lelikanet** [Pr-Mex/vanessa-automation#1291]
На форме документа - формат даты короткий ("дд.мм.гггг")
А если получать состояние формы в виде шагов - то длинный ("дд.мм.гггг чч:мм:сс")
Используемый шаг всегда "И элемент формы с именем "ИмяЭлемента" стал равен 'Значение'"
Ожидается, что формат и при прочтении в сценарии и при получения значений всей формы в виде шагов будет единообразно. В соответствии с тем значением и форматом что есть в действительности. В моём случае это должен быть короткий вормат "дд.мм.гггг"
![image](https://user-images.githubusercontent.com/45041332/127183832-84876b3a-bd20-441a-8f47-33f6159d1c15.png)

**Comment by Pr-Mex** [comment]
@lelikanet 
Видимо апи платформы отдаёт такое представление поля.
Просто используйте не полное сравнение поля а по шаблону, чтобы можно было с помощью * заэкранировать часть строки.

**Comment by Pr-Mex** [comment]
Решено.
