### ISSUE TITLE
Поправить чтение из файла, и добавление недостающих параметров в vaparams

### ISSUE THREAD

**Issue by lelikanet** [Pr-Mex/vanessa-automation#1292]
Показывается ошибка, когда после загрузки vaparams (чистый кэш) жмёшь "Показывать различия в редакторе отдельно". Галочка на пункте изначально - стояла. Скрин с демонстрацией куда нажимать - уже после ошибки. Галочка снялась.
Файл настроек приложен всю информацию, что мне хотелось скрыть - заменена на "***". Также сменён формат файла с json на txt. Полагаю в этом issues кроется секрет и суть того, что vaparams не загружаются корректно из файла.
![image](https://user-images.githubusercontent.com/45041332/127299956-d9023986-a0d1-4abb-ac02-046c8e80ce48.png)
![image](https://user-images.githubusercontent.com/45041332/127299969-1c639e14-085c-447b-af5f-e8fc4722b58c.png)
[vanessaParamissues.txt](https://github.com/Pr-Mex/vanessa-automation/files/6892003/vanessaParamissues.txt)

```
Значение не является значением объектного типа (type)
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(3830)}:	Если Вкладка.type = "vs.editor.IDiffEditor" Тогда
{ВнешняяОбработка.VanessaAutomation.Форма.РаботаСGit.Форма(260)}:	Если НЕ Ванесса.ЭтоВкладкаDiff(Ванесса.VanessaTabs.current) Тогда
{ВнешняяОбработка.VanessaAutomation.Форма.РаботаСGit.Форма(38)}:	УстановитьРежимОтображенияРазличийУТекущейВкладки();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(2029)}:	МодульРаботаСGit().ВидОтображенияОтличийВРедактореПриИзменении();	
```

**Comment by Pr-Mex** [comment]
Решено.
