### ISSUE TITLE
Ошибка передачи параметров структуры сценария во вложенные сценарии

### ISSUE THREAD

**Issue by PavelVir** [Pr-Mex/vanessa-automation#13]
Функционал: Как разработчик тестов я хочу иметь возможность создавать сложные структуры сценариев со вложенными сценариями и параметрами 

Контекст:
  Дано:  Ванесса 1.2.009
  И 8.3.10

Сценарий: 

При указании в качестве параметров вложенного сценария параметра типа <Парам> неправильно происходит замена параметров внутри вложения и далее примеры неверное подставляются.

![default](https://user-images.githubusercontent.com/40602668/43652226-41920508-974d-11e8-9abf-d40493fafb9b.png)

![default](https://user-images.githubusercontent.com/40602668/43652245-4bf46324-974d-11e8-89e9-259b21a5f38e.png)

Сценарий для проверки из самотеста

Структура сценария: Перемещение по группам и фасовка 4
	Когда первый шаг <ШК>	
	Когда шаг дерево 
		И шаг лист <ШК>
		И перейти к <ШК> таблице:
		| Кол1 | Кол2|
		И вызов экспортного сценария для структуры сценария <ШК>
	И финальный шаг <ШК>	
				
		Примеры:
			|ШК           |
			|'2200001008004'|
			|2200001015504|

Сценарий: Вызов экспортного сценария для структуры сценария "Парам1"
	Когда Простой шаг "Парам1"

**Comment by slaxxals** [comment]
Чтобы не дублировать обсуждение, столкнулся скорее всего с этой же проблемой.
Вызов экспортного сценария из другого сценария читает параметры без проблем.

Но, вызов экспортного сценария из Структуры сценария с Примерами - переданные параметры не передаются в экспортный сценарий, вместо них название переменных экспортного сценария.

Пример сценария:

```gherkin
#language: ru

@tree

Функционал: Начальное заполнение данных

Как Тестировщик системы
Я хочу заполнить систему тестовыми данными
Чтобы использовать их в сценариях проверки поведения

Контекст:
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: Создание ЕИ без примеров
	Дано Я Создаю ЕИ с наименованием "бут 0.5" и объемом "0,50"

Структура сценария: Создание ЕИ из примеров
	Дано Я Создаю ЕИ с наименованием <НаименованиеЕИ> и объемом <ОбъемЕИ>

Примеры:
	|НаименованиеЕИ|ОбъемЕИ|
	|бут 1.5|1.5|
```

```gherkin
#language: ru

@tree
@ExportScenarios

Функционал: Создание единицы измерения

Как Пользователь системы
Я хочу создать новую единицу измерения
Чтобы использовать ее при создании товара

Контекст:
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: Я Создаю ЕИ с наименованием "НаименованиеЕИ" и объемом "ОбъемЕИ"
	Когда я открываю список единиц измерения
		Когда В панели разделов я выбираю 'Классификаторы'
		И В панели функций я выбираю 'Единицы измерения'
		Тогда открылось окно 'Единицы измерения'
	Если в таблице "Список" нет строки Тогда
		| 'Наименование'   | 'Объем'   |
		| 'НаименованиеЕИ' | 'ОбъемЕИ' |
		Тогда Добавляю новую единицу измерения
			И я нажимаю на кнопку с именем 'ФормаСоздать'
			Тогда открылось окно 'Единицы измерения (создание)'
			И в поле 'Наименование' я ввожу текст 'НаименованиеЕИ'
			И я перехожу к следующему реквизиту
			И в поле 'Объем' я ввожу текст "ОбъемЕИ"
		Когда я записываю единицу измерения
			И я нажимаю на кнопку 'Записать и закрыть'
			И я жду закрытия окна 'Единицы измерения (создание)' в течение 20 секунд
		Тогда Добавленная единица измерения отображается в списке единиц
			Тогда открылось окно 'Единицы измерения'
			И в таблице "Список" я перехожу к строке:
				| 'Наименование'   | 'Объем'   |
				| 'НаименованиеЕИ' | 'ОбъемЕИ' |
```

Как это видит VA:

![image](https://user-images.githubusercontent.com/6349413/53450180-43aaa000-3a24-11e9-9748-e9c8863ceefd.png)

![image](https://user-images.githubusercontent.com/6349413/53450339-a3a14680-3a24-11e9-95fa-0a473aef390a.png)

**Comment by Pr-Mex** [comment]
Ок. Проверю.

**Comment by asosnoviy** [comment]
Я похоже тоже впаровался.
