### ISSUE TITLE
При выгрузке ошибок для СППР в файлах xml нет ссылок на скриншоты

### ISSUE THREAD

**Issue by DoublesunRUS** [Pr-Mex/vanessa-automation#1303]
Настроил выгрузку ошибок для СППР при тестировании. В результирующих xml файлах нет ссылок на картинки. Хотя на макеты есть. И сами картинки есть в папке куда сохраняются ошибки.
Настроечный файл прилагаю.
[VAParams.json.txt](https://github.com/Pr-Mex/vanessa-automation/files/6933633/VAParams.json.txt)

**Comment by Pr-Mex** [comment]
Решено.
