### ISSUE TITLE
Без использования нового парсера Геркин, не верно парсится многострочная строка

### ISSUE THREAD

**Issue by ViktorErmakov** [Pr-Mex/vanessa-automation#1310]
В тройных кавычках без нового парсера строка читается не полностью, если сделать как на картинке, тогда строка 
## Оглавление 
Теряется, упраздняется.

![image](https://user-images.githubusercontent.com/39617680/128701205-c7a4cad9-9ee2-44df-ba2b-bedb85ade548.png)

**Comment by Pr-Mex** [comment]
Решено.
