### ISSUE TITLE
Шаг вызова контекстного меню в табличном документе

### ISSUE THREAD

**Issue by chEEzys** [Pr-Mex/vanessa-automation#1311]
Необходим новый шаг для Ячейки табличного документа:
`И в табличном документе "РеквизитТабличныйДокумент" я вызываю контекстное меню на текущей ячейке`

Связано с тем что шаг `И я выбираю пункт контекстного меню с именем 'ВыборИзМеню' на элементе формы "РеквизитТабличныйДокумент"`
Падает в "Неопределено", но при этом если вручную в клиенте вызвать контекстное меню, после этого начинает работать.

Принудительный шаг по аналогии с `И в табличном документе "РеквизитТабличныйДокумент" я делаю двойной клик на текущей ячейке` должен помочь в решении этой проблемы

**Comment by Pr-Mex** [comment]
@chEEzys 
Тут видимо проявляется особенность работы контекстного меню в табличном документе.
В апи платформы нет метода для вызова контекстного меню, только для выбора конкретного значения из меню, и при этом оно не появляется на экране.
Вашу проблему можно решить эмуляцией клавиатуры или кликом по картинке, насколько я понимаю.

**Comment by chEEzys** [comment]
Можно ли сделать шаг по аналогии с `И я выбираю пункт контекстного меню с именем 'ВыборИзМеню' на элементе формы "РеквизитТабличныйДокумент"` но в качестве третьего параметра передать номер ячейки табличного документа?
`И я выбираю пункт контекстного меню с именем 'ВыборИзМеню' на элементе формы "РеквизитТабличныйДокумент" в ячейке "НомерЯчейки"`

**Comment by Pr-Mex** [comment]
> Можно ли сделать шаг по аналогии с `И я выбираю пункт контекстного меню с именем 'ВыборИзМеню' на элементе формы "РеквизитТабличныйДокумент"` но в качестве третьего параметра передать номер ячейки табличного документа?
> `И я выбираю пункт контекстного меню с именем 'ВыборИзМеню' на элементе формы "РеквизитТабличныйДокумент" в ячейке "НомерЯчейки"`

В целом да, но надо помнить,  что апи платформы по автотестам пока не умеет правильно вызывать пункты контекстного меню для табличного документа.
