### ISSUE TITLE
Показать выполняемый код, когда ВА в режиме отладочных сообщений

### ISSUE THREAD

**Issue by DitriXNew** [Pr-Mex/vanessa-automation#1312]
Проблема - есть вычисляемые выражение, не важно какой шаг, пусть это будет - Выполнить произвольный код на сервере.
Я ему передаю код, выполняю, у меня падает в ошибку.
И что там выполняется - я не знаю.

Что хочу - чтобы когда я поставил галочку отладочных сообщений в ВА, то чтобы текст, которые будет вычислятся - тоже там выводился. Иначе идешьна ощупь, или надо заводить конфигуратор.

**Comment by Pr-Mex** [comment]
Решено.
