### ISSUE TITLE
Выполнение кода на сервере

### ISSUE THREAD

**Issue by Xershi** [Pr-Mex/vanessa-automation#1321]
```Ghekin
И я выполняю код встроенного языка
|'МассивДокументов = Новый Массив;'|
|'Для Каждого ЭлементДокумент Из Метаданные.Документы Цикл'|
|'	МассивДокументов.Добавить(ЭлементДокумент.Имя);'|	
|'КонецЦикла;'|
|'МассивСправочников = Новый Массив;'|
|'Для Каждого ЭлементСправочник Из Метаданные.Справочники Цикл'|
|'	МассивСправочников.Добавить(ЭлементСправочник.Имя);'|	
|'КонецЦикла;'|
|'Контекст.Вставить("МассивДокументов",		МассивДокументов);'|
|'Контекст.Вставить("МассивСправочников",	МассивСправочников);'|
```
В толстом клиенте УФ на файловой базе работало.
В тонком клиенте на УФ в клиент-серверной базе нет.
В связи с этим этот код нужно переписывать на серверный, но в текущей версии нет передачи параметра "Контекст" на сервер. На инфостарте как я понял был урок как допилить ваши обработки, чтобы они на сервер передали переменную, возможно такой допил уже сделали?
Качал vanessa-automation.1.2.036.28.zip

**Comment by Pr-Mex** [comment]
@Xershi 
1. Надо использовать шаг И я выполняю код встроенного языка на сервере
2. Если нужно передать значение с сервера на клиент надо записать его в Объект.ЗначениеСервер
3. Далее в следующих шагах его можно будет прочитать уже на клиенте.
4. Но вообще лучше создать свой шаг, если вам нужно выполнить какой-то большой блок кода. Инструкция тут
https://www.youtube.com/watch?v=xuxyb4Y16lQ&list=PLalsS95_a3a_N9tEBfaisBRPtIWEKV5Ng&index=11&ab_channel=VSL
