### ISSUE TITLE
UI Automation падает при нажатии кнопки переключения режима просмотра (список / иерархический список)

### ISSUE THREAD

**Issue by AndrewChuprina** [Pr-Mex/vanessa-automation#1323]
```Gherkin
* Hello! In this short video we will see brand new Янус ERP possibilities
        И Пауза 3

* Let's create project
        И В командном интерфейсе я выбираю 'Projects' 'Project'
        Когда открылось окно 'Project'
        И я рисую рамку вокруг элемента "ФормаСоздать" в браузере
                | 'color'   | 'red'  |
                | 'size'    | '3'    |
                | 'timeout' | '4000' |
        И Пауза 4
        И я нажимаю на кнопку с именем 'ФормаСоздать'
        Тогда открылось окно 'Project (создание)'
        И пауза 1

* For now it's only a draft in managed interface
        И Пауза 2

* Let's select contractor
        И я показываю подсказку "Contractor field is here" EnjoyHint у элемента "Контрагент" в браузере
                | 'shape'    | 'rect'  |
                | 'timeout'  | '4000'  |
                | 'noFreeze' | 'false' |
        И Пауза 4
        И из выпадающего списка с именем "Контрагент" я выбираю по строке '1С ЗАО'
        И Пауза 1

* And for this simple video we will add a translation service
        Тогда открылось окно 'Project (создание) *'
        И в таблице "Услуги" я нажимаю на кнопку с именем 'УслугиДобавить'
        И Пауза 1
        И в таблице "Услуги" я нажимаю кнопку выбора у реквизита с именем "УслугиНоменклатура"
        Тогда открылось окно 'List of Services'
        И я нажимаю на кнопку с именем 'ФормаСписок'
        И в таблице "Список" я перехожу к строке:
                | 'Item\'s Name in Russian' | 'Name'    |
                | 'Translation'             | 'Перевод' |
        И в таблице "Список" я выбираю текущую строку
        Тогда открылось окно 'Project (создание) *'
        //И в таблице "Услуги" из выпадающего списка с именем "УслугиНоменклатура" я выбираю по строке 'Перевод'
        И Пауза 2

* Finally we will save our project
        И я нажимаю на кнопку с именем 'Записать'
        И Пауза 2

* And close opened windows
        И Я закрываю окно 'Project  от *'
        Тогда открылось окно 'Project'
        И Я закрываю окно 'Project'
        И Пауза 1
```

Коллеги, добрый день!

Пишу автотест полноценного подбора номенклатуры (не вводом наименования в поле заказа, а через открытие формы выбора).

При открытии форма выбора имеет режим "Иерархический список". Соответственно, ожидается, что скрипт автотеста перед подбором переключит режим.

Запись действий на клиенте дала шаг сценария для этого:

>  И я нажимаю на кнопку с именем 'ФормаСписок'

Проблема в том, что шаг Ванессы падает, потому что она не смогла найти кнопку с помощью UI Automation. Т.е. эта проблема будет только в режиме когда я делаю автоинструкцию. 

![Ошибка Ванессы](https://user-images.githubusercontent.com/28924736/130357667-5a1c851b-d543-4c74-b4ca-208a68bfd1c5.jpg)

Чтобы это обойти, перед этим шагом выключаю использование UI Automation, а потом включаю.

**Comment by Pr-Mex** [comment]
@AndrewChuprina 
Также нужна база, на которой эта проблема воспроизводится.

**Comment by AndrewChuprina** [comment]
Базу предоставить не могу. Коммерчески чувствительная информация

**Comment by AndrewChuprina** [comment]
Привет! Разворачивать стенд, скажу честно, мне лень.

Но я упростил автотест. Воспроизводится на любой форме списка с иерархическим режимом просмотра. Например:

// Предварительные действия: Раскрываем заказ покупателя и раскрываем в нём форму выбора номенклатуры первой строки табличной части Услуги
И В командном интерфейсе я выбираю 'Projects' 'Project'
Тогда открылось окно 'Project'
И в таблице "Список" я перехожу к строке:
        | 'Client'  | 'Currency' | 'Date'             | 'End date'         | 'Number'        | 'Our legal entity'     | 'Our project name' | 'Responsible PM'  | 'Status'                  | 'Subject area'          | 'Total'   |
        | 'Acclaro' | 'USD'      | '02.09.2021 00:22' | '18.06.2021 01:30' | 'JAN_200_01641' | 'Janus Worldwide Inc.' | 'Sintering FA'     | 'Mogilevsky Igor' | 'Received, not allocated' | 'Marketing/Advertising' | '149,060' |
И в таблице "Список" я выбираю текущую строку
Тогда открылось окно 'Project JAN_200_01641 от *'
И в таблице "Услуги" я активизирую поле с именем "УслугиНоменклатура"
И в таблице "Услуги" я выбираю текущую строку
И в таблице "Услуги" я нажимаю кнопку выбора у реквизита с именем "УслугиНоменклатура"
Тогда открылось окно 'List of Services'

// Непосредственно ошибка: Воспроизводится в любой форме списка с иерархическим режимом просмотра
И я нажимаю на кнопку с именем 'ФормаСписок'

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
