### ISSUE TITLE
Выбор файла в модальном окне в веб клиенте (Chrome)

### ISSUE THREAD

**Issue by Sushkovv** [Pr-Mex/vanessa-automation#1358]
Не получается выбрать файл в модальном окне браузера. 
Использовались следующие шаги:

1. И я нажимаю на HTML элемент "document.querySelector('\#fileSelectButton\')" в браузере
2. И я выбираю файл "\\C:\123.xml\\" ВК
3. И я буду выбирать внешний файл "C:\123.xml"
    И я нажимаю на кнопку 'Открыть файл...'
![Screenshot_5](https://user-images.githubusercontent.com/90677105/133212772-52134df9-38f3-4e59-9717-545ea9dd2c61.png)

**Comment by Pr-Mex** [comment]
@Sushkovv 
Лучше приложить ваш сценарий, который вы хотите выполнить и базу, на которой он должен работать.

**Comment by Sushkovv** [comment]
https://releases.1c.ru/version_files?nick=StateAccounting20&ver=2.0.80.31 - типовая конфа, сценарий написал под ту же самую ситуацию, которая у меня. Свою конфу не могу выложить. 
[файл.zip](https://github.com/Pr-Mex/vanessa-automation/files/7161283/default.zip)

**Comment by Pr-Mex** [comment]
@Sushkovv 

Правильный сценарий такой
```Gherkin
	И В командном интерфейсе я выбираю 'Органайзер' 'Файлы'
	Тогда открылось окно 'Файлы'
	И я нажимаю на кнопку с именем 'ФормаСоздатьИзФайла'
	И я выбираю файл "C:\Temp\111.xml" ВК
```
