### ISSUE TITLE
Ошибки инициализации параметров

### ISSUE THREAD

**Issue by DitriXNew** [Pr-Mex/vanessa-automation#1361]
- [ ] Тут Стр явно лишняя:

![image](https://user-images.githubusercontent.com/11927866/133612809-305cbd8d-5922-410c-8619-a2c22eb0cf4c.png)

- [ ] Функция ПолучитьСтрокуЗапускаDesktopПриложение. Тут ДопПараметр не определен, но плюсуется в конце. Возмонжо там что то другое должно быть

![image](https://user-images.githubusercontent.com/11927866/133613077-eee94389-edc4-4b0d-a464-f9a1d62b18f9.png)

- [ ] Процедура ЗаписатьВыполнениеШагаАллюр2. Судя по контексту - ШагВложенный всегда будет = Неопределено.

![image](https://user-images.githubusercontent.com/11927866/133613305-45d77f83-6a70-49bb-8f18-c8518b4362b7.png)

**Comment by Pr-Mex** [comment]
Решено.
