### ISSUE TITLE
При прерывании цикла возникает ошибка о том что не найден цикл для прерывания.

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#1362]
Описание воспроизведения:

Выполнить код сценария, который ниже. 

И Я запоминаю значение выражения '3' в переменную "X"
И Я запоминаю значение выражения '3' в переменную "N"
И Я запоминаю значение выражения '2' в переменную "Y"
И Я запоминаю значение выражения '1' в переменную "M"
Цикл И я делаю $N$ раз
        
        Цикл И я делаю $Y$ раз
                
                Если переменная "M" имеет значение 1 Тогда
                        
                        И Я запоминаю значение выражения 'Число($X$ - 1)' в переменную "X"
                        Тогда я прерываю цикл
                        
                КонецЕсли
                
        КонецЦикла
        
        И Я запоминаю значение выражения 'Число($M$ + 1)' в переменную "M"
        
КонецЦикла

Версия VA для СППР: 1.2.037.1
Платформа: 8.3.18.1483
![Безымянный](https://user-images.githubusercontent.com/68432407/133660082-bb1d5ba2-da73-489f-975e-faf2d0af163e.png)
3

**Comment by Pr-Mex** [comment]
@egorovsergio 
У тебя шаги стали группами, т.к. нет апострофов.
Нужно так:
И я делаю '$N$' раз
вместо
И я делаю $N$ раз

**Comment by egorovsergio** [comment]
Да. Получилось как ты сказал. Спасибо. Но всё же может быть в сообщении пользователю как-то конкретнее сообщать что произошло? Например, "Некорректно задано условие цикла". Или что-то вроде того.

**Comment by Pr-Mex** [comment]
@egorovsergio 
Так пользователю и говорится, что он пытается прервать цикл, а его нет.

**Comment by egorovsergio** [comment]
Как по мне, то получается двоякая ситуация - в коде используется аж два цикла, но система сообщает что цикл для прерывания не найден. Мне кажется что было бы понятнее если в сообщении говорилось о том что некорректно заданы параметры цикла.

**Comment by Pr-Mex** [comment]
> Как по мне, то получается двоякая ситуация - в коде используется аж два цикла, но система сообщает что цикл для прерывания не найден. Мне кажется что было бы понятнее если в сообщении говорилось о том что некорректно заданы параметры цикла.

Так шаг цикла был написан некорректно, что получается, что в сценарии нет ни одного цикла.
Если перейти в режим редактора. то это хорошо видно. Эти шаги стали группами.
