### ISSUE TITLE
Не выполняется прерывание цикла.

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#1363]
Описание воспроизведения:
Выполнить код сценария, который ниже. 

И Я запоминаю значение выражения '1' в переменную "M"

Цикл И я делаю 3 раз
        
        Цикл И я делаю 2 раз
                
                Если переменная "M" имеет значение 1 Тогда
                        
                        Тогда я прерываю цикл
                        
                КонецЕсли
                
        КонецЦикла

КонецЦикла

Версия VA для СППР: 1.2.037.1
Платформа: 8.3.18.1483

**Comment by Pr-Mex** [comment]
@egorovsergio 
Какого поведение ты ожидаешь?
Должен прерваться только внутренний цикл.

**Comment by egorovsergio** [comment]
На деле ни один из циклов не прерывается. Ожидается что 3 раза прервётся только второй цикл.

**Comment by Pr-Mex** [comment]
Решено.
