### ISSUE TITLE
При записи автовидео группу считать шагом

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#137]
Сейчас, чтобы группу шагов записать как один шаг нужно перед группой ставить специальную директиву. И бывает, что такие директивы нужно проставить для всех групп из фичи.
Нужно добавить опцию, которая будет интерпретировать группы шагов как один шаг:
"Группа шагов как шаг."

**Comment by zeegin** [comment]
@Pr-Mex  А зачем нужна группа шагов?

**Comment by Pr-Mex** [comment]
Часто надо сделать несколько низкоуровневых действий, которые объединены логически. Тогда проще создать группу.

**Comment by zeegin** [comment]
А чем это отличается от подсценария?

**Comment by Pr-Mex** [comment]
По идее тоже самое. Но по умолчанию подсценарий тоже будет интерпретироваться как набор шагов, а не один шаг.
Данная доработка позволяет это исправить.

**Comment by Pr-Mex** [comment]
Решено.
