### ISSUE TITLE
Починить переключение в режим vaeditor

### ISSUE THREAD

**Issue by SvetaShum0vaya** [Pr-Mex/vanessa-automation#1373]
1. открываем обработку va (как внешний файл)
2. загружаем настройки в которых "ИспользоватьРедакторVanessaEditor": false,
3. подтягивается каталог файлов функциональности [но не открывается](https://github.com/Pr-Mex/vanessa-automation/issues/1371).
4. жмём первый раз на "Перейти в vanessa editor" **Результат**: подтягиваются все файлы фич из каталога функциональности (**[vaparams.txt](https://github.com/Pr-Mex/vanessa-automation/files/7223738/vaparams.txt)**, что будет переход в режим vanessa editor, каталог функциональности будет отображён в панели слева (если панель должна была быть видна))
5. жмём второй раз "Перейти в vanessa editor" **Результат**: обработка переходит в режим, и каталог функциональности определяется "стоковый". Temp.  (**[Uploading vaparams.txt…]()**, что каталог функциональности будет соответстовать параметру "КаталогФич" и будет отображён в панели слева (если панель должна была быть видна)).

**Comment by Pr-Mex** [comment]
@lelikanet 
Проверьте данное поведение на текущей версии из ветки develop, пожалуйста.

**Comment by Pr-Mex** [comment]
Закрываю, т.к. нет ответа.
