### ISSUE TITLE
Добавить шаг "И таблица "ИмяТаблицы" не содержит строки по шаблону"

### ISSUE THREAD

**Issue by chEEzys** [Pr-Mex/vanessa-automation#1374]
Нужно добавить шаг умеющий работать со * в значениях, проверяющий что нужной строки нет в таблице.
`И таблица "ИмяТаблицы" не содержит строки по шаблону`
В дальнейшем его планируется использовать как условие, возможно есть смысл сразу сделать шаги для условий:
`Если таблица "ИмяТаблицы" содержит строки по шаблону тогда`
`Если таблица "ИмяТаблицы" не содержит строки по шаблону тогда`

**Comment by chEEzys** [comment]
P.S. Отдельные шаги для условий всегда лучше тем что:
1. не ждут по таймауту выполнения условий, т.е. работают быстрее
2. не спамят в лог ошибки при невыполнения условия (особенно когда приходится это делать циклом ожидания срабатывания какого нибудь триггера)

**Comment by Pr-Mex** [comment]
@chEEzys 
Сейчас не нужно создавать дополнительные копии шагов как условия.
Тут описано (пункт 26) как вызвать любой шаг как условие
https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/FAQ/index.md

**Comment by chEEzys** [comment]
> @chEEzys
> Сейчас не нужно создавать дополнительные копии шагов как условия.
> Тут описано (пункт 26) как вызвать любой шаг как условие
> https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/FAQ/index.md

про это же мой первый комментарий:
Отдельные шаги для условий всегда лучше тем что:
- Не ждут по таймауту выполнения условий, т.е. работают быстрее.
- Не спамят в лог ошибки при невыполнения условия (особенно акутально когда приходится это делать циклом ожидания срабатывания какого нибудь триггера).

**Comment by Pr-Mex** [comment]
> Отдельные шаги для условий всегда лучше тем что:
> 
> * Не ждут по таймауту выполнения условий, т.е. работают быстрее.
> * Не спамят в лог ошибки при невыполнения условия (особенно акутально когда приходится это делать циклом ожидания срабатывания какого нибудь триггера).

Не понял чем они лучше.
1. Если в шаге не указано, что он работает в течение стольки-то секунд, то он ничего ждать не будет.
2. Про какой спам в лог идёт речь? Можно пример?

**Comment by chEEzys** [comment]
1. есть стандартные таймауты, ожидания значений и окон, по ощущениям это где то 2-5 секунд
2. Ну вот например обертка шага проверки значения в табличном документе через подобный цикл:
`И в течение 350 секунд я выполняю
	Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда
		| '№ ЗЭ'		| '№ накладной'		   |
		| '$НомерЗЭ_1$' | '$НомерНакладной_1$' |
		| '$НомерЗЭ_2$' | '$НомерНакладной_2$' |
		| '$НомерЗЭ_3$' | '$НомерНакладной_3$' |
		| '$НомерЗЭ_4$' | '$НомерНакладной_4$' |
		| '$НомерЗЭ_5$' | '$НомерНакладной_5$' |
		Тогда я прерываю цикл
	Иначе
		И я нажимаю на кнопку с именем 'АРМОбновитьДанные'`
выдает такой вот лог на выходе (снизу вверх читать):
```
27.09.2021 15:18:42 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:18:37 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:18:32 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:18:27 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:18:22 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:18:17 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:18:12 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:18:07 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:18:02 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:17:57 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:17:52 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:17:47 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:17:41 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:17:36 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:17:31 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:17:26 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:17:21 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:17:16 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:17:11 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:17:06 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:17:01 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:16:55 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:16:50 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:16:45 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:16:40 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:16:35 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:16:30 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:16:25 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:16:20 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:16:15 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:16:08 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:16:03 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:15:58 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:15:52 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:15:47 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
27.09.2021 15:15:42 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
```
т.е. пока не дождался значений, каждые пять секунд спамил ошибку в лог, но при этом не вызывал исключение, т.к. обернут через Если

**Comment by Pr-Mex** [comment]
@chEEzys 
>есть стандартные таймауты, ожидания значений и окон, по ощущениям это где то 2-5 секунд

Все таймауты задаются настройками. См страницу настроек "Выполнение сценариев"

**Comment by Pr-Mex** [comment]
@chEEzys 
>Ну вот например обертка шага проверки значения в табличном документе через подобный цикл:
Посмотри флаг отладочных сообщений, пожалуйста. Он включен? Влияет ли он на показ этих сообщений?

**Comment by chEEzys** [comment]
1.  я понимаю что есть встроенные таймауты которые можно настроить, это не отменяет того факта что стандартный шаг со стандартным условием "Если" выполняется моментально, а обернутый в условие будет ждать таймаута )
2. данный лог с выключенной галкой про отладочные сообщения.
С включенной добавляются две дополнительные строки:
```
28.09.2021 11:22:17 ОписаниеОшибки()={ВнешняяОбработка.VanessaAutomationsingle.Форма.Тест_РаботаСИнтерфейсом.Форма(11894)}: Табличный документ не содержит нужные строки <01390134631;01390134632;01390134633;01390134634;>
28.09.2021 11:22:17 Шаг (Если табличный документ "РезультатЗаявкиЭкспедитора" содержит значения: тогда) не выполнен.
28.09.2021 11:22:19 {ВнешняяОбработка.VanessaAutomationsingle.Форма.Тест_РаботаСИнтерфейсом.Форма(11894)}: Табличный документ не содержит нужные строки <01390134631;01390134632;01390134633;01390134634;>
...
```

**Comment by Pr-Mex** [comment]
> 1. я понимаю что есть встроенные таймауты которые можно настроить, это не отменяет того факта что стандартный шаг со стандартным условием "Если" выполняется моментально, а обернутый в условие будет ждать таймаута )
Будет ждать таймаута или нет определяется только реализацией шага. Что в коде написано так и будет работать.
И условия тоже могут ждать таймаутов.

**Comment by Pr-Mex** [comment]
Закрываю.
