### ISSUE TITLE
[BUG] Некорректная передача в шаг значения строкового параметра, в которых есть экранированные кавычки

### ISSUE THREAD

**Issue by ovcharenko-di** [Pr-Mex/vanessa-automation#1377]
Некорректная передача значения строкового параметра, в которых есть экранированные кавычки.
Проявляется на шагах, которые подразумевают использование шаблонов.

См. пример:

Определение шага[^1]:
![image](https://user-images.githubusercontent.com/24920942/135657594-2be0b478-3f6d-4d4c-ac34-bb3bca55adea.png)

Результат подстановки (через VanessaExt аналогично)[^2]:
![image](https://user-images.githubusercontent.com/24920942/135658955-880a954b-cbc0-42f7-91f7-eb509e58c0ed.png)

[^1]: Определение шага
    ```gherkin
    #language: ru

    @tree
    @ExportScenarios
    
    Сценарий: я передаю параметр с кавычками "Параметр" в шаг перехода к строке по шаблону
    	    И в таблице "ИмяТаблицы" я перехожу к строке по шаблону:
		    | 'Колонка'   |
		    | 'Параметр*' |
    ```
[^2]: Вызов шага
    ```gherkin
    #language: ru

    @tree

    Сценарий: <описание сценария>
	    И я передаю параметр с кавычками "Значение \"в кавычках\"" в шаг перехода к строке по шаблону
    ```

**Comment by Pr-Mex** [comment]
@ovcharenko-di 
Привет!
У тебя в определении шага написано Параметр*.
В таком случае подстановка не должна производится.
Попробуй написать **[Параметр]***

**Comment by ovcharenko-di** [comment]
@Pr-Mex , спасибо, получилось!

Дополнил справку информацией о такой особенности.

**Comment by Pr-Mex** [comment]
@ovcharenko-di 
Ага, спасибо!
