### ISSUE TITLE
Ошибка определения типового шага при использовании настройки "Использовать парсер Gerkin из компоненты VanessaExt" в VASingle

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1388]
#language: ru

@tree

Функционал: Создание абонента с помощью обработки Мастер создания

Как Тестировщик
Я хочу создать абонента путем ручного заполнения
Чтобы исключить наличие ошибки в механизме создания 

Контекст: 
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: Создание абонента путем ручного заполнения

Открытие АРМ_Мастер создания абонента
	И В командном интерфейсе я выбираю 'РНГ' 'Мастер создания абонента'
	Тогда открылось окно 'Создание абонента. ЛС № *'
![Снимок](https://user-images.githubusercontent.com/19662685/136539756-ec1dc726-37c1-4046-93be-ad236409afcb.PNG)

```

> Прикладывайте файлы скриншотов

**Comment by akademik1986** [comment]
VA 1.2.38.1, на другой уже конфигурации, платформа 8.3.18.1616, режим совместимости Версия 8.3.16. 
Выполняю простейший тест
#language: ru

@tree

Функционал: Проверка циклов

Как <Роль> я хочу
<описание функционала> 
чтобы <бизнес-эффект> 

Контекст:
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий
	 

Сценарий: Запуск цикла
	
	И я делаю 5 раз
	
		И я открываю окно настройка начальной страницы (расширение)
		И     Пауза 1		
		И я закрываю все окна клиентского приложения
		
		
	С настройкой "Использовать парсер Gerkin из компоненты VanessaExt" ошибка определения шага
23.12.2021 15:25:50 Пустой адрес снипета у шага: Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Убраю данную настройку, все проходит успешно.

**Comment by Pr-Mex** [comment]
@akademik1986 
Опишите ваше окружение. ОС. База серверная или нет. Каталог в котором находится VA.

**Comment by akademik1986** [comment]
Win 10, база файловая, каталог VA стандартный - C:\Program Files\OneScript\lib\vanessa-automation-single

**Comment by akademik1986** [comment]
Кстати, ошибка только на single версии

**Comment by Pr-Mex** [comment]
Разобрался.
