### ISSUE TITLE
Некорректная работа Ванесса.Шаг для многострочного шага сравнения таблиц

### ISSUE THREAD

**Issue by 1cto** [Pr-Mex/vanessa-automation#139]
Функционал: Чёткая работа Ванесса.Шаг
   Как разработчик 1С
   Я хочу чтобы Ванесса.Шаг не глючил

Контекст:
  Дано: 1.2.018
  И 1С:Предприятие 8.3 (8.3.12.1790)
  И Управление холдингом, редакция 1.3 (1.3.10.9)

Сценарий: Некорректная работа Ванесса.Шаг для многострочного шага
  Допустим: в обработчике шага сценария сгенерирована следующая строка:
"И таблица "График" содержит строки:
| 'Дата'       | 'Получение займа' | 'Возврат займа' | 'Задолженность' |
|'01.01.2018'| '1 200 000,00'| ''                | '1 200 000,00'|
|'01.02.2018'| ''                | '100 000,00'| '1 100 000,00'|
"
  Когда: я передаю сгенерированную строку в качестве параметра в Ванесса.Шаг
  Тогда: Ванесса.Шаг всегда выполняется без ошибок хотя таблица "График" не содержит этих строк
  И даже не содержит этих колонок

```
Проблема в том, что в процедуре ВыполнитьМетодШагЧерезВременныйФичаФайл не находятся шаги во временной фиче для такого шага.
Если эту строку оформить отдельным фичефайлом и запустить в VA - то всё отрабатывает корректно.

**Comment by 1cto** [comment]
Проблема локализована. Когда прогон сценариев в ванессе запускается с использованием тегов отбора (указываются теги, по которым должен идти прогон сценариев):
![image](https://user-images.githubusercontent.com/15178930/51305876-b51a2a80-1a44-11e9-9d78-59eba0894b68.png)
тогда в случае многострочного шага создаётся временный фичефайл, в котором этих тегов нет. И парсинг её не подгружает.
Соответственно нужно при обработке временного фичефайла игнорировать теги запуска и исключения.

**Comment by Pr-Mex** [comment]
Решено. Добавлен тест.
