### ISSUE TITLE
[BUG] перестало работать тестирование озвучки

### ISSUE THREAD

**Issue by ovcharenko-di** [Pr-Mex/vanessa-automation#1403]
Укажите:
   1. Версия Vanessa Automation - develop acac698069c1f1726e7cc22294916f9de1e1b6e2
   2. Версия платформы - 8.3.17
   3. Режим совместимости базы, где запускается Vanessa Automation - 8.3.16
   4. Операционная система - Windows 10

Проблему локализовал и решил, PR направлю

**Comment by Pr-Mex** [comment]
Решено.
