### ISSUE TITLE
Некорректно разделяется stacktrace и текст ошибки

### ISSUE THREAD

**Issue by KrapivinAndrey** [Pr-Mex/vanessa-automation#1406]
Укажите:
   1. 1.2.037.1
   2. 8.3.17.1386
   3. РежимСовместимостиTestManager: Версия8_3_12
   4. Linux

В тексте ошибки встречается точка. Тогда стектрейс и текст ошибки не корректно разбивается.

![chrome_FcoJatC3SQ](https://user-images.githubusercontent.com/586025/137311735-5aeb1164-8eec-4143-a9c2-a0fbd6464645.png)

**Comment by Pr-Mex** [comment]
Решено.
