### ISSUE TITLE
Настройка колонок в интерфейсе ванессы работает не так как ожидается

### ISSUE THREAD

**Issue by tsukanov-as** [Pr-Mex/vanessa-automation#141]
Ванесса: ver 1.2.0.18 Vanessa Automation single 
Платформа: 1С 8.3.12.1790 x64

При открытии обработки в настройках колонок все галки стоят, но при этом колонки в дереве отображаются не все. Кажется галки должны стоять только на тех колонках, которые видны.

Скрин:
https://i.imgur.com/yhQUjnI.png

**Comment by Pr-Mex** [comment]
Решено. Добавлен тест.
