### ISSUE TITLE
ошибка при использовании секции "Переменные"

### ISSUE THREAD

**Issue by atyz2013** [Pr-Mex/vanessa-automation#1411]
Укажите:
   1. Версия Vanessa Automation - 1.2.037.11
   2. Версия платформы - 8.3.17.1549
   3. Режим совместимости базы, где запускается Vanessa Automation - Версия 8.3.15
   4. Операционная система - Windows 10

при использовании секции "Переменные" появляется ошибка:
![image](https://user-images.githubusercontent.com/78148551/137971047-83663fc5-7569-4193-8125-293525bfe46b.png)

подробнее:
Ошибка вычисления переменной из выражения <Универсальный обмен данными в формате XML (2.1.8)>. Таблица переменных не найдена.
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(28375)}:				ВызватьИсключение СтрокаОшибки;
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(35218)}:					НовоеЗначение = ЗначениеИзТаблицыПеременных(МассивПараметров[Сч], ДанныеПоПростымПеременным, ДанныеПоПеременныхВТаблицах);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(25269)}:	МассивПараметров = ПолучитьМассивПараметровИзСписокАргументов(
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(26201)}:	ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);

с закоменченной секцией "Переменные" ошибка не возникает, сценарий выполняется:
![image](https://user-images.githubusercontent.com/78148551/137971246-b636934e-9853-4717-bfa7-5ed7efaf35bd.png)

**Comment by Pr-Mex** [comment]
Решено.
