### ISSUE TITLE
Проблема с получением состояния формы в виде шагов

### ISSUE THREAD

**Issue by Severnity** [Pr-Mex/vanessa-automation#1419]
Укажите:
   1. VA 1.2.037.9
   2. 1C:Enterprise 8.3 (8.3.20.1479)
   3. Windows 10
  
  При попытке получить состояние всей формы в виде шагов или получить состояние текущего элемента формы в виде шагов возникает ошибка 
  26.10.2021 14:11:24 GetFormConditionTestClient:{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(34135)}: Value is not of object type (НайтиОбъект)

Проблема воспроизводится только на 20-й платформе, на более ранних платформах механизм работает нормально

**Comment by Pr-Mex** [comment]
@Severnity 
Уточни, плиз, при получении какой именно формы это воспроизводится?

**Comment by Severnity** [comment]
@Pr-Mex например форма документа SalesInvoice.
На версии VA 1.2.038.15 ошибка также воспроизводится

**Comment by Pr-Mex** [comment]
@Severnity 
Проверил на форме нового документа SalesInvoice. Ошибки нет.
Можешь записать видео как это у тебя происходит?
Заодно попробуй обновить платформу.

**Comment by Pr-Mex** [comment]
@Severnity 
Вот для такой формы получал состояние
![image](https://user-images.githubusercontent.com/8627416/155012684-66731dca-7527-452c-a0fd-a34d27cd71ef.png)

**Comment by Severnity** [comment]
@Pr-Mex
[ПримерОшибки.zip](https://github.com/Pr-Mex/vanessa-automation/files/8111635/default.zip)
Записала видео. Эта ошибка воспроизводится только на версии платформы  8.3.20.1479. Проверяла ещё на  8.3.20.1674 и 8.3.21.1140 такой ошибки нет

**Comment by Pr-Mex** [comment]
Да, это проблема платформы. Нужно использовать более новые версии. Там ошибка исправлена.
