### ISSUE TITLE
Проблема с шагом сортировки по колонке

### ISSUE THREAD

**Issue by Severnity** [Pr-Mex/vanessa-automation#1420]
Укажите:
   1. 1.2.037.9
   2. 1С:Предприятие 8.3 (8.3.19.1351)
   3. Windows 10
   4. В клиенте тестирования установлено расширение VAExtension

При выполнении шага 
И в таблице "ИмяТаблицы" текущего окна я устанавливаю сортировку по колонке "ИмяКолонки" по убыванию (расширение) возникает ошибка
![image](https://user-images.githubusercontent.com/66120736/139099882-339cefdd-9cc2-4be0-9690-4f92a40bc822.png)
База и тест для воспроизведения

```
[DataBase.zip](https://github.com/Pr-Mex/vanessa-automation/files/7427537/DataBase.zip)


[служебные сообщения.txt](https://github.com/Pr-Mex/vanessa-automation/files/7427542/default.txt)

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
