### ISSUE TITLE
Исправить опечатку.

### ISSUE THREAD

**Issue by lelikanet** [Pr-Mex/vanessa-automation#1426]
Во всех упоминаниях в проекте "Hellow world" сменить слово "Hellow" на "Hello".
Всего таких упоминаний - 20.
![image](https://user-images.githubusercontent.com/45041332/139837811-580a5302-ecb8-453f-9226-8a4e807674fc.png)

**Comment by ovcharenko-di** [comment]
опечатки в VA, которые нашел я:

- ассинхронно
- Асинхроно
- неш
- скринщоте
- Руский
- существуюющий

некоторые можно исправить простой заменой, а некоторые приведут к нарушению обратной совместимости и это надо как-то дополнительно обработать.

**Comment by Pr-Mex** [comment]
> опечатки в VA, которые нашел я:
> 
> * ассинхронно
> * Асинхроно
> * неш
> * скринщоте
> * Руский
> * существуюющий
> 
> некоторые можно исправить простой заменой, а некоторые приведут к нарушению обратной совместимости и это надо как-то дополнительно обработать.

@ovcharenko-di 
Можешь сделать ревквест на то, что можно сразу исправить?

**Comment by Pr-Mex** [comment]
Решено.
