### ISSUE TITLE
Борьба с утечками памяти.

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1429]
Обнаружено несколько проблем с утечками памяти из-за циклических ссылок.

**Comment by ovcharenko-di** [comment]
@Pr-Mex , а как ты их обнаруживаешь? С помощью платформы?

**Comment by Pr-Mex** [comment]
> @Pr-Mex , а как ты их обнаруживаешь? С помощью платформы?

Конкретно в этом случае просто сообразил по косвенным признакам. Оставались ссылки на форму VA.

**Comment by Pr-Mex** [comment]
Решено.
