### ISSUE TITLE
Файл отчета cucumber с "русским" uri не понимает плагин CucumberReport Jenkins

### ISSUE THREAD

**Issue by azheval** [Pr-Mex/vanessa-automation#143]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Корректный файл отчета Cucumber
   Как тестировщик   
   Я хочу видеть корректный отчет Cucumber в Jenkins

Контекст:
  Дано: VA 1.2.018
  И Jenkins 2.150.1
  и плагин CucumberReport 4.3.0

Сценарий: После выполнения сценария формируется корректный файл отчета cucumber
Сейчас uri формируется на языке Функциональности фичи и русский вариант плагин Jenkins не понимает. Если Функциональность в фиче написана латиницей, то проблем нет.


```

> Прикладывайте файлы скриншотов

**Comment by nixel2007** [comment]
Тоже сталкиваюсь с этой проблемой. На мой взгляд это не проблема va, а проблема плагина для jenkins. Именно в него надо репортить эту проблему и исправлять там.

**Comment by Pr-Mex** [comment]
@azheval 
У тебя получилось решить эту проблему?

**Comment by azheval** [comment]
Да, обновление плагина проблему решило

**Comment by Pr-Mex** [comment]
@azheval 
Скажи, пожалуйста, версию плагина и версию Jenkins, которые у тебя используются.

**Comment by azheval** [comment]
Jenkins 2.150.2
Cucumber report 4.4.0

**Comment by Pr-Mex** [comment]
@azheval 
спасибо!
