### ISSUE TITLE
Передача контекста при загрузке фикстуры с клиента на сервер

### ISSUE THREAD

**Issue by PashaMak** [Pr-Mex/vanessa-automation#1438]
Укажите:
   1. Версия ванессы 1.2.0.37.1
   2. Версия платформы 8.3.12.1790
   3. Управляемый режим совместимости
   4. Win10 Pro

> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Ускорение загрузки макета
   Как разработчик
   Я хочу ускорить прогон 100 тестов за один раз

Контекст:
  Дано: 1.2.0.37.1
  И 8.3.12.1790
  И Тонкий клиент

Сценарий: Быстрая загрузка макетов
  Допустим: Загружаю макет в одном из 100 тестов дерева
  Когда: выполняется загрузка макета
  Тогда:не передается контекст дерева шагов на сервер

```

![image](https://user-images.githubusercontent.com/24808007/141884188-f71786df-36c8-4b23-9abc-4f0e9f10b768.png)
![image](https://user-images.githubusercontent.com/24808007/141884862-3e6158be-e9d0-4922-ba07-79101497c44b.png)
![image](https://user-images.githubusercontent.com/24808007/141884581-8c564cc0-f615-489f-a5d7-7b1a882b03fa.png)

**Comment by PashaMak** [comment]
https://github.com/Pr-Mex/vanessa-automation/pull/1443

**Comment by Pr-Mex** [comment]
Решено.
