### ISSUE TITLE
Не типовая конфигурация Слишком много фактических параметров

### ISSUE THREAD

**Issue by olegmm** [Pr-Mex/vanessa-automation#1439]
Укажите:
   1. 1.2.037.1
   2. 8.3.18.1483
   3. 8.3.15
   4. Windows server 2012 Standart R2
   5. Конфигурация 1С фитнес

Функционал: Открытие обработки
![vanessa_fit](https://user-images.githubusercontent.com/3460830/142039098-6c0052d5-98cc-455c-980d-67df2e321ed8.png)

**Comment by Pr-Mex** [comment]
@olegmm 
В каком-то глобальном модуле конфигурации объявлена функция с таким же именем?

**Comment by Pr-Mex** [comment]
Решено.
