### ISSUE TITLE
Доработать шаг проверки ячейки табличного документа.

### ISSUE THREAD

**Issue by alehinsasha** [Pr-Mex/vanessa-automation#144]
Наверно нужно два шага, один проверяет значение ячейки, второй - текст/представление ячейки.

![image](https://user-images.githubusercontent.com/8247178/51237063-bab03b80-1984-11e9-8a56-bed94c471f79.png)

> записью в VA тыкнул ячейку табличного документа, он мне записал как R23C3, далее я написал шаг как видно на картинке, а VA говорит что там пусто

**Comment by Pr-Mex** [comment]
Как выяснилось, проблема была в том, что отчет не успел сформироваться.
Плюс для ячейки есть только метод "ПолучитьПолеТекущейОбласти()".
Закрываю.
