### ISSUE TITLE
Прерывание раскраски строк после переключения выполняемого сценария

### ISSUE THREAD

**Issue by ZhokhovM** [Pr-Mex/vanessa-automation#1460]
1. Версия Vanessa Automation 1.2.037.12
2. Версия платформы 8.3.19.1264
3. Режим совместимости базы, где запускается Vanessa Automation Такси
4. Операционная система Windows Server 2016 Standard

Сценарий VA:
1. Открыть сценарий ААА (время выполнения сценария 10 минут).
2. Открыть сценарий БББ (время выполнения сценария 15 минут).
3. Переключить на сценарий ААА и нажать "Выполнить" сценарий. В сценарии ААА есть раскраска строк.
4. Переключить на сценарий БББ. 
Причина: Раскраска строк прерывается в сценарии ААА и продолжает раскраску строк в сценарии БББ.
Ожидалось увидеть раскраску строк в выполняемом сценарии ААА.

**Comment by Pr-Mex** [comment]
@ZhokhovM 
Я что-то не понял из текстового описания что именно вы делаете. Можете записать видео с экрана?

**Comment by ZhokhovM** [comment]
Открыть 2 любых сценария, выполнить первый сценарий, в сценарии видно что раскрашиваются строки, перейти на второй сценарий(несколько раз нажать на вторую закладку чтобы была активной вторая закладка) и во втором сценарии раскрашиваются строки, а в первом нет. Причина в том что должна продолжать раскрашиваться в первом сценарии, а не во втором.

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
