### ISSUE TITLE
Зависает редактор сценария после нажатия "Остановить" + белый фон на всех сценариях/консоли

### ISSUE THREAD

**Issue by ZhokhovM** [Pr-Mex/vanessa-automation#1461]
1. Версия Vanessa Automation 1.2.037.12
2. Версия платформы 8.3.19.1264
3. Режим совместимости базы, где запускается Vanessa Automation Такси
4. Операционная система Windows Server 2016 Standard

Запустить сценарий, подождать какое-то время, нажать "Остановить", отключить раскраску строк, очистить все сообщения пользователю на форме, отключить все подключенные клиенты тестирования, закрыть все запущенные базы "Клиенты тестирования".
Причина: Редактор зависает каждые несколько секунд, редактировать сценарий стало неудобно. 
Решение: помогает сохранить измененный сценарий и перезапустить менеджер тестирования, но хотелось бы другой вариант обхода.

![image](https://user-images.githubusercontent.com/8123751/144589658-f5569cee-3164-4ce4-902b-7f3ed600b82f.png)
после долгого пользования сценария сценарии безследно пропадают, сценарии никак не редактировать, закрыть и открыть обработку VA не помогает.

![image](https://user-images.githubusercontent.com/8123751/144589904-dbfd452e-b383-408f-9ae6-e7a27ec50d79.png)
на фото сверху открыл консоль когда возникает ситуация с большой задержкой, а снизу через несколько десятков минут.

**Comment by Pr-Mex** [comment]
@ZhokhovM 
Редактор был обновлен. Попробуйте версию из develop или из этого релиза
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.037.18

**Comment by ZhokhovM** [comment]
![image](https://user-images.githubusercontent.com/8123751/145173561-2c0387d2-e095-4948-b8c2-90591dd8554a.png)
тоже самое. консоль открыл.

**Comment by ZhokhovM** [comment]
![image](https://user-images.githubusercontent.com/8123751/145174120-3c529ebf-6947-42b8-bbbf-ac27e6174434.png)
переоткрыл обработку. открыл сценарий и консоль. все пусто.

**Comment by Pr-Mex** [comment]
@ZhokhovM 
По данному текстовому описанию непонятно как воспроизвести проблему.
Запишите, пожалуйста, видео с экрана с момента запуска VA и до возникновения зависания.
Плюс надо выгрузить VA настройки в json и приложить к issue.

**Comment by Pr-Mex** [comment]
@ZhokhovM 
Пока issue закрываю, т.к. нет ответа.
