### ISSUE TITLE
[BUG] Вызов несуществующего метода VanessaExt НачатьВызовСканироватьПапку

### ISSUE THREAD

**Issue by ovcharenko-di** [Pr-Mex/vanessa-automation#1469]
Укажите:
   1. Версия Vanessa Automation: 1.2.037 (и в develop тоже, и single)
   2. Версия платформы 8.3.18.1289
   3. Режим совместимости базы, где запускается Vanessa Automation: 8.3.16
   4. Операционная система: Debian GNU/Linux 11 (bullseye)

![image](https://user-images.githubusercontent.com/24920942/145189830-82b43ddf-13db-47e4-a63f-927e84bef7fd.png)

**Comment by ovcharenko-di** [comment]
связано с #1144

**Comment by Pr-Mex** [comment]
@ovcharenko-di 
Приложи json с настройками VA, которые были установлены, пожалуйста.

**Comment by ovcharenko-di** [comment]
http://sprunge.us/4mctjn

@Pr-Mex , подключился к агенту после возникновения ошибки и выгрузил настройки в файл.

Бросается в глаза `/\\features`, но на Win тот же конфиг работает, да и вызов несуществующего метода все равно имеет место.

**Comment by Pr-Mex** [comment]
> http://sprunge.us/4mctjn
> 
> @Pr-Mex , подключился к агенту после возникновения ошибки и выгрузил настройки в файл.
> 
> Бросается в глаза `/\\features`, но на Win тот же конфиг работает, да и вызов несуществующего метода все равно имеет место.

Можешь передать правильный путь вместо /\\features?
Нужно исключить лишние варианты.

**Comment by lintest** [comment]
Под Линукс нужно использовать другой метод компоненты НачатьВызовПрочитатьПапку, это связано с различным поведением многопоточности в Линукс и Виндоуз.

**Comment by Pr-Mex** [comment]
Решено.
