### ISSUE TITLE
Заполнение тестового клиента, значениями по-умолчанию

### ISSUE THREAD

**Issue by hawk911** [Pr-Mex/vanessa-automation#147]
```Gherkin
Функционал:  Меняю только один параметр запуска Тестового клиента
   Как Программист
   Я хочу менять параметр запуска тестового клиента, а остальные заполнялись по умолчанию
```

Путь до базы - считать путь до базы из которого запущена VA. 

![image](https://user-images.githubusercontent.com/11535209/51241337-29ef5500-19b0-11e9-8995-a7b6779c96e7.png)

**Comment by GenVP** [comment]
@hawk911
Протестируй после внесения изменений из #616. Должно заполняться так:
1. "Тест клиент" при открытии обработки - настройками по умолчанию (база из СтрокаСоединенияИнформационнойБазы())
2. "Тест клиент" из загружаемых настроек VAParams.json - только те поля, которые указал. Укажешь одно поле - заменится одно поле. Но нужно обязательно указать "Имя"/"Name" = "Тест клиент"/"This client".

**Comment by hawk911** [comment]
@GenVP Хорошо, на неделе протестирую. Спасибо!

**Comment by hawk911** [comment]
@GenVP Протестировал - работает. Теперь надо на проде запускать.

**Comment by hawk911** [comment]
@GenVP Ошибка, если использовать английский, то есть `this client`: 

![image](https://user-images.githubusercontent.com/11535209/74429986-88765380-4e8e-11ea-9803-fd82e609803d.png)

При заполнении использую вот такой JSON:

```JSON

"TestClient": {
		"runtestclientwithmaximizedwindow": true,
		"testclienttimeout": 60,
		"testclientports": "",
		"testclientdebug": false,
		"testclientdebugkeys": "",
		"testclientdebugaddress": "",
		"datatestclients": [
			{
				"Name": "this client",
				"PathToInfobase": "",
				"PortTestClient": 1538,
				"AddItionalParameters": "",
				"ClientType": "Thin",
				"ComputerName": "localhost"
			}
		]
    }
```

То есть, я не могу использоваться русские наименования в JSON, то есть `ЭтотКлиент` и происходит дублирование :(

**Comment by hawk911** [comment]
А нет, поменял на `This client` - заработало. Спасибо!

**Comment by Pr-Mex** [comment]
Решено.
