### ISSUE TITLE
[BUG] При включенном флаге "Различать broken и failed по ключевому слову Тогда" в Allure не всегда прикрепляется вся доп. информация

### ISSUE THREAD

**Issue by ovcharenko-di** [Pr-Mex/vanessa-automation#1479]
1. Версия Vanessa Automation 1.2.038
   2. Версия платформы 8.3.20.1590
   3. Режим совместимости базы, где запускается Vanessa Automation не имеет значения
   4. Операционная система CentOS

Дано:
- "Различать broken и failed по ключевому слову Тогда" = Истина
- `И в таблице "Продукция" я перехожу к строке` имеет статус Broken (желтый) 

В отчете Allure по сценарию отсутствуют:
- описание ошибки (то, что в Allure называется trace)
- скриншоты

ЖР, состояния форм, данные о сетевых соединениях прикрепляются

нет trace
![image](https://user-images.githubusercontent.com/24920942/147250539-7cb8ac13-6d36-43b7-bc8d-2ff769ac4ebc.png)

нет скриншотов
![image](https://user-images.githubusercontent.com/24920942/147250649-d32d8a84-b8fa-478f-b6d8-af2d39ac4926.png)

**Comment by Pr-Mex** [comment]
@ovcharenko-di 
Сможешь посмотреть что там происходит?

**Comment by ovcharenko-di** [comment]
@Pr-Mex 
посмотрю, да

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
