### ISSUE TITLE
Ошибка в сценарии урока: Глава 3.3.4 Спецсимволы в шагах сценариев

### ISSUE THREAD

**Issue by jamis460773** [Pr-Mex/vanessa-automation#1480]
Укажите:
   1. Версия Vanessa Automation: 1.2.0.38.1
   2. Версия платформы: 8.3.17.1549
   3. Режим совместимости базы, где запускается Vanessa Automation: 8.3.12
   4. Операционная система: windows 10

```Gherkin

Сценарий: Спецсимволы в шагах сценариев
И я делаю подсветку фрагмента текста в редакторе VA в строке в режиме обучения подсценарий 7 '"Часть1 \\" Часть2"' 'Параметр шага'

```
Во вложении текст ошибки и скрин.
![image](https://user-images.githubusercontent.com/3115412/147320489-8b8c8716-4a57-44ed-85e2-7ea67ec45dcb.png)
[error.txt](https://github.com/Pr-Mex/vanessa-automation/files/7772777/error.txt)

**Comment by Pr-Mex** [comment]
@jamis460773 
Приложите видео, пожалуйста, как у вас это происходит.

**Comment by Pr-Mex** [comment]
Не воспроизводится.
