### ISSUE TITLE
Ошибка определения пути при использовании workspaceRoot в параметрах

### ISSUE THREAD

**Issue by StupnikovVG** [Pr-Mex/vanessa-automation#1483]
```Gherkin

Контекст:
  Дано: Версия компоненты 1.2.0.38
  И Версия платформы 8.3.17.1989
  и в конфигурационном файле указаны параметры:
	"КаталогФич": "$workspaceRoot/features",
	"ДелатьОтчетВФорматеАллюр": true,
	"ОтчетAllure": {
		"КаталогВыгрузкиAllure": "$workspaceRoot/build/allure/add",
		"КаталогВыгрузкиAllureБазовый": "$workspaceRoot/build/allure/add"
         }

```

Для параметра "КаталогФич" подмена "$workspaceRoot" в пути происходит корректно, а для параметров "КаталогВыгрузкиAllure", "КаталогВыгрузкиAllureБазовый" подмена не происходит.  
Причина: ошибка в параметрах метода `ОбработатьСпецсимволыПриЧтенииНастроек` при его вызове для параметров вложенной структуры

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
