### ISSUE TITLE
Исправить опечатки в тексте подсказки

### ISSUE THREAD

**Issue by SOYAllure** [Pr-Mex/vanessa-automation#1487]
1. Исправить слово "Включет" на "Включает"
![image](https://user-images.githubusercontent.com/45041332/147732092-34ca0014-1fd5-4cc7-b667-56b7d6ccc631.png)

2. Исправить слово "отправлет" на "отправляет"
![image](https://user-images.githubusercontent.com/45041332/147732471-f789d504-bec0-42d9-96c7-5f800515ba74.png)

3. Исправить слово "мшкой" на "мышью"
4. Исправить слово "пноку" на "кнопку"
5. Исправить строение предложения с существующего на "_Если опция включена, то курсор мыши сначала переместится к кнопке, только после этого, кнопка будет нажата_" 
![image](https://user-images.githubusercontent.com/45041332/147733401-a91d8599-695e-46a0-b4c8-8f9010b85371.png)

6. Исправить слово "баузера" на "браузера"
![image](https://user-images.githubusercontent.com/45041332/147733460-41c01841-3b1f-49cd-b7a9-7eb7b7ca1c75.png)
....

**Comment by Pr-Mex** [comment]
@lelikanet 
Будешь создавать реквест?

**Comment by Pr-Mex** [comment]
Надо мне обновить MD  файлы, которые формируются по текстам подсказок.

**Comment by KrapivinAndrey** [comment]
@Pr-Mex А эти тексты можно как-то массово вытащить?

**Comment by Pr-Mex** [comment]
@KrapivinAndrey 
Исходники находятся в xml основной формы и править их надо там.
Также на основании этих подсказок к элементам я собираю этот файл документации
https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/Settings/SettingsRU.md

**Comment by KrapivinAndrey** [comment]
Про xml это понятно. Я про то, что если есть скрипт для разборки - можно организовать автопроверку орфографии. Если нет - надо организовать скрипт)

**Comment by KrapivinAndrey** [comment]
можно это даже на github-actions повесить. чтобы jenkins не гонять

**Comment by Pr-Mex** [comment]
@KrapivinAndrey 
Да, это было бы полезно.

**Comment by KrapivinAndrey** [comment]
Попробую сделать. Сначала подсказки - они более очевидно располагаются в xml.
Потом можно попробовать надписи обработать.

**Comment by Pr-Mex** [comment]
@KrapivinAndrey 
Супер! Давай.

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
