### ISSUE TITLE
Проверка экранирования фигурных скобок

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1489]
Надо проверить, что корректно работает шаг вида
И значение поля "А1" содержит текст '\{\"key\" : \"value\"\}'

**Comment by Pr-Mex** [comment]
@astrizhachuk

**Comment by Pr-Mex** [comment]
@astrizhachuk 
Нужен конкретный пример. Нужна база и сценарий.

**Comment by astrizhachuk** [comment]
@Pr-Mex проверил, FP. Ошибка с неработающим экранированием была связана с другой причиной, не связанной с VA.

**Comment by Pr-Mex** [comment]
@astrizhachuk 
Ок, тогда закрываю issue.
