### ISSUE TITLE
Некорректная работа сериализатора MXL при загрузке макетов, содержащих регистры накопления

### ISSUE THREAD

**Issue by 1cto** [Pr-Mex/vanessa-automation#149]
Функционал: Загрузка макетов с регистрами накопления
   Как бизнес-аналитик 
   Я хочу выгружать (и что важно: загружать!) макеты для воспроизведения сценариев на тестовой базе

Контекст:
Дано: 1.2.018
И 1С:Предприятие 8.3 (8.3.12.1790)
И Управление холдингом, редакция 1.3 (1.3.10.9)

Сценарий: Загрузка макета с движениями регистров накопления
  Допустим: Имеется макет с движениями РН [US42договор.zip](https://github.com/Pr-Mex/vanessa-automation/files/2763945/US42.zip)

  Когда: в VA выполняется шаг по загрузке из макета
  Тогда: выпадает вот такая ошибка
14.01.2019 14:13:21 ОписаниеОшибки()={ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(6296)}: Ошибка при вызове метода контекста (СоздатьДанныеПоТабличномуДокументуСервер): Ошибка передачи данных между клиентом и сервером. Значение недопустимого типа.: Ошибка преобразования данных XDTO:
НачалоСвойства: ret Форма: Элемент  Тип: {http://www.w3.org/2001/XMLSchema}anyType: Ошибка преобразования данных XDTO:
НачалоСвойства: Value   Форма: Элемент  Тип: {http://www.w3.org/2001/XMLSchema}anyType: Ошибка преобразования данных XDTO:
НачалоСвойства: {http://v8.1c.ru/8.1/data/enterprise/current-config}Filter  Форма: Элемент  Тип: {http://www.w3.org/2001/XMLSchema}anyType

![image](https://user-images.githubusercontent.com/15178930/51246246-a5daa480-1992-11e9-880e-b59320173444.png)

**Comment by Pr-Mex** [comment]
Решено.
