### ISSUE TITLE
Подготовка и загрузка данных, добавить флажок "Снять все"

### ISSUE THREAD

**Issue by ovcharenko-di** [Pr-Mex/vanessa-automation#1499]
Укажите:
   1. Версия Vanessa Automation 1.2.038
   2. Версия платформы 8.3.20
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.15
   4. Операционная система Win\Linux

Доработки:
1. На вкладке "Отбор по метаданным" нужна возможность снять все флажки. Без этого сложно генерировать фичи по частям - приходится снимать все лишние флажки вручную.

![image](https://user-images.githubusercontent.com/24920942/150142219-cff2ae3d-2c21-4094-9743-8ba73155c9e7.png)

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
