### ISSUE TITLE
Подготовка и загрузка данных, исключать колонки с пустыми значениями

### ISSUE THREAD

**Issue by ovcharenko-di** [Pr-Mex/vanessa-automation#1500]
Укажите:
   1. Версия Vanessa Automation 1.2.038
   2. Версия платформы 8.3.20
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.15
   4. Операционная система Win\Linux

Доработки:
1. Нужна опция, позволяющая исключить из таблиц Gherkin колонки с незаполненными значениями и значениями по умолчанию (False, 0 и тд). Это повысит удобство работы с таблицами.

![image](https://user-images.githubusercontent.com/24920942/150143430-31e194bf-f86d-492b-b2ff-631c051b91ae.png)

**Comment by DitriXNew** [comment]
Это будет весьма сложно реализовать. Фичу записали, но исправление будет не скоро.

**Comment by ovcharenko-di** [comment]
@DitriXNew я могу сам сделать, когда надоест по несколько экранов вправо скроллить 😄 

В код пока не заглядывал, но самый наивный способ будет выглядеть примерно так:
```bsl
Для Каждого Колонка Из ТаблицаGherkin.Колонки Цикл
    ЗначенияКолонки = ТаблицаGherkin.Выгрузить(Колонка.Имя).Свернуть(Колонка.Имя);
    Если ЗначенияКолонки.Количество() = 1 
        И Не ЗначениеЗаполнено(ЗначенияКолонки[0][Колонка.Имя]) Тогда
        // удалить колонку
    КонецЕсли;
КонецЦикла;
```

**Comment by DitriXNew** [comment]
Тут надо типы учитывать. Может быть составной тип, где пустая строка - это определение типа. Или Ложь.

**Comment by ovcharenko-di** [comment]
@DitriXNew @Pr-Mex я решил, что эта фича принесет больше вреда - при актуализации данных будет каша, если изначально фича была сформирована без лишних колонок, а потом с ними.

issue закрываю
