### ISSUE TITLE
Ошибка при использовании шага "И я проверяю или создаю для справочника "ИмяОбъекта" объекты:"

### ISSUE THREAD

**Issue by Divanmgn** [Pr-Mex/vanessa-automation#1503]
Укажите:
   1. Версия Vanessa Automation 1.2.038.1
   2. Версия платформы 8.3.19.1351
   3. Режим совместимости базы, где запускается Vanessa Automation "Не использовать"
   4. Операционная система Windows 10 Pro

> Заполните шаблон обсуждения GIT

```Gherkin

#language: ru
@tree
Функциональность: Выбор контрагента (создание в случае отсутствия)

Контекст:
	И я подключаю профиль TestClient "<Система>. База: File=\"C:\\1C.DB\\Infobase1\""
	И Я закрыл все окна клиентского приложения

@КодСценария=000000056
@UIDСценария=21d18468-79c0-11ec-8429-005056be090d
@UIDРазделПроекта=2e2229a4-7cc7-11eb-8ad3-50465d0655ee
Сценарий: Выбор контрагента (создание в случае отсутствия)
	И я проверяю или создаю для справочника "Контрагенты" объекты:
		| 'Ref'                                                               |'Наименование'|
		| 'e1cib/data/Справочник.Контрагенты?ref=80cd0050568d6b1711e97c9e11727398'|'ВЧ 45'|


> Прикладывайте файлы скриншотов

![image](https://user-images.githubusercontent.com/60695342/150299526-b487c540-cb80-40bd-afe7-85cb811d209c.png)

**Comment by DitriXNew** [comment]
А ошибка где?

**Comment by Divanmgn** [comment]
> А ошибка где?

на скриншоте

**Comment by Pr-Mex** [comment]
@DitriXNew 
![image](https://user-images.githubusercontent.com/8627416/150407333-6bb5ce83-6046-42e3-adab-e00e5140438c.png)

**Comment by DitriXNew** [comment]
Теперь вижу :) 
Это не ошибка, этот механизм не позволяет подключаться к другой базе. Загрузка идет в базе тест менеджера. И судя по всему - в вашей базе тест менеджера нет такого справочника.

Если все же это одна база, то приложите лог из журнала регистрации тест менеджера

**Comment by Divanmgn** [comment]
> Теперь вижу :) Это не ошибка, этот механизм не позволяет подключаться к другой базе. Загрузка идет в базе тест менеджера. И судя по всему - в вашей базе тест менеджера нет такого справочника.
> 
> Если все же это одна база, то приложите лог из журнала регистрации тест менеджера

Действительно так. Ванессу запускаю из СППР, а она в свою очередь запускает другую базу.
