### ISSUE TITLE
Ошибка разбора парсером VA выражения  в фигурных скобках. 

### ISSUE THREAD

**Issue by MVK80** [Pr-Mex/vanessa-automation#1507]
Укажите:
   1. Версия Vanessa Automation - 1.2.038.1
   2. Версия платформы - 8.3.20.1613
   3. Режим совместимости базы, где запускается Vanessa Automation - 8.3.18
   4. Операционная система - Windows 10. 

 Проблема: 
При попытке вычисления выражения в фигурных скобках, если внутри них содержится точка, то собственный парсер VA выдает ошибку. Смотрите скриншот. Он думает, что это таблица переменных! 
Ошибка разбора вот такой строки: {"e1cib/data/Catalog.Units?ref=" + СтрЗаменить(Новый УникальныйИдентификатор(), "-", "")}
Если включить галочку Использовать парсер Gherkin из компоненты VanessaExt, то сценарий отрабатывает без ошибок. 

Сам сценарий, для примера:

Контекст:
	Дано Я открыл новый сеанс TestClient или подключил уже существующий
		
Сценарий: создание большого объема данных (справочник Ед. измерения)
	И Я запоминаю значение выражения '1' в переменную "Шаг"
	И я делаю 10 раз
		И я запоминаю значение выражения '$Шаг$ + 1' в переменную "Шаг"
		И Я запоминаю значение выражения '"ед.изм." + $Шаг$' в переменную "ЕдиницаИзмерения"
		И я проверяю или создаю для справочника "Units" объекты:
			| 'Ref'                                                                                       | 'DeletionMark' | 'Code' | 'Item' | 'Quantity' | 'BasisUnit' | 'UOM' | 'Description_en'     | 'Description_hash' | 'Description_ru' | 'Description_tr' | 'Height' | 'Length' | 'Volume' | 'Weight' | 'Width' |
			| '{"e1cib/data/Catalog.Units?ref=" + СтрЗаменить(Новый УникальныйИдентификатор(), "-", "")}' | 'False'        |        | ''     | 1          | ''          | ''    | '$ЕдиницаИзмерения$' | ''                 | ''               | ''               |          |          |          |          |         |

		
**Стек вызовов и ошибка:**

![Screenshot_35](https://user-images.githubusercontent.com/37073189/150971673-cf1fd760-1482-49f0-ac50-30ee023775a7.png)

Ошибка вычисления выражения выражения <"e1cib/data/Catalog.Units?ref=" + СтрЗаменить(Новый УникальныйИдентификатор(), "-", "")>. Текст ошибки: <{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(29127)}: Ошибка вычисления переменной из выражения <"e1cib/data/Catalog.Units?ref=" + СтрЗаменить(Новый УникальныйИдентификатор(), "-", "")>. Таблица переменных не найдена.>.
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(29225)}:ВызватьИсключение СтрокаОшибки;
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(29272)}:Результат = Результат + ВычислитьВыражениеВнутриФигурныхСкобок(Выражение, ДанныеПоПростымПеременным, ДанныеПоПеременныхВТаблицах);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(29155)}:Выражение = ПодставитьЗначенияИнлайнВыраженийВСтроку(Выражение, ДанныеПоПростымПеременным, ДанныеПоПеременныхВТаблицах);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(25969)}:Значение = ВычислитьИнлайнВыражениеЕслиЭтоВозможно(Значение, ДанныеПоПростымПеременным, ДанныеПоПеременныхВТаблицах, МассивСценариевДляВыполнения[ТекИД_СценарияВМассиве].ЕстьСекцияПеременные);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(26883)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(28239)}:ВыполнитьШаг();
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(26456)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(26340)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(26883)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(28239)}:ВыполнитьШаг();
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(26456)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(26340)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(26883)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(28239)}:ВыполнитьШаг();
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(26456)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(26340)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(26883)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(28239)}:ВыполнитьШаг();
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(26456)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(26340)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(26883)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);

**Comment by MVK80** [comment]
Модуль управляемой формы. Строка 29212. Функция ВычислитьВыражениеВнутриФигурныхСкобок.
В общем парсер проверяет:
			Если ДанныеПоПеременныхВТаблицах <> Неопределено И Найти(Выражение, ".") > 0 Тогда
				НовоеЗначение = ЗначениеИзТаблицыПеременных(Выражение, ДанныеПоПростымПеременным, ДанныеПоПеременныхВТаблицах);
				Если НовоеЗначение <> Неопределено Тогда
					Возврат НовоеЗначение; 
				КонецЕсли;	 
			КонецЕсли;	 

а нас на входе пустая структура приходит. А дальше идет попытка получения значения из таблицы переменных!
Если в этой точке заменить значение ДанныеПоПеременныхВТаблицах  на Неопределено, то всё отрабатывает.

**Comment by Pr-Mex** [comment]
@MVK80 
Это уже исправлялось.
Проверьте на версии из ветки develop, пожалуйста.

**Comment by MVK80** [comment]
@Pr-Mex, не исправлено. Прикладываю скриншот. При включенной галочке "Использовать парсер Gherkin из компоненты VanessaExt" работает нормально. 
![Screenshot_37](https://user-images.githubusercontent.com/37073189/151028805-09b7757c-a201-41df-b397-b23fc43127f3.png)

**Comment by Pr-Mex** [comment]
@MVK80 
Хорошо, посмотрю.

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
