### ISSUE TITLE
При одновременном формировании отчетов Allure и JUnit с флагом "Добавлять скриншоты в отчеты (GitLab)" нет файла скриншота в JUnit

### ISSUE THREAD

**Issue by 1cgh** [Pr-Mex/vanessa-automation#1508]
1. VA 1.2.037.18
   2. Версия платформы: любая из поддерживаемых
   3. Режим совместимости: любой из поддерживаемых
   4. Операционная система: любая из поддерживаемых

Если установить настройки снятия скриншотов, формирования отчетов в форматах Allure и JUnit с флагом "Добавлять скриншоты в отчеты (GitLab)", то при сохранении результатов JUnit в GitLab отсутствуют файлы скриншотов при ошибках.

Причина, скорее всего, в том, что файл скриншота **переносится** из каталога скриншотов в каталог результатов Allure, а в JUnit ссылка на файл указывает на его расположение в каталоге скриншотов, где его уже нет.

**Comment by Pr-Mex** [comment]
@1cgh 
Прикрепи json с настройками VA, плиз, при которых это воспроизводится.

**Comment by 1cgh** [comment]
[VAParams.txt](https://github.com/Pr-Mex/vanessa-automation/files/7942151/VAParams.txt)

**Comment by Pr-Mex** [comment]
@1cgh 
Проверь на 1.2.038. пожалуйста.
Должно работать.

**Comment by Pr-Mex** [comment]
@1cgh 
Хотя не надо. Понял проблему. Буду исправлять.

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
