### ISSUE TITLE
Ошибка. Выполняется не текущая открытая фича, а прописанная в настройках

### ISSUE THREAD

**Issue by azheval** [Pr-Mex/vanessa-automation#1509]
Укажите:
   1. Версия Vanessa Automation 1.2.038.1

Воспроизведение:
1. Сохраняем в каталог фичу 001.
2. Выгрузить настройки в файл. В параметр "Каталог фич" сохраняется и каталог и путь к текущей фиче 001.
3. Сохраняем в каталог фичу 002.
4. Переоткрываем VA.
5. Открываем файл фичи 002.
6. Загрузить настройки из файла. В текущий каталог функциональности загружается путь с фичей 001.
7. Выполняем фичу 002.
8. Вместо фичи 002 выполняется фича 001.

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
