### ISSUE TITLE
Год в дате отчета Allure

### ISSUE THREAD

**Issue by zeegin** [Pr-Mex/vanessa-automation#151]
```Gherkin
Сценарий: Просмотр отчета Allure
  Допустим: Я открываю отчет Allure
  Когда: Я смотрю на дату
  Тогда: Я хочу чтобы она показывала реальный год в дате теста.
```
Например сегодняшний тест может показать дату "1/16/3988"

**Comment by Pr-Mex** [comment]
Ты знаешь как это поправить?

**Comment by zeegin** [comment]
Пока нет, надо ковырять.

**Comment by hawk911** [comment]
Это связано с тем, что используется функция 1С `ТекущаяУниверсальнаяДатаВМиллисекундах()`. Она считает от `Jan 1, 1970 00:00:00 UTC`  а от  `Jan 1, 0001 00:00:00 UTC`. В Allure нужен формат, который идёт от 1970

**Comment by Pr-Mex** [comment]
@hawk911 
Спасибо! Стало понятнее.

**Comment by hawk911** [comment]
Можно закрывать. Исправлено.
