### ISSUE TITLE
Не срабатывает отбор по тегам в рамках одного сценария при использовании нового парсера

### ISSUE THREAD

**Issue by SevernityQA** [Pr-Mex/vanessa-automation#1510]
Укажите:
   1. VA 1.2.038.1
   2. 8.3.20.1613

При установленной галочки использовать парсер Gherkin из компоненты VanessaExt не срабатывает отбор по тегам в рамках одного сценария (и в случае исключаемых тегов и в случае отбора тегов для запуска), выполняются все сценарии из фича файла.

**Comment by Pr-Mex** [comment]
@SevernityQA 
Приведи пример воспроизведения, пожалуйста.

**Comment by SevernityQA** [comment]
Во вложении пример фича файла в котором 2 сценария, у первого сценария тег @ПоступлениеТоваров, у второго @Номенклатура. Ставлю отбор для запуска по тегу @Номенклатура, но все равно выполняется 2 сценария (галочка использовать парсер Gherkin из компоненты VanessaExt снята)  
[Тест.zip](https://github.com/Pr-Mex/vanessa-automation/files/7956763/default.zip)

**Comment by Pr-Mex** [comment]
@SevernityQA Разобрался.

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
