### ISSUE TITLE
Не реализовано выполнение шага И я проверяю или создаю для справочника "ИмяОбъекта" объекты с обмен данными загрузка истина:

### ISSUE THREAD

**Issue by dimjmur** [Pr-Mex/vanessa-automation#1517]
Укажите:
   1. Версия Vanessa Automation: 1.2.38.1
   2. Версия платформы: 8.3.20.1674 
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.20 (Не использовать)
   4. Операционная система Windows Server 2019

> Заполните шаблон обсуждения GIT

Сценарий: При запуске шага
`И я проверяю или создаю для справочника "ИмяОбъекта" объекты с обмен данными загрузка истина:`
  Допустим: 	
```
`И я проверяю или создаю для справочника "ИмяОбъекта" объекты с обмен данными загрузка истина:`
		| 'Ссылка'                                                           | 'ПометкаУдаления' | 'Код'       | 'Наименование'           |
		| 'e1cib/data/Справочник.Банки?ref=8ca0000d8843cd1b11dc8d043d71008e' | 'False'           | '000000006' | 'МосСтройСити Банк'      |

```
  Когда: Запускается выполнение шага
  Тогда: 
Выводится сообщение:
`Пустой` адрес снипета у шага: И я проверяю или создаю для справочника "Банки" объекты с обмен данными загрузка истина:`

Исследование вороса показало, что шаг 
И я проверяю или создаю для справочника "Банки" объекты:
выполняется без ошибок. 
Не выполняется именно, обмен данными = истина
Кроме того, оказались не реализованы и другие шаги с этим предложением .
У себя добавил реализацию этих шагов, могу сделать PR. Или же лучше чтобы исправил автор этого модуля?

**Comment by Pr-Mex** [comment]
@DitriXNew 
Ответь, плиз.

**Comment by DitriXEDT** [comment]
На самом деле там была проблема в том, что исторически - шаги без  ```с обмен данными загрузка истина```, грузились с ложью, и было много жалоб от людей.
Мы сделали новые шаги, с этим окончанием, но уже было написанно тысячи тестов, и переделывать их было почти не реально. Поэтому по сути надо реализовать:
```с обмен данными загрузка Ложь```, а не истина.
Или, лучше вообще указывать параметром Ложь или Истина.
А те что есть шаги - так и оставить уже для совместимости.
Так что перепроверьте код, там одни и те же функции вызываются. Если уже кто-то что-то не исправил :)

**Comment by dimjmur** [comment]
Так может быть реализовать оба варианта, Загрузка = Истина, и Загрузка = Ложь.

**Comment by Pr-Mex** [comment]
@dimjmur 
Как я понял в коде была ошибка.
Этот реквест её должен исправить 
https://github.com/Pr-Mex/vanessa-automation/pull/1518#issuecomment-1024640298

**Comment by Pr-Mex** [comment]
@dimjmur 
Реквест принят. Можете проверить исправление?

**Comment by dimjmur** [comment]
@Pr-Mex, да, проверю - напишу.

**Comment by dimjmur** [comment]
> 
Сообщение изменилось: 
31.01.2022 11:57:54 {<Неизвестный модуль>(1)}: Метод объекта не обнаружен (ЯПроверяюИлиСоздаюДляСправочникаОбъектыСОбменДаннымиЗагрузкаИстина)
--
Не были внесены изменения в файл 
..\vanessa-automation\features\Libraries\ПодготовкаИЗагрузкаДанных\ПодготовкаИЗагрузкаДанных.epf 
Там тоже нужно добавить эти функции.

**Comment by Pr-Mex** [comment]
@dimjmur 
Принял ещё один реквест по исправлению этой проблемы. Проверьте, пожалуйста.

**Comment by dimjmur** [comment]
@Pr-Mex Всё ОК!

**Comment by KalyakinAG** [comment]
аналогичная проблема с регистром сведений: подсказка есть, а снипет отсутствует

![image](https://user-images.githubusercontent.com/6729749/154688343-67693171-c50f-4065-a934-2f9605b6dcf4.png)
