### ISSUE TITLE
Убрать Формат у некоторых шагов связанные с Датой

### ISSUE THREAD

**Issue by hawk911** [Pr-Mex/vanessa-automation#152]
```Gherkin

Сценарий:  Формат даты зависит от "локали" Windows
  Допустим: Я пишу шаг "Я ввожу начало месяца" и у меня формат даты 15/12/2019
  Когда: Шаг "Я ввожу начало месяца" сравнивает даты с учётом "локали" Windows
  Тогда:  Тест проходит 

```

- Считаем, что "локаль" Windows у разработчика и развёрнутого тестового сервера совпадает. 
- Сейчас используется принудительное формитирование даты до ДД.ММ.ГГГГ.  Это некорректно. 
- Изменить все шаги, в которых явно не указывается дата.

**Comment by Pr-Mex** [comment]
Переехало в https://github.com/Pr-Mex/vanessa-automation/issues/732
