### ISSUE TITLE
Ошибка при записи Видеоинструкций, если Имя пользователя Windows на кириллице.

### ISSUE THREAD

**Issue by inD000** [Pr-Mex/vanessa-automation#1522]
1. vanessa-automation.1.2.038.1
   2. 1C 8.3.20.1613 x64
   3. Режим совместимости базы - Не использовать
   4. Win 10

Ошибка при записи Видеоинструкций, если Имя пользователя Windows на кириллице.
![274fda718ddfc629cf31b172997a3690](https://user-images.githubusercontent.com/97388786/151790084-a36f4993-ba13-4861-8731-f50a6df365dd.jpg)

Решение:
В обработке РаботаСВидео.epf

1. Во всех местах, где выполняется запись во временные файлы формата "bat" и "cmd" заменить кодировку "UTF-8" на "cp866"
	
Пример 1: 	
ИмяВременногоФайла = ПолучитьИмяВременногоФайла("cmd");

Было: ЗТ = Новый ЗаписьТекста(ИмяВременногоФайла, "UTF-8", , Истина);
Стало: ЗТ = Новый ЗаписьТекста(ИмяВременногоФайла, "cp866", , Истина);

Пример 2:
ИмяВременногоBat = ПолучитьИмяВременногоФайла("bat");

Было: ЗТ = Новый ЗаписьТекста(ИмяВременногоBat, "UTF-8", , Истина);
Стало: ЗТ = Новый ЗаписьТекста(ИмяВременногоBat, "cp866", , Истина);

2. Убрать команды ЗТ.ЗаписатьСтроку("CHCP 65001");

**Comment by Pr-Mex** [comment]
@inD000 
1. Посмотрите какой язык у вас задан в ОС для команд Unicode. Должен быть русский язык.
2. Я бы не стал сейчас в VA менять кодировку для файлов из командной строки. Это уже давно стабилизированный механизм.
3. Ещё можно переопределить в ОС временный каталог пользователя, чтобы там не было русских букв.

**Comment by inD000** [comment]
> @inD000
> 
> 1. Посмотрите какой язык у вас задан в ОС для команд Unicode. Должен быть русский язык.
> 2. Я бы не стал сейчас в VA менять кодировку для файлов из командной строки. Это уже давно стабилизированный механизм.
> 3. Ещё можно переопределить в ОС временный каталог пользователя, чтобы там не было русских букв.

**Comment by inD000** [comment]
Нашел еще 1 вариант решения. 
Нужно установить галочку в настройках языка Windows
![Региональные стандарты](https://user-images.githubusercontent.com/97388786/151928343-62bba881-6260-4f2d-90f1-2a494d9488fc.jpg)

**Comment by Pr-Mex** [comment]
Ага, супер.
