### ISSUE TITLE
Сделать VanessaInteractiveDemo для вэб клиента.

### ISSUE THREAD

**Issue by ViktorErmakov** [Pr-Mex/vanessa-automation#1523]
Укажите:
   1. Версия Vanessa Automation
   2. Версия платформы
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система

> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: <Необходимый эффект>
   Как <роль пользователя>
   Я хочу <Необходимый функционал>

Контекст:
  Дано: <версия инструментария>
  И <полная версия 1С>
  и <конфигурация запуска>

Сценарий: <ожидамое поведение>
  Допустим: <Пример данных>
  Когда: <Что-то нажимается или вызывается>
  Тогда: <Что-то происходит>

```

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
