### ISSUE TITLE
Если в каталоге отчета Allure использовать русские буквы, то отчет будет пустым

### ISSUE THREAD

**Issue by KalyakinAG** [Pr-Mex/vanessa-automation#1529]
Укажите:
   1. Версия Vanessa Automation 1.2.038.1
   2. Версия платформы 8.3.18.1520
   3. Режим совместимости базы, где запускается Vanessa Automation - Не использовать
   4. Операционная система Windows 10

```Gherkin
Функционал: каталог отчета Allure
   Как Тестировщик
   Я хочу чтобы данные отчета сохранялись в указанном каталоге

Контекст:
  Дано: Vanessa Automation 1.2.038.1, Allure 2.17.2
  И 8.3.18.1520
  и Демонстрационное приложение (1.0.34.1)

Сценарий: система должна отобразить отчет по результату работы тестового сценария
  Допустим: есть результат выполнения сценария в каталоге "Новая папка"
  Когда: вызывается команда Показать отчет Allure
  Тогда: система не находит каталог отчета Allure и формирует пустой отчет
```

![image](https://user-images.githubusercontent.com/6729749/152307276-efcc8f38-9fa3-4789-839c-f5344dc9154b.png)

**Comment by Pr-Mex** [comment]
@KalyakinAG 
Посмотрите тут
https://github.com/Pr-Mex/vanessa-automation/issues/1522
У вас видимо та же проблема.

**Comment by KalyakinAG** [comment]
Да, т.е. просто лучше не использовать русские буквы в настройках путей внешних инструментов. Ок.

**Comment by Pr-Mex** [comment]
@KalyakinAG 
В указанной тебе проблему решили изменением настроек ОС.
