### ISSUE TITLE
Мелкий глюк на форме + опечатки

### ISSUE THREAD

**Issue by miofik** [Pr-Mex/vanessa-automation#1530]
Укажите:
   1. Версия Vanessa Automation   1.2.0.38.1
   2. Версия платформы  8.3.18.1363
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система Windows 2008 R2

Ошибка при нажатии на кнопку подбор в списке значений тегов для запуска
![image](https://user-images.githubusercontent.com/97720882/152632982-377236af-0c82-416a-ac8b-44ffa6e400b8.png)

Опечатки в подсказке
![image](https://user-images.githubusercontent.com/97720882/152633015-cb662290-414c-4366-b345-7ffa5749f5ab.png)

**Comment by Pr-Mex** [comment]
@miofik 
По опечаткам - они уже исправлялись. Тут надо смотреть что в ветке develop.

**Comment by miofik** [comment]
такая же ошибка со списком значений в поле "Список исключаемых тегов" на этой же странице чуть выше

**Comment by Pr-Mex** [comment]
@miofik 
Про список значений посмотрю.

**Comment by Pr-Mex** [comment]
@miofik 
Посмотрел. Не найду где отключить эту кнопку подбора.

**Comment by Pr-Mex** [comment]
@miofik 
Видимо эта кнопка не отключается. Закрываю.
