### ISSUE TITLE
Не нажимается кнопка в диалоге типа ПоказатьВопрос при включенной настройке Использовать UI Automation

### ISSUE THREAD

**Issue by Divanmgn** [Pr-Mex/vanessa-automation#1534]
Укажите:

Версия Vanessa Automation 1.2.038.1
Версия платформы 8.3.19.1351
Режим совместимости базы, где запускается Vanessa Automation "Не использовать"
Операционная система Windows 10 Pro
Заполните шаблон обсуждения GIT

Функционал: Выбор ответа на вопрос

Контекст:
	И я подключаю профиль TestClient "<Система>. База: File=\"C:\\1C.DB\\Infobase1\""
	И Я закрыл все окна клиентского приложения

Сценарий: 
При отработке шагов, я ожидаю, что откроется диалог с вопросом, где буду отражены кнопки Да и Нет. Далее нажмется кнопка Нет. 
Вот шаги
И я нажимаю на кнопку с именем 'ФормаОтправитьЗапрос'
Тогда открылось окно '1С:Предприятие'
И я нажимаю на кнопку 'Нет'

  Допустим: 
И я нажимаю на кнопку с именем 'ФормаОтправитьЗапрос'
Тогда открылось окно '1С:Предприятие'
И я нажимаю на кнопку 'Нет'
  Когда: в настройках используется Использовать UI Automation
  Тогда: возникает ошибка
{ВнешняяОбработка.VanessaAutomationsingle.Форма.Тест_РаботаСИнтерфейсом.Форма(3929)}: Не получилось нажать на кнопку <Нет>.
{ВнешняяОбработка.VanessaAutomationsingle.Форма.УправляемаяФорма.Форма(14654)}: Не получилось найти кнопку средствами UI Automation <<Система>. База: File="C:\1C.DB\РСП для автотестов">.

Технические данные:
        ЗаголовокАктивногоОкна: 1С:Предприятие
        ИмяАктивнойФормы: MessageBox
        ИмяФичи: Запуск нескольких сценариев
        ИмяСценария: Основной тест
        НомерСтрокиДерева: 76
        НомерСтрокиФичи: 109
        ПолныйПутьКФиче: E:\!Работа_Ваня\РСП\Тестирование\Commons\Exchange\Features\Test.feature
        ИмяФайла: ВнешняяОбработка.VanessaAutomationsingle.Форма.Тест_РаботаСИнтерфейсом
        ИмяПроцедуры: ЯНажимаюНаКнопку
        ИмяРаннера: DESKTOP-AIRA4VB
        ТипПлатформы: Windows x86
        ТипКлиентаТестирования: Тонкий
        СтрокаСоединения: File="C:\1C.DB\РСП для автотестов"
        PIDКлиентаТестирования: 1980
        ВерсияVA: ver 1.2.038.1
        ВерсияПлатформы: 8.3.19.1351
        РежимСовместимостиTestManager: НеИспользовать
        ДатаВремяОшибки: 28.01.2022 17:59:24
Текст модального окна:
    Отправить через пакет?

К сожалению базу приложить не могу. На пустой конфигурации ошибку также не удалось воспроизвести. Все отработало нормально. Однако, ее удалось воспроизвести на типовой демо базе 1С:ERP Управление предприятием 2 (2.5.7.269) со следующим сценарием
И В командном интерфейсе я выбираю 'Склад и доставка' 'Пересчеты товаров'
Тогда открылось окно 'Пересчеты товаров'
И я нажимаю на кнопку с именем 'СоздатьЗаданиеНаПересчетНеадресныйСклад'
Тогда открылось окно 'Пересчет товаров (создание)'
И я нажимаю кнопку выбора у поля с именем "Склад"
Тогда открылось окно 'Склады и магазины'
И в таблице "Список" я перехожу на один уровень вниз
И в таблице "Список" я перехожу на один уровень вниз
И в таблице "Список" я выбираю текущую строку
Тогда открылось окно 'Пересчет товаров (создание) *'
И я перехожу к закладке с именем "ГруппаТовары"
И я нажимаю на кнопку с именем 'ТоварыЗаполнить'
И я нажимаю на кнопку с именем 'ФормаПровести'
Тогда открылось окно '1С:Предприятие'
И я нажимаю на кнопку 'Отмена'

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
