### ISSUE TITLE
Ошибка при сохранении фиче-файла

### ISSUE THREAD

**Issue by miofik** [Pr-Mex/vanessa-automation#1535]
Укажите:

Версия Vanessa Automation 1.2.0.38.1
Версия платформы 8.3.18.1363
Режим совместимости базы, где запускается Vanessa Automation
Операционная система Windows 2008 R2

Если в последнем сценарии в имени стереть букву ы (то есть имя сценария будет пустым) то при сохранении будет ошибка (хотя сам файл все равно сохранится). Стабильно ошибка не воспроизводится (сохранение с пустым именем сценария), но уже второй раз поймал ее.

Поле объекта не обнаружено (name)
{ExternalDataProcessor.VanessaAutomation.Form.ПарсерGherkin.Form(420)}:		СтрокаСценария.Имя = СокрЛП(ДанныеСценария.name);
{ExternalDataProcessor.VanessaAutomation.Form.ПарсерGherkin.Form(406)}:			ДобавитьСценарий(ЭлементыФичи, ДанныеСценария, ФайлФичи, ИдСтроки, КешСнипетовНаКлиенте, Ложь, СтруктураПараметров);
{ExternalDataProcessor.VanessaAutomation.Form.ПарсерGherkin.Form(171)}:			ДобавитьФичу(СтрокаИмяФайла.ПолучитьЭлементы(), ДанныеJSON, ФайлФичи, ИдСтроки, КешСнипетовНаКлиенте, Неопределено, СтруктураПараметров);

[Заказ-поставщику.txt](https://github.com/Pr-Mex/vanessa-automation/files/8013295/-.txt)

**Comment by asosnoviy** [comment]
Парсер из компоненты?

**Comment by Pr-Mex** [comment]
@miofik 
Это уже исправлялось. Проверьте на VA из ветки develop.

**Comment by asosnoviy** [comment]
> @miofik Это уже исправлялось. Проверьте на VA из ветки develop.

На днях падал на этом же месте, но по другой причине. Вроде как на девелопе. Перепроверю.

**Comment by Pr-Mex** [comment]
@asosnoviy 
Ага, напиши как проверишь.

**Comment by asosnoviy** [comment]
@Pr-Mex я упал в другом месте. Ща закину ихуз.

**Comment by Pr-Mex** [comment]
@asosnoviy 
Тогда этот закрываем?

**Comment by asosnoviy** [comment]
@miofik Удалось проверить на девелопе?

**Comment by asosnoviy** [comment]
@Pr-Mex проверил этот кейс. На сингле 38.1 падает. На девелопе не падает. Можно закрывать.
