### ISSUE TITLE
Ошибка при использовании одинакового имени локальной/глобальной переменной 

### ISSUE THREAD

**Issue by miofik** [Pr-Mex/vanessa-automation#1543]
Укажите:
   1. Версия Vanessa Automation 1.2.0.38.1
   2. Версия платформы 8.3.18.1363
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система Windows 2008 R2

Этот код отрабатывает без ошибок: 
```
	И я сохраняю навигационную ссылку текущего окна в переменную "$$Ссылка1$$"
	И я сохраняю навигационную ссылку текущего окна в переменную "$Ссылка1$"
```

Но если поменять строки местами, то есть так: 
```
	И я сохраняю навигационную ссылку текущего окна в переменную "$Ссылка2$"
	И я сохраняю навигационную ссылку текущего окна в переменную "$$Ссылка2$$"

```

То будет ошибка: 

09.02.2022 9:52:47 {ExternalDataProcessor.РаботаСИнтерфейсом.Form.Форма.Form(15730)}: {ExternalDataProcessor.VanessaAutomation.Form.УправляемаяФорма.Form(11703)}: Ошибка при вызове метода контекста (Insert): Задано неправильное имя атрибута структуры

Технические данные:
        ЗаголовокАктивногоОкна: Товар без характеристик (Номенклатура)
        ИмяАктивнойФормы: Catalog.Items.Form.ItemForm
        ИмяФичи: <описание фичи>
        ИмяСценария: глобальные переменные
        НомерСтрокиДерева: 33
        НомерСтрокиФичи: 46
        ПолныйПутьКФиче: C:\Users\miofik\Documents\GitHub\TestQA\Internal\Модуль-5\ТестПеременные.feature
        ИмяФайла: C:\Program Files\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf
        ИмяПроцедуры: ЯСохраняюНавигационнуюСсылкуТекущегоОкнаВПеременную
        ИмяРаннера: msk
        ТипПлатформы: Windows x86-64
        ТипКлиентаТестирования: Тонкий
        СтрокаСоединения: File="C:\Users\miofik\Documents\TestIRP";
        PIDКлиентаТестирования: 27000
        ВерсияVA: ver 1.2.038.1
        ВерсияПлатформы: 8.3.18.1363
        РежимСовместимостиTestManager: DontUse
        ДатаВремяОшибки: 09.02.2022 9:52:47
09.02.2022 9:52:46 Шаг (И я сохраняю навигационную ссылку текущего окна в переменную "$$Ссылка2$$") не выполнен.

**Comment by Pr-Mex** [comment]
@miofik 
Проверил на версии из ветки develop. Не воспроизводится.
Проверьте, пожалуйста.
Либо уточните сценарий воспроизведения.
