### ISSUE TITLE
Ошибка после прохождения тестов при заполненном пути в настройке Каталог allure отчета (несколько сборок)

### ISSUE THREAD

**Issue by SevernityQA** [Pr-Mex/vanessa-automation#1544]
1. VA 1.2.038.8
   2. Версия платформы 8.3.20.1613
 
При заполненном пути Каталог allure отчета (несколько сборок) после прохождения тестов возникает ошибка
![image](https://user-images.githubusercontent.com/88192056/153427286-cf5c74bd-c6b5-40b7-be89-bef2ebef3196.png)
Файл настроек во вложении
[VAParams.zip](https://github.com/Pr-Mex/vanessa-automation/files/8041725/VAParams.zip)

**Comment by Pr-Mex** [comment]
@SevernityQA 
Не воспроизводится.
Приведи, пожалуйста, полный сценарий как такое получить.

**Comment by SevernityQA** [comment]
@Pr-Mex 
Это видео и сценарий для воспроизведения
[ПримерОшибки.zip](https://github.com/Pr-Mex/vanessa-automation/files/8110506/default.zip)
[Проверка заполненности поля Организация.zip](https://github.com/Pr-Mex/vanessa-automation/files/8110511/default.zip)

**Comment by SevernityQA** [comment]
[IRP.zip](https://github.com/Pr-Mex/vanessa-automation/files/8111594/IRP.zip)

**Comment by Pr-Mex** [comment]
Понял в чём проблема. Она воспроизводится только при запуске теста локально, когда указан каталог базовый, но не указан простой каталог Allure.

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
