### ISSUE TITLE
Разрешить вызывать подсценариям одной и той же фичи вызывать друг друга.

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1549]
Разрешить вызывать подсценариям одной и той же фичи вызывать друг друга.

**Comment by nixel2007** [comment]
Ооо, так это возможно? Нарывались на обучениях.

**Comment by Pr-Mex** [comment]
Теперь это легально.

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
