### ISSUE TITLE
В подготовке данных выгрузки для регистра сведений не учитывается настройка Обмен данными

### ISSUE THREAD

**Issue by KalyakinAG** [Pr-Mex/vanessa-automation#1554]
Укажите:
   1. Версия Vanessa Automation 1.2.038.1 single
   2. Версия платформы 1С:Предприятие 8.3 (8.3.18.1483)
   3. Режим совместимости базы, где запускается Vanessa Automation Версия 8.3.14
   4. Операционная система Windows 10

```Gherkin
Функционал: Подготовка и загрузка данных
   Как Тестировщик
   Я хочу Подготовить тестовые данные

Контекст:
  Дано: Vanessa Automation 1.2.038.1 Подготовка и загрузка данных
  И 1С:Предприятие 8.3 (8.3.18.1483)
  и конфигурация на базе БСП

Сценарий: Должен подставиться шаг "И я проверяю или создаю для регистра сведений "ИмяРегистра" записи с обмен данными загрузка истина"
  Допустим: регистр сведений помечен к выгрузке данных и обмен данными загрузка выбран "Да"
  Когда: вызывается команда "Сгенерировать фичу"
  Тогда: система показывает текст фичи с шагом "И я проверяю или создаю для регистра сведений "ИмяРегистр" записи"

```

> Прикладывайте файлы скриншотов

![image](https://user-images.githubusercontent.com/6729749/154633905-f1dd000b-ccda-4053-84e4-311feb169057.png)

**Comment by Pr-Mex** [comment]
Закрываю, обсуждение продолжается тут:
https://github.com/Pr-Mex/vanessa-automation/issues/1517
