### ISSUE TITLE
Ошибка сравнения области макета с эталонным макетом

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1556]
ТипПлатформы: Windows x86-64
        ТипКлиентаТестирования: Тонкий
        ВерсияVA: ver 1.2.038.1
        ВерсияПлатформы: 8.3.20.1674
        РежимСовместимостиTestManager: Версия8_3_16
        ДатаВремяОшибки: 18.02.2022 20:15:32

Функционал:  сравнение области макета с эталонным макетом
   Как тестировщик
   Я хочу получить работоспособный шаг, который будет работать быстрее, чем И табличный документ равен макету

Контекст:
  Дано: 1.2.038.1
  И 8.3.20.1674
  и VA полная

Сценарий: сравнение области макета с эталонным макетом
  Допустим:  у нас есть табличный документ  сформированного отчета в предприятии
  Когда я вызываю шаги
  	Когда Я задаю параметры чтения области макета "R6C7:R79C8"
	И область "R6C7:R79C8" табличного документа "Результат" равна макету "эталон"	
Я ожидаю, что область "R6C7:R79C8" равная последним колонкам отчета (сальдо конечное) будет равна точно такому же макету, сохраненному как эталон.
А VA выдает ошибку 

![image](https://user-images.githubusercontent.com/19662685/154731636-c9d6b313-376a-45b0-9e90-3528c2dcf659.png)
![image](https://user-images.githubusercontent.com/19662685/154731934-e8a9eaa5-2f7e-4fe9-a2ce-0cdac5797792.png)
![image](https://user-images.githubusercontent.com/19662685/154732504-7df356ac-2f05-43a2-a7e3-fdd3f380560a.png)

В случае, если в эталонный макет сохранить весь макет и в какой нибудь ячейке ЗА проверяемой областью изменить значение, то шаг
И область "R6C7:R79C8" табличного документа "Результат" равна макету "эталон"
тоже упадет, хотя ожидалось, что VA И не должна анализировать ячейки ЗА проверяемой областью

**Comment by Pr-Mex** [comment]
@akademik1986 
Нужно ещё приложить эталонный макет, сценарий и базу, на которой можно воспроизвести проблему.

**Comment by akademik1986** [comment]
[Downloads.zip](https://github.com/Pr-Mex/vanessa-automation/files/8099337/Downloads.zip)

**Comment by akademik1986** [comment]
там немного другие области задействованы, потому что по-быстрому переделал на демонстрационную базу

**Comment by Pr-Mex** [comment]
@akademik1986 
И название конфигурации

**Comment by Pr-Mex** [comment]
@akademik1986 
Оказывается dt уже приложен в архиве.

**Comment by Pr-Mex** [comment]
@akademik1986 
У тебя неправильный эталон.
![image](https://user-images.githubusercontent.com/8627416/154795099-55ec5751-6b28-40d6-bd69-dbfe66703b18.png)

В нём есть лишняя строка. Поэтому в эталоне ожидается 217 строк, а в фиче ты пытаешься считать 216 строк (с 2 по 217)

**Comment by Pr-Mex** [comment]
@akademik1986 
Плюс нашел проблему вывода данных, т.к. в эталоне были пустые строки.
Это поправлю. Спасибо.

**Comment by akademik1986** [comment]
@Pr-Mex Можно возобновить заявку? Я понял что не указал в параметрах для воспроизведения! Нужно установить настройку использовать получения макетов через VanessaExtension. Пример все также можно использовать тот, что я выкладывал выше
![image](https://user-images.githubusercontent.com/19662685/155486194-4a87d3d9-b5d8-4561-b593-e2a8728d7881.png)
![image](https://user-images.githubusercontent.com/19662685/155486358-1a647b6b-e6e0-423a-bcd0-fc4ffc819f12.png)

**Comment by Pr-Mex** [comment]
@akademik1986 
Проверьте ваш случай на VA из ветки develop, пожалуйста

**Comment by akademik1986** [comment]
![image](https://user-images.githubusercontent.com/19662685/155492328-d66a2de3-21e4-43f9-8dee-f26bceff3337.png)
Прикрепи пжт собранную версию, хоть VaSingle

**Comment by akademik1986** [comment]
@Pr-Mex  Подтверждено на версии из develop!
![image](https://user-images.githubusercontent.com/19662685/155506859-968e3d8e-ea0b-4c08-8600-a17f50b3c6a8.png)

PS зачем compile просит 17 версию для сборки?

**Comment by Pr-Mex** [comment]
@akademik1986 
Ага, посмотрю

**Comment by Pr-Mex** [comment]
@akademik1986 
8.3.17 надо, чтобы гарантировать сборку.

**Comment by akademik1986** [comment]
Вот теперь все хорошо, спасибо!
