### ISSUE TITLE
Разное поведение шага "И из выпадающего списка с именем "ИмяПоля" я выбираю по строке "ЧастьСтроки"" в зависимости от настройки ввода по клавиатуре

### ISSUE THREAD

**Issue by chEEzys** [Pr-Mex/vanessa-automation#1562]
1. Версия Vanessa Automation - 1.2.038.1
   2. Версия платформы - 8.3.10
   3. Режим совместимости базы, где запускается Vanessa Automation - Выключен
   4. Операционная система - Windows 10

**Шаги воспроизведения:**
- ЭмулироватьВводКлавиатурыVanessaExt = false
- шаг вида `И из выпадающего списка с именем "Реквизит" я выбираю по строке 'Значение'` делает выбор значения без открытия формы списка выбора
- ЭмулироватьВводКлавиатурыVanessaExt = true

**Ожидаемый результат:**
- шаг вида `И из выпадающего списка с именем "Реквизит" я выбираю по строке 'Значение'` делает выбор значения без открытия формы списка выбора

**Действительный результат:**
- шаг вида `И из выпадающего списка с именем "Реквизит" я выбираю по строке 'Значение'` открывает форму списка выбора, что в итоге работает некорректно, т.к. список выбора например может быть более 1000 строк

![image](https://user-images.githubusercontent.com/52081206/155150749-12231422-745b-49c8-908e-489ba0a94a8b.png)

**Comment by chEEzys** [comment]
8.3.10 - Такси.
Форма выбора из списка появляется всегда, вне зависимости от включенной галки клавиатуры и даже компоненты Vanesssa Ext

8.3.18 - Такси.
Форма выбора из списка не появляется, шаг работает корректно, вне зависимости от включенной галки клавиатуры.

8.3.16 - Такси.
и
8.3.16 - Обычный в закладках
Форма выбора из списка не появляется, вне зависимости от включенной галки клавиатуры и галки компоненты Vanesssa Ext

Получается ошибка только на 8.3.10 (хотя чистоты эксперимента не получилось, т.к. на 10, 16 и 18 платформе разные реквизиты выбирались по строке)

**Comment by Pr-Mex** [comment]
@chEEzys 
Видимо были изменения в платформе после 8.3.10.
