### ISSUE TITLE
Разное поведение однотипных шагов с таблицей Gherkin

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1568]
ТипПлатформы: Windows x86-64
    ТипКлиентаТестирования: Тонкий
    ВерсияVA: ver 1.2.038.1
    ВерсияПлатформы: 8.3.20.1674
    РежимСовместимостиTestManager: Версия8_3_16
    ДатаВремяОшибки: 28.02.2022 18:05:36

Разное поведение двух шагов
1. И таблица "ИмяТаблицы" стала равной
2. И таблица "ИмяТаблицы" содержит строки по шаблону:

Если в таблице имеем колонки такого характера
			| 'ВР'  | 'В\nР' |
			| 'ВР:' | 'ВР:'  |
То шаг "И таблица "ИмяТаблицы" стала равной" выполняется
![image](https://user-images.githubusercontent.com/19662685/156006195-1e085835-57a2-4ff0-ab43-2e6b2fb57003.png)

А шаг "И таблица "ИмяТаблицы" содержит строки по шаблону:" выдает ошибку
![image](https://user-images.githubusercontent.com/19662685/156006374-d7f31b91-b36d-44e2-8fa1-500571b7038f.png)

**Comment by Pr-Mex** [comment]
@akademik1986 
А что в это время в проверяемой таблице?

**Comment by akademik1986** [comment]
вот проверяемая таблица
![image](https://user-images.githubusercontent.com/19662685/156132622-9a3b6620-911e-4cc3-9a00-3dd9f88567a9.png)

**Comment by akademik1986** [comment]
перевод строки в заголовки роли не играет, проверил

**Comment by Pr-Mex** [comment]
@akademik1986 
Можете приложить базу для воспроизведения проблемы?

**Comment by akademik1986** [comment]
[TestQA.zip](https://github.com/Pr-Mex/vanessa-automation/files/8161734/TestQA.zip)

**Comment by akademik1986** [comment]
Шаги подобные приведенному ниже тоже валятся с такой же ошибкой одинаковых колонок
И таблица "ИмяТаблицы" содержит строки из макета "ИмяМакета" по шаблону

**Comment by Pr-Mex** [comment]
@akademik1986 
Посмотрел.
В данном случае есть колонка Цена и Це\nна (сильно искусственный вариант) и такой случай не обрабатывается из-за особенностей алгоритма.
Думаю пока оставить как есть, иначе там много придётся переписывать.

**Comment by Pr-Mex** [comment]
Закрываю как особенность поведения.
