### ISSUE TITLE
Добавление известного шага в окно Сценарий поведения

### ISSUE THREAD

**Issue by etnety** [Pr-Mex/vanessa-automation#1576]
Укажите:
   1. Версия Vanessa Automation 1.2.038.1
   2. Версия платформы 8.3.20.1710
   3. Режим совместимости базы, где запускается Vanessa Automation Версия 8.3.14
   4. Операционная система Windows 10

Сценарий: Добавление шага
  Допустим: Я записал последовательность действий
  И в окне Сценарий поведения нажал кнопку Добавить известный шаг
  Тогда: открывается окно Известные шаги
  И я открываю раздел UI, открываю раздел Всплывающие окна
  Когда выбираю строку И я закрываю окно предупреждения
  Тогда появляется диалоговое окно Метод объекта не обнаружен (getPosition)

Перед вызовом добавления шага надо проверять, какой редактор открыт.
Обработка.VanessaAutomation.УправляемаяФорма.МодульФормы
Процедура ОбработкаОповещения, стр.719

Подробное сообщение:
Метод объекта не обнаружен (getPosition)
{ВнешняяОбработка.VanessaAutomation.Форма.РедакторТекста.Форма(1124)}:ПозицияVanessaEditor = ЭкземплярVanessaEditor.getPosition();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(721)}:МодульРедакторТекста().ВставитьТекстСУчетомФорматирования(Параметр.Текст);
{ВнешняяОбработка.VanessaAutomation.Форма.ВыборИзвестногоШага.Форма(144)}:Оповестить("ВыборИзвестногоШага", Значение);

**Comment by Pr-Mex** [comment]
@etnety 
Проверьте тоже самое на версии из ветки develop, пожалуйста.

**Comment by etnety** [comment]
Проверил на версии 1.2.038.16. Поведение не меняется.

Обработка.VanessaAutomation.УправляемаяФорма.МодульФормы
Процедура ОбработкаОповещения, стр.765

```
			Если Объект.ИспользоватьРедакторVanessaEditor  Тогда
				Если НЕ ОтсутствуетVanessaEditor() Тогда
					МодульРедакторТекста().ВставитьТекстСУчетомФорматирования(Параметр.Текст);
				КонецЕсли;	 
			Иначе	
				Объект.СгенерированныйСценарий = Объект.СгенерированныйСценарий + Символы.ПС + Символы.Таб + СокрП(Параметр.Текст);
			КонецЕсли;	 

```

**Comment by Pr-Mex** [comment]
@etnety 
Можете записать видео с экрана что именно вы делаете?
По текстовому описанию я не совсем понял что происходит.

**Comment by etnety** [comment]
Видео запись действий:
https://user-images.githubusercontent.com/4059050/157654611-a23dab25-668e-4b78-8ee4-7d24ab7ee999.mp4

**Comment by Pr-Mex** [comment]
@etnety 
Ага, теперь понял. Спасибо!

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
