### ISSUE TITLE
Ошибка: При "Создавать Markdown инструкцию" и относительном пути каталога 

### ISSUE THREAD

**Issue by ilyanet** [Pr-Mex/vanessa-automation#1581]
1. Версия Vanessa Automation: 1.2.038.16
   2. Версия платформы: 8.3.18.1616
   3. Режим совместимости базы, где запускается Vanessa Automation: Версия 8.3.15
   4. Операционная система: Win 10 x64

Ошибка:
При установленной галочке "Создавать Markdown инструкцию"
и установке в поле "Каталог инструкций Marckdown" относительного пути на пример "./doc/manual/va/md"

При попытке записать файл инструкции выдает ошибку каталог не обнаружен (см. вложение)

При создании HTML инструкции все в порядке.

![Ошибка](https://user-images.githubusercontent.com/77289608/159113060-fde75b4e-5e48-4124-90c3-924993b53205.JPG)

![Настройки](https://user-images.githubusercontent.com/77289608/159113055-eb01adfc-d378-46b9-9787-ce26159e63c8.JPG)

[VAParams.zip](https://github.com/Pr-Mex/vanessa-automation/files/8308817/VAParams.zip)

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
