### ISSUE TITLE
VA клиент запускает, но не видит.

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#1583]
VA+СППР 
VA: 1.2.038.1, 
СППР: 2.0.1.58, тонкий клиент, платформа: 8.3.18.1433. 
ИБ: толстый клиент, простые формы, платформа 8.3.11.3034.
VA+СППР пытается запустить ИБ, но, не смотря на то что сама ИБ запускается, VA её не видит. В списке подключений строка подключения ИБ зелёная, но само подключение не выполняется, и выводится ошибка: "Не смог подключить TestClient".

![Безымянный](https://user-images.githubusercontent.com/68432407/159305128-b95cec24-74e7-4381-8c9f-902a0aa8be0c.png)

**Comment by Pr-Mex** [comment]
@egorovsergio 
Точно клиент запускается на 8.3.11.3034? Это не опечатка?

**Comment by Pr-Mex** [comment]
Закрываю, т.к. нет ответа.
