### ISSUE TITLE
Не выполняются шаги из VAExtension под неполными правами

### ISSUE THREAD

**Issue by ovcharenko-di** [Pr-Mex/vanessa-automation#1588]
1. Версия Vanessa Automation 1.2.038
   2. Версия платформы не важна
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.14
   4. Операционная система не важна

В расширении VAExtension не заполнено свойство "Основные роли", из-за чего шаги из расширения не выполняются под пользователем с неполными правами.

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
