### ISSUE TITLE
Иногда шаг "И я жду доступности элемента с именем "ИмяЭлемента" в течение 20 секунд" работает не корректно

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1595]
ВерсияVA: ver 1.2.038.1
ВерсияПлатформы: 8.3.20.1674
РежимСовместимостиTestManager: Версия8_3_16

Иногда шаг "И я жду доступности элемента с именем "ИмяЭлемента" в течение 20 секунд" ("И я жду недоступности элемента с именем "ИмяЭлемента" в течение 20 секунд" также) работает не корректно.

![image](https://user-images.githubusercontent.com/19662685/160794739-4504a067-12fd-4a1c-a741-5ab0212d406e.png)

При этом доступность элемента подтверждена исследователем формы
![image](https://user-images.githubusercontent.com/19662685/160794850-f1c6a95e-e67d-4d65-9f4e-caaf11bf52cf.png)

При повторном запуске ошибки нет, так как элемент быстрее становится доступным.

Проверить на dev возможности нет, но вроде бы ничего не правилось в этих шагах.
База доступна по [ссылке ](https://disk.yandex.ru/d/JkGmBYtlObbHfw) (чистая типовая БП). Администратор без пароля.

**Comment by akademik1986** [comment]
Вот еще свежий пример того, что шаг сбоит иногда...
для начала покажу, что на истории было все хорошо - выборка минимальна, но все же))
![image](https://user-images.githubusercontent.com/19662685/168278931-c3e7346e-fec6-45b2-a44d-44aff41d15dc.png)

далее само падание, шаг доступности отработал, а шаг установки флага упал
![image](https://user-images.githubusercontent.com/19662685/168279213-f5d88226-a540-4df0-9b6b-ea5175091352.png)

скрин экрана после ошибки - доступен флаг, но не показатель конечно, могло снять когда уже стал доступ флаг
![image](https://user-images.githubusercontent.com/19662685/168279364-11aa973a-29b2-4f94-bf21-a4efe289a2b6.png)

**Comment by Pr-Mex** [comment]
@akademik1986 
При запуске тестов в CI рекомендуется увеличивать значения у параметров, которые отвечают за сглаживание проблем производительности.
Попробуй увеличить значение параметра ТаймаутДляАсинхронныхШагов. Например установить ему значение 60.

**Comment by akademik1986** [comment]
Так у меня вроде бы ВыполнятьШагиАссинхронно = ложь, тогда и ТаймаутДляАсинхронныхШагов не поможет же?

**Comment by akademik1986** [comment]
И на скриншоте же видно, что шаг выполнялся 1.5 секунды, т.е. дело не во времени ожидания. 
Или время выполнения не показатель?

**Comment by Pr-Mex** [comment]
> Так у меня вроде бы ВыполнятьШагиАссинхронно = ложь, тогда и ТаймаутДляАсинхронныхШагов не поможет же?

Это про другое. Шаги, которые ждут чего-то в течение скольки-то секунд всегда работают асинхронно.

**Comment by Pr-Mex** [comment]
> И на скриншоте же видно, что шаг выполнялся 1.5 секунды, т.е. дело не во времени ожидания. Или время выполнения не показатель?

Это значит, что апи платформы вернуло, что Доступность = Истина.
Тут возможны варианты почему далее флаг не удалось установить.
Например может быть, что реально элемент не был доступен. Такое бывает, т.к. по апи отдаётся только значение флага Доступность, но по апи нельзя получить реальную доступность элемента.

**Comment by akademik1986** [comment]
> @akademik1986 При запуске тестов в CI рекомендуется увеличивать значения у параметров, которые отвечают за сглаживание проблем производительности. Попробуй увеличить значение параметра ТаймаутДляАсинхронныхШагов. Например установить ему значение 60.

А это работает только для CI ? 
с настройкой ТаймаутДляАсинхронныхШагов = 60 все равно падает при интерактивном запуске
![image](https://user-images.githubusercontent.com/19662685/169548411-35d84d75-1a41-49fa-92e6-6614cc8d110f.png)

**Comment by Pr-Mex** [comment]
@akademik1986 
Не важно в CI это или нет.
Попробуй добавить тегов @screenshot перед шагом, где падает и за пару шагов до этого.
Можно будет посмотреть как меняется состояние формы.
