### ISSUE TITLE
Реализовать обход строк таблицы переменных

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1596]
ВерсияVA: ver 1.2.038.1
ВерсияПлатформы: 8.3.20.1674
РежимСовместимостиTestManager: Версия8_3_16

**Большая просьба реализовать по возможности в ближайший релиз, очень нужна эта доработка**

Планируется использовать секцию переменных в плане того, что в отдельном файле будут заданы некоторые параметрические переменные, планируется объявление много таблиц переменных.
С этими таблицами переменных нужно уметь работать в цикле, сейчас это не реализовано , например, использование шага  "И для каждого значения "Строка" из таблицы в памяти "СписокКонтрагентов" выдает ошибку, что таблица в памяти не найдена.

![image](https://user-images.githubusercontent.com/19662685/160891856-0413b589-969f-4e79-bf75-d49046167c26.png)

Приложен [фичи файл](https://disk.yandex.ru/d/T_sJq_ZCUjfNug), где сделана попытка перебора строк таблицы переменных.

**Comment by Pr-Mex** [comment]
@akademik1986 
Это будет шаг
```Gherkin
И для каждой строки таблицы "СписокКонтрагентов" я выполняю
```

**Comment by Pr-Mex** [comment]
@akademik1986 Решено.
