### ISSUE TITLE
Не формируется отчет Allure

### ISSUE THREAD

**Issue by vsyaschenko** [Pr-Mex/vanessa-automation#1598]
Приветствую! 
  
   1. Версия Vanessa Automation 1.2.038.1 (+allure 2.17.3)
   2. Версия платформы 8.3.20.1613 (Учебная)
   3. Режим совместимости не используется
   4. Операционная система Windows 11

Проблема следующая:

Нажимаю "Показать отчет в Allure" в выпадающем меню "Инструменты". Выполнение команды завершается с ошибкой **Could not serve the report**
![image](https://user-images.githubusercontent.com/47042283/161599765-3faf8e49-031f-4e2a-bb2c-e4a4a73bd152.png)

Формирование отчета прерывается из-за отсутствия каталога ...\1cv8t\8.3.20.1613\bin\allure-report. В настройках указан иной "Каталог отчета Allure".  В качестве эксперимента я создал каталог allure-report в папке bin и ошибки при формировании не было. При этом я увидел вот такой "отчет".
![image](https://user-images.githubusercontent.com/47042283/161601056-6102f7ff-f622-481f-830c-f57d9b9b046d.png)

Настройки следующие:
![image](https://user-images.githubusercontent.com/47042283/161601744-f28b7924-84e3-4ee8-9c24-373b8871c0b7.png)
![image](https://user-images.githubusercontent.com/47042283/161601793-07f34eb6-199e-4a6a-ac4e-9ec4737095d3.png)
![image](https://user-images.githubusercontent.com/47042283/161601869-1a19aec7-c6be-45b0-81cb-3284eca52b48.png)

В чем может быть причина такого поведения?

**Comment by nixel2007** [comment]
Каталог проекта заполнен?

**Comment by vsyaschenko** [comment]
> Каталог проекта заполнен? 

Заполнен

**Comment by Pr-Mex** [comment]
@vsyaschenko 
  Попробуйте убрать русские буквы из путей

**Comment by vsyaschenko** [comment]
> @vsyaschenko Попробуйте убрать русские буквы из путей

Ваш совет помог, спасибо!
