### ISSUE TITLE
Запуск в пакетном режиме конкретного браузера

### ISSUE THREAD

**Issue by zeegin** [Pr-Mex/vanessa-automation#160]
```Gherkin
Функционал: Запуск в пакетном режиме конкретного браузера

Сценарий: Я указываю ТипКлиента": "Web"
  Когда: Я формирую файл JSON
  Тогда: Я хочу указать какой конкретно браузер надо запустить
```
Необходимость 1:
Если придерживаться идеологии IACC, то подняв новую машину я должен настроить ее полностью автоматически. Я хочу тестировать хром, а установить его по умолчанию я не могу программно, т.к. это запрещено Майкрософтом. Ни реестром. Ни групповой политикой ни как-нибудь еще это сделать нельзя.

Необходимость 2:
Я хочу одну развернутую базу и один сценарий проверить сразу в Хроме и в Фаерфоксе не переустанавливая окружение.

**Comment by Pr-Mex** [comment]
Принято.

**Comment by Pr-Mex** [comment]
Решено. Можно указать в параметрах какой браузер запускать.
