### ISSUE TITLE
Изменение флага при записи действий пользователя

### ISSUE THREAD

**Issue by AlexRovichKMA** [Pr-Mex/vanessa-automation#1600]
Версия Vanessa Automation 1.2.038.1
Версия платформы 8.3.20.1613
Режим совместимости базы, где запускается Vanessa Automation 8.3.14
Операционная система Windows 11

Описание проблемы: При использовании записи действий пользователя при установке или снятии галочек в формах, программа пишет обе ситуации шагом "И я изменяю флаг с именем", а хотелось бы чтобы было более надежно то есть когда ставишь галочку в положение Истина, чтобы записывался шаг "И я устанавливаю флаг с именем", а когда снимаешь флаг чтобы писался шаг "И я снимаю флаг с именем". Пока что приходится вручную корректировать сценарий. Я могу ошибаться и не все испытывают такой дискомфорт.

**Comment by Pr-Mex** [comment]
@AlexRovichKMA 
Такая ситуация будет только если у VA не получилось прочитать состояние формы, в которой менялось значение флага.
Если форма не была закрыта - то будет сгенерирован другой шаг для флага - по установки или снятию.

**Comment by AlexRovichKMA** [comment]
@Pr-Mex 
Кстати, да, не всегда такая ситуация воспроизводится. Спасибо, вопрос снят.
