### ISSUE TITLE
Ошибка при выполнении шага - И в поле с именем "ИмяПоля" я ввожу значение переменной "ИмяПеременной"

### ISSUE THREAD

**Issue by ZukiNoAru** [Pr-Mex/vanessa-automation#1606]
Укажите:
   1. Версия Vanessa Automation - 1.2.038.1
   2. Версия платформы - 8.3.19.1467
   3. Режим совместимости базы, где запускается Vanessa Automation - 8.3.16
   4. Операционная система - Windows

При выполнении шага **И в поле с именем "ИмяПоля" я ввожу значение переменной "ИмяПеременной"**, если значение переменной это ссылка, и представление этого значения содержит кавычки, то шаг падает с ошибкой:
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(36147)}: Шаг <И В открытой форме в поле с именем "Организация" я ввожу текст "ООО "Ромашка""> не реализован.

![image](https://user-images.githubusercontent.com/103739842/163790959-4543bb8c-f4b8-48f5-811e-058788364232.png)

**Comment by Pr-Mex** [comment]
@ZukiNoAru 
Ага, посмотрю. Спасибо!

**Comment by ZukiNoAru** [comment]
Я у себя поправил - работает.
Закинуть PR? Или обсудим решение?

**Comment by Pr-Mex** [comment]
@ZukiNoAru 
Закидывай. Посмотрим.

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
