### ISSUE TITLE
Ошибка при выполнении шага "Я удаляю переменные текущего сценария"

### ISSUE THREAD

**Issue by AlexPCRus** [Pr-Mex/vanessa-automation#1608]
Укажите:
   1. Версия Vanessa Automation "1.2.038.1"
   2. Версия платформы "8.3.18.1289"
   3. Режим совместимости базы, где запускается Vanessa Automation "Версия 8.3.16"
   4. Операционная система "Windows 10 Pro"

Повторное присвоение значения переменной шагом "Я запоминаю в переменную значение" вызывает ошибку на шаге "Я удаляю переменные текущего сценария".

![Снимок экрана 2022-04-20 092049](https://user-images.githubusercontent.com/47207960/164163595-481e9c54-d0d3-44a8-8598-c9e9feb336dc.png)

**Comment by unichkin** [comment]
Исправлено в форке, скоро залью
![image](https://user-images.githubusercontent.com/10799597/165605316-76233405-c0e8-4d1e-acb0-4aaa82e65f27.png)

![image](https://user-images.githubusercontent.com/10799597/165605349-b73c6c5b-4f41-46ea-82e3-f0c2ef3f7220.png)

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
