### ISSUE TITLE
Переопределение настроек параметров  запуска Vanessa Automation

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1609]
На текущий момент нигде не описан механизм переопределения настроек параметров  запуска Vanessa Automation.
Например, в разных pipeline нужно использовать один и тот же файл настроек, но с разными отборами по СписокТеговИсключение  и СписокТеговОтбор. Нет примеров как это сделать через командную строку, учитывая также , что это массив тегов. Прошу описать это в документации и для оперативности привести пример тут в issue. Спасибо.

**Comment by Pr-Mex** [comment]
Я думаю через командную строку можно переопределить простые переменные.
А СписокТеговИсключение и СписокТеговОтбор это массивы в json. Для них, видимо, надо делать доработку.

**Comment by Pr-Mex** [comment]
@akademik1986 
Исправил проблемы с переопределением параметров в командной строке.
Добавил описание как надо передавать параметры тут, внизу страницы
https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/CommandSetting.md
