### ISSUE TITLE
Обрезание двойных слешей в параметрах шага.

### ISSUE THREAD

**Issue by fenixnow** [Pr-Mex/vanessa-automation#1617]
Укажите:
   1. Версия Vanessa Automation - любая
   2. Версия платформы - любая
  
мне прислали шаг вида
И я выбираю файл "$КаталогИнструментов$\features\Libraries\....." ВК
если ванесса открыта локально, то все отработает, если ванесса из сетевой папки, шаг упадет. парсер съест начальные слеши

Получается парсер в параметрах шага съедает "\\\\" заменяя его на "\\". Для это искусственно в шагах добавляет в начале сетевого пути не два слеша, а четыре.

Может быть ситуация, когда ванесса запуститься из сетевой папки, и шаг однозначно упадет, тк в начале не будет иметь дополнительные два слеша.

Требуется изменить поведение парсера, или вынести обработку пути как параметра в файл шага .epf

**Comment by Pr-Mex** [comment]
Закрываю т.к. нет ответа.

**Comment by Pr-Mex** [comment]
@AlexNsk26 

Зарегистрируйте новый issue, пожалуйста. И приложите файлы для воспроизведения проблемы.
