### ISSUE TITLE
Выводить в отчет Allure пропущенные тесты

### ISSUE THREAD

**Issue by freddy121** [Pr-Mex/vanessa-automation#162]
```Gherkin
Функционал: выводить в отчет allure проущенные тесты со статусом "skipped"
   Как Заказчик, руководитель проекта
   Я хочу видеть пропущенные в проекте тесты помеченными статусом skipped
   Чтобы видеть объективное состояние проекта

Контекст:
  Дано: <версия инструментария> самая последняя
  И <полная версия 1С> любая
  и <конфигурация запуска> любая

Сценарий: Вывод пропущенных тестов в отчет allure
  Допустим: я помечаю сценарий тегом @ignore 
  Когда: ванесса проигрывает проект
  Тогда: такие сценарии получаю статус skipped в результатах для отчета allure

```

> Прикладывайте файлы скриншотов
![image](https://user-images.githubusercontent.com/11014844/52372070-3f641600-2a68-11e9-9ff4-dd796ba7b76c.png)

Для чего нужно: чтобы видеть реальное состояние проекта. Не только количество автотестов, но и количество ручных проверок функциональности.

Функционал описан и используется в specflow:
https://specflow.org/documentation/Using-Gherkin-Language-in-SpecFlow/

SpecFlow treats the @ignore tag as a special tag. SpecFlow generates an ignored unit test method from scenarios with this tag.
![image](https://user-images.githubusercontent.com/11014844/52372460-463f5880-2a69-11e9-81c1-1913107cc8aa.png)

Возможно более корректно устанавливать соответствие тегов в файле настроек.

**Comment by freddy121** [comment]
функционал работает, но немного не так, как в описании
если пометить сценарий тегом @skipped и первый шаг сделать нереализованный - то сценарий в отчете аллюр будет помечаться как @skipped и отмечаться серым цветом

возможно стоит вывести настройку тегов пропуска в vbparams.json

**Comment by Pr-Mex** [comment]
Я правильно понимаю, что вы хотите, чтобы:
если сценарий или фича помечены тегом **@Skipped**, то независимо от того, _упал_ сценарий, _выполнился_ или _не реализован_, он должен получать статус **@Skipped**?

**Comment by freddy121** [comment]
да. причем я бы его даже и не выполнял. только включал в отчет (и аллюра и кукумбера).

**Comment by nixel2007** [comment]
как-то очень сильно перекликается со "списком тегов исключения". только эти вообще в дерево шагов не грузятся.

**Comment by freddy121** [comment]
тут смысл другой.
в системе существует 600 сценариев использования.
автоматизировали 100.
остальные проверяем руками.
если  посмотреть на состояние базы в отчете аллюр без неавтоматизированных тестов - окажется что 100 процентов зеленое и все покрыто тестами, а это вранье. а так видно реальное покрытие функционала.

**Comment by Pr-Mex** [comment]
Ок. Тогда давайте такие сценарии не будем выполнять. Сразу в отчёт.

**Comment by freddy121** [comment]
Да!

**Comment by Pr-Mex** [comment]
Решено в 1.2.035
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.035
