### ISSUE TITLE
Метод объекта не обнаружен (КаталогУроков)

### ISSUE THREAD

**Issue by shalimski** [Pr-Mex/vanessa-automation#1624]
Окружение:
   1. VA Single 1.2.038.21
   2. Платформа 8.3.21.1197
   3. Режим совместимости "Версия 8.3.17"
   4. Windows 10

В мастере настройки интерактивной справки, на третьем шаге загрузке файлов уроков возникает ошибка.
`Метод объекта не обнаружен (КаталогУроков)
{ВнешняяОбработка.VanessaAutomationsingle.Форма.МастерНастройкиИнтерактивнойСправки.Форма(320)}:ИмяКаталога = Ванесса.КаталогУроков();`

![Screenshot_2](https://user-images.githubusercontent.com/1501405/167794825-212277a5-b3e4-4a51-a355-6c8a1b0d1792.png)

**Comment by Pr-Mex** [comment]
@shalimski 
Это возникает при попытке воспроизвести любой урок?

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
