### ISSUE TITLE
Использование тегов severity для формирования отчета Allure

### ISSUE THREAD

**Issue by freddy121** [Pr-Mex/vanessa-automation#163]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: размечать тегами фичи и сценарии 
   Как QA, заказчик , РП
   Я хочу размечать тегами сценарии и фичи
   Чтобы отчет Allure был более информативным

Контекст:
  Дано: <версия инструментария> любая
  И <полная версия 1С> какая угодно
  и <конфигурация запуска> любая

Сценарий: установка тега severity
  Допустим: Я помечаю сценарий тегом @normal
  Когда: формируется отчет allure
  Тогда: он выглядит так:
```
![image](https://user-images.githubusercontent.com/11014844/52373261-46d8ee80-2a6b-11e9-8ce3-26e3aa0b252b.png)

Все теги подробно описаны тут https://github.com/allure-framework/allure-csharp#features
Формат файла настроек тут: https://github.com/allure-framework/allure-csharp/blob/master/Tests.SpecRun/allureConfig.json

В этот же файл можно внести теги для пропущенных тестов из https://github.com/Pr-Mex/vanessa-automation/issues/162

**Comment by freddy121** [comment]
Severity

You can add Severity for your scenarios using tags. It can be configured in allureConfig.json

 "labels": {
      "severity": "^(blocker|critical|normal|minor|trivial)"
    },
The following scenario

@normal
Scenario: ....
will set current scenario severity in Allure report as Blocker


предлагаю данный раздел завести в vbparams.json

**Comment by Pr-Mex** [comment]
@freddy121 ты про раздел labels?

**Comment by freddy121** [comment]
Я про раздел allure-reports

**Comment by Pr-Mex** [comment]
Сделано.

**Comment by freddy121** [comment]
Как работает:
в настройках во вкладке аллюра в таблицу добавляем название тега, тип метки severity и значение метки и critical и тогда в сгенереном json это должно в массиве labels появится
