### ISSUE TITLE
Невозможно интерактивно произвести настройки формирования отчетов

### ISSUE THREAD

**Issue by azheval** [Pr-Mex/vanessa-automation#1631]
Укажите:
   1. Vanessa Automation 1.2.038.27
   2. 8.3.21.1302
   3. Режим совместимости базы, 8.2
   4. win10

Нет возможности интерактивно произвести настройки формирования отчетов.

> Прикладывайте файлы скриншотов
![Screenshot_1](https://user-images.githubusercontent.com/14293358/170478156-53520424-5519-44b0-accd-22ee4f01a49d.png)

**Comment by Pr-Mex** [comment]
@azheval 
А если включить "такси" - то проблема останется?

**Comment by Pr-Mex** [comment]
Закрываю т.к. нет ответа.
