### ISSUE TITLE
проблема с вычислением выражения из области Переменные

### ISSUE THREAD

**Issue by atyz2013** [Pr-Mex/vanessa-automation#1635]
Укажите:
   1. Версия Vanessa Automation - 1.2.038.1
   2. Версия платформы - 8.3.17.1549
   3. Режим совместимости базы, где запускается Vanessa Automation - 8.3.15
   4. Операционная система - Windows 10

Допустим на форме есть реквизит "ВыборМесяца", который принимает значение Формат(ТекущаяДата(), "ДФ='MMMM yyyy'")) + " " + "г." - например, "Май 2022 г."

в области Переменные производится объявление переменной перемПериод:
перемПериод = '{Строка(Формат(ТекущаяДата(), "ДФ='MMMM yyyy'")) + " " + "г."}'

в дальнейшем, при проверке формы, вызывается шаг: И элемент формы с именем "ВыборМесяца" стал равен '{перемПериод}'
данный шаг падает с сообщением "Значение равно: Май 2022 г. , а ожидалось : "
![image](https://user-images.githubusercontent.com/78148551/171195196-082c59bd-7390-4ad5-af61-33f9e11d75f5.png)

шаг И Я запоминаю значение выражения 'Строка(Формат(ТекущаяДата(), "ДФ=\'MMMM yyyy\'")) + " " + "г."' в переменную "ИмяПеременной" срабатывает корректно, при условии экранирования одинарных ковычек
![image](https://user-images.githubusercontent.com/78148551/171194343-49300967-1ad0-405e-b373-55e3835e7d42.png)

в области Переменные добавление экранирования одинарных ковычек приводит к ошибке вычисления выражения

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
