### ISSUE TITLE
Опечатки в предварительном релизе 1.2.038.32

### ISSUE THREAD

**Issue by AlexRovichKMA** [Pr-Mex/vanessa-automation#1642]
Версия Vanessa Automation 1.2.038.1
Версия платформы 8.3.20.1613
Режим совместимости базы, где запускается Vanessa Automation 8.3.14
Операционная система Windows 11

1. "элмент"
![image](https://user-images.githubusercontent.com/98798801/172535375-bd08014b-9b7c-40b2-a68c-ab3646143477.png)
2. "сесии"
![image](https://user-images.githubusercontent.com/98798801/172535834-75922c6c-7c1c-4ba5-8d28-ed514c4fa619.png)
3. "подсвечитьвать"
![image](https://user-images.githubusercontent.com/98798801/172537991-a5e9e330-28e5-4a3d-9240-cd134ece121c.png)
4. "паараметры"
![image](https://user-images.githubusercontent.com/98798801/172538176-6dbe94f4-6ae8-4c46-9791-eb04ba4e9309.png)
5. "Mобильный" - Слово содержит кириллицу и латиницу.
![image](https://user-images.githubusercontent.com/98798801/172538461-885c46bb-5eee-48ea-b035-8cd57c33b7c5.png)

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
