### ISSUE TITLE
В версии 1.2.038.32 не отрабатывает шаг "И я проверяю или создаю для справочника "Склады" объекты:"

### ISSUE THREAD

**Issue by AlexRovichKMA** [Pr-Mex/vanessa-automation#1643]
ТипПлатформы: Windows x86-64
ТипКлиентаТестирования: Тонкий
СтрокаСоединения: File="C:\Base1CKMA\VanessaUT11_4_14_140";
ВерсияVA: ver 1.2.038.32
ВерсияПлатформы: 8.3.21.1302
РежимСовместимостиTestManager: Версия8_3_16

Ссылка на dt базы: https://clck.ru/qBbsD
Доступы к базе без паролей
Ссылка на фичу: https://clck.ru/qBcgg
Ссылка на VAParams: https://clck.ru/qBcUT

![image](https://user-images.githubusercontent.com/98798801/172597241-87b4e880-2d4c-4774-8f71-46d7759046b2.png)

**Comment by Pr-Mex** [comment]
Разобрались. Надо использовать шаг, который устанавливает ОбменДаннымми.Загрузка = Истина

**Comment by AlexRovichKMA** [comment]
Все еще не понимаю как и на что влияет ОбменДаннымми.Загрузка = Истина при создании склада. При этом странно что в VA 1.2.038.1 работают оба шага.

**Comment by Pr-Mex** [comment]
@AlexRovichKMA 
Скорее всего раньше этот флаг ставился всегда. Теперь поведение разнесено.
