### ISSUE TITLE
Некорректное поведение поиска в табличной части "ДеревоТестов"

### ISSUE THREAD

**Issue by sdemon72** [Pr-Mex/vanessa-automation#1647]
Укажите:
   1. Версия Vanessa Automation 1.2.038.1
   2. Версия платформы 8.3.19.1522
   3. Режим совместимости базы, где запускается Vanessa Automation Версия 8.3.17
   4. Операционная система Windows Serwer 2016 Standard

После нажатия Ctrl+F на табличной части "Дерево тестов" и выполнении какого-либо поиска, нет возможности отменить результаты поиска (все инструменты управления поиском спрятаны):
![изображение](https://user-images.githubusercontent.com/80454353/173104936-ba0e83cd-fc42-4a4b-82ee-b9fe9373a131.png)
Для решения проблемы достаточно установить в "Авто" свойство "Положение состояния просмотра" табличной части "ДеревоТестов":
![изображение](https://user-images.githubusercontent.com/80454353/173105376-efa06c7f-09d1-4d56-9d61-758259c8f3ed.png)
Тогда над таблицей появляются метки поиска, которые можно удалить:
![изображение](https://user-images.githubusercontent.com/80454353/173105654-e00cd21c-3c52-4290-a082-259a0cb50180.png)

**Comment by Pr-Mex** [comment]
@sdemon72 
Ок, сделаю.

**Comment by nixel2007** [comment]
Можно нажать ctrl-q для отмены поиска.

**Comment by Pr-Mex** [comment]
Решено в https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.1
