### ISSUE TITLE
Ошибки при добавлении колонки в форме редактирования таблицы Gerkin

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1656]
Укажите:
   1. Версия Vanessa Automation 1.2.039.1
   2. Версия платформы 8.3.20
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.20
   4. Операционная система windows

В форме редактирования таблицы есть возможность добавления колонки (неявная). При выборе типа Строка у колонки, вводим имя колонки и выдается ошибка

![image](https://user-images.githubusercontent.com/19662685/175051231-d3e97a82-9524-472e-8b2d-cc818b24e43d.png)

После этого, если попытаемся переместить вновь добавленную колонку вверх, получим еще ошибку
![image](https://user-images.githubusercontent.com/19662685/175051578-236ead22-fec4-4345-8a66-080264dce9b6.png)

**Comment by Pr-Mex** [comment]
Решено.
