### ISSUE TITLE
Парсер Gherkin. Вложенные в экспорт экспорты падают в Pending

### ISSUE THREAD

**Issue by chEEzys** [Pr-Mex/vanessa-automation#1657]
Укажите:
   1. Версия Vanessa Automation - 1.2.039.1
   2. Версия платформы - проверено на 8.3.10, 8.3.18.1289, 8.3.21.1302 поведение идентичное
   3. Режим совместимости базы, где запускается Vanessa Automation - 
   4. Операционная система - Win

"ИспользоватьКомпонентуVanessaExt": true,
"ИспользоватьПарсерGherkinИзКомпонентыVanessaExt": true,

Положить в одну папку все три сценария.
Загрузить demo.feature

**Ожидаемый результат:**
Экспорт Сотрудники.feature корректно подгрузился в шагах `Когда Я Создаю Сотрудника в ЛИС Должность:"$ПДолжности$" Подразделение:"$ППодразделения$" и наименованием:"$ПНаименования$"`

**Действительный результат:**
шаг `Когда Я Создаю Сотрудника в ЛИС Должность:"$ПДолжности$" Подразделение:"$ППодразделения$" и наименованием:"$ПНаименования$"` подсвечивается как пустой сниппет и не грузит вложенные шаги

Если снять галочку ИспользоватьПарсерGherkinИзКомпонентыVanessaExt то все работает корректно

[demo.zip](https://github.com/Pr-Mex/vanessa-automation/files/8959668/demo.zip)

**Comment by Pr-Mex** [comment]
Решено
