### ISSUE TITLE
Ошибка при выполнении обращения к таблице из секции переменных, если в конце заголовка таблицы стоит пробел

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1658]
Укажите:

Версия Vanessa Automation 1.2.039.1
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.20
Операционная система windows

При сохранении  в секции переменных именованной таблицы, если в колонке будет пробел в названии, то VA ругнется.
Однако, если в заголовке таблицы в конце будет добавлен пробел или tab, то фича сохранится, однако при выполнении будет выдана ошибка, что таблицу с именем объявленной таблицы переменной не найдена на форме. ТО есть он поискал объявленную таблицу в сначала в таблице переменных, не нашел, потом начал искать на форме и тоже не нашел и шаг упал.
Предлагаю при сохранении фичи анализировать также отсутствие пробела в имени  таблицы переменных и выдавать ошибку, как это делается при контроле правильности заполнения колонок таблицы переменных

**Comment by Pr-Mex** [comment]
@akademik1986 
Нужен полный пример кода для воспроизведения ошибки.

**Comment by akademik1986** [comment]
![image](https://user-images.githubusercontent.com/19662685/175288844-6d2619aa-3ffe-45fb-b06c-db46894d1a75.png)


#language: ru

@tree

Функционал: Ошибки секции переменных 

Переменные:
	* ПараметрыВесовПечати
		| 'УИД'     | 'ФорматПечати' | 'Вес_КГ' |
		| 'Строка1' | 'C4'           | '0,027'  |
		| 'Строка2' | 'A4'           | '0,005'  |
		| 'Строка3' | 'B5'           | '0,031'  |

	* ПараметрыВесовПечатиДва 
		| 'УИД'     | 'ФорматПечати' | 'Вес_КГ' |
		| 'Строка1' | 'C4'           | '0,027'  |
		| 'Строка2' | 'A4'           | '0,005'  |
		| 'Строка3' | 'B5'           | '0,031'  |

	* Параметры ВесовПечати
		| 'УИД'     | 'ФорматПечати' | 'Вес_КГ' |
		| 'Строка1' | 'C4'           | '0,027'  |
		| 'Строка2' | 'A4'           | '0,005'  |
		| 'Строка3' | 'B5'           | '0,031'  |

Сценарий: Успешный сценарий

	И для каждой строки таблицы "ПараметрыВесовПечати" я выполняю
		И выражение внутреннего языка 'Истина=Истина' Истинно

Сценарий: Выполнет сценарий с пробелом в имени, нормально ли?

	И для каждой строки таблицы "Параметры ВесовПечати" я выполняю
		И выражение внутреннего языка 'Истина=Истина' Истинно

Сценарий: Ошибка сценарий

	И для каждой строки таблицы "ПараметрыВесовПечатиДва" я выполняю
		И выражение внутреннего языка 'Истина=Истина' Истинно

**Comment by Pr-Mex** [comment]
Решено
