### ISSUE TITLE
Перепутано описание парных шагов "И у элемента формы с именем "ИмяПоля" текст редактирования стал равен "ТекстПоля""

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1661]
Версия Vanessa Automation 1.2.039.1
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.20
Операционная система windows

Некорректная подсказка у шагов "И у элемента формы с именем "ИмяПоля" текст редактирования стал равен "ТекстПоля" по шаблону" и "И у элемента формы с именем "ИмяПоля" текст редактирования стал равен "ТекстПоля""

![image](https://user-images.githubusercontent.com/19662685/175494261-9b4405b7-4525-4cb9-82a3-57f959811125.png)

![image](https://user-images.githubusercontent.com/19662685/175494325-48e30c6e-9461-492d-a783-da3e701a7c24.png)

**Comment by Pr-Mex** [comment]
Решено
