### ISSUE TITLE
Ошибка при открытии формы при запуске клиентского сеанса с параметрами

### ISSUE THREAD

**Issue by demoninfernal** [Pr-Mex/vanessa-automation#1662]
Укажите:
   1. Версия Vanessa Automation: 1.2.039.1
   2. Версия платформы: 8.3.18.1289
   3. Режим совместимости базы, где запускается Vanessa Automation: 8.3.14
   4. Операционная система: Win10

Толстый клиент обычное приложение.
Открываю стандартную поставку VA через файл-открыть - получаю ошибку:
{ВнешняяОбработка.VanessaAutomation.Форма.Форма.Форма(383)}: Ошибка при вызове метода контекста (Вставить)
			Результат.Вставить(Элем,Истина);
по причине:
Задано неправильное имя атрибута структуры

В метод ПолучитьСтруктуруПараметров(Стр) толстой формы обработки VA в качестве параметра Стр передаются дополнительные параметры запуска, в моем случае строка "/UCПароль /CРежимОтладки" (скрин во вложении), и из-за наличия пробела происходит ошибка.
По идее, в этот метод в качестве параметра должно приходить только содержание параметра /C
![screen](https://user-images.githubusercontent.com/41343952/175552038-695fd296-a1ab-45dd-966e-d329a9ccb240.png)

**Comment by Pr-Mex** [comment]
Решено
