### ISSUE TITLE
Ошибка PredefinedDataName формы подготовки и загрузки данных при режиме совместимости 8.3.2

### ISSUE THREAD

**Issue by astrizhachuk** [Pr-Mex/vanessa-automation#1666]
Укажите:
   1. Версия 1.2.039.1
   2. Версия платформы 8.3.10.2667
   3. Режим совместимости 8.3.2
   4. win

Ошибка создания фичи по ссылке на объект.

**Comment by Pr-Mex** [comment]
Решено
