### ISSUE TITLE
Присваивать ошибкам времени выполнения статус failed, а не broken, независимо от вида шага

### ISSUE THREAD

**Issue by BarinovIN** [Pr-Mex/vanessa-automation#1668]
1. Версия Vanessa Automation 1.2.039.1
   2. Версия платформы 8.3.19.1351
   3. Режим совместимости базы, где запускается Vanessa Automation 8_3_14
   4. Операционная система Windows

```Gherkin
Функционал: Различать broken и failed
   Как тестировщик
   Я хочу легко отличать ошибки требующие исправлений тестируемого приложения, от требующих доработок сценариев

Дано:
  "Различать broken и failed по ключевому слову Тогда" = Истина

Сценарий: ошибка времени выполнения всегда со статусом failed
  Допустим: Ключевое слово падающего шага <> "Тогда"
  Когда: Шаг падает с ошибкой времени выполнения тестируемого приложения
  Тогда: сценарию присваивается статус failed
```
Под ошибками времени выполнения понимаются такие как: 
- "Поле объекта не обнаружено"
- "Преобразование значения к типу Булево не может быть выполнено"
- "Метод объекта не обнаружен"
- и т.д.
Такие ошибки однозначно требуют исправлений в тестируемом приложении.

Даже если цель теста была проверить работу другой функции, но тест упал с подобной ошибкой - это ошибка в тестируемом функционале, а не в тесте.  В соответствии с концепцией https://github.com/Pr-Mex/vanessa-automation/issues/696

**Comment by Pr-Mex** [comment]
Думаю да. Так лучше.
