### ISSUE TITLE
VA отнимает запущенный клиент add

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1671]
Версия Vanessa Automation 1.2.039.1
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.20
Операционная система windows

Иногда происходит ситуация, когда тесты в add на открытие форм не выполняются с ошибкой 
"Ошибка подключения к клиенту тестирования. Тестируемый клиент уже установил соединение с другим менеджером тестирования."
Последнюю ошибку детально сегодня разобрал. Получилось следующее:
Настройки запуска VA
![image](https://user-images.githubusercontent.com/19662685/176386460-175e62af-b574-4bb0-ba95-ff3d43a0057c.png)
Настройки запуска add
![image](https://user-images.githubusercontent.com/19662685/176387518-9dbb05c4-85a7-4bc4-b325-27f05e53f987.png)

Теперь журнал регистрации рассказывает, как было дело:
Подключение клиента add
![image](https://user-images.githubusercontent.com/19662685/176387849-c764f8a6-6206-4e34-aaa9-dcfd7b57757e.png)
![image](https://user-images.githubusercontent.com/19662685/176387987-789cfc41-ff4a-4cc3-96c9-a756debfb3d9.png)
Далее включается в работу VA
![image](https://user-images.githubusercontent.com/19662685/176388257-0e08e158-8ad9-46dc-9ae5-a49db7c547f9.png)
![image](https://user-images.githubusercontent.com/19662685/176388807-ef652a5d-ea48-4fe0-8a4b-08594dd26363.png)

Ну а дальше ошибка в тестах add, что клиент тестирования отжат другим менеджером
![image](https://user-images.githubusercontent.com/19662685/176389270-7f278c83-7379-467b-b73a-1ed0f37b8e58.png)

**Comment by nixel2007** [comment]
Любое приложение, работающие через апи "тестируемого приложения" будет вести себя точно так же.
Разносите разные инструменты по разным диапазонам портов или используйте изоляцию подсетей

**Comment by akademik1986** [comment]
Просто мне кажется, диапазон портов по умолчанию пересекается с add, через наследование, и это сказывается иногда коллизией, если прям все-все правильно не разнести. 
Можно было бы в VA поменять стандартный диапазон поиска свободного порта, но если нет, так нет. Действительно, разнесение должно помочь, что я и начал делать до оформления issue, но все таки решил поделиться.
