### ISSUE TITLE
Прошу добавить шаг "И я выполняю скрипт SikuliX "%1 ИмяСкрипта" с параметрами"

### ISSUE THREAD

**Issue by sergey-dubinin-work** [Pr-Mex/vanessa-automation#1672]
Укажите:
   1. Версия Vanessa Automation 1.2.0.39
   2. Версия платформы 8.3.16
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система Windows

```Gherkin
Функционал: Передавать в шаг, который выполняет SikuliX скрипт, параметры из тестов
   Как тестировщик 1С
   Я хочу иметь возможность передавать параметры в Sikulix скрипт

У Sikulix есть возможность читать и использовать параметры, передаваемые в командной строке
Ессли запускать сикуликс скрипт следующим образом: <путь к скрипту> --args "1" "2" и тд, то в самом SikuliX скрипте можно перехватывать и использовать эти параметры
Это будет полезно, например, для создания универсального SikuliX скрипта, который, к примеру будет находить и вводить в какое-то текстовое поле различные символы, передаваемые из сценария ванессы
```
Возможность реализации этого в ванессе:
![photo_2020-11-04_20-07-18](https://user-images.githubusercontent.com/57937645/176442413-2116c97b-c945-4b63-82b6-f01d406f842b.jpg)
тапками не кидайте, я тестировщик, я так вижу

Из SikuliX скрипта перехватить и использовать параметры можно, используя следующую конструкцию:
![photo_2020-11-04_20-07-31-1](https://user-images.githubusercontent.com/57937645/176444429-ed614ceb-024e-4c26-9c9d-6499e91c155d.jpg)

Прошу реализовать это шаг, как в русском, так и в английском варианте

Также прошу реализовать корректную работу этого шага при использовании передаваемых параметров в шаг из высшего сценария [], локальных $ и глобальных переменных $$

**Comment by Pr-Mex** [comment]
@sergey-dubinin-work 
А зачем вы используете  SikuliX для клика по картинкам и эмуляции клавиш? Сейчас это лучше делать с помощью компоненты.

**Comment by Pr-Mex** [comment]
> @Pr-Mex Меня интересует клик по картинкам и вставка текста Реализуемо ли это на версии vanessa-automation 1.2.029?

Точно не помню. Но в любом случае лучше обновиться на 39 версию.
