### ISSUE TITLE
Для фич на английском языке отсутствует перевод слов Структура сценария и Примеры

### ISSUE THREAD

**Issue by Severnity** [Pr-Mex/vanessa-automation#1673]
Укажите:
   1. VA 1.2.039.1
   2. Платформа: 1C:Enterprise 8.3 (8.3.21.1197)

Для фич на английском языке отсутствует перевод слов Структура сценария и Примеры
![image](https://user-images.githubusercontent.com/66120736/176849574-21be5753-2f95-46c4-83e2-0b5b1e38ec90.png)

**Comment by Pr-Mex** [comment]
Речь про перевод русской фичи на английский одной кнопкой.

**Comment by Pr-Mex** [comment]
Решено
