### ISSUE TITLE
Ошибка при запуске клиента тестирования стандартным шагом при включенной настройке "Использовать браузер + web soket"

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1680]
Версия Vanessa Automation 1.2.039.1
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Если установлена настройка "Использовать браузер + web soket", то шаги 
Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий
И я подключаю TestClient "ИмяКлиента" логин "Логин" пароль "Пароль"

выдают ошибки вида
![image](https://user-images.githubusercontent.com/19662685/177537234-afa85fe0-55d5-40dc-a68f-98ec96500d28.png)
![image](https://user-images.githubusercontent.com/19662685/177537261-94d57677-9a6a-49f1-a67f-3914e194fd3c.png)

Без использования данной настройки подключение происходит штатно.

**Comment by Pr-Mex** [comment]
@akademik1986 
Сохраните ваши настройки в json, при которых это воспроизводится и приложите к issue, пожалуйста.

**Comment by akademik1986** [comment]
[BugSetting.zip](https://github.com/Pr-Mex/vanessa-automation/files/9055589/BugSetting.zip)

Приложил

**Comment by Pr-Mex** [comment]
Решено
