### ISSUE TITLE
Попытки при записи объекта в загрузке данных

### ISSUE THREAD

**Issue by DitriXNew** [Pr-Mex/vanessa-automation#1693]

**Comment by akademik1986** [comment]
Расскажите пожалуйста поподробнее, что это за доработка? 
случайно не реализация issue #1561 ?

**Comment by DitriXNew** [comment]
@akademik1986 нет. Тут просто добавили попытку в цикле при записи объекта.

**Comment by Pr-Mex** [comment]
Решено.
