### ISSUE TITLE
Кнопка выбора - это Select button или Choice button. Ошибка перевода

### ISSUE THREAD

**Issue by pravets** [Pr-Mex/vanessa-automation#1696]
Укажите:
   1. Версия va1.2.039.1
   2. Версия платформы 8.3.20.1674
   3. Режим совместимости не используется
   4. Операционная система Windows 10

Проблема в локализации шагов на английский язык.

Есть два шага
И я нажимаю кнопку выбора у поля ""
И я нажимаю кнопку выбора у поля с именем ""

В первом случае на английском это "And I click **Select** button of "" field"
Во втором случае And I click **Choice** button of the field named ""

Кнопка выбора - это Select button или Choice button?

**Comment by Pr-Mex** [comment]
@pravets 
Затрудняюсь сказать как "правильно".
Вы предлагаете оставить какой-то один вариант?

**Comment by pravets** [comment]
Я тоже не знаю какой из вариантов верный, но для однообразия шагов лучше оставить что-то одно.
И похоже верный вариант не знает даже фирма 1С.
1. https://1c-dn.com/library/tutorials/mobile_application_adding_desktop_buttons/?sphrase_id=189978 
в справке по конфигуратору кнопка выбора называется "Select button"
2. https://1c-dn.com/library/tutorials/practical_developer_guide_quick_choice_property/?sphrase_id=189979
"Быстрый выбор" в справочнике в конфигураторе это "Quick choice"
3. https://1c-dn.com/forum/forum1/topic154/?sphrase_id=189979#message523
а судя по этому диалогу, событие "НачалоВыбора" называется "StartChoice"

Предварительно больше аргументов в пользу Choice
Скорее всего так будет логичнее и понятнее.

**Comment by pravets** [comment]
P.S. форма выбора вроде как тоже называется choice form

**Comment by Pr-Mex** [comment]
Думаю это не критично в данный момент.
В общем случае можно обновить перевод на какой-то один из вариантов если на это будет запрос.
