### ISSUE TITLE
VanessExt: фигуры и надписи по координатам

### ISSUE THREAD

**Issue by artkor83** [Pr-Mex/vanessa-automation#1700]
1. Версия Vanessa Automation: 1.2.039.1
   2. Версия платформы: 8.3.19
   3. Режим совместимости базы, где запускается Vanessa Automation: 8.3.14
   4. Операционная система: Windows 2016

#encoding: utf-8
#language: ru

@ExportScenarios

Функционал: Оформление фигур с помощью VanessaExt

@ТипШага:  Прочее.VanessaExt.Фигуры по координатам
@Описание:  Я рисую рамку по координатам "ФигураX" "ФигураY" "ФигураW" "ФигураH" "ТабПараметрыРисования"
@ПримерИспользования:  И Я рисую рамку по координатам "542" "153" "34" "34"
@ПримерИспользования:        |'Цвет'      | 'Красный'    |
@ПримерИспользования:        |'Длительность'  | '2000'       |
@ПримерИспользования:        |'Прозрачность'   | '127'         |
@ПримерИспользования:        |'Толщина'     | '2'         |

Сценарий: Я рисую рамку по координатам "ФигураX" "ФигураY" "ФигураW" "ФигураH" "ТабПараметрыРисования"
	И Я рисую рамку по координатам "ФигураX" "ФигураY" "ФигураW" "ФигураH" "ТабПараметрыРисования"

@ТипШага:  Прочее.VanessaExt.Фигуры по координатам
@Описание:  Я рисую эллипс по координатам "ФигураX" "ФигураY" "ФигураW" "ФигураH" "ТабПараметрыРисования"
@ПримерИспользования:  И Я рисую эллипс по координатам "542" "153" "34" "34"
@ПримерИспользования:        |'Цвет'      | 'Красный'    |
@ПримерИспользования:        |'Длительность'  | '2000'       |
@ПримерИспользования:        |'Прозрачность'   | '127'         |
@ПримерИспользования:        |'Толщина'     | '2'         |

Сценарий: Я рисую эллипс по координатам "ФигураX" "ФигураY" "ФигураW" "ФигураH" "ТабПараметрыРисования"
	И Я рисую эллипс по координатам "ФигураX" "ФигураY" "ФигураW" "ФигураH" "ТабПараметрыРисования"

@ТипШага:  Прочее.VanessaExt.Фигуры по координатам
@Описание:  Я рисую тень по координатам "ФигураX" "ФигураY" "ФигураW" "ФигураH" текст надписи "ТекстНадписи" "ТабПараметрыРисования"
@ПримерИспользования:  И Я рисую тень по координатам "100" "100" "1000" "400" текст надписи "Область ввода данных"
@ПримерИспользования:        |'Цвет'      | 'Красный'    |
@ПримерИспользования:        |'Длительность'  | '2000'       |
@ПримерИспользования:        |'Прозрачность'   | '127'         |
@ПримерИспользования:        |'Толщина'     | '2'         |

Сценарий: Я рисую тень по координатам "ФигураX" "ФигураY" "ФигураW" "ФигураH" текст надписи "ТекстНадписи" "ТабПараметрыРисования"
	И Я рисую тень по координатам "ФигураX" "ФигураY" "ФигураW" "ФигураH" "ТабПараметрыРисования", текст надписи "ТекстНадписи"

@ТипШага:  Прочее.VanessaExt.Фигуры по координатам
@Описание:  Я рисую надпись по точкам "ФигураX" "ФигураY" текст надписи "ТекстНадписи" "ТабПараметрыРисования"
@ПримерИспользования:  И Я рисую надпись по точкам "100" "150" текст надписи "Привет Мир!"
@ПримерИспользования:        |'ЦветШрифта'      | 'Красный'    |
@ПримерИспользования:        |'РазмерШрифта'      | '14'    |
@ПримерИспользования:        |'Длительность'  | '2000'       |
@ПримерИспользования:        |'Прозрачность'   | '127'         |
@ПримерИспользования:        |'Толщина'     | '2'         |

Сценарий: Я рисую надпись по точкам "ФигураX" "ФигураY" текст надписи "ТекстНадписи" "ТабПараметрыРисования"
	И Я рисую надпись по точкам "ФигураX" "ФигураY" текст надписи "ТекстНадписи" "ТабПараметрыРисования"

@ТипШага:  Прочее.VanessaExt.Фигуры по координатам
@Описание:  Я рисую подсказку-балон по точкам "ФигураX" "ФигураY" текст надписи "ТекстНадписи" "ТабПараметрыРисования"
@ПримерИспользования:  И Я рисую подсказку-балон по точкам "100" "150" текст надписи "Привет Мир!"
@ПримерИспользования:        |'ЦветШрифта'      | 'Красный'    |
@ПримерИспользования:        |'РазмерШрифта'      | '14'    |
@ПримерИспользования:        |'Длительность'  | '2000'       |
@ПримерИспользования:        |'Прозрачность'   | '127'         |
@ПримерИспользования:        |'Толщина'     | '2'         |

Сценарий: Я рисую подсказку-балон по точкам "ФигураX" "ФигураY" текст надписи "ТекстНадписи" "ТабПараметрыРисования"
	И Я рисую подсказку-балон по точкам "ФигураX" "ФигураY" текст надписи "ТекстНадписи" "ТабПараметрыРисования"

**Comment by artkor83** [comment]
Есть файл epf реализации шагов, но приаттачить не получается

**Comment by lo0p3r** [comment]
> Есть файл epf реализации шагов, но приаттачить не получается

> Прочее.VanessaExt.Фигуры по координатам

Если я правильно понимаю, то этот шаг реализован в расширении?
Полагаю, что, во-первых, сама обработка реализации шага добавлена в расширение?
Во-вторых, модифицирована обработка VAExtension.epf, которая возвращает список тестов из расширения?

1. Расширение хранится в папке `.\vanessa-automation\lib\VAExtension`
2. Обработка хранится в папке `.\vanessa-automation\features\Libraries\VAExtension`

[Подробная статья](https://infostart.ru/1c/articles/1092009/), как предлагать улучшения.

Кратко:
1. Ставите **oscript** и две платформы: **8.3.14** для расширения и **8.3.17** для обработок, х32.
2. Клонируете репозиторий к себе на компьютер
3. Запускаете скрипт **Compile.bat**, чтобы собрать обработки.
4. Загружате расширение из файлов на **8.3.14** из папки `.\vanessa-automation\lib\VAExtension`, модифицируете, выгружаете обратно в файлы.
5. Модифицируете обработку `.\vanessa-automation\features\Libraries\VAExtension\VAExtension.epf` на платформе **8.3.17**.
6. Запускаете **Decompile.bat** для разборки обработок обратно в исходники.
7. Я ещё отдельно отменял изменения во всех не связанных с изменениями файлах, т.к. почему-то после загрузки расширения из файлов и выгрузки обратно в файлы git считает, что поменялась куча строк в файлах, хотя визуально они осталась неизменными, возможно дело в разных подрелизах платформы.
8. Теперь можно пушить изменения в свой форк и делать pull request в основной репозиторий в ветку **develop**.

**Comment by Pr-Mex** [comment]
Решено.
