### ISSUE TITLE
Добавить шаг "И я запоминаю значение таблицы "Таблица1" как "ИмяПеременной"" без указания колонок ТЧ

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1704]
Версия Vanessa Automation 1.2.039.1
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Просьба добавить шаг, аналогичный нижеследующему, либо же адаптировать его, чтобы можно было не указывать список колонок.
И я запоминаю значение таблицы "Таблица1" как "ИмяПеременной"
    | 'ИмяКолонки1' |
    | 'ИмяКолонки2' |

Область применения: 
на форме имеется ТЧ с динамическими именами колонок. Хотелось бы используя подобный шаг запомнить в какой то момент времени таблицу на форме всю, и в конце сценария шагом "И таблица "ИмяПеременной1" содержится в таблице "ИмяПеременной2"" проверить, что данные в таблице остались неизменны.

**Comment by Pr-Mex** [comment]
@akademik1986 
Хотелось бы ещё получить демо пример, где бы это использовалось.
Можешь создать такой пример?
Можно на основании пустой базы. Главное чтобы там была нужная таблица, затем что-то с ней происходило, затем проверка результата.

**Comment by akademik1986** [comment]
@Pr-Mex 
примерно набросал
[Downloads.zip](https://github.com/Pr-Mex/vanessa-automation/files/9210234/Downloads.zip)
