### ISSUE TITLE
Шаг для перемещения курсора к элементу формы. UI Automation

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1715]
```Gherkin
И я перемещаю курсор к элементу формы  'PID' 'Имя' 'Тип' UI Automation
```

**Comment by mrshadow300373** [comment]
Приветствую! В этом шаге есть ошибка: #1795

**Comment by Pr-Mex** [comment]
@mrshadow300373 
Буду смотреть

**Comment by mrshadow300373** [comment]
@Pr-Mex  такая же проблема один в один с шагом:
И я рисую рамку вокруг элементов формы UI Automation "PID"
	| 'Имя'   | 'Тип' |
	| 'Поле1' | 'Тип1' |
	| 'Поле2' | 'Тип2' |

	| 'Имя'      | 'Знач |

**Comment by Pr-Mex** [comment]
Решено.
