### ISSUE TITLE
Сконвертировать 4 подсценария из основной поставки в шаги.

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1716]
Это упросит работу Single с фичами на других языках и новым парсером.

**Comment by mrshadow300373** [comment]
Это исправление приводит к тому, что после открытия клиента тестирования закрываются все окна клиентского приложения принудительно, включая и те, которые были открыты из строки запуска, например внешняя обработка которая должна что либо запустить запущенная с клиентом тестирования ключом /Execute

**Comment by mrshadow300373** [comment]
> Это исправление приводит к тому, что после открытия клиента тестирования закрываются все окна клиентского приложения принудительно, включая и те, которые были открыты из строки запуска, например внешняя обработка которая должна что либо запустить запущенная с клиентом тестирования ключом /Execute

Не совсем верно написал, выяснилось, что в шаге "Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий" сокрыты два других, которые в 39.1 отображаются снизу
![photo_2022-08-14_18-14-37](https://user-images.githubusercontent.com/34220218/184541075-5d29d940-cb7b-4ef6-ae1c-6ca1a0bec34f.jpg)
34 й релиз не показывает их, в итоге это вводит в заблуждение

**Comment by Pr-Mex** [comment]
Решено.
