### ISSUE TITLE
Баг в шагах группировки Allure

### ISSUE THREAD

**Issue by 1cto** [Pr-Mex/vanessa-automation#1724]
Укажите:
   1. Версия Vanessa Automation 1.2.39.1
![image](https://user-images.githubusercontent.com/15178930/183311624-2f6cf67c-ab0e-4a2f-8252-58739dba8fd3.png)

**Comment by Pr-Mex** [comment]
@1cto 
Ага, посмотрю.

**Comment by Pr-Mex** [comment]
Решено
