### ISSUE TITLE
Непонятное поведение при запуске клиентов тестирования шагами

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1732]
Версия Vanessa Automation 1.2.039.4
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Пытаюсь реализовать следующее поведение:
- есть экспортный шаг, который будет выполняться первым и запустит нужный клиент тестирования с нужными параметрами
- все остальные сценарии включают экспортный шаг открытия клиента тестирования с параметрами.

1. Запускаю фичу по запуску клиента тестирования с заданными параметрами. 
Получается следующее - в попытке он не нашел запущенного сеанса с такими параметрами (что естественно, это первый запуск), в исключении происходит подключение клиента по заданным параметрам.
![image](https://user-images.githubusercontent.com/19662685/184653830-a8711a87-d7f0-4331-9df1-35419cca3292.png)

Однако, если посмотреть на таблицу клиентов тестирования, то там будет другой порт у запущенного клиента
![image](https://user-images.githubusercontent.com/19662685/184653982-ddf4e316-f36c-4465-9460-d6a1e2c76916.png)
2. Если далее будет запускаться фича (в приложении это фича "проверка запуска клиента.feature"), где в контексте вызван наш экспортный шаг из пункта 1, то произойдет ошибка выполнения. Отладку выполнить не удалось.
3. 
![image](https://user-images.githubusercontent.com/19662685/184658118-7bdf6bb3-b259-42c6-95c9-956d3ee2cafe.png)

PS. В экспортном шаге после в таблице поиска клиента удалил колонку Порт, тогда фича 2 выполнилась.
ОДНАКО, в строке сообщений 2 раза выводится сообщение о перезаполнении таблицы подключений, что намекает на то, что шаг "Когда Я подключаю уже запущенный клиент тестирования с параметрами:" выполняется  2 раза зачем то
![image](https://user-images.githubusercontent.com/19662685/184662026-a1087009-4411-4abd-bedc-918c22c5a57d.png)

В конечном итоге непонятно, почему при заданном указанном номере порта не происходит запуск клиента по указанному порту. (ну и в PS еще описана странные сообщения шага)

Приложены фичи для анализа 
[Downloads.zip](https://github.com/Pr-Mex/vanessa-automation/files/9337985/Downloads.zip)

**Comment by Pr-Mex** [comment]
@akademik1986 Порт в таблице клиентов тестирования указывается, чтобы найти уже подключённый клиент. Если он не найден, то при запуске нового клиента порт будет выбираться из диапазона свободных портов и может не совпаст  с тем что был в таблице до подключения клиента.

**Comment by Pr-Mex** [comment]
@akademik1986 
Почему сообщение два раза - посмотрю.
