### ISSUE TITLE
Не работает шаг "И я закрываю все вкладки браузера"

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1734]
Версия Vanessa Automation 1.2.039.4
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Сценарий: Закрытие клиента тестирования
	И я активизирую текущее окно браузера
	И я закрываю все вкладки браузера
На картинке ниже видно, что шаг активизации текущего окна успешно выполняется, а закрытие всех вкладок пишет об отсутствии соединения с браузером, но предыдущий шаг это опровергает.
![image](https://user-images.githubusercontent.com/19662685/184874493-9f771b11-0601-481f-aa74-7693f920dfc4.png)
[Настройки VA](https://github.com/Pr-Mex/vanessa-automation/files/9350711/VAParams_interactiv_Empty.zip)

**Comment by Pr-Mex** [comment]
@akademik1986 
Проверь, пожалуйста, тоже самое на ветке develop. Я недавно правил закрытие вкладок.

**Comment by akademik1986** [comment]
@Pr-Mex Вроде не помог девелоп
И там еще при открытии фичи опять валится ошибка снипет уже был в другом epf
![image](https://user-images.githubusercontent.com/19662685/185048634-a29351ff-8747-4135-b345-ceeae21cb3d0.png)

**Comment by Pr-Mex** [comment]
@akademik1986 у меня этот шаг работает. Как ты подключаешь браузер? Приложи настройки  VA.

**Comment by Pr-Mex** [comment]
А сообщения про снипет появляются из-за того, что остались epf, которых больше не должно быть. Удали все epf и собери их заново.

**Comment by akademik1986** [comment]
С сообщениями помогло, спасибо
По поводу закрытия всех закладок браузера все также.
вот настройки
[VAParams.zip](https://github.com/Pr-Mex/vanessa-automation/files/9371922/VAParams.zip)

**Comment by Pr-Mex** [comment]
> С сообщениями помогло, спасибо По поводу закрытия всех закладок браузера все также. вот настройки [VAParams.zip](https://github.com/Pr-Mex/vanessa-automation/files/9371922/VAParams.zip) А, забыл про вопрос как подключаешь браузер... Не очень я понял как на него ответить) Подключаю стандартно. фичи в браузере выполняются, т.е. связь с браузером точно есть. Шаг И я активизирую текущее окно браузера потребовал установки настройки Использовать браузер + web soket, пришлось включить, однако для шага закрытие всех закладок эта настройка хоть включена, хоть выключана, не работает.

У тебя вот такая настройка установлена
![image](https://user-images.githubusercontent.com/8627416/185387338-2c0f697e-1bf8-4c9a-a25b-936fab4208b1.png)

А должно быть так
![image](https://user-images.githubusercontent.com/8627416/185387458-9ef6127b-ad67-40c0-8ddd-9a0dc1dbe620.png)

Иначе нельзя управлять браузером.

**Comment by akademik1986** [comment]
@Pr-Mex нет, мне не помогла настройка. Не закрывает. Можешь своими поделиться, чтобы проверил?
И кстати, в шагах нет пояснения, что нужен этот дебаг, не очевидно

**Comment by Pr-Mex** [comment]
@akademik1986 
Ты ведь закрываешь каждый раз браузер перед тем как проверять?

**Comment by akademik1986** [comment]
@Pr-Mex вот где собака зарылась) Спасибо, получилось. Только вкладки закрывал от открытых клиентов(

**Comment by Pr-Mex** [comment]
@akademik1986 
Эти особенности тут описаны
https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/FAQ/MakeAutoVideo.md

**Comment by akademik1986** [comment]
@Pr-Mex ну во первых, это описание находится в видеоинструкциях, а так как я ими не пользуюсь, то и не особо читал этот раздел. 
Да и описано так, что не очень понятно, почему именно дебаг нужен, просто - для видеоинструкций установите так
![image](https://user-images.githubusercontent.com/19662685/185555915-db72106a-8574-4450-ac93-e450745b2812.png)
Это я к тому, что не очень очевидно, что для тех , что не использует запись видеоинструкций эта настройка нужна для работы с браузером.

**Comment by Pr-Mex** [comment]
@akademik1986 
Да, согласен. Этот функционал изначально появился для работы видеоинструкций. И поэтому был описан в этом разделе.
А теперь он используется гораздо шире.
