### ISSUE TITLE
Ошибка при выполнении шага " и в меню формы я выбираю", при этом значение имеет знак переноса строки "\n"

### ISSUE THREAD

**Issue by BelovaElena80** [Pr-Mex/vanessa-automation#1736]
Укажите:
   1. Версия Vanessa Automation 1.2.038.1
   2. Версия платформы 8.3.21.1393
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.14
   4. Операционная система windows

[Ошибка с переносом строки.docx](https://github.com/Pr-Mex/vanessa-automation/files/9356765/default.docx)

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
@BelovaElena80 
Нужна база, на которой воспроизводится ошибка и сценарий.

**Comment by BelovaElena80** [comment]
> @BelovaElena80 Нужна база, на которой воспроизводится ошибка и сценарий.

Добрый день. К сожалению, база корпоративная, предоставить не можем. Могу ответить на уточняющие вопросы, чтобы помочь воспроизвести ошибку.

**Comment by Pr-Mex** [comment]
@BelovaElena80 
Вы можете создать тестовый пример на пустой базе или базе без данных или на базе с тестовыми данными.

**Comment by BelovaElena80** [comment]
В конфигурации 1С ERP в документе заявка на расходование денежных средств есть ссылка на группу реквизитов " реквизиты платежа в бюджет" ( см скрин 1 в приложенном документе word). Ошибка воспроизводится если записать при помощи VA действие по выбору из списка значения поля " статус плательщика". Дополнительно прикладываю скрин как выглчдет поле статус плательщика в конфигураторе.
![статус плательщика](https://user-images.githubusercontent.com/111412900/186091332-b9aa26ba-5758-4e57-bbdf-1a33bbc4142c.png)

**Comment by BelovaElena80** [comment]
Для демонстрации воспроизведения ошибки можно связаться со мной https://t.me/BelovaElena80

**Comment by Pr-Mex** [comment]
Решено
