### ISSUE TITLE
Ошибка шага "И я запоминаю значение таблицы "Таблица1" как "ИмяПеременной"  с колонками, содержащими \n в заголовке

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1739]
Версия Vanessa Automation 1.2.039.4
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Я смотрю, проблема все таки популярна.
На это указывают issue моя [1568](https://github.com/Pr-Mex/vanessa-automation/issues/1568), недавно заведенная [1736](https://github.com/Pr-Mex/vanessa-automation/issues/1736), ну и собственно текущая заявка.

#language: ru
@tree
Функционал: <описание фичи>
Контекст:
 	Дано Я открыл новый сеанс TestClient или подключил уже существующий
Сценарий: проверка запоминания значения таблицы

	И Я открываю навигационную ссылку "e1cib/data/Документ.Заказ?ref=af4760a44c6060c511ec68b8fde84559"

	Тогда таблица "Товары" стала равной:
		| 'Товар'     | 'Цена'      | 'Количество' | 'Сумма'     | 'Це\nна'    |
		| 'Veko345MO' | '17 500,00' | '2'          | '35 000,00' | '17 500,00' |
		| 'Босоножки' | '2 200,00'  | '5'          | '11 000,00' | '2 200,00'  |

	// ошибка в шаге, если брать имя колонки, как в шаге выше "Тогда таблица "Товары" стала равной"
	И я запоминаю значение таблицы "Товары" как "ТоварыЭталон"
		| 'Це\nна'|

	// и так тоже не работает (вывел список ТЧ и скопировал название колонки)
	И я запоминаю значение таблицы "Товары" как "ТоварыЭталон"
		| 'Це на'|

Базу для этой фичи можно взять из  [1568](https://github.com/Pr-Mex/vanessa-automation/issues/1568).
Там конечно очень не наглядный пример, и как ты выразился, искусственный, однако у нас в конце очень много решений, где используется \n в заголовке, вот например один из наглядных скринов
![image](https://user-images.githubusercontent.com/19662685/185364512-eac00d22-b5a0-407b-9d5b-7c15390a24fd.png)

**Comment by Pr-Mex** [comment]
Решено.
