### ISSUE TITLE
Параметр СписокСценариевДляВыполнения не работает, если используется внешняя компонента VanessaExt

### ISSUE THREAD

**Issue by serg-repin** [Pr-Mex/vanessa-automation#1742]
Укажите:
   1. Версия Vanessa Automation - 1.2.039
   2. Версия платформы - 8.3.20.1789
   3. Режим совместимости базы, где запускается Vanessa Automation - Версия 8.3.17
   4. Операционная система - Windows Server 2019

> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: выполнить сценарии из отбора
   Как администратор
   Я хочу запустить vanessa-automation с выполнением только сценариев из списка

Контекст:
  Дано: 1.2.039
  И 8.3.20.1789
  и ERP УХ

Сценарий: выполнить отбор по сценариям при запуске
  Допустим: у меня есть каталог с фича-файлами, но для целей тестирования я хочу выполнить не все фичи из каталога, а, например, только одну
  Когда: запускаю vanessa-automation с файлом параметров VA, содержащим "СписокСценариевДляВыполнения" = массив имен сценариев (в массиве 1 элемент)
  Тогда: запускаются все фичи из каталога, отбор не работает

```

Был merge-request (https://github.com/Pr-Mex/vanessa-automation/pull/1474) с этой функциональностью, но похоже в нем ошибка (недоработка) - отбор не работает, если используется внешняя компонента VanessaExt.

> Прикладывайте файлы скриншотов

![image](https://user-images.githubusercontent.com/11225084/186737465-039f9301-8e1b-48a9-922b-4b47240decb2.png)

**Comment by Pr-Mex** [comment]
Решено.

**Comment by balchugovg** [comment]
> Решено.

К сожалению решено частично. Отбор сценариев работает, но сценарии выполняются в порядке следования в фича-файле.
А должны выполняться в порядке следования в данной настройке.
VA version: [1.2.040.20](https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.040.20)
