### ISSUE TITLE
Возможность при запуске клиента тестирования отключить регл.задания

### ISSUE THREAD

**Issue by atyutyakin** [Pr-Mex/vanessa-automation#1749]
Укажите:
   1. Версия Vanessa Automation - 1.2.039.8
   2. Версия платформы - 8.3.17.2306
   3. Режим совместимости базы, где запускается Vanessa Automation - 8.3.15
   4. Операционная система - Windows 10

> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: отключить запуск регламентных заданий при запуске клиентов тестирования в файловой базе
   Как администратор
   Я хочу иметь возможность отключить запуск регламентных заданий для файловой базы при запуске клиентов тестирования

Контекст:
  Дано: 1.2.039.8
  И 8.3.17.2306
  и Самописная_конфигурация_на_базе_БСП_3

Сценарий: отключить запуск регламентных заданий при запуске клиентов тестирования в файловой базе
  Допустим: В тестируемой конфигурации есть предопределенные регламентные задания. 
  Когда: Я запускаю клиент тестирования для файловой информационной базы
  Тогда: (целевое поведение) в нем отключен запуск регламентных заданий.

```

В тестируемой самописной конфигурации активно используются регламентные задания. Разработка и ручное выполнение тестов ведется в том числе и на файловых базах. В прикладном коде имеются проверки флага использования регламентных заданий вида РегламентныеЗадания.НайтиПредопределенное("Некоторое_Имя_РЗ").Использование.
Поэтому для тестирования ряда механизмов требуется, чтобы у регламентных заданий признак использования был включен, однако сами они не стартовали по расписанию - необходимо управлять моментом запуска из теста.

Для серверных баз это решается отключением регл.заданий в настройках кластера. Для файловой базы можно прописать ключ /AllowExecuteScheduledJobs -Off для тестируемой базы, однако для запускаемых тест-клиентов этот ключ не будет использован, и в них регл.задания выполняются.

Поэтому необходима настройка для отключения регл.заданий - добавляющая в строку запуска клиента тестирования ключ /AllowExecuteScheduledJobs -Off 

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
Решено.
