### ISSUE TITLE
При передаче таблиц в экспортный сценарий, она копируются только в первый шаг экспортного сценария

### ISSUE THREAD

**Issue by NikitaLysenkoA** [Pr-Mex/vanessa-automation#1752]
Укажите:
   1. 1.2.038.27
   2. 8.3.18.1363
   3. Версия 8.3.14
   4. Windows 10

> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Вызов экспортного сценария, принимающего таблицу
   Как Разработчик
   Я хочу  Передать таблицу в экспортный сценарий и использовать ее в нескольких местах

Контекст:
  Дано: Single 1.2.038.27
  И 1С:Предприятие 8.3 (8.3.18.1363)
  и Бухгалтерия предприятия, редакция 3.0 (3.0.87.28) 

Сценарий:  Передаю таблицу в экспортный сценарий
  Тогда: Таблица доступна во всех посдценариях
  Факт: Таблица доступна только в первом подсценарии

```

> Прикладывайте файлы скриншотов

![image](https://user-images.githubusercontent.com/102023443/187639125-fa74f70a-f40c-47d7-b16c-10aa0f5055cf.png)

![image](https://user-images.githubusercontent.com/102023443/187637862-19a0e7f9-515f-435c-88a1-a455268e58f0.png)

[Основной сценарий.txt](https://github.com/Pr-Mex/vanessa-automation/files/9460136/default.txt)
[Подсценарий.txt](https://github.com/Pr-Mex/vanessa-automation/files/9460139/default.txt)

Проблема в функции МодульОбъекта.СкопироватьПодчиненныеТаблицы()
При первой подстановке ИдТаблицыДляКопирования (общий параметр для сценария) становится 0 и исходная таблица дальше не копируется.
Под условие "Если" заходит только для первого подсценария:
![image](https://user-images.githubusercontent.com/102023443/187641082-a835cf67-d791-4d4c-8eee-3ede363da33d.png)

Аналогично если использовать парсер компоненты. Там в json у второй строки нет переданной таблицы.

**Comment by Pr-Mex** [comment]
@NikitaLysenkoA 
Это плановое поведение. Имена подчиненных таблиц не имеют значения.
Если надо передать данные во вторую таблицу - тогда надо при вызове подсценария передавать две таблицы.

**Comment by Pr-Mex** [comment]
> @Pr-Mex , спасибо, понял. А ради интереса, почему поведение плановое?
@NikitaLysenkoA 
Когда я делал механизм передачи таблиц был выбран алгоритм передачи таблиц по порядку как и другие параметры шагов.

**Comment by akademik1986** [comment]
@Pr-Mex  извините, что вклиниваюсь. А как передать несколько таблиц? Как их отделять? пустая строка между ними должна быть?

**Comment by Pr-Mex** [comment]
> @Pr-Mex извините, что вклиниваюсь. А как передать несколько таблиц? Как их отделять? пустая строка между ними должна быть?
@akademik1986 
Да. Пустая строка.
