### ISSUE TITLE
Какие то проблемы использования Попытки в циклах, долгое выполнение шагов

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1756]
Версия Vanessa Automation 1.2.039.4
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Изначально проблема замечена в аллюре
![image](https://user-images.githubusercontent.com/19662685/188401741-b2247a2a-0e66-49be-bbc0-91f4c8cc0763.png)
Сам тест фичи
![image](https://user-images.githubusercontent.com/19662685/188401838-7a89d1b8-5446-4b30-851a-e11d965c4b20.png)
Воспроизвел фрагментом, на маленькой базе у меня вообще зависло на первой строке цикла, пришлось закрывать менеджер

#language: ru
@tree
Функционал: Проверка проведения документа Регламентная операция
Контекст:
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий
Сценарий: Проверка проведения документа 
	И я делаю 10 раз
		Если открылось окно 'Список ошибок*' Тогда
			Попытка
				И табличный документ "СписокОшибок" не содержит значения:
					| 'Подробная информация об ошибке записана в журнал регистрации' |
			Исключение
				И я регистрирую ошибку "Ошибка проведения документа Регламентная операция" по данным исключения
			И я закрываю текущее окно

**Comment by Pr-Mex** [comment]
@akademik1986 
Нужно приложить файл настроек VA, сценарий и базу, на которой воспроизводится проблема.

**Comment by akademik1986** [comment]
@Pr-Mex прикладываю
[база, настройки, фичи-файл](https://disk.yandex.ru/d/qd_9Jil7vuOlSg)

**Comment by Pr-Mex** [comment]
Уже решено.
