### ISSUE TITLE
Ошибка при загрузке данных при проверка на соответствие uuid

### ISSUE THREAD

**Issue by azheval** [Pr-Mex/vanessa-automation#1758]
При загрузке данных, если длина строки = 36 символам и имеет 4 - (минуса) считается, что это uuid. Строка "Пн-пт 10:00-20:00, СБ-ВС 10:00-19:00" вызывает ошибку.

{ВнешняяОбработка.VanessaAutomation.Форма.ПодготовкаИЗагрузкаДанных.Форма(1823)}: Ошибка при вызове конструктора (UUID): Недопустимое значение параметра (параметр номер '1')

Технические данные:
        ВерсияVA: ver 1.2.039.1

**Comment by Pr-Mex** [comment]
Решено.
