### ISSUE TITLE
[BUG] Для сценариев со статусом Broken в Allure не прикрепляется описание ошибки

### ISSUE THREAD

**Issue by BarinovIN** [Pr-Mex/vanessa-automation#1766]
1. Версия Vanessa Automation 1.2.039.1
   2. Версия платформы 8.3.19.1351
   3. Режим совместимости базы, где запускается Vanessa Automation не используется
   4. Операционная система Windows

Описание полностью соответствует #1479 с той разницей, что снимки экрана теперь в отчёт попадают, но всё ещё отсутствует описание ошибки (то, что в Allure называется trace) и заголовок ошибки (тот по которому группируются дефекты на закладке "Categories").

**Comment by Pr-Mex** [comment]
@BarinovIN 
Вижу коммит в твою ветку. Будешь сам реквест делать?

**Comment by BarinovIN** [comment]
Да, сделаю.

**Comment by Pr-Mex** [comment]
Решено.
