### ISSUE TITLE
Не заполняется переменная "СинонимКлиентаТестирования" в шаге  "И я читаю данные текущего профиля клиента тестирования"

### ISSUE THREAD

**Issue by Lelushka** [Pr-Mex/vanessa-automation#1772]
Укажите:
   1. Версия Vanessa Automation 1.2.039.4
   2. Версия платформы 8.3.20.1710
   3. Режим совместимости базы, где запускается Vanessa Automation  Версия 8.3.14
   4. Операционная система Windows 10 Pro

> Проблематика:
 При повторном использовании шага "И я читаю данные текущего профиля клиента тестирования" служебная переменная СинонимКлиентаТестирования очищается и остается пустой, пока не будет выполнен перезапуск Ванессы.

Пример фичи :
```Gherkin
Сценарий: Проверка
	И я подключаю TestClient "Пользователь 1" логин "Пользователь 1" пароль "$Password$"
	И я читаю данные текущего профиля клиента тестирования
	И я подключаю TestClient "Пользователь 2" логин "Пользователь 2" пароль "$Password$"
	И я читаю данные текущего профиля клиента тестирования

```

> Прикладывайте файлы скриншотов
![Снимок экрана 2022-09-22 093728](https://user-images.githubusercontent.com/66218157/191666476-9e6b7f36-de89-4e4f-9255-9750b2999b8d.png)

**Comment by Pr-Mex** [comment]
@Lelushka 
Проверил у себя на приведенном сценарии - всё отработало корректно.
Синоним остаётся пустым, т.к. при создании нового подключения Синоним не заполняется, а заполняется поле Имя. Оно заполнилось корректно.
Если считаете, что проблема есть - просьба уточнить сценарий воспроизведения.

**Comment by Lelushka** [comment]
т.е. это ожидаемое поведение, при создании нового подключения ?
Просто странно тогда, у нового подключения свой синоним.
А почему его нельзя тоже заполнить, есть особенности/сложности ?
Имя да - заполняется, вопрос именно синонима касался.
В целом не критично , но закрывает некоторые возможности.

**Comment by Pr-Mex** [comment]
@Lelushka 
Синоним - это специальное поле, которое используется также для поиска строки в таблице клиентов тестирования.
Оно нужно в том случае, когда поле Имя было уже заполнено при старте VA внешней системой, например СППР, а в сценарии надо как-то задать идентификатор для этого подключения. Больше Синоним ни для чего не используется.
