### ISSUE TITLE
Вероятно неверная работа шага "Затем я останавливаю выполнение сценария "СтатусСценария""

### ISSUE THREAD

**Issue by Lelushka** [Pr-Mex/vanessa-automation#1773]
Укажите:
   1. Версия Vanessa Automation 1.2.039.4
   2. Версия платформы 8.3.20.1710
   3. Режим совместимости базы, где запускается Vanessa Automation  Версия 8.3.14
   4. Операционная система Windows 10 Pro

> Проблематика : 
Если в одном фича-файле несколько сценариев,  использование шага "Затем я останавливаю выполнение сценария "СтатусСценария"", в одном из них,  приводит к пропуску остальных последующих сценариев, что противоречит описанию в шаге : "Останавливает выполнение шагов в данном сценарии."

Более того, пропущенным таким способом сценариям присваивается статус Passed в отчете Allure.

Считаю работу шага некорректным. Это ограничивает возможность присвоения различных статусов для разных сценариев в пределах одного фича-файла. 

Пример:
```Gherkin
Сценарий: <20.1 Предварительное создание иерархии Каналов продаж и контрагента>
	Когда открылось окно 'Каналы продаж предприятий'
Сценарий: <20.2 Пропуск сценария фичи в случае ошибки создания номенклатуры.>
	Если предыдущий сценарий выполнен успешно тогда
	Иначе 
		Затем я останавливаю выполнение сценария "Skipped"
Сценарий: <20.3 Проверка присвоения 'Ответственного' для канала продаж при создании записи через БП>
...
```

> Прикладывайте файлы скриншотов
![Снимок экрана 2022-09-22 101953](https://user-images.githubusercontent.com/66218157/191672746-f918ebcd-3ca6-4c69-aab3-c2f55c1c6a1e.png)

![Снимок экрана 2022-09-22 100459](https://user-images.githubusercontent.com/66218157/191670373-165ba39a-1831-4969-bbba-ca3511320dbc.png)

![Снимок экрана 2022-09-22 102027](https://user-images.githubusercontent.com/66218157/191672718-2d91b743-d362-439b-8197-189240fc01ca.png)

**Comment by Pr-Mex** [comment]
Решено.
