### ISSUE TITLE
Производительность стандартных шагов

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1779]
Версия Vanessa Automation 1.2.039.11
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Просьба рассмотреть производительность по шагам:
И выражение внутреннего языка 'Выражение' Истинно
Если элемент "ИмяЭлементаФормы" не присутствует на форме Тогда

1. По результатам аллюр шаг сильно деградирует, если условие в выражении ложно (стабильно всегда)
2. А шаг элемент не присутствует на форме сам по себе очень долгий при выполнении на CI (скачет время, 12 секунд первые 2-4 раза,потом по 2-3 секунды, при условии что элемента нет на форме)

![image](https://user-images.githubusercontent.com/19662685/193228062-d462da4d-aad1-4f07-b2bb-b0ce5c5042a1.png)

код фичи
![image](https://user-images.githubusercontent.com/19662685/193228307-699029e2-df81-4610-9297-714d8aebbda4.png)

Шаги стандартные, я думаю примеры есть и у вас в CI.

**Comment by Pr-Mex** [comment]
@akademik1986 
Приложите пример для воспроизведения, пожалуйста. Нужна база и сценарий.

**Comment by Pr-Mex** [comment]
@akademik1986  Надо смотреть код шага.

**Comment by akademik1986** [comment]
@Pr-Mex  Посмотри на кусок кода теста, там очень много таких шагов, перед каждым из них и сразу после изменять настройку это лишний код и захламление. 
Ведь даже шаг и я открываю окно тоже возможно требует 3 попыток, схалявить вначале и в конце поставить настройку не получится. 
Может все таки жля шагов вычисления выражения попытку одну сделать?

**Comment by Pr-Mex** [comment]
@akademik1986 
Пока не готов сказать. Надо подумать.

**Comment by Pr-Mex** [comment]
Скорее всего речь идёт об обычных шагах,  которые вызывается как условия. Для них наверное можно сократить количество попыток.

**Comment by akademik1986** [comment]
Ну на шаге типа Если открылось окно хотелось бы количество попыток оставить наверное

**Comment by Pr-Mex** [comment]
> Ну на шаге типа Если открылось окно хотелось бы количество попыток оставить наверное

В общем надо подумать как лучше.

**Comment by akademik1986** [comment]
@Pr-Mex  приветствую!
В новый релиз никак не сделать эту задачу?
у меня прям на некоторых фичах время доходит до 4 часов , активно использую шаги
Если выражение внутреннего языка 'нрег($УчетПоПодразделениям$) = нрег("Да")' Истинно Тогда 
то есть вычисляемые шаги, там по идее незачем иметь несколько попыток, один раз вычислили и все
все остальные условия Если Тогда оставить количество попыток как  было, сейчас по крайней мере.
Как думаешь? Я в такие дебри не полезу, так как нужно правильно отделить шаги просто условия от условий с вычислением выражения, так что надежда на тебя)
![image](https://user-images.githubusercontent.com/19662685/215104133-aff64e23-0f04-4daf-aacd-0f41abcfacc9.png)

**Comment by Pr-Mex** [comment]
@akademik1986 
Я посмотрел по коду - у шага
```Gherkin
И выражение внутреннего языка 'Выражение' Истинно.
```
нет внутри нескольких попыток вычислить выражение.

У тебя точно условие правильно написано? Оно ведь не может скомпилироваться, т.к. написано:
нрег(АП) = нрег("А")
Т.к. АП не обернуто в кавычки - то условие будет всегда ложным скорее всего

**Comment by Pr-Mex** [comment]
@akademik1986 
В общем непонятно почему ветка когда условие ложно вычисляется дольше.
Мне нужно это у себя воспроизвести.

**Comment by akademik1986** [comment]
@Pr-Mex  Исходный код вот такой.
И он работает в тех строках таблиц, если задано удовлетворение этому условию
![image](https://user-images.githubusercontent.com/19662685/215124692-2657f229-c195-4745-9963-f40950df9a2e.png)

**Comment by akademik1986** [comment]
Сама таблица переменных задается вот так
![image](https://user-images.githubusercontent.com/19662685/215125329-d50ab41d-17d7-4a14-9f74-e69df3c2208a.png)

**Comment by akademik1986** [comment]
Кстати, вот пример того, что там где ложь в выражении он не зашел в условие, а там где истина, зашел
![image](https://user-images.githubusercontent.com/19662685/215126205-735122e4-eb9b-49b9-bb8e-4c3a3d4b4b2b.png)

**Comment by Pr-Mex** [comment]
@akademik1986 
Чтобы это у себя воспроизвести мне нужна база и сценарий.

**Comment by akademik1986** [comment]
@Pr-Mex выродил в универсальную [фичу](https://disk.yandex.ru/d/_bVjfCaEWq2z3Q)
посмотри пжт
PS включил отладочные сообщения, там все ок

30.01.2023 12:40:11 Шаг (Если выражение внутреннего языка 'нрег($Вал$) = нрег("Да")' Истинно Тогда) не выполнен.
30.01.2023 12:40:13 {ВнешняяОбработка.ВстроенныйЯзык.Форма.Форма.Форма(132)}: Выражение <нрег(ОбъектКонтекст.Вал) = нрег("Да")> оказалось равно <Нет>, а ожидали <Да>.

**Comment by Pr-Mex** [comment]
@akademik1986 
> выродил в универсальную [фичу](https://disk.yandex.ru/d/_bVjfCaEWq2z3Q)
не понял - как мне у себя воспроизвести проблему?

**Comment by akademik1986** [comment]
@Pr-Mex  запустить на любой базе
На всякий случай [настройки](https://disk.yandex.ru/d/r4fzYoRtc7nefA), но там наверное из особенностей это стандартное повторение после ошибки = 3 раза, больше ничего интересного не должно быть
![image](https://user-images.githubusercontent.com/19662685/215470693-2ea66e30-976b-4de9-baff-cd3f40e0e494.png)

**Comment by Pr-Mex** [comment]
@akademik1986 
Какой именно сценарий нужно запустить на любой базе? Приложи feature файл, пожалуйста.

**Comment by akademik1986** [comment]
@Pr-Mex  
так она приложена же
![image](https://user-images.githubusercontent.com/19662685/215475959-c150b900-fd92-454d-ae4f-ca7ebe8fcccc.png)

**Comment by Pr-Mex** [comment]
Решено.
