### ISSUE TITLE
Некорректное поведение шагов из блока "Таблицы" при наличии в таблице TestClient'а колонки с заголовком содержащим фигурные кавычки.

### ISSUE THREAD

**Issue by Lelushka** [Pr-Mex/vanessa-automation#1781]
Укажите:
   1. Версия Vanessa Automation 1.2.039.11
   2. Версия платформы 8.3.20.1710
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.14
   4. Операционная система Windows 10 Pro

> Проблематика :
При наличии в таблице колонки с заголовком содержащим фигурные кавычки (« »)- шаг : И таблица "Список" содержит строки по шаблону  - падает в ошибку

```Gherkin
Функционал: <20. Справочник «Группы кредитного комитета»>

Как <Роль> я хочу
<описание функционала> 
чтобы <бизнес-эффект> 
Переменные:
	Справочник = 'Группы кредитного комитета'
	Имя = 'TestТест^1'
Контекст:
	И я запоминаю содержимое файла "Password.txt" в переменную "Password"
	И я закрываю все окна клиентского приложения
Сценарий: <20. Справочник «Группы кредитного комитета»>
1.1 Пользователь Администратор создает новый элемент справочника, нажатием кнопки «Подбор» на командной панели формы.
	И я подключаю TestClient "Администратор" логин "Администратор MDM" пароль "$Password$"
	Дано Я открываю навигационную ссылку 'e1cib/list/Справочник.ки_ГруппыКредитногоКомитета'
	Тогда открылось окно 'Справочник'
	И я нажимаю на кнопку с именем 'ФормаСоздать'			
1.2	Нажимает кнопку «Записать», проверяет список полей, обязательных для заполнения.
	Когда открылось окно '$Справочник$ (создание)'
	И я нажимаю на кнопку с именем 'ФормаЗаписатьИЗакрыть'
	Тогда в логе сообщений TestClient есть строки:
		| 'Поле "Наименование" не заполнено'         |	
1.3	Заполняет необходимые поля и записывает элемент и сохраняет номер
	Когда открылось окно '$Справочник$ (создание)'
	И в поле с именем 'Наименование' я ввожу текст 'Имя'
	И я нажимаю на кнопку с именем 'ФормаЗаписать'
	И я запоминаю значение поля с именем 'Код' как 'КодID'
	И я нажимаю на кнопку с именем 'ФормаЗаписатьИЗакрыть'
	И я жду закрытия окна '$Имя$ (Группы кредитного комитета)*' в течение 20 секунд
1.4 проверка наличия созданой записи
	И таблица "Список" содержит строки по шаблону
		| 'Наименование' | 'Код'     | 'MDM key' |
		| 'Имя'          | '$КодID$' | '*'       |
Закрытие
	И я закрываю все окна клиентского приложения	
```
п.с.
Причина точно в кавычках - выяснено опытным путем.
Не проверял, но вероятно, в других подобных шагах, со взаимодействием строк в таблице - поведение будет такое же. 
> Прикладывайте файлы скриншотов

![Снимок экрана 2022-10-03 175817](https://user-images.githubusercontent.com/66218157/193596199-60b5756d-72af-4b67-9f3e-6c833f6ce65e.png)

![photo_2022-10-03_17-44-26](https://user-images.githubusercontent.com/66218157/193592966-5fc4da92-99b2-4ef3-828e-a9242fdb76b9.jpg)

**Comment by Pr-Mex** [comment]
@Lelushka 
Ещё нужен сценарий и база для воспроизведения проблемы.

**Comment by Lelushka** [comment]
Полную фичу написал выше. 
Самый простой вариант воспроизвести:
1.Под правами администратора, в любом справочнике любой конфигурации, через настройку формы изменить заголовок колонки, добавив фигурные кавычки
![Снимок экрана 2022-10-03 193431](https://user-images.githubusercontent.com/66218157/193619802-44133297-9bd5-4c55-8a27-f55e52e8b42a.png)
2.  Создать элемент справочника
3.  В ванессе написать шаг для поиска созданного элемента:  "И таблица "ИмяТаблицы" содержит строки по шаблону" - можно через запись
4.  Попытаться выполнить шаг - получим ошибку, которую приводил выше.

**Comment by Lelushka** [comment]
Если не понятно, могу видео записать .

**Comment by Pr-Mex** [comment]
@Lelushka 
Пока понятно. Ещё не добрался.

**Comment by Pr-Mex** [comment]
Решено.
