### ISSUE TITLE
Не делать скриншот если он не нужен при сборках инструкций.

### ISSUE THREAD

**Issue by ViktorErmakov** [Pr-Mex/vanessa-automation#1787]
Много мусора, т.к. все равное делает все скриншоты

**Comment by ViktorErmakov** [comment]
Никита, я сделал этот этот ишью для себя, скажу сразу. Ну и видимо ты не понял смысл задачи, скриншоты нужны, но если есть шаги при которых они делаться не должны физически скриншотов в папке инструкции быть не должно. Как то так.

**Comment by nixel2007** [comment]
Окей, не лезу :)
