### ISSUE TITLE
Шаг "И я перемещаю курсор к элементу формы  'PID' 'Имя' 'Тип' UI Automation" не учитывает Тип поля и находит все с указанным именем

### ISSUE THREAD

**Issue by mrshadow300373** [Pr-Mex/vanessa-automation#1795]
Версия: VA 1.2.039.14
Версия платформы: 8.3.17.1549
Версия совместимости приложения: 8.3.14
Операционная система Windows 10

```Gherkin
Функционал: UI Automation
   Как Тестировщик
   Я хочу Переместить указатель мыши на нужное мне поле с использованием шага
         И я перемещаю курсор к элементу формы  'PID' 'Имя' 'Тип' UI Automation

Контекст:
  Дано: 1.2.039.14
  И 8.3.17.1549
 и конфигурация запуска
[VAParams.zip](https://github.com/Pr-Mex/vanessa-automation/files/9891831/VAParams.zip)

Сценарий: Перемещение указателя мыши к нужному полю
  Допустим: Есть поле ввода у которого имя 'Ветка:' тип 'поле' и заголовок поля тоже Ветка: тип 'текстовый' 
  Когда: я исполняю шаг: И я перемещаю курсор к элементу формы  '$PIDКлиентаТестирования$' 'Ветка:' 'поле' UI Automation
  Тогда: происходит ошибка
29.10.2022 0:39:23 {ВнешняяОбработка.UIAutomation.Форма.Форма.Форма(2695)}: {ВнешняяОбработка.UIAutomation.Форма.Форма.Форма(2665)}: Найдено <2> элементов UI Automation по переданным данным PID <11 300>, заголовок <Ветка:>, тип <поле>.
  Если изменить заголовок у поля ввода на "Ветка исправления" (Ещё/Изменить форму) тогда шаг исполняется, и курсор подводится к нужному элементу.
```
Конфигурация + фича для воспроизведения
[TestCase.zip](https://github.com/Pr-Mex/vanessa-automation/files/9891868/TestCase.zip)
Загрузить конфигурацию, запустить как менеджера, открыть VA, открыть клиента тестирования эту же конфигурацию. Загрузить и проиграть фичу.
Результат:
![1666991781311](https://user-images.githubusercontent.com/34220218/198734300-8786a2cc-0770-4571-ba2d-371639bf6ec1.png)
Изменить через Ещё/Изменить форму заголовок поля "Ветка" на что то другое
проиграть ещё раз, фича завершится без ошибок.

**Comment by Pr-Mex** [comment]
@mrshadow300373 
На форме два элемента с заголовком "Ветка:"
Правильный шаг выглядит так
И я перемещаю курсор к элементу формы  '$PIDКлиентаТестирования$' 'Ветка:' 'Edit' UI Automation

**Comment by mrshadow300373** [comment]
@Pr-Mex 
Я для определения элемента управления использовал Accessibility Insights for Windows он мне для обоих полей сообщал что это "поле", про  Edit не было ни слова. Попробую так спасибо!
