### ISSUE TITLE
Ошибка открытия под толстым клиентом

### ISSUE THREAD

**Issue by PashaMak** [Pr-Mex/vanessa-automation#1796]
Укажите:
   1. Версия Vanessa Automation 1.2.039.11
   2. Версия платформы 8.3.12.1790
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система 8.3.9

> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: <Необходимый эффект>
   Как разработчик
   Я хочу тестировать под толстым клиентом

Контекст:
  Дано: 1.2.039.11
  И 8.3.12.1790
  и толстый клиент обычное приложение

Сценарий: Запуск тестов под толстым клиентом в обычных формах
  Допустим: Я запускаю толстый клиент в обычных формах
  Когда: Загружаются тесты
  Тогда: Не возникает ошибок построения дерева тестов

```

> Прикладывайте файлы скриншотов
![image](https://user-images.githubusercontent.com/24808007/198932472-b74db37a-4e4a-4d1d-b1a2-06f9040af1f0.png)

**Comment by Pr-Mex** [comment]
Решено.
