### ISSUE TITLE
При открытии обработки Vanessa Automation появляется окно Обнаружены ошибки: Неизвестное имя формы. Имя: "ВнешняяОбработка.VanessaAutomation.Форма"

### ISSUE THREAD

**Issue by Eu-Ti** [Pr-Mex/vanessa-automation#1802]
Укажите:
   1. Версия Vanessa Automation 1.2.039.1
   2. Версия платформы 8.3.22.1603
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система Windows 10 Pro, 64-разрядная

> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: <Необходимый эффект>
   Как пользователь
   Я хочу открыть vanessa-automation

Контекст:
  Дано: 1.2.039.1
  И 1С:Предприятие 8.3 (8.3.22.1603)
  и Система проектирования прикладных решений, редакция 2.0 (2.0.4.15)

Сценарий: открытие обработки vanessa-automation
  Допустим: Файл - Открыть - выбираю обработку
  Когда: открывается окно
  Тогда: сообщение Обнаружены ошибки: Неизвестное имя формы. Имя: "ВнешняяОбработка.VanessaAutomation.Форма"

```

> Прикладывайте файлы скриншотов
![vanessa_err](https://user-images.githubusercontent.com/117901469/201055569-d7138ed4-a09d-4060-a1cc-5bd821989525.jpg)

**Comment by Pr-Mex** [comment]
@Eu-Ti 
Такое может быть если открывалось несколько разных версий  VA в одном сеансе.
Перезапустите сеанс 1С и перезапустить сервер, если база серверная.

**Comment by Eu-Ti** [comment]
Несколько разных версий VA в одном сеансе не открывалось, но попросил перезапустить службу 1С на сервере и это помогло. Спасибо!
