### ISSUE TITLE
Открытие плагина "СериализаторMXL" в обычных формах выдает ошибку

### ISSUE THREAD

**Issue by PashaMak** [Pr-Mex/vanessa-automation#1803]
Укажите:
   1. Версия Vanessa Automation 1.2.0.39.11
   2. Версия платформы 8.3.12.1790
   3. Режим совместимости базы, где запускается Vanessa Automation не установлен
   4. Операционная система Win10

> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Создание макетов в обычных формах
   Как разработчик
   Я хочу быстро создавать окружение для тестов

Контекст:
  Дано: Vanessa Automation 1.2.0.39.11
  И  8.3.12.1790
  и обычные формы

Сценарий: Открывается плагин "СериализаторMXL"
  Допустим: открываю плагин "СериализаторMXL"
  Когда: открывается
  Тогда: не возникает ошибок

```
![image](https://user-images.githubusercontent.com/24808007/202610529-7473b313-a550-4439-9945-c316d32b5f04.png)

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
Решено.
