### ISSUE TITLE
Ошибка шага  "И я запоминаю значение таблицы "Таблица1" как "ИмяПеременной" без указания колонок, когда в ТЧ имеется колонка без заголовка

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1810]
Версия Vanessa Automation 1.2.039.11
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

У нас в продукте используется юзабилити решение - пустая колонка в конце таблиц на форме, для того, чтобы пользователь имел возможность играться с шириной предпоследней значащей колонки.
![image](https://user-images.githubusercontent.com/19662685/204571489-aa399f88-272d-4801-9888-504ac6f58143.png)

Но это мешает использованию шага "И я запоминаю значение таблицы "Таблица1" как "ИмяПеременной"" без указания колонок, которые нужно запомнить, так как количество колонок на форме больше 50.
Выходит ошибка.

Задано неправильное имя атрибута структуры
{ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(14637)}:Ванесса.УбратьЗапрещенныеСимволыИзКлючаСтруктуры(ИмяКолонки.Кол1));
{(1)}:Обработка.ЯЗапоминаюЗначениеТаблицыКак(МассивАргументов[0],МассивАргументов[1])
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27065)}:Выполнить(Команда);

по причине:
Задано неправильное имя атрибута структуры

Может быть в этом шаге отбрасывать по умолчанию колонки, которые не имеют Заголовка? или автоматически задавать некий УИД... В общем, чтобы можно было использовать шаг в таким набором колонок.

**Comment by Pr-Mex** [comment]
@akademik1986 
Да, думаю их стоит игнорировать.

**Comment by Pr-Mex** [comment]
Решено.
