### ISSUE TITLE
Индекс находится за границами массива

### ISSUE THREAD

**Issue by evg-e** [Pr-Mex/vanessa-automation#1811]
Укажите:
   1. Версия Vanessa Automation 1.2.039.1
   2. Версия платформы 8.3.21.1622
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.15
   4. Операционная система windows

В процессе прогона тестов в Jenkins возникает ошибка. Выполняется больше половины тестов, затем возникает ошибка, которая блокирует дальнейшее выполнение тестов. Локально работает нормально.

Если обернуть ТекШаг = Шаги[ТекИД_ШагаВМассиве]; в попытку, то ошибка не возникает, но не знаю на что в дальнейшем это может повлиять.

Текст ошибки:
Индекс находится за границами массива
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(11876)}:ТекШаг = Шаги[ТекИД_ШагаВМассиве];
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(30462)}:Стр = ПодставитьПеременныеВСтроку(Стр);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(30536)}:ЗначениеПеременной = ПодставитьЗначенияИнлайнВыраженийВСтроку(ЗначениеПеременной, ДанныеПоПростымПеременным, ДанныеПоПеременныхВТаблицах);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(30620)}:ИнициализироватьПеременныеИзСекцииПеременные(МассивСценариевДляВыполнения[ТекИД_СценарияВМассиве]);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29006)}:ВыполнитьСценарийАссинхронноТаймер();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29366)}:ПерейтиКВыполнениюСледующегоСценария();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(29423)}:ВыполнитьШаг();
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27512)}:ПерейтиКВыполнениюСледующегоШага(,, ИдСледующегоШага);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27396)}:ВыполнитьШагОкончание(РезультатПрохожденияТестовСценария, РезультатПрохожденияШага, ШагВыполнен, ШагНеРеализован, СтрокаШага, БылОбновленКешФормы, СтрОшибка);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(27939)}:ВыполнитьШагПродолжение(РезультатПрохожденияШага, ОбработкаТеста);

**Comment by Pr-Mex** [comment]
@evg-e 
Проверьте, пожалуйста, возникает ли проблема на этом релизе
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.039.11

**Comment by evg-e** [comment]
Да, возникает

**Comment by Pr-Mex** [comment]
Решено
