### ISSUE TITLE
Возможно неверное выполнение комбинации шагов обхода строк ТЧ и проверки текущей строки ТЧ

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1817]
Версия Vanessa Automation 1.2.039.11
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Имеется ТЧ на форме, например
![image](https://user-images.githubusercontent.com/19662685/207618077-519eee48-0073-4fa6-978c-cdc19d244b18.png)

Выполняем   в фиче такую конструкцию
	И для каждой строки таблицы "Товары" я выполняю в обратном порядке
		Если в таблице "Товары" текущая строка равна Тогда
			| 'Товар'  |
			| 'Сапоги' |
			И я продолжаю цикл
		Иначе
			И в таблице "Товары" я удаляю строку

И ожиданием выполнения этой части кода будет 1 оставшаяся строка в ТЧ - Сапоги.

Однако, при выполнении получаем иной результат
![image](https://user-images.githubusercontent.com/19662685/207618737-c249b93b-3ea8-4b87-a001-735ac471ef2f.png)

Даже если выполнить просто  удаление строк в этом цикле, то останется одна строка в ТЧ
	И для каждой строки таблицы "Товары" я выполняю в обратном порядке
		И в таблице "Товары" я удаляю строку
![image](https://user-images.githubusercontent.com/19662685/207619282-4fb95e4e-c7a6-4c81-89ff-33a5c93280dd.png)

 [Ссылка на фичу и базу](https://disk.yandex.ru/d/ZFQhTNyV_qit3Q)

**Comment by Pr-Mex** [comment]
@akademik1986 
Думаю это не ошибка.
Шаг цикла делает сдвиг строки на одну вверх. Плюс удаление строки тоже делает сдвиг вверх, но цикл этого не ожидает.
Вообще при обходе коллекции лучше не менять состав коллекции, а сохранять куда-то ид строк к удалению и потом их удалять уже после завершения цикла.
