### ISSUE TITLE
Ошибка при загрузке через механизм подготовки и загрузки данных счетов Хозрасчетного плана счетов

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1820]
Версия Vanessa Automation 1.2.039.11
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Воспроизводится на типовой БП. 
Можно по любому плану счета сформировать фичу для выгрузки / загрузки и будет ошибка.
Например, текст фичи

	И я проверяю или создаю для плана счетов "Хозрасчетный" объекты с обмен данными загрузка истина:
		| 'Ссылка'                                                                | 'ПометкаУдаления' | 'Родитель' | 'Код' | 'Наименование'                 | 'Порядок' | 'Вид'       | 'Забалансовый' | 'ЗапретитьИспользоватьВПроводках' | 'КодБыстрогоВыбора' | 'Валютный' | 'Количественный' | 'УчетПоПодразделениям' | 'НалоговыйУчет' |
		| 'e1cib/data/ПланСчетов.Хозрасчетный?refName=АмортизацияОсновныхСредств' | 'False'           | ''         | '02'  | 'Амортизация основных средств' | ' 02'     | 'Пассивный' | 'False'        | 'True'                            | '02'                | 'False'    | 'False'          | 'True'                 | 'True'          |

	И я перезаполняю для объекта табличную часть "ВидыСубконто":
		| 'Ссылка'                                                                | 'ВидСубконто'                                                                         | 'Предопределенное' | 'ТолькоОбороты' | 'Суммовой' | 'Валютный' | 'Количественный' |
		| 'e1cib/data/ПланСчетов.Хозрасчетный?refName=АмортизацияОсновныхСредств' | 'e1cib/data/ПланВидовХарактеристик.ВидыСубконтоХозрасчетные?refName=ОсновныеСредства' | 'True'             | 'False'         | 'True'     | 'True'     | 'True'           |

выдает ошибку
![image](https://user-images.githubusercontent.com/19662685/208428093-846ea70b-d596-4143-9b2f-ec3099dff761.png)

**Comment by DitriXNew** [comment]
Детальный лог нужен. Скрин метаданных этого плана счета, чтобы понять что такое ВидыСубконто.
К тому же - этот механизм не дорабатывался особо для планов счетов, так как обычно все эти счета предопределенные и загружать их смысла нету. Если я понял вашу задачу.

**Comment by Pr-Mex** [comment]
@akademik1986 
Скинешь?

**Comment by akademik1986** [comment]
@Pr-Mex  скинул. Этого достаточно?

![image](https://user-images.githubusercontent.com/19662685/208439969-53a18a42-9a1f-4488-a7b5-aa2033f2105c.png)

![image](https://user-images.githubusercontent.com/19662685/208440052-ac900e57-1f7f-4ce0-80b9-cd5582224ff1.png)

**Comment by akademik1986** [comment]
@DitriXNew  у нас около 100 своих счетов)

**Comment by Pr-Mex** [comment]
Решено.
