### ISSUE TITLE
Обновление таблицы из контекстного меню и текстового поля

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1821]
Версия Vanessa Automation 1.2.039.11
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Иногда при работе с таблицами Gerkin требуется обновить значения таблицы из таблицы клиента (изменился эталон). Была бы полезной кнопка в контекстном меню, чтобы можно было обновить значения в существующей таблице из клиентского приложения, так как делать новую таблицу более трудозатратно - изменены состав колонок, их порядок, настроен шаблон в значениях таблицы.
Причем предлагаю не менять значения в колонках с шаблоном.

![image](https://user-images.githubusercontent.com/19662685/209296192-39d9f31b-e66c-4ccc-9132-2649ccef2d51.png)

**Comment by Pr-Mex** [comment]
@akademik1986 
Да, это было бы полезно. Я сам думал о том, что пользователю нужно периодически обновлять данные из эталона.

**Comment by mors1eska** [comment]
@Pr-Mex это я попробую взять (в чате такое же писал)
Разобъю на 2 части:
1. актуализация обычного текстового поля
2. актуализация таблицы

Тут еще попишу для себя штуки всякие, чтобы не запутаться

Т_аблицаЭталон - если пустая, то заменяем значение
МодульРедакторТекста().ВставитьТекстСУчетомФорматирования(Объект.СгенерированныйСценарий); - так вставляем текст
НомерСтрокиДерева - где именно надо что-то вставить

ОбработкаОповещения

ИначеЕсли ИмяСобытия = "ПерейтиКСтрокеДереваСОшибкой" Тогда
		ПерейтиКСтрокеДереваСОшибкой(Параметр);_

**Comment by Pr-Mex** [comment]
@mors1eska хорошо

**Comment by mors1eska** [comment]
@Pr-Mex а как понять, какие методы имеет ванесса эдитор?
Я про, например, вот эти ,ПозицияVanessaEditor = ЭкземплярVanessaEditor.getPosition();

Я получил значение, хочу его вставить в правильное место
Пока не догоняю?

<img width="803" alt="image" src="https://user-images.githubusercontent.com/34914654/210225996-2e0791a9-23a6-4cad-b428-8c2626f1f661.png">

**Comment by Pr-Mex** [comment]
@akademik1986 
Сейчас точно не помню метод. Его можно подсмотреть в методе контекстного меню - Редактировать таблицу. Ctrl+shift+T. Там открывается форма для редактирования таблицы Gherkin. Затем идёт оповещение формы VA, чтобы сделать вставку в редактор.

**Comment by Pr-Mex** [comment]
@lintest 
Подскажи, пожалуйста, где лежит список методов редактора?

**Comment by lintest** [comment]
> @lintest Подскажи, пожалуйста, где лежит список методов редактора?
Список методов лучше смотреть в исходном коде редактора:
https://github.com/Pr-Mex/VAEditor/blob/master/src/vanessa-editor.ts#L18

**Comment by mors1eska** [comment]
> > @lintestПодскажи, пожалуйста, где лежит список методов редактора?
> 
> Список методов лучше смотреть в исходном коде редактора: https://github.com/Pr-Mex/VAEditor/blob/master/src/vanessa-editor.ts#L18
> 
> А также на официальном сайте Monaco Editor API https://microsoft.github.io/monaco-editor/api/index.html

Спасибо, чуть стало понятнее
Но чот не могу совладать с 
ПолныйТекстСтроки = ЭкземплярVanessaEditor.getLineContent(ТекущаяСтрокаVanessaEditor);

Он какие-то произвольные строки возвращает =( а не ту, которую хочу править
Может как-то можно найти и передать правильную?

**Comment by Pr-Mex** [comment]
@mors1eska 
А что у тебя в переменной ТекущаяСтрокаVanessaEditor?

**Comment by mors1eska** [comment]
> @mors1eska А что у тебя в переменной ТекущаяСтрокаVanessaEditor?

Ну туда строку текущую возвращает, причем, она, получается, ориентируется на курсор
А курсор может быть где угодно же

<img width="985" alt="image" src="https://user-images.githubusercontent.com/34914654/210319490-e8412f05-88fa-4acd-bfaf-91d0d34e3ba1.png">

Надо как-то правильную строку найти

**Comment by mors1eska** [comment]
Кажется, туплю
У меня есть номер строки дерева и можно попробовать с ним поиграть

**Comment by mors1eska** [comment]
> @mors1eska А что у тебя в переменной ТекущаяСтрокаVanessaEditor?

Пока сделал на сингл, буду разбираться как перетащить в обычную и залить
И только для обычных значений (без таблиц), хочу чтобы код поглядел, может все плохо очень =))

Записал видео как работает, по эргономике - норм?
http://recordit.co/oQZrJf444l

**Comment by Pr-Mex** [comment]
@mors1eska 
Видео посмотрел. Всё ок.

**Comment by Pr-Mex** [comment]
@mors1eska 
Код неудобно смотреть через сравнение epf. Сделай реквест и там код будет виден.

**Comment by mors1eska** [comment]
> @mors1eska Код неудобно смотреть через сравнение epf. Сделай реквест и там код будет виден.

Что-то отправил вроде
https://github.com/Pr-Mex/vanessa-automation/pull/1829

**Comment by mors1eska** [comment]
Собираю информацию для обновления таблиц

1. В деталях ошибки у нас какое-то хитрое представление таблиц
2. Мы можем его преобразовать в ТабличныйДокумент

	МассивКлючей                 = Неопределено;
	ТаблицаЭталонТабДок          = ПреобразоватьЗначениеВМакет(ТаблицаЭталон,МассивКлючей);
	ТаблицаТекущееЗначениеТабДок = ПреобразоватьЗначениеВМакет(ТаблицаТекущееЗначение,МассивКлючей);
3. Надо понять, есть ли готовая функция, которая преобразует табличный документ в таблицу геркин. По идее она есть. мы же получаем данные таблиц, когда записываем тесты

**Comment by mors1eska** [comment]
@Pr-Mex можешь подсказать, https://t.me/testspro1c/68138

**Comment by mors1eska** [comment]
Попробую подробнее расписать про актуализацию таблиц

Смотрю форму детальной информации об ошибке
Там есть 2 переменные:
- ТаблицаЭталон
- ТаблицаТекущееЗначение

У них довольно своеобразный формат
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/34914654/215330201-c67916d5-c913-4a9c-94d1-c473b8dc5b7e.png">

Задача
В тесте подменить ТаблицаЭталон на ТаблицаТекущееЗначение

Пытаюсь воспользоваться механизмом, который используется при редактировании таблиц
`ИмяСобытия = "РедактированиеТаблицыGherkin" Тогда`

Там таблица передается как массив строк
МассивТаблицы

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/34914654/215330384-d2d3eb3d-cda6-4ff0-a1d6-1f0e8a7865d8.png">

Там используется вот такая функция
`ЗаменитьТаблицуGherkinПослеРедактирования`

В ней есть процедура `ФорматироватьТаблицуGherkin(МассивСтрокТаблицы);`
Может она может преобразовать строку полученного значения в таблицу? Хотя, не похоже на это

В итоге мой вопрос такой:
Есть ли какие-то средства готовые, которые ТаблицаТекущееЗначение переделаю в массив строк с нужным форматированием? чтобы скормить ее в ЗаменитьТаблицуGherkinПослеРедактирования?

**Comment by Pr-Mex** [comment]
> У них довольно своеобразный формат

Это просто табличный документ

**Comment by mors1eska** [comment]
А нет ли чего готового - как перевести из табличного документа в таблицу Геркин?

**Comment by Pr-Mex** [comment]
Решено.
