### ISSUE TITLE
При использовании парсера из компоненты не подставляется параметр во вложенный сценарий

### ISSUE THREAD

**Issue by 1cgh** [Pr-Mex/vanessa-automation#1823]
Укажите:
   1. Версия Vanessa Automation 1.2.039.1
   2. Версия платформы 1С:Предприятие 8.3 (8.3.18.1563)
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.14
   4. Операционная система Windows

Есть простой экспортный сценарий для очистки произвольного независимого РС:
```Gherkin
Сценарий: Я очищаю независимый регистр сведений "ИмяРегистраСведений"
	Дано я выполняю код встроенного языка на сервере без контекста
		|' НаборЗаписей = РегистрыСведений[\"[ИмяРегистраСведений]\"].СоздатьНаборЗаписей();       '|
		|' НаборЗаписей.ОбменДанными.Загрузка = Истина;                                            '|
		|' НаборЗаписей.ДополнительныеСвойства.Вставить(\"ОтключитьМеханизмРегистрацииОбъектов\"); '|
		|' НаборЗаписей.Записать(Истина);                                                          '|
```

Если вызывать этот сценарий, то при использовании встроенного парсера (на 1С) параметр подставляется корректно и шаг выполняется. В редакторе с отображением вложенных сценариев это выглядит так:
![image](https://user-images.githubusercontent.com/24507052/209528579-ee061d3b-f340-4905-9346-80224c8e5204.png)

При использовании парсера из компоненты параметр не подставляется, шаг не выполняется. В редакторе с отображением вложенных сценариев это выглядит так:
![image](https://user-images.githubusercontent.com/24507052/209528472-7ccf4352-c1e9-45a6-b713-5b87cb71935d.png)

**Comment by Pr-Mex** [comment]
@1cgh 
Ты проверял это поведение на последнем релизе?

**Comment by 1cgh** [comment]
@Pr-Mex проверял на 039.22, там аналогично проявляется, парсер компоненты не подставляет параметр

**Comment by Pr-Mex** [comment]
@1cgh 
Понял. Посмотрю. Спасибо!

**Comment by Pr-Mex** [comment]
@lintest

**Comment by 1cgh** [comment]
@Pr-Mex на 040.15 не воспроизводится. видимо, @lintest поправил в компоненте

**Comment by 1cgh** [comment]
Поторопился с предыдущим камментом. На 040.15 с компонентой 1.3.9.14 шаг компонентой вообще не грузится
Не найдена процедура или функция для выполнения шага: И Я очищаю независимый регистр сведений "пуп"
При использовании встроенного парсера всё работает, как ожидается.

**Comment by Pr-Mex** [comment]
Решено.
