### ISSUE TITLE
Ошибка при выполнении выражения 'ВыражениеВстроенногоЯзыка'

### ISSUE THREAD

**Issue by Eu-Ti** [Pr-Mex/vanessa-automation#1825]
Укажите:
   1. Версия Vanessa Automation ver 1.2.039.22
   2. Версия платформы 8.3.22.1704
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.22.1704
   4. Операционная система Win 10

Контекст:
  Дано: Vanessa Automation ver 1.2.039.22
  И 1С:Предприятие 8.3 (8.3.22.1704)
  и 1С:ERP Управление предприятием 2 (2.5.8.232)

Сценарий: Есть сценарий проверки документа Счет-фактура, где нужно открыть список документов, перейти к последнему, открыть последний документ, записать, закрыть. Проблема в том, что в списке документов дата отображается в формате "дд:мм:гггг", а в форме открытого окна дата отображается в формате "дд:мм:гггг чч:мм:сс".
![image](https://user-images.githubusercontent.com/117901469/209640402-6b7cc349-7a3c-4bf1-947d-8114db6fa77b.png)
![image](https://user-images.githubusercontent.com/117901469/209640553-d89034d6-1912-4eaf-96d4-6b9194a47079.png)

Встроенная функция почему-то не выполняется
![image](https://user-images.githubusercontent.com/117901469/209642478-c4a865c0-02d9-4872-83c1-0dab507d65a2.png)
Текст ошибки:
{ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(2565)}: Окно с заголовком <Счет-фактура полученный 44100178366/0410 от КонецДня(31.08.2022)> не найдено. 
                            Таймаут поиска окна: <10>. Заголовок активного окна: <Счет-фактура полученный 44100178366/0410 от 31.08.2022 23:59:59>.  
Вопрос - как можно добавить время в переменную с помощью встроенного языка?
Спасибо!
```

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
@Eu-Ti 
У вас строка 30 не срабтала, т.к. подстановка переменных  в $ в шаги происходит через СтрЗаменить().
Используйте Лев(КонецДня(Контекст.ДатаДокумента),10)

**Comment by Eu-Ti** [comment]
Т.е. правильно я понимаю, что в 30 строке шаг должен выглядеть вот так?
И я запоминаю значение выражения 'Лев(КонецДня(Контекст.ДатаДокумента_Дата),10)' в переменную "ДатаДокумента_Дата"

**Comment by Pr-Mex** [comment]
@Eu-Ti 
Да. Ещё корректнее вместо Лев использовать Формат.

**Comment by Eu-Ti** [comment]
![image](https://user-images.githubusercontent.com/117901469/209707793-479000ac-ea23-48c7-a8d4-b21a49a24cb3.png)
![image](https://user-images.githubusercontent.com/117901469/209707923-7cf16d25-acb2-4b16-a294-8965facb88d0.png)

{ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(2565)}: Окно с заголовком <Счет-фактура полученный 44100178366/0410 от Формат(КонецДня(Контекст.ДатаДокумента_Дата),10)> не найдено. Таймаут поиска окна: <10>. Заголовок активного окна: <Счет-фактура полученный 44100178366/0410 от 31.08.2022 23:59:59>.
Возможная строка шаблона <*чет-фактура полученный 44100178366/0410 от *>.
Получается так же..

**Comment by Pr-Mex** [comment]
@Eu-Ti 
Я примерно написал. У вас ещё нет переменной Контекст.ДатаДокумента_Дата в строке 30. Берите переменную из строки 28.
