### ISSUE TITLE
Шаг "И элемент формы с именем "Имя" стал равен "Текст"" в VA 1.2.039.22 перестал работать так как раньше.

### ISSUE THREAD

**Issue by AlexRovichKMA** [Pr-Mex/vanessa-automation#1826]
1. Версия Vanessa Automation 1.2.039.22
   2. Версия платформы 8.3.21.1302
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.14
   4. Операционная система Windows 11

Описание проблемы: после обновления с VA 1.2.039.1 до VA 1.2.039.22 перестал работать следующий шаг:
"И элемент формы с именем "ЛентаВзаимодействий_HTML" стал равен "*тест комментарий 5*тест комментарий 4*тест комментарий 3*тест комментарий 2*тест комментарий 1*" по шаблону"

Дело в том что с помощью данного шага мы проверяли нужную нам фиксированную последовательность в реквизите типа строка, который называется "ЛентаВзаимодействий_HTML" как следует из названия реквизита там у нас хранится текст HTML разметки и это очень длинная строка. 

На VA 1.2.039.1 если мы выполняли данный шаг и последовательность "*тест комментарий 5*тест комментарий 4*тест комментарий 3*тест комментарий 2*тест комментарий 1*" была нарушена, например "тест комментарий 5" и "тест комментарий 3" будут поменяны местами, то шаг выдавал ошибку. Если последовательность не нарушена то шаг выполнялся.

На VA 1.2.039.22 если мы выполняем данный шаг то VA виснет и прервать ее выполнение возможно только с помощью диспетчера задач и завершения сеанса. 

Мы могли бы пользоваться шагом "Тогда HTML документ с именем "ИмяЭлемента" стал равен", но в нем нет возможности использовать конструкцию "по шаблону", соответственно не подходит.

Пока что откатываемся назад на VA 1.2.039.1. Ждем ответа по данному вопросу. Спасибо!)

**Comment by Pr-Mex** [comment]
@AlexRovichKMA 
Приложите  к issue пример для воспроизведения проблемы. Нужен сценарий и база.

**Comment by AlexRovichKMA** [comment]
@Pr-Mex 
С этим сложно, попробую предоставить.

**Comment by Pr-Mex** [comment]
@AlexRovichKMA 
Можно смоделировать эту ситуацию на "пустой" базе.
