### ISSUE TITLE
Ошибка Метод объекта не обнаружен (НайтиПоИдентификатору) 

### ISSUE THREAD

**Issue by oompaloomp** [Pr-Mex/vanessa-automation#1827]
Укажите:
   1. Версия Vanessa Automation
   2. Версия платформы
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система

> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Проверить создания заявки
   Как инициатор заявок
   Я хочу Проверить создания заявки

Контекст:
  Дано: Vanessa Automation - 1.2.039.22
  И Управление холдингом, редакция 3.0 (3.0.9.3)
  и ВерсияПлатформы: 8.3.20.2184

Сценарий: Создание заявки
  Допустим: Я создаю документ "Заявка на оплату"
  Когда: И в таблице "ТаблицаДвижений" в поле с именем "ТаблицаДвиженийСтатьяДвиженияДенежныхСредств" я ввожу текст 'Прочие материалы'
  Тогда: Ошибка Метод объекта не обнаружен (НайтиПоИдентификатору) 

```
   1. Версия Vanessa Automation - 1.2.039.22
   2. ВерсияПлатформы: 8.3.20.2184
   3. РежимСовместимостиTestManager: Версия8_3_12
   4. Операционная система Windows Server 2019. версия 1809
   5.  ИмяФайла: ВнешняяОбработка.VanessaAutomationsingle.Форма.Тест_РаботаСИнтерфейсом
   6. ИмяПроцедуры: ВТаблицеВПолеСИменемЯВвожуТекст
   7. Ошибка Метод объекта не обнаружен (НайтиПоИдентификатору) {ОбщийМодуль.ОперативноеПланированиеФормыУХ.Модуль(116)}:ТекущиеДанные = ТаблицаРеквизит.НайтиПоИдентификатору(ИдентификаторСтроки);

> Прикладывайте файлы скриншотов
![image](https://user-images.githubusercontent.com/9010611/209939835-f6d6371e-fb7b-409d-9ca5-33d4eb08f069.png)

**Comment by oompaloomp** [comment]
Ошибка воспроизводится только после подключения клиента тестирования при работе с ТЧ документа.
Если документ закрыть в подключенном клиенте и снова начать заполнять ТЧ, ошибка не возникает.

**Comment by Pr-Mex** [comment]
@oompaloomp 
Регистрируйте эту ошибку на v8@1c.ru
То, что она воспроизводится только в режиме клиента тестирования не отменяет  того, что это ошибка конфигурации.

**Comment by oompaloomp** [comment]
Почему тогда в подключенном клиенте в новой создаваемой заявке при работе с ТЧ не возникает?

**Comment by 1cgh** [comment]
> Почему тогда в подключенном клиенте в новой создаваемой заявке при работе с ТЧ не возникает?

скорее всего, по-разному с технической точки зрения выполняется ввод значения сценарием и руками. но это не отменяет того, что ошибка в конфе

**Comment by oompaloomp** [comment]
Дак в том то и дело что в подключенном клиенте в обоих случаях вводится сценарием.
При ручном вводе ошибка не воспроизводится.

**Comment by oompaloomp** [comment]
Даже если остановить сценарий перед вводом значения в ТЧ, вести интерактивно и продолжить сценарий, ошибка не появляется.

**Comment by 1cgh** [comment]
> Даже если остановить сценарий перед вводом значения в ТЧ, вести интерактивно и продолжить сценарий, ошибка не появляется.

Вы можете отладить поведение при ручном вводе и при выполнении шага, посмотреть какие из событий платформы вызывается и в чем различия контекста выполнения. А далее уже сделать выводы, где ошибка: в конфигурации / в платформе / в реализации шага / в VA.

**Comment by Pr-Mex** [comment]
> Почему тогда в подключенном клиенте в новой создаваемой заявке при работе с ТЧ не возникает?

Возможно это какая-то особенность данной формы. Но в любом случае такое исключение форма не должна показывать не в каких режимах.

**Comment by oompaloomp** [comment]
Решил проблему правильным позиционированием на ТЧ документа:
И я активизирую поле "ТаблицаЗначений"
Вывод проблема не в конфе.

**Comment by Pr-Mex** [comment]
> Решил проблему правильным позиционированием на ТЧ документа: И я активизирую поле "ТаблицаДвижений" Вывод проблема не в конфе.

Вы путаете причину и следствие. Если конфигурация показывает исключение, которое она не должна показывать - то причина в конфигурации. В каком режиме запущена конфигурация при этом не важно. Если конфигурация не учитывает, что ещё существует АПИ автотестов - это тоже проблема конфигурации.
Вы же нашли обход данной проблемы конфигурации.

**Comment by oompaloomp** [comment]
По моему скромному мнению не конфигурация должна подстраиваться под АПИ, а наоборот.
Хотя как я и сказал, это мое скромное мнение.

**Comment by Pr-Mex** [comment]
> По моему скромному мнению не конфигурация должна подстраиваться под АПИ, а наоборот. Хотя как я и сказал, это мое скромное мнение.

Почему не должна? Если нужно чтобы с формой работали автотесты. Это всё же АПИ платформы 1С:Предприятие.
