### ISSUE TITLE
При создании нового сценария добавить строку с контекстом про открытие testclient

### ISSUE THREAD

**Issue by mors1eska** [Pr-Mex/vanessa-automation#1828]
При создании нового фича-файла нужно добавить текст контекста

`Контекст:
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий`

**Comment by mors1eska** [comment]
<img width="914" alt="image" src="https://user-images.githubusercontent.com/34914654/210170114-cfd02bf5-af3c-4b50-92f6-c58ab0c3d23f.png">

**Comment by mors1eska** [comment]
ПолучитьVanessaEditor().insertText(МодульРедакторТекста().ТекстНовогоСценария(), ЗаписатьОбъектJSON(Соответствие));

Не сильно понимаю, как тут организован код
Смотрю ванесса сингл (может надо не его смотреть?)

В нем поправил в форме (РедакторТекста) текст, но это не влияет ни на что

@Pr-Mex можешь кратко рассказать как это все лучше дорабатывать?

**Comment by Pr-Mex** [comment]
@mors1eska 
Запишите видео с экрана, пожалуйста, при какой последовательности действий вы хотите получить строку в секции Контекст.

**Comment by mors1eska** [comment]
Приложил
https://recordit.co/XSGeO93OUb
чот не тянет обновленный модуль с формы как-будто

**Comment by mors1eska** [comment]
Тут явно мой тупняк, может не сохранил нормально
Все работает

Запулю чуть позже

**Comment by Pr-Mex** [comment]
@mors1eska 
Вижу, что ты нашёл код который добавляет текст новой фичи. Думаю лучше всего сделать настройку, позволяющую читать данный текст из файла. Если настройка не заполнена, то поведение останется таким же как сейчас.
Таким образом любой пользователь сможет настроить под себя текст новой фичи как ему удобно.

**Comment by mors1eska** [comment]
А файл-шаблон каждый пользователь будет для себя сам писать и сохранять?

**Comment by Pr-Mex** [comment]
@mors1eska
Да. Кого не устраивает типовой шаблон - может использовать свой.
В VA надо добавить настройку - путь к файлу шаблона.

**Comment by mors1eska** [comment]
Сделал как-то так https://recordit.co/emgGqWyNlf
Я пока не сильно понимаю как PR отправить, к какой ветке и т.п.
Может так выложишь? =)
Правда, там еще про актуализацию еще есть https://github.com/Pr-Mex/vanessa-automation/issues/1821
но недоделано

**Comment by mors1eska** [comment]
[vanessa-automation-single.epf.zip](https://github.com/Pr-Mex/vanessa-automation/files/10331926/vanessa-automation-single.epf.zip)

**Comment by Pr-Mex** [comment]
@mors1eska 
Давай лучше обычный реквест.
Тут описано как он делается.
https://infostart.ru/public/1092009/

**Comment by mors1eska** [comment]
> @mors1eska Давай лучше обычный реквест. Тут предоставляется как он делается. https://infostart.ru/public/1092009/

Боюсь, я тебя замучаю
В репо не вижу ни папки с исходниками, ни компилированный готовый epf

Я какбы в инструкции вижу русские буквы, но пока не понимаю, что значат команды =))

или просто туториалу следовать?))

Я дорабатывал именно сингл

**Comment by mors1eska** [comment]
Сделал compile не появились обработки =(
<img width="792" alt="image" src="https://user-images.githubusercontent.com/34914654/210250295-b1df1738-0ca6-4275-9d8b-fa759230a314.png">

**Comment by Pr-Mex** [comment]
@mors1eska 
Дорабатывать  надо основной репозиторий. Не Single. 
Если не компилируются обработки - запусти батник из cmd и покажи вывод консоли.

**Comment by mors1eska** [comment]
> @mors1eska Дорабатывать надо основной репозиторий. Не Single. Если не компилируются обработки - запусти батник из cmd и покажи вывод консоли.

Тут не понятно
Вроде как успешно что-то проходит, но где обработки сами не оч понимаю
<img width="987" alt="image" src="https://user-images.githubusercontent.com/34914654/210346431-88ff3e39-60d2-4b73-94ce-03a0e9ab943d.png">

**Comment by mors1eska** [comment]
Или это оно и есть?

**Comment by Pr-Mex** [comment]
@mors1eska 
Ага. Это и есть основная обработка VA.

**Comment by mors1eska** [comment]
> @mors1eska Ага. Это и есть глубокая обработка В.А.

Что-то отправил вроде
https://github.com/Pr-Mex/vanessa-automation/pull/1829
