### ISSUE TITLE
Поправить VAparams

### ISSUE THREAD

**Issue by SvetaShum0vaya** [Pr-Mex/vanessa-automation#1836]
[VAParams.txt](https://github.com/Pr-Mex/vanessa-automation/files/10438436/VAParams.txt)
1. Для чего параметры меняют своё значение при запуске предприятия и командой открытия ванессы?
`ИспользоватьРедакторVanessaEditor `было true сменилось на false
`ВыполнитьСценарии` было false сменилось на true
`ЗавершитьРаботуСистемы `было false сменилось на true
`ЗакрытьTestClientПослеЗапускаСценариев `было false сменилось на true

2. Поправьте пожалуйста имя параметра (так, чтобы это потом ещё и работало :) )
с "ПоказыватьСтрокиПодсценариевVanessaEdittor" на "`ПоказыватьСтрокиПодсценариевVanessaEditor`" (косметика и эстетика)

3. Несмотря на параметр `ПоказыватьМиниатюруКода": false,`, при запуске ванессы через командную строку, и всё же переходе в режим VanessaEditor миниатюра кода всё же показывается. Хотя показываться не должна.
3.1. Несмотря на параметр `"ОтображениеТабуляцииИПробелов": 3,` (отображать всё), при запуске ванессы через командную строку - пробелы и табуляция - не показываются в редакторе. Хотя показываться должны и табы и пробелы. Думаю что это не единственные два параметра из раздела настроек VanessaEditor которые не подтягиваются так как надо в обработку.
PS. чтобы пункты 3 и 3.1. всё же заработали из надо перевыбрать, и для закрепления нажать "Сохранить настройки".

4. Параметр `"ПутьКФайлуДляВыгрузкиСтатусаВыполненияСценариев": "$workspaceRoot\\BuildStatus.log"` при запуске ванессы через командную строку и выгрузке параметров в файл приобретает значение: `"./BuildStatus.log"` а должно быть - путь до этого файла целиком например `"C:\\Users\\Public\\Documents\\BuildStatus.log"`

Ожидается в пунктах 1, 3, 3.1 "как параметры в vaparams прописаны, так они и загрузятся и отработают". Не смотря на запуск из командной строки или через выбор файла обработки через "Открыть файл" в предприятии.

**Comment by Pr-Mex** [comment]
@SOYAllure 
Не понял что происходит с первым пунктом. Расскажи подробнее, пожалуйста.

**Comment by SOYAllure** [comment]
Запустите ванессу из командной строки (с указанием откуда тянутся параметры. Файл параметров приложен ранее)
затем сохраните настройки из UI Ванессы в отдельный файл настроек.

насколько json новый будет совпадать со старым?
у меня в результате есть разнящиеся параметры (которые сменили значения false↔️true)
`ИспользоватьРедакторVanessaEditor `было true
`ВыполнитьСценарии `было false
`ЗавершитьРаботуСистемы `было false
`ЗакрытьTestClientПослеЗапускаСценариев `было false

**Comment by Pr-Mex** [comment]
@SvetaShum0vaya 
Пункт 1 работает правильно, т.к. происходит подготовка файла к запуску из командной строки.

**Comment by Pr-Mex** [comment]
@SvetaShum0vaya 
С остальным постараюсь разобраться.

**Comment by Pr-Mex** [comment]
Решено.
