### ISSUE TITLE
Добавить шаг Я устанавливаю метке "ИмяМетки" значение "ЗначениеМетки"

### ISSUE THREAD

**Issue by 1cgh** [Pr-Mex/vanessa-automation#1839]
Для шага уже есть служебный метод в фиче для установки меток для аллюра.
Предлагаю и сам метод добавить как шаг.
Зачем: можно будет в сценариях задавать произвольные метки со значениями, которые прокинутся в allure.

https://github.com/Pr-Mex/vanessa-automation/blob/23905848196b10a4aa5866e406a8e7be519cdfb1/features/Libraries/allure/step_definitions/%D0%93%D1%80%D1%83%D0%BF%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0%D0%92%D0%90%D0%BB%D0%BB%D1%8E%D1%80/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L108

**Comment by Pr-Mex** [comment]
@1cgh 
Такие шаги вроде уже есть. Но у них не заполнено описание и поэтому они не отображаются в дереве шагов.
Глянешь - это то что надо?
https://github.com/Pr-Mex/vanessa-automation/blob/develop/features/Libraries/allure/step_definitions/%D0%93%D1%80%D1%83%D0%BF%D0%BF%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0%D0%92%D0%90%D0%BB%D0%BB%D1%8E%D1%80/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L26

**Comment by 1cgh** [comment]
@Pr-Mex шаги по фиче/эпику/стори в библиотеке в служебных отображаются. и они задают метки с фиксированными именами. а я про то, чтобы метод, который эти шаги под капотом используют, тоже сделать шагом. тогда можно будет свои метки/значения писать в аллюр.
например, зачем: мне надо в результаты теста передавать дополнительно некоторые значения, которые я получаю из базы во время прогона сценария (у меня есть сценарии, которые гоняются на реальных данных, которые меняются между прогонами). и с помощью такого шага я мог бы в метку записать полученное значение. а при постобработке считать его из результатов тестов.

**Comment by 1cgh** [comment]
ну т.е. код для шага уже есть. надо под него просто строчку в ПолучитьСписокТестов добавить

**Comment by Pr-Mex** [comment]
@1cgh 
Ок, давай

**Comment by Pr-Mex** [comment]
Решено.
