### ISSUE TITLE
Ванесса не ругается если есть два экспортных сценария с одним названием

### ISSUE THREAD

**Issue by tsukanov-as** [Pr-Mex/vanessa-automation#184]
ver. 1.2.0.19 Vanessa Automation Single

Основная спецификация:
```Gherkin
#language: en

Feature: test

Background:
	Given I launch TestClient opening script or connect the existing one

Scenario: Test
	And I say "foo"
	And I say "bar"
```

Дополнительная спецификация с экспортным сценарием №1
```Gherkin
#language: en

@ExportScenarios

Feature: export test

Scenario: I say "foo"
    Then I raise "foo" exception
```

Дополнительная спецификация с экспортным сценарием №2 
```Gherkin
#language: en

@ExportScenarios

Feature: export test

Scenario: I say "bar"
    And Delay "bar"
```

При загрузке основной спецификации в GUI Ванессы такая картина: https://i.imgur.com/n0I2dWY.png
и никаких сообщений.

Наверно ошибка должна выдаваться

**Comment by Pr-Mex** [comment]
Согласен.

**Comment by Pr-Mex** [comment]
Решено.
@tsukanov-as 
Просьба проверить.
