### ISSUE TITLE
Если в регистре сведений у измерений нет Ведущий, то ОбменДанными.Загрузка=Истина не работает 

### ISSUE THREAD

**Issue by astrizhachuk** [Pr-Mex/vanessa-automation#1849]
Для случаев, когда нет ведущего у измерений, мы попадаем в ветку  с записью через менеджер записи, где нет свойства обмена данными. Эта проверка нужна? Может подавлять работу через менеджер записи принудительно, если при вызове метода DataExchangeLoad=True?

https://github.com/Pr-Mex/vanessa-automation/blob/2e74af36549bc9cc90f79007cae9dcd33c9cb1c9/VanessaAutomation/Forms/%D0%9F%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BA%D0%B0%D0%98%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0%D0%94%D0%B0%D0%BD%D0%BD%D1%8B%D1%85/Ext/Form/Module.bsl#L864

**Comment by Pr-Mex** [comment]
Решено.
