### ISSUE TITLE
Непонятное поведение. Экранированная кавычка в параметре

### ISSUE THREAD

**Issue by tsukanov-as** [Pr-Mex/vanessa-automation#185]
ver. 1.2.0.19 Vanessa Automation Single

Основная спецификация:

```Gherkin
#language: en

Feature: test

Background:
	Given I launch TestClient opening script or connect the existing one

Scenario: Test
	And I say "fo\'o"
	Then I raise "fo\'o" exception
```

Дополнительная спецификация с экспортным сценарием:

```Gherkin
#language: en

@ExportScenarios

Feature: export test

Scenario: I say "fo\'o"
    Then I raise "fo\'o" exception
```

Если загрузить основную спецификацию в GUI Ванессы то будет такая картина: https://i.imgur.com/PJoSFIa.png

Не знаю ошибка или нет. Но ругань на кавычку в параметре экспортного сценария помогла бы избежать казуса.

**Comment by Pr-Mex** [comment]
Это ошибка. Будем исправлять.

**Comment by Pr-Mex** [comment]
Решено.
@tsukanov-as 
Просьба проверить.
