### ISSUE TITLE
Ошибка запуска VA на конфигурации ТопЛог

### ISSUE THREAD

**Issue by alkoleft** [Pr-Mex/vanessa-automation#1850]
Укажите:
   1. Версия Vanessa Automation: 1.2.039

Есть отраслевая конфигурация, которая имеет глобальный метод "СтруктураОшибки", он конфликтует с методом VA и не позволяет ее использовать.

> Прикладывайте файлы скриншотов

![image](https://user-images.githubusercontent.com/13838250/217523910-ccdaf169-8529-4f6b-8749-0a3dcfdd5cab.png)

**Comment by Pr-Mex** [comment]
Решено.
