### ISSUE TITLE
Ошибка при передаче таблицы в подсценарий, который является структурой сценария

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1852]
Версия Vanessa Automation 1.2.040.1
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Пытался разобраться, как из основного сценария вызвать подсценарий, в который передам таблицу геркин, и в подсценарии по ней будет что то сделано, например, в табличную часть документа загрузятся данные.
В итоге в подсценарий таблицу передаю, а как ее на стороне подсценария обойти - не понятно даже из видео ванессы), по крайней меря я не понял как сделать для моего примера. Если есть возможность, подскажите как 
в итоге, попытался передать таблицу в структуру сценария, но такое выполнение работает некорректно. Сценарий выполняется успешно, но на клиенте не то, что мы задали в таблице и в строке сообщений ошибка парсера геркин

![image](https://user-images.githubusercontent.com/19662685/218106693-63e1097b-b888-4650-8c62-eee5742e2788.png)

Базу и настройки можно взять [тут](https://disk.yandex.ru/d/ZFQhTNyV_qit3Q)

Фичу [тут](https://disk.yandex.ru/d/aa67P_Kor5nysw)

**Comment by akademik1986** [comment]
Если подсценарий вынести в отдельный фича файл, то количество строк в документе  равно количеству строк в переданный таблице, а вот наполнение не то
![image](https://user-images.githubusercontent.com/19662685/218115924-6364b50c-1041-47f7-ad02-67c04e843491.png)

**Comment by akademik1986** [comment]
на всякий случай
![image](https://user-images.githubusercontent.com/19662685/218117648-44e4c8a0-ecf9-4fdf-a52d-ff1e47f3e024.png)

**Comment by Pr-Mex** [comment]
@akademik1986 
Сделал пример как такое решается
[КакНадо.zip](https://github.com/Pr-Mex/vanessa-automation/files/11481537/default.zip)

**Comment by akademik1986** [comment]
@Pr-Mex спасибо, я так и использую экспортные шаги с передачей таблицы. 
Но смысл данного использования был немного другой. 
Есть например у меня структура сценария, которая в примерах описывает разное заполнение документа при его создании.
Я хотел вызвать эту структуру сценария для создания документа по одному из примеров , и передать таблицу идентичную примеру структуры сценария. Ожидал, что таблица примеры в структуре сценария заменится на передаваемую таблицу.

**Comment by Pr-Mex** [comment]
@akademik1986 
В этом случае неверно сработал парсер из компоненты. Я зарегистрировал проблему
https://github.com/lintest/VanessaExt/issues/74
