### ISSUE TITLE
Ошибка при вызове метода контекста (СоздатьКаталог)

### ISSUE THREAD

**Issue by VladFrost** [Pr-Mex/vanessa-automation#1853]
```Gherkin
Функциональность: База
   Как пользователь Vanessa Automation
   Я хочу начать работать с Vanessa Automation

Контекст:
  Дано: Версия Vanessa Automation 1.2.040.1
  И Версия платформы 8.3.20.2184
  И Режим совместимости базы, где запускается Vanessa Automation 8.3.17
  И Операционная система Microsoft Windows [Version 10.0.19045.2486]

Сценарий: Запуск фреймворка тестирования vanessa-automation
  Допустим: Я выполняю команду системы opm install vanessa-automation
  и существует файл C:\Program Files\OneScript\lib\vanessa-automation\vanessa-automation.epf
  Когда: Я открываю файл C:\Program Files\OneScript\lib\vanessa-automation\vanessa-automation.epf
  Тогда: Запускается фреймворк тестирования 
```

Результат:
```
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(13644)}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка создания каталога: Ошибка доступа к файлу 'C:\Program Files\OneScript\lib\vanessa-automation\VAEditorCacheFiles'. 5(0x00000005): Отказано в доступе. 
C:\Program Files\OneScript\lib\vanessa-automation\VAEditorCacheFiles\1.3.6.2
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(13647)}:ВызватьИсключение ТекстОшибки + Символы.ПС + ИмяФайла;
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(49294)}:СоздатьКаталогКомандаСистемы(VanessaEditorКаталог);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(25370)}:ИнициализироватьVanessaEditorUrl(БылоИзменениеUrl);
```

![Картинка](https://user-images.githubusercontent.com/11960251/218131191-8a75f26e-7b49-4ba0-9137-45c47e7eb00d.png)

**Comment by 1cgh** [comment]
Возможно, стоит уточнить, что пользователь ОС, под которым идет запуск, не имеет прав на запись в Program Files, т.е. не админ, например

**Comment by VladFrost** [comment]
@lintest подскажи, пожалуйста, почему папка для кеша создаётся в каталоге инструментов?
https://github.com/Pr-Mex/vanessa-automation/commit/8f535699f4039300fbcc9ef6eae5436ad6f13b38#diff-149cfe06fc249005849e209db050f79b273ff500f017cd8a0f4353f75ac1d879R49179

При этом есть ситуации, когда папка для кэша создаётся во временной папке
https://github.com/Pr-Mex/vanessa-automation/commit/8f535699f4039300fbcc9ef6eae5436ad6f13b38#diff-149cfe06fc249005849e209db050f79b273ff500f017cd8a0f4353f75ac1d879R49187

Не понятно, почему нужно разное поведение.

**Comment by Pr-Mex** [comment]
@VladFrost 
Эту папку выбрал я. Т.к. программ может создавать файлы в своём каталоге.

**Comment by Pr-Mex** [comment]
@VladFrost 
Временный каталог используется, когда не получается определить каталог VA.

**Comment by Pr-Mex** [comment]
Решено.
