### ISSUE TITLE
Возможность передачи в Allure дополнительных тегов

### ISSUE THREAD

**Issue by fenixnow** [Pr-Mex/vanessa-automation#1858]
Необходимо иметь возможно передавать в отчет аллюр служебных тегов, по аналогии как это есть в Java

В Allure есть возможность аннотировать тест специальными тегами
@owner
@Issue
@Link
@Description
и тд

Необходимо добавить соответствующий функционал в VA

**Comment by fenixnow** [comment]
![image](https://user-images.githubusercontent.com/13418562/218486100-4d1de3ec-649d-42bb-a408-7f5bc7162307.png)
Эти данные может отдавать Ваннесса для отчета Allure

**Comment by KrapivinAndrey** [comment]
Если не ошибаюсь - есть же шаги "И я устанавливаю метку"

**Comment by fenixnow** [comment]
> Если не ошибаюсь - есть же шаги "И я устанавливаю метку"

Возможно и есть. Но концептуально метки ставятся на всю фичу или сценарий. Метки это не шаги сценария, это сервис к сценарию не относящийся

**Comment by Pr-Mex** [comment]
Решено.
