### ISSUE TITLE
Лишнее действие (активация) в шаге нажатия кнопки выбора

### ISSUE THREAD

**Issue by tsukanov-as** [Pr-Mex/vanessa-automation#186]
ver. 1.2.0.19 Vanessa Automation Single

Сейчас реализация шага выбора выглядит так:
```bsl
Процедура ВОткрытойФормеЯНажимаюКнопкуВыбораУПоляСЗаголовком(ИмяРеквизита,ИскатьПоИмени = Ложь) Экспорт
	Ванесса.ОбработатьСменуАктивногоОкна();
	
	Поле = Ванесса.НайтиРеквизитОткрытойФормыПоЗаголовку(ИмяРеквизита, ИскатьПоИмени, Истина, Тип("ТестируемоеПолеФормы"));
	Если Поле = Неопределено Тогда
		Если ИскатьПоИмени Тогда
			ТекстСообщения = Ванесса.ПолучитьТекстСообщенияПользователю("Поле с именем <%1> не найдено.");
		Иначе	
			ТекстСообщения = Ванесса.ПолучитьТекстСообщенияПользователю("Поле с заголовком <%1> не найдено.");
		КонецЕсли;	 
		ТекстСообщения = СтрЗаменить(ТекстСообщения,"%1",ИмяРеквизита); 
		
		ВызватьИсключение ТекстСообщения;
	КонецЕсли;	 
	
	Поле.Активизировать(); // <-------------
	СделатьДействияПриЗаписиВидео();
	СделатьДействияПриЗаписиHTML();
	Поле.Выбрать();
КонецПроцедуры
```

Эта активация перед нажатием кнопки выбора может доставить (и уже) проблем.
Т.к. на активации может висеть какая-то логика и шаг может не сработать, или сработать не так как ожидается.

Как минимум, хотелось бы где-то видеть информацию о том, что шаг делает больше чем кажется по его наименованию.

**Comment by Pr-Mex** [comment]
Активизация кнопок и полей была сделана для автоинструкций. Это позволяло подсветить поле перед тем как с ним произойдёт какое-либо действие.
Предлагаю описать эту особенность поведения в описании шага.

**Comment by tsukanov-as** [comment]
Да, я понимаю зачем было сделано.

> Предлагаю описать эту особенность поведения в описании шага.
Думаю пойдет.

**Comment by Pr-Mex** [comment]
Решено оставить как работает сейчас.
