### ISSUE TITLE
Простановка меток времени в feature - файл

### ISSUE THREAD

**Issue by benadis** [Pr-Mex/vanessa-automation#1871]
Укажите:
   1. Версия Vanessa Automation
   2. Версия платформы
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система

> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Возможность добавления при конвертации ЖурналаДействийПользователя в feature - файл комментария с указанием текущего времени в момент записи действий пользователя.
   Как аналитик большого массива автоматически записанных ЖДП.
   Я хочу иметь возможность синхронизировать по времени действия пользователей из разных ЖДП.

Контекст:
  Дано: Vanessa Automation 1.2.040.1
  И полная версия 1С 8.3.20.2184
  и 1С:ERP Управление предприятием 2 (2.5.8.329)

Сценарий: Простановка меток времени в feature - файл
  Допустим: Файл ЖДП.xml содержит специальную метку<!-- <ВремяНачала> 02.02.2023 9:25:32 <ВремяОкончания> 02.02.2023 9:36:21 -->
  Когда: Конвертор находит в файле ЖДП.xml специальную метку
  Тогда: Конвертор записывает в feature - файл комментарий вида: //ТекущееВремя 02.02.2023 9:36:21

```

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
@benadis 
Расскажите подробнее какую задачу решаете, пожалуйста

**Comment by benadis** [comment]
Создал расширение, которое при подключении к любой базе с конфигурацией у которой версия совместимости выше 8.3.16 записывает ЖДП всех пользователей которые отмечены для записи ЖДП.
Запись ведется с периодичностью указанной при начале записи сессии пользователя (по умолчанию 10 минут).
На выходе получаются xml файлы в которых записаны 10 минутные куски журнала работы пользователя в рамках каждой из записываемых сессий.
Файлы склеиваются в один файл для каждой сессии, в места склейки вставляется комментарий вида:

Эти файлы пакетно конвертируются в feature файлы с помощью немного доработанной Ванессы.
В результате получаем feature-файлы полных сессий работы пользователей в конкретной базе, которые можно анализировать.
Проблема заключается в том что нельзя сопоставить по времени действия выполняемые в одной сессии с действиями выполняемыми в другой сессии или записями в журнале регистрации. Для сессии имеем время начала и время окончания сессии, при этом некоторые сессии продолжаются по несколько дней.
Если добавить внутри feature-файла метку текущего времени, оперирую периодом записи ЖДП можно довести точность синхронизации действий например до минуты.
Велосипедить рабочую конвертацию в Ванессе под себя, внося изменения после каждого обновления, считаю плохим вариантом.
В данный момент собрано около 1 800 сессий для 2 баз ERP, в одной базе 100 одновременно работающих пользователей, в другой около 70.

**Comment by benadis** [comment]
Вставка образца комментария не показалась на новой строке.
Попробую так:

**Comment by Pr-Mex** [comment]
@benadis 
Ок, стало понятнее.
1. Не понял в чем проблема вставить в фича файл произвольный комментарий.
2. Эти фича файлы потом предполагаются для запуска? Или что с ними потом предполагается делать?

**Comment by benadis** [comment]
1. Вставка должна производиться в конкретных местах фича-файла на основе содержимого xml, для реализации этого прийдется залезать в процедуру конвертации и при обновлении ванессы иметь проблемы. Если добавить в конвертацию обработку комментариев (вставлять текст комментария в фича-файл), то можно добавлять нужные данные в исходный ЖДП и потом анализировать их в фича-файле без танцев с бубном. Думаю найдутся применения помимо простановки отметок времени.
2. Фича-файлы предполагается использовать:
- в качестве исходных данных для тестирования используемого функционала
- для анализа того что именно используется в конфигурации (для ERP это реальная проблема)
- для выработки рекомендаций/инструкций и отслеживания следования этим инструкциям.
Надеюсь в дальнейшем список расширится.

**Comment by Pr-Mex** [comment]
@benadis 
Можно посмотреть пример полученного фича файла?

**Comment by benadis** [comment]
По ссылке архив с исходным xml и результатом конвертации в фича-файл:
https://disk.yandex.ru/d/qxgf4m6d6DdWRw
Замечу что 63 строка исходного xml в фича-файле никак себя не проявила.

**Comment by Pr-Mex** [comment]
@benadis 
1. По тегу setFileDialogResult посмотрю.
2. Насчет вставки комментария - предлагаю ввести ещё один тег вида
	<comment>Текст комментария</comment>
Такие строки будут вставляться в фича файл так
//Текст комментария
3. Можете выложить ваше расширение?

**Comment by benadis** [comment]
2. Что-то типа:
 -xml
<Comment> Нужный текст для вставки в фича-файл </Comment>
-feature
//Нужный текст для вставки в фича-файл

По ссылке 2 версия логгера:
https://disk.yandex.ru/d/hNFh3fW7ZhzRjA
В разработке 3 версия с переходом на централизованный сбор логов с передачей данных при подключении через HTTP-сервисы.
В планах 4 версия с отказом от 1С в сборщике журналов.

**Comment by Pr-Mex** [comment]
> 2. Что-то типа:
>    -xml
>     Нужный текст для вставки в фича-файл 
>    -feature
>    //Нужный текст для вставки в фича-файл
> 

@benadis 
Не вставился пример с первого раза.
Тег вида:
```xml
<comment>Текст комментария</comment>
```

**Comment by Pr-Mex** [comment]
@benadis 
Это станет строкой в фиче
//Текст комментария

**Comment by benadis** [comment]
Отлично, когда примерно можно ждать реализации?

**Comment by Pr-Mex** [comment]
> Отлично, когда примерно можно ждать реализации?
Это недолго. Сделаю на неделе.

**Comment by Pr-Mex** [comment]
@benadis 
Сделал в рамках #1880
Доступно в ветке develop.

**Comment by Pr-Mex** [comment]
@benadis 
Можете статью написать, например на Инфостарте, о том как вы применяете ваш подход для сбора ЖДП и анализа результатов?

**Comment by benadis** [comment]
> @benadis Сделал в рамках #1880 Доступно в ветке develop.

Спасибо, разгребу завалы на работе и протестирую.

**Comment by benadis** [comment]
> @benadis Можете статью написать, например на Инфостарте, о том как вы применяете ваш подход для сбора ЖДП и анализа результатов?

Статью имеет смысл писать после перехода на 3 версию логгера (на http-сервисах), сейчас область применения сильно ограничена требованием минимальной версии совместимости конфигурации (8.3.16).
К тому-же нужно сделать хотя бы заготовку анализатора логов, чтобы показать как их можно анализировать и какие выгоды из этого использования извлечь.

**Comment by Pr-Mex** [comment]
@benadis 
Хорошо. Было бы очень интересно почитать об обзоре технологии и о результатах.

**Comment by benadis** [comment]
Добрый день.
Наконец появилось время проверить добавленный функционал, проверил, все работает.
Отдельное спасибо за setFileDialogResult.

**Comment by Pr-Mex** [comment]
@benadis 
Отлично!
