### ISSUE TITLE
Добавить шаг для выполнения запроса 1с

### ISSUE THREAD

**Issue by MaratDevOps** [Pr-Mex/vanessa-automation#1872]
Функционал: Возможность получать список данных по параметрам с помощью запроса на языке 1С
   Как разработчик тестов
   Я хочу найди список документов на проведение которых наложено ограничение по определенным параметрам выбрать первый из них и попытаться провести его.

**Comment by 1cgh** [comment]
Уже есть шаги для выполнения кода встроенного языка, в т.ч. и произвольных запросов.

**Comment by MaratDevOps** [comment]
Вот такой например?
И я выполняю код встроенного языка
"""bsl
    Сообщить("Hello world.")
""" 
а как передать список параметров?
и получить таблицу значений?

**Comment by 1cgh** [comment]
https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/MainHelp/1.2.040.1/%D0%93%D0%BB%D0%B0%D0%B2%D0%B006/%D0%9A%D0%B0%D0%BA%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D0%9F%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D1%83%D1%8E%D0%94%D0%BB%D1%8F%D0%92%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F%D0%9D%D0%B0%D0%A1%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%B5.MD

**Comment by MaratDevOps** [comment]
Благодарю!

**Comment by MaratDevOps** [comment]
Здесь в примере описывается как передать переменную.
А есть описание как передать или массив значений или ТЗ?

**Comment by Pr-Mex** [comment]
> Здесь в примере описывается как передать переменную. А есть описание как передать или массив значений или ТЗ?

@MaratDevOps 
Ванесса.Объект.ЗначениеНаСервере = Новый Массив;

**Comment by MaratDevOps** [comment]
спасибо

**Comment by Pr-Mex** [comment]
@MaratDevOps 
Но лучше создать свой шаг.
