### ISSUE TITLE
Параметр "КаталогФич" не заполняется при сохранении настроек (Настройки - "Выгрузить настройки в файл") в файл из главной формы (Файл открыть Ванесса.epf) Ванессы, если не открыт ни один фича файл. (Использование BAT файлов)

### ISSUE THREAD

**Issue by workd1ts** [Pr-Mex/vanessa-automation#1888]
Полное описание проблемы:
Если Ванесса запускается из батника, тогда сценарии для выполнения определяются из параметра "КаталогФич".
Параметр "КаталогФич" не заполняется при сохранении настроек (Настройки - "Выгрузить настройки в файл") в файл из главной формы (Файл открыть Ванесса.epf) Ванессы, если не открыт ни один фича файл.
Чтобы в параметр "КаталогФич" записался каталог необходимо открыть другую форму Ванессы (Кнопка "загрузить фичи" - "загрузить фичи из каталога" - Выбрать каталог - В открывшейся форме нажать на шестеренку - "Выгрузить настройки в файл").
После выполнения этих действий выбранный каталог будет записан в параметр "КаталогФич" в файле VAParams.json.

Хотелось бы в параметр "КаталогФич" в файле VAParams.json при сохранении из главной формы записывался путь к каталогу проекта из настроек или выбранный путь из дерева каталогов, если не открыт ни один фича файл.

   1. Версия Vanessa Automation 1.2.040.1
   2. Версия платформы 1С:Предприятие 8.3 (8.3.21.1393)
   3. Режим совместимости базы, где запускается Vanessa Automation Версия 8.3.18
   4. Операционная система Windows

```Gherkin
Функционал:  Запуск сценариев для выполнения с помощью BAT файла.
   Я хочу чтобы в параметр "КаталогФич" в файле VAParams.json при сохранении из главной формы записывался путь к каталогу проекта из настроек или выбранный путь из дерева каталогов, если не открыт ни один фича файл.

Контекст:
  Самописная конфигурация IRP (2021.43.2644) (https://github.com/IRPTeam/IRP) IRP Team


Сценарий:  Заполнение параметра "КаталогФич" в файле VAParams.json при сохранении из главной формы
  Когда: при сохранении настроек (Настройки - "Выгрузить настройки в файл") в файл из главной формы (Файл открыть Ванесса.epf) Ванессы, если не открыт ни один фича файл.
  Тогда: Параметр "КаталогФич" в выгружаемом файле VAParams.json не заполнен.
```

![ВанессаГлавнаяФорма](https://user-images.githubusercontent.com/123542850/222690956-184f01e0-7e10-4312-af22-0499981cae0b.jpg)

**Comment by Pr-Mex** [comment]
@workd1ts 
Да, думаю можно такое сделать.

**Comment by Pr-Mex** [comment]
@workd1ts 
Убрал из заголовка "Баг", т.к. это не ошибка.

**Comment by Pr-Mex** [comment]
Решено.
