### ISSUE TITLE
Руководство контрибьютора ведёт на несуществующую страницу в ветках develop и master

### ISSUE THREAD

**Issue by VladimirLitvinenko84** [Pr-Mex/vanessa-automation#189]
Попытка открыть ссылку на файл CONTRIBUTING.md в ветках master и develop приводит к ошибке 404:

![contributing](https://user-images.githubusercontent.com/24396934/52661110-4f6d7100-2f12-11e9-8145-63a51d692bb4.png)

**Comment by Pr-Mex** [comment]
Спасибо. Исправим.

**Comment by VladimirLitvinenko84** [comment]
@Pr-Mex 
Нет ли возможности сделать подробное руководство контрибьютора с иллюстрациями? Для чайников )) Продемонстрировать на примере решения **любой задачи или бага** как поучаствовать в разработке. Как правильно сделать пул-реквест и какой информацией и/или тестами должен сопровождаться пул-реквест. Сейчас довольно высокий порог входа в контрибьютинг даже для тех, кто пользуется инструментами.

**Comment by Pr-Mex** [comment]
@VladimirLitvinenko84 
Такое руководство конечно нужно.
Я подумаю как это лучше оформить.

**Comment by Pr-Mex** [comment]
Решено.
