### ISSUE TITLE
Ошибка при актуализации таблицы Gerkin в шаге "Тогда табличный документ "Результат" содержит строки"

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1899]
Версия Vanessa Automation 1.2.0.49.1
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

При попытке актуализировать значение таблицы Gerkin  в шаге "Тогда табличный документ "Результат" содержит строки" будет выдана ошибка
Итератор для значения не определен
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(38552)}:Для каждого Элем Из СтрТЧ Цикл
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(50856)}:МассивСтрокТаблицыИзСценария = _СтрРазделить(СокрП(ПолучитьСтрокуСТЧФормаTestClient(ДанныеДляАктуализации.ТаблицаТекущееЗначение, НужныеКолонки)), Символы.ПС);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(50837)}:АктуализироватьТаблицуGherkinПоДаннымОшибкиВРедактореПродолжение2(МассивСтрокТаблицыИзСценария, НомерПервойСтрокиТаблицы, ДанныеДляАктуализации);
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(50727)}:АктуализироватьТаблицуGherkinПоДаннымОшибкиВРедакторе(глДопПараметры.НомерСтрокиВФиче, глДопПараметры.ПроизвольныеЗначения);

Если же использовать шаг  "Тогда табличный документ "Результат" равен" , то в этом шаге актуализация выполняется
Фича и база приложены [тут](https://disk.yandex.ru/d/3ohOvcKIsCriGQ)

**Comment by Pr-Mex** [comment]
@akademik1986 
Решено. Проверь, пожалуйста
