### ISSUE TITLE
Актуализация таблицы Gerkin по ошибке

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1900]
Версия Vanessa Automation 1.2.0.49.1
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Просьба при актуализации по ошибке таблицы Gerkin не заменять значения в таблице локальной или глобальной переменной, пропускать их как и шаблон

**Comment by Pr-Mex** [comment]
@akademik1986 
Не понял про что ты. Расскажи подробнее.

**Comment by akademik1986** [comment]
@Pr-Mex например, имеем в фиче такой шаг с таблицей gerkin
	И я нажимаю на кнопку с именем 'ФормаСформировать'
	Тогда табличный документ "Результат" равен:
		| 'Товар'                              | 'Большой'                    |
		| ''                                        | 'Количество Остаток' |
		| '$НоменлатураОсобая$' | '-2,00'                           |
		| 'Bosch*'                          | '1,00'                             |

При актуализации таблицы значение в колонке Товар со значением  'Bosch*' не заменится, так как это шаблон, однако параметризуемое значение  '$НоменлатураОсобая$' заменится, а хотелось бы, чтобы тоже осталось неименным

**Comment by Pr-Mex** [comment]
@akademik1986 
Решено. Проверь, пожалуйста
