### ISSUE TITLE
Добавить развернутый ответ при указании "Тэги для запуска"

### ISSUE THREAD

**Issue by TheJustPvP** [Pr-Mex/vanessa-automation#1905]
Полное описание проблемы:
на вкладке Сервис - Основные - если установить "Тэги для запуска" и после этого не указать тэг в фиче, то при запуске фичи - ванесса выдает сообщение "Выполнение сценариев закончено. БЫЛИ ОШИБКИ.". Предлагаю добавить развернутый ответ, указывающий на то, что заполнен "Тэги для запуска", которые не установлены в фиче. Убил 30 минут на то, чтобы понять в чем дело и почему фича не может запуститься) 

Укажите:
   1. 1.2.040.9
   2. 8.3.19.1770
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Windows

> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Добавить более развернутый ответ при ошибке
   Как пользователь
   Я хочу ускорить процесс поиска ошибки


Сценарий: Дополнить базу ответов при возникновении ошибок
  Допустим: мы указали "Тэг для запуска"
  Когда: Нажимаю "Выполнить", чтобы выполнить фичу
  Тогда: Высвечивается сообщение "Выполнение сценариев закончено. БЫЛИ ОШИБКИ."
  Должно быть: Служебное сообщение, которое указывает, на заполненность "Тэг для запуска", которого нет в фиче.

**Comment by TheJustPvP** [comment]
К сожалению, не обладаю навыками разработчика) так бы с радостью)

**Comment by Pr-Mex** [comment]
Решено.
