### ISSUE TITLE
Не стабильная работа шага "И Я устанавливаю фильтр на список"

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1915]
Версия Vanessa Automation 1.2.040.9
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Периодически при разборе ночного прогона встречаю в разных тестах падение на шаге "И Я устанавливаю фильтр на список" с комментарием, что "Кнопка с именем <*ListSettings> не найдена."
![image](https://user-images.githubusercontent.com/19662685/230553651-289ca6a6-936e-4427-95aa-941fdbbd0799.png)

Посмотрел код этого шага, данная ошибка возникает, если шаг не смог достучаться до кнопки русского интерфейса. Хотя интерфейс у меня русский. И перед этим успешно выполнен шаг "Тогда открылось окно "Документы по договору". Количество попыток в настройках равно 3.
![image](https://user-images.githubusercontent.com/19662685/230554348-8bf9f014-f5af-4fae-b01f-4471f5e94f11.png)

**Comment by akademik1986** [comment]
Да, при ручном прогоне тоже иногда падает этот шаг, но при повторном запуске успешно выполняется, поэтому не сильно мешает, чего конечно нельзя сказать о ночных тестах)

**Comment by Pr-Mex** [comment]
@akademik1986 
Странно. Получается что не была найдена кнопка "*НастройкаСписка"
А если перед установкой фильтра принудительно проверить что такая кнопка точно есть?

**Comment by akademik1986** [comment]
@Pr-Mex  а что это даст? Оттянет время выполнения шага "И Я устанавливаю фильтр на список" ? Тогда будет падать шаг проверки наличия кнопки) 
После перезапуска кнопка находится, то есть тут возможно проблема отображения некешированной формы, но странно,что шаг открытия окна прошел и еще 3 раза пытался до кнопки достучаться... Скриншот в ошибке показывает полную доступную форму.

**Comment by 1cgh** [comment]
@akademik1986 на момент выполнения шага нажатия на кнопку, кнопка еще могла "не отрисоваться".
На момент снятия скриншота уже может быть на экране.
Добавление проверки может помочь, потому что явно проверяем наличие кнопки (с ожиданием) до нажатия.

**Comment by akademik1986** [comment]
@1cgh 
Ну вот как то не хотелось тесты нагружать лишним проверочным шагом. Может эту проверку можно заложить в шаг "И Я устанавливаю фильтр на список".

**Comment by 1cgh** [comment]
@akademik1986 так добавьте эту проверку в И я устанавливаю фильтр на список. Это экспортный сценарий.
Проверьте у себя, что добавление проверки помогает. Если помогает, то можно самостоятельно сделать PR по доработке этого шага-сценария. Либо отписать сюда, что помогло.
Если не помогает, то проблема в чем-то другом и надо дальше расследовать.

**Comment by akademik1986** [comment]
Добавил ожидание доступности кнопки, падает все равно не на доступности, а  при нажатии на кнопку. 
Ванессу перезапускал.
![image](https://user-images.githubusercontent.com/19662685/234560412-41792f72-07e5-44bf-9166-689465e20253.png)

**Помогло добавление проверки существования кнопки!**
КнопкаСИменемСуществует("*НастройкаСписка", Истина);
Однако, я не знаю, как локализовать для "en"
@Pr-Mex  можешь этот вариант посмотреть и доработать нормально?
Для поиска - 
Функция ЯУстанавливаюФильтрНаСписок(ТабПарам, ЕслиЭтоВозможно = Ложь) Экспорт
	
	ТекЯзык = "ru";
	КнопкаСИменемСуществует("*НастройкаСписка", Истина);
	Элемент = Ванесса.НайтиРеквизитОткрытойФормыПоЗаголовку("*НастройкаСписка",Истина, Ложь);

![image](https://user-images.githubusercontent.com/19662685/234560485-ab136b01-1440-46a6-b1b7-1d2f5896c013.png)

**Comment by Pr-Mex** [comment]
@akademik1986 
Именно по наличию кнопки с именем *НастройкаСписка и принимается решение о языке.
Ты точно перед вызовом шага "И я устанавливаю фильтр на список" проверяешь, что список уже открылся?

**Comment by akademik1986** [comment]
А нельзя свойство конфигурации дергать "Основной язык"?

**Comment by Pr-Mex** [comment]
@akademik1986 
Покажи скриншот, пожалуйста - что там такое крутится?

**Comment by akademik1986** [comment]
![image](https://user-images.githubusercontent.com/19662685/235089630-b9872c0c-dc97-4d4a-8a95-c415b8aae417.png)
вот это имею ввиду, окно вроде бы открыто, но форма еще не прогрузилась

**Comment by Pr-Mex** [comment]
@akademik1986 
Попробуй добавить шаг - ожидания завершения фоновых заданий.

**Comment by Pr-Mex** [comment]
@akademik1986 
Шаг установки фильтра на список предполагает, что список уже сформирован.
Думаю проверку на то, что список сформирован лучше переложить на другие шаги.
Ещё, можно проверить, что в списке количество строк больше нуля, например.

**Comment by akademik1986** [comment]
Понял, спасибо, закрываю issue
