### ISSUE TITLE
Некорректное отображение шагов в аллюре при использовании шагов цикла

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1916]
Версия Vanessa Automation 1.2.040.9
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Например, есть простой сценарий.

Сценарий: Создание реализации по правой кнопке
	* Проверяем создание документа по правой кнопке мыши
		И В командном интерфейсе я выбираю 'Продажи' 'Реализация (акты, накладные, УПД)'
		Тогда открылось окно 'Реализация (акты, накладные, УПД)'
		И я выбираю пункт контекстного меню с именем 'СписокКонтекстноеМенюСоздать' на элементе формы с именем "Список"
		И я запоминаю значение таблицы "СписокВидовОпераций" как "ПерСписок"
		И я закрываю текущее окно		
		И для каждого значения "Стандартный" из таблицы в памяти "ПерСписок"
			И я выбираю пункт контекстного меню с именем 'СписокКонтекстноеМенюСоздать' на элементе формы с именем "Список"
			Тогда открылось окно 'Форма документа'
			И в таблице "СписокВидовОпераций" я перехожу к строке
					| 'Представление' |
					| '$Представление$' |
			И в таблице "СписокВидовОпераций" я выбираю текущую строку
			Попытка	
				Тогда открылось окно 'Реализация*'
			Исключение 
				@screenshot
				И я регистрирую ошибку "Ошибка создания документа" по данным исключения	
			И я закрываю текущее окно

Ожидается, что данный сценарий соберет все ошибки при открытии всех видов операций создания РТУ, однако падает на первой ошибке (хотя она не одна) и дальше не продолжается обход. Почему? Нужно добавить шаг "И я продолжаю цикл" ? Вроде и без него же должен был продолжить?
Ну и главная причина заведения ошибки - некорректное отображение шагов в аллюр
![image](https://user-images.githubusercontent.com/19662685/230563313-b08ffc62-8200-4c89-9d93-f5b23ba3a226.png)

**Comment by Pr-Mex** [comment]
@akademik1986 
Приложи, пожалуйста, базу, сценарий и файл настроек VA чтобы можно было у себя локально повторить.

**Comment by akademik1986** [comment]
ссылку на пример с фичей и базой кину в телеграм

**Comment by Pr-Mex** [comment]
Решено.

**Comment by Pr-Mex** [comment]
@akademik1986 
Давай проверим тоже самое на 1.2.040.20
