### ISSUE TITLE
Постоянная ссылка на последнгий релиз ванессы

### ISSUE THREAD

**Issue by zeegin** [Pr-Mex/vanessa-automation#193]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Автоматическая загрузка ванессы с гитхаба

Контекст:
  Дано: Я программа которая хочет загрузить ванессу с гитхаба

Сценарий: При формировании ссылке на загрузку
  Когда: я формирую ссылку на загрузку
  Тогда: я не хочу извращаться с вычислением номера версии в имени файла архива
  Когда: я выполняю команду загрузки
  Тогда я хочу чтобы на последний релиз была постоянная ссылка
```

Например так будет выглядеть команда загрузки без номера версии.
```cmd
curl https://github.com/Pr-Mex/vanessa-automation/releases/latest/download/vanessa-automation-single.zip -o vanessa-automation-single.zip
```

![default](https://user-images.githubusercontent.com/729213/53382539-b31d8280-3985-11e9-929b-09411a2bc38c.png)

**Comment by asosnoviy** [comment]
opm install не предлагать?

**Comment by Pr-Mex** [comment]
@asosnoviy 
>opm install не предлагать?

Я не знаю как это делать.
Это востребовано? По идее ванесса не является пакетом ванскрипта.

**Comment by asosnoviy** [comment]
> @asosnoviy
> 
> > opm install не предлагать?
> 
> Я не знаю как это делать.
> Это востребовано? По идее ванесса не является пакетом ванскрипта.

Сам пока не могу понять, вроде удобно. Завернуть  в пакет тоже не сложно. Но надо ли....

**Comment by zeegin** [comment]
Да походу не получается сделать постоянную ссылку, все равно нужно два запроса, один к АПИ, второй на загрузку.

https://api.github.com/repos/Pr-Mex/vanessa-automation/releases/latest

**Comment by Pr-Mex** [comment]
@zeegin 
Тогда закрываем ишуз?

**Comment by nixel2007** [comment]
> Я не знаю как это делать.
Это востребовано? По идее ванесса не является пакетом ванскрипта.

установка через opm для меня оказалась очень удобной на CI. и возврат к wget/curl/submodules выглядит немного болью.

Для создания пакета нужно совсем немного - packagedef, в котором бы было указано, какие файлы включать в релиз и собственно добавление в релизный пайплайн сборки пакета и пуша его в хаб. все это можно делать из командной строки.

**Comment by zeegin** [comment]
Ну я не хочу использовать ни OneScript ни opm. У меня есть более удобный вариант:

![default](https://user-images.githubusercontent.com/729213/53404379-99e8f600-39c6-11e9-9f06-757e8b1cf50d.png)

**Comment by zeegin** [comment]
> 
> 
> @zeegin
> Тогда закрываем ишуз?

Close

**Comment by Pr-Mex** [comment]
> > Я не знаю как это делать.
> > Это востребовано? По идее ванесса не является пакетом ванскрипта.
> 
> установка через opm для меня оказалась очень удобной на CI. и возврат к wget/curl/submodules выглядит немного болью.
> 
> Для создания пакета нужно совсем немного - packagedef, в котором бы было указано, какие файлы включать в релиз и собственно добавление в релизный пайплайн сборки пакета и пуша его в хаб. все это можно делать из командной строки.

Тут не понятно почему из всех пакетных менеджеров выбирается именно ванскрипт.
В чём его плюсы?

**Comment by nixel2007** [comment]
> Тут не понятно почему из всех пакетных менеджеров выбирается именно ванскрипт.
В чём его плюсы?

распространенность прочих около-ci-cd инструментов на оскрипте. тех же ванесса-ранеров, деплойки да и просто скриптов автоматизации. наличие оскрипта на CI-сервере для 1С в целом вероятнее, чем, к примеру, питона. 

Возможно это именно мое окружение, но из знакомых CI на питоне и прямом запуске 1c только у @zeegin

**Comment by Pr-Mex** [comment]
@nixel2007 
Я не против формирования пакетов. Можно сделать, если это нужно многим пользователям VA.
