### ISSUE TITLE
В шаге И в табличном документе "Результат" я перехожу к ячейке содержащей текст "Текст" нельзя использовать параметр

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1932]
Версия Vanessa Automation 1.2.040.15
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

При использовании шага И в табличном документе "Результат" я перехожу к ячейке содержащей текст "Текст" нельзя на текущий момент использовать параметр вместо текста
![image](https://user-images.githubusercontent.com/19662685/233668465-1b20e9e5-6ed1-4bdc-8f88-0cef44bc6dcb.png)

**Comment by Pr-Mex** [comment]
@akademik1986
Вы уверенны, что переменная была определена в этот момент?
Приложите полный текст сценария,  пожалуйста.

**Comment by akademik1986** [comment]
Переменная объявляется в секции переменных и используется в экспортном сценарии этой же фичи
![image](https://user-images.githubusercontent.com/19662685/233916111-c5584b10-3de9-489e-b0e8-ac48d5880246.png)

**Comment by akademik1986** [comment]
Ссылка на фичу https://disk.yandex.ru/d/MDKjtw1qNHa2JQ

**Comment by akademik1986** [comment]
Какой конфуз! 
Извини, все работает.
