### ISSUE TITLE
Логирование вызова метода УстановитьРезультатДиалогаВыбораФайла.

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#1936]
Логирование вызова метода УстановитьРезультатДиалогаВыбораФайла.
Нужно, чтобы можно было расследовать проблемы, когда в клиенте тестирования выбор файла происходит не корректно.

**Comment by akademik1986** [comment]
Ух ты, я так понимаю это по моей проблеме, спасибо Леонид! Забираю себе для расследования

**Comment by Pr-Mex** [comment]
@akademik1986 
Да, это оно )

**Comment by Pr-Mex** [comment]
Решено.
