### ISSUE TITLE
Запись в журнале регистрации при использовании импорта переменных

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1938]
Версия Vanessa Automation 1.2.040.15
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Имеем фичу для хранения переменных
#language: ru
@tree
Функциональность: Секция переменные
Переменные:
	ТекущаяДата = '{Строка(Формат(ТекущаяДата(), "ДФ=dd.MM.yyyy"))}'
	Организация1 = "Наша организация"

В фиче сценарной подключаем фича файл переменных импортом и выполняем сценарий, например,
#language: ru
@tree
@Exportscenarios
Функционал: Анализ отчеты
Контекст:	
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий
Переменные:
	Импорт "00.010. Переменные импорт.feature"

Сценарий: Анализ отчета
		И пауза 1

В журнале регистрации появляется сообщение вида
Ошибка вычисления переменной из выражения <Строка(Формат(ТекущаяДата(), "ДФ=dd.MM.yyyy"))>. Таблица переменных не найдена.

Хотя сама переменная ТекущаяДата существует и заполнена, но ошибки в журнале регистрации мешают анализу действительно полезных ошибок.

**Comment by Pr-Mex** [comment]
Решено.
