### ISSUE TITLE
Ошибка в шаге И Я запускаю очистку базы данных

### ISSUE THREAD

**Issue by TABWorkGit** [Pr-Mex/vanessa-automation#1941]
Укажите:
   1. Версия Vanessa Automation 1.2.040.9
   2. Версия платформы 8.3.20
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.14
   4. Операционная система W10

> Заполните шаблон обсуждения GIT

```Gherkin
Сценарий: <ожидаемое поведение>
  Допустим: На менеджере тестирования запускается VA с сценарием с одним шагов И Я запускаю очистку базы данных
  Когда: выполняется шаг  И Я запускаю очистку базы данных 
  Тогда: выдает ошибку "объект администрирование информационной базы недоступен"

```

> Прикладывайте файлы скриншотов
![image](https://user-images.githubusercontent.com/102640534/235054270-f97c9975-171b-439c-9ab9-f07a66c2cebb.png)

**Comment by Pr-Mex** [comment]
@TABWorkGit 
База файловая или серверная?
Насколько я помню, это будет работать только в серверной базе.

**Comment by TABWorkGit** [comment]
> @TABWorkGit База файловая или серверная? Насколько я помню, это будет работать только в серверной базе.

Файловая, у шага нет описания как и ему подобных в той же секции, поэтому не совсем понятно что ожидает сам шаг и как мне с ним работать. Поэтому поводу я еще напишу отдельно.

**Comment by Pr-Mex** [comment]
@TABWorkGit 
Я добавлю в описание шага, что он работает только в серверных базах.

**Comment by TABWorkGit** [comment]
> @TABWorkGit Я добавлю в описание шага, что он работает только в серверных базах.

А по итогу что очистка делает, искал инфу не нашел?

**Comment by Pr-Mex** [comment]
@TABWorkGit 
Вызывает этот метод
![image](https://github.com/Pr-Mex/vanessa-automation/assets/8627416/a8d3830c-03c0-484f-b343-4902d98a9c85)
