### ISSUE TITLE
Не срабатывает актуализация таблицы

### ISSUE THREAD

**Issue by mors1eska** [Pr-Mex/vanessa-automation#1944]
Укажите:
   1. Версия Vanessa Automation 1.2.040.15
   2. Версия платформы  8.3.21.1624
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.17
   4. Операционная система Windows

Есть расхождение между эталонной таблицей проводок и результатами, полученными в тесте
Нажимаю кнопку "Актуализировать"
1. интерфейсно ничего не происходит, не понятно, отработал алгоритм или нет (возможно, должна пропадать ошибка или кнопка Актуализировать) иначе не очевидно
https://recordit.co/tzE4Sg0Hdy

2. сама таблица не актуализируется
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/34914654/235284447-0418a52f-0d80-424a-83a1-bbe02cd35213.png">

**Comment by Pr-Mex** [comment]
@mors1eska 
Проверю этот момент

**Comment by Pr-Mex** [comment]
Решено.
