### ISSUE TITLE
Неверно отображаются таблицы Gerkin при нажатии Детали - Сравнить таблицы, когда в колонке присутствует перенос строк \n

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1945]
Версия Vanessa Automation 1.2.040.15
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Неверно отображаются таблицы Gerkin при нажатии Детали - Сравнить таблицы, когда в колонке присутствует перенос строк \n
Например, падает шаг Тогда таблица "Таблица" стала равной:
Анализируем ошибку и видим такую картину
![image](https://user-images.githubusercontent.com/19662685/236493597-c08b3938-695d-487a-b74f-46c3a8125e02.png)

Нажимаем Детали - Сравнить таблицы, и видим, что VA все колонки, в которых в заголовке присутствует перенос строк \n в таблице ПОЛУЧИЛИ значения не видит совсем

![image](https://user-images.githubusercontent.com/19662685/236493929-913a858a-d035-4b82-8dd6-5734a7155288.png)

Еще пример из таблицы Gerkin в фиче
![image](https://user-images.githubusercontent.com/19662685/236494178-72e1c1b6-a0dd-4609-ad1d-52db9c1a6de5.png)

и эти же колонки в сравнении таблиц
![image](https://user-images.githubusercontent.com/19662685/236494462-4680c6c2-99bb-464f-a5cf-4dce067872cb.png)

PS
базу , фичу, настройки кину ссылкой в телеграм

**Comment by Pr-Mex** [comment]
Решено.
