### ISSUE TITLE
Ошибка при выполнении на CI шага И я выбираю файл "" 

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1955]
Версия Vanessa Automation 1.2.040.15
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

@Pr-Mex  Добрый день!
В личке довольно много обсуждали эту ошибку, пока ничего из того что делал не помогло. Возможно есть какой то баг при особенности построения фичи, мало ли.
Базу , настройки использовать те, что выслал в телеграмме.
Фичи и файл загрузки ниже. (в фиче только обрати внимание на путь к файлу загрузки, возможно для чистоты эксперемента сделать такую же вложенность папок)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/5db0a59a-1e06-458c-aef6-b0e7d4f06e7e)

[Ошибка шага И я выбираю файл.zip](https://github.com/Pr-Mex/vanessa-automation/files/11441869/default.zip)

Напомню, ошибка следующего характера: 
При запуске ручном ошибки нет
Ошибка проявляется только при запуске на CI
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/d83ed37b-43c9-42d0-bd1f-9493b2b2ed96)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/7523d69f-d555-442c-981e-b7f89e58cd6d)

**Comment by Pr-Mex** [comment]
@akademik1986 
Если при ручном запуске работает, а в CI нет, значит есть какая-то разница в окружении, настройках или ещё в чём-то.
Если проблема есть, то мне её как-то надо локально воспроизвести.
От тебя нужен алгоритм либо как её воспроизвести локально, либо как настроить CI так, чтобы проблема воспроизводилась.

**Comment by Pr-Mex** [comment]
@akademik1986 
Тут классическая проблема - в одном окружении проблема воспроизводится, в другом - нет.
Думаю стоит копать в направлении понимания чем эти два окружения различаются: настройки VA, набор сценариев, тип базы и т.д.
И пытаться воспроизвести проблему локально.

**Comment by akademik1986** [comment]
@Pr-Mex 
в том то и дело, что я не могу найти зависимость, отчего разное выполнение:
-при ручном загружаю те же настройки для базы, что и в CI
-база одна и таже используется
-тип базы соответственно тоже

лог отладочный, что ты сделал для этого шага, тоже содержит абсолютно идентичные значения
{
"ИмяФичи": "Работа со списками объектов",
"ИмяФайлаФичи": "C:\\jenkins\\workspace\\job_settings\\regacc\\features\\03 Функциональные тесты\\90 Последние проверки\\03.90.030. Регучет. Работа со списками объектов.feature",
"ИмяСценария": "Создание списков объектов",
"ИмяШага": "И я выбираю файл \"$КаталогПроекта$$ПутьКФайлуЗагрузки$\"",
"НомерСтрокиФичи": 179,
"РезультатВыбораФайла": true,
"ИмяФайла": "C:/jenkins/workspace/job_settings/regacc/features\\03 Функциональные тесты\\90 Последние проверки\\Файлы\\СписокКонтрагентов.xlsx",
"ИндексФильтра": null
}

Возможно, как это обычно и бывает, ошибка на поверхности, но я никак не могу понять в чем дело.
Как тебе помочь воспроизвести на CI ? Разве не достаточно, базы, настроек и фич ? 
Запускать в CI стандартно, с тэгом исключения фич IgnoreOnCIMainBuild

Кстати, каюсь, настройки немного не те приложил, исправлюсь
[VAParams.zip](https://github.com/Pr-Mex/vanessa-automation/files/11442859/VAParams.zip)

**Comment by akademik1986** [comment]
Мда, похоже нет смысла тебе настраивать и запускать.
Сделал отдельный тэг для этой фичи, запустил только его через CI  - все успешно выполнилось (

**Comment by akademik1986** [comment]
Заведение issue - это стоило того! )
Кажется нашел проблему, как ты и говорил, поставить в настройках ПолучатьМакетыСПомощьюРасширенияVAExtension = Истина, по моему я не настройки пихнул эту Истину. Завтра проверю ночной прогон и закрою issue.

**Comment by Pr-Mex** [comment]
@akademik1986 
Ага, напиши результат, пожалуйста

**Comment by akademik1986** [comment]
@Pr-Mex  Ты лечишь "по фотографии" просто)
настройка  ПолучатьМакетыСПомощьюРасширенияVAExtension = Истина помогла

**Comment by Pr-Mex** [comment]
@akademik1986 
Пожалуйста )
