### ISSUE TITLE
Некорректная загрузка шагов экспортного сценария встроенным парсером

### ISSUE THREAD

**Issue by 1cgh** [Pr-Mex/vanessa-automation#1956]
Укажите:
   1. Версия Vanessa Automation 1.2.039.1, 1.2.040.15
   2. Версия платформы 8.3.18.1653
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.14
   4. Операционная система Windows Server 2016 Standart

Пусть есть фича Фича1 с экспортным сценарием Сценарий1
При этом в Сценарий1 используется в качестве шага Сценарий2, также находящийся в Фича1
Если в другой фиче Фича2 использовать в качестве вложенного сценария Сценарий1 несколько раз, то встроенный парсер загрузит шаги сценария некорректно (не полностью).
Если использовать парсер компоненты, ошибка не проявляется.
Если вынести Сценарий2 из Фича1 в другую фичу, то ошибка также не проявляется.

Файлы с демо-примером.
[bug_VA_parser.zip](https://github.com/Pr-Mex/vanessa-automation/files/11455956/bug_VA_parser.zip)

**Comment by Pr-Mex** [comment]
Решено.
