### ISSUE TITLE
Не запускается клиент тестирования. "Ошибка при вызове метода контекста (Run)"

### ISSUE THREAD

**Issue by Templlg** [Pr-Mex/vanessa-automation#1957]
Надеюсь в тот раздел )
В серверной и файловой базе не запускается клиент тестирования. 
К серверу подключаюсь по RDP
Галочка у пользователя "Защита от опасных действий" снята

Укажите:
   1. Версия Vanessa Automation  - 1.2.040.15
   2. Версия платформы    -   1С:Предприятие 8.3 (8.3.22.1750)
   3. Режим совместимости базы, где запускается Vanessa Automation    -   Версия 8.3.17
   4. Операционная система  -  windows server 2016

Конфигурация на сервере  1С:ERP Управление предприятием 2 (2.5.10.93) тонкий клиент
Конфигурация файловая база  IRP (2021.43.2644)  тонкий клиент

```

> Прикладывайте файлы скриншотов
![2023-05-13_19-52-00](https://github.com/Pr-Mex/vanessa-automation/assets/119128603/a683ea9a-21c0-41c2-9927-f2187a8e2add)

Сообщение об ошибке  13.05.2023 17:47:56 {ВнешняяОбработка.VanessaAutomation.Форма.ОбщегоНазначенияVA.Форма(642)}: Ошибка при вызове метода контекста (Run): Произошла исключительная ситуация (0xffffffff)

**Comment by Pr-Mex** [comment]
@Templlg 
Если запустить 1С под правами администратора - проблема останется?

**Comment by Templlg** [comment]
Добавили права, все запустилось
