### ISSUE TITLE
Улучшение работы "Подготовки и загрузки данных" "Добавить по ссылке"

### ISSUE THREAD

**Issue by VO28** [Pr-Mex/vanessa-automation#1958]
![photo_2023-05-19_11-41-58](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/f6b7d4f3-f815-488a-bd56-cc04a44e52e9)

Добавить возможно скопировав колонку геркин таблицы быстро отобрать объекты по ссылкам для подготовки загружаемых данных
![photo_2023-05-19_11-57-53](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/728e8de3-e68d-4413-b38c-99433bca71c2)

Примерный код:
	Объект.Строка = СтрЗаменить(Объект.Строка, "'", ""); 
	СтрокаОбработанная = "";
	Для Индекс = 1 По СтрЧислоСтрок(Объект.Строка) Цикл  
		ТекПодстрока = СтрПолучитьСтроку(Объект.Строка, Индекс);   
		Если Лев(ТекПодстрока, 10) = "e1cib/data" Тогда
			СтрокаОбработанная = СтрокаОбработанная + ?(ПустаяСтрока(СтрокаОбработанная), ТекПодстрока, Символы.ПС + ТекПодстрока);	
		КонецЕсли;
	КонецЦикла;	
	Объект.Строка = СтрокаОбработанная;

**Comment by Pr-Mex** [comment]
@VO28 
Расскажите, пожалуйста, подробнее про вашу доработку.

**Comment by VO28** [comment]
Суть доработки очистить лишние не являющиеся навигационной ссылкой строки
Например строка: 
**'Значение'
30
'True'
'01.11.2017 0:00:00'
'Уважаемый клиент!'
'Здравствуйте! '
'e1cib/data/Справочник.ШаблоныСообщений?ref=83abb49691160f3511eb911fa4acac49'**

Должна остаться строка только строка навигационной ссылки т.е. выглядеть так
**e1cib/data/Справочник.ШаблоныСообщений?ref=83abb49691160f3511eb911fa4acac49**

иначе такая ошибка
![image](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/f1aeb078-8646-4ada-93a0-4eced209560b)

т.е. предлагаю сделать кнопку которая будет вычищать не ссылки
![Безымянный](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/262e1edc-4c18-4e84-8312-cf0dde932266)

полезно когда например есть какой-то регистр сведений в котором значения могут быть любого типа
сначала делаем выгрузку этого регистра, 
потом через редактор таблиц Gherkin копируем колону
и сразу вставляем её в окошко "Введите навигационные ссылки"
далее **нажимаем новую кнопку которая уберет мусор**
нажимаем ок и тогда в табличной части объектов добавятся новые объекты и не будет ошибок

**Comment by Pr-Mex** [comment]
@VO28 
Может попробуете сделать пул реквест?
Тут рассказано как это делать https://infostart.ru/1c/articles/1092009/

**Comment by VO28** [comment]
@Pr-Mex Ок. Сделаю когда будет время.

**Comment by Pr-Mex** [comment]
Решено.
