### ISSUE TITLE
Ошибка работы группы шагов "И таблица содержит строки"

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1960]
Версия Vanessa Automation 1.2.040.15
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Шаг  "И Таблица равна" отрабатывает успешно, а вот если использовать шаги "И таблица содержит строки" в различных вариантах, то происходит ошибка "В результирующей таблице существуют две колонки с одинаковым заголовком: ВР", хотя это же строка в таблице содержится и при выполнении шага "И Таблица равна"
Базу , настройки использовать те, что высылал в телеграмме (если нужно, продублирую ссылку).
Фича [тут](https://disk.yandex.ru/d/204M0Nxcl7SvUQ)

![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/64cfa944-adc0-4e66-a04b-03115059e273)

**Comment by akademik1986** [comment]
И вопрос со звездочкой. 
Можно ли текущими шагами проверить, что в таблице содержатся значения в таких то колонках? Содержит строки ожидает весь набор колонок, а это не всегда удобно и нужно. Хотелось бы перечислить нужные для проверки колонки и значения, ожидаемые в них. Сойдет для issue?

**Comment by Pr-Mex** [comment]
@akademik1986 
1. В содержит строки можно передавать не все колонки.
2.  Колонки с двумя заголовками не поддерживаются из-за особенностей механизма поиска значений.
Можно до того как таблица будет проверятся сделать всем колонкам уникальный заголовок с помощью расширения VanessaExt.

**Comment by akademik1986** [comment]
1. Да, это я наверное с табличным документом перепутал. Извиняюсь.
2. А почему тогда сработал шаг на равенство ? Мне казалось, что ты подобное правил для какого то шага, подумал может не везде, поэтому и завел задачу. А как через VanessaExt задать уникальный заголовок, не понял...

**Comment by Pr-Mex** [comment]
@akademik1986 

> 2. А почему тогда сработал шаг на равенство ? Мне казалось, что ты подобное правил для какого то шага, подумал может не везде, поэтому и завел задачу.

Почему сработал шаг - я не в контексте, сходу ответить не могу.

> А как через VanessaExt задать уникальный заголовок, не понял...

https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/VAExtension/VAExtension.md
Пункт 7.

**Comment by akademik1986** [comment]
Ну контекст весь есть у тебя, можешь глянуть как будет время? 
Базу давал в телеге, фича тут.
За пункт доки спасибо, попробую!

**Comment by Pr-Mex** [comment]
@akademik1986 
Прежде чем глядеть - давай ещё раз сформулируем в чем проблема?

**Comment by akademik1986** [comment]
// шаг работает
Тогда таблица "Хозрасчетный" стала равной:

// не работает
И таблица "Хозрасчетный" содержит строки:

таблица на входе у обоих шагов одинакова

**Comment by Pr-Mex** [comment]
@akademik1986 
Там разные алгоритмы используются, насколько я помню. Один из них требует уникальности колонок, другой - нет.
