### ISSUE TITLE
Vanessa Automation виснет при запуске, что с сервера 1с, что с клиента

### ISSUE THREAD

**Issue by Vitaliy276** [Pr-Mex/vanessa-automation#1962]
Укажите:
   1. Версия Vanessa Automation
   vanessa-automation.1.2.040.9
   пробовал так же 
   vanessa-automation 1.2.040.1
   2. Версия платформы
   1С:Предприятие 8.3 (8.3.22.1923)
   3. Режим совместимости базы, где запускается Vanessa Automation -   8.3.17
   4. Операционная система
   Windows Server 2008 r2
   5. Проверял на релиза 
   Управление торговлей, редакция 11 (11.5.12.53)
   Управление торговлей, редакция 11 (11.5.8.295)

> Заполните шаблон обсуждения GIT

Помогите пжста, столкнулся с такой проблемой , при запуске Vanessa Automation, принимаю установку внешней компоненты,
ДА, ОК и после должен появится помошник, 1с с Vanessa Automation виснет на глуха, не работает ничего, только через диспетчер задач можно закрыть 1ску. 
Помогите найти причину, чтобы запустить Vanessa Automation.
спасибо

```

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
@Vitaliy276 
Если я правильно понял - то при первом запуске появляется вопрос - включить ли компоненту и вы отвечаете Да. А  если ответить Нет - то что будет?

**Comment by Vitaliy276** [comment]
самое интересное, что для теста, перенес базу с Windows server 2008r2  на Windows server 2016 одну и ту же базу, открываю и нажимаю ОК , то вижу помощника, и база не виснет. 
Как понять, почему такое?

**Comment by Pr-Mex** [comment]
@Vitaliy276 
У вас почему-то не работает показ Onboarding в определенном окружении.
Для работы инструмента он необязателен.
Достаточно установить этот флаг и сохранить настройки (обязательно).
![image](https://github.com/Pr-Mex/vanessa-automation/assets/8627416/6e45228b-9403-421d-811c-d0a8dbdaab6c)

**Comment by Vitaliy276** [comment]
сейчас проверю и дам обратку

**Comment by Vitaliy276** [comment]
после это сохраняю и можно работать ? больше ни каких действий можно не делать ?

**Comment by Pr-Mex** [comment]
@Vitaliy276 
> после это сохраняю и можно работать ? больше ни каких действий можно не делать ?

Да

**Comment by lo0p3r** [comment]
Возникает такая же проблема на одном компе:
 1. Версия Vanessa Automation: 1.2.040.1
 2. Версия платформы: 8.3.22.1750
 3. Режим совместимости базы, где запускается Vanessa Automation: Версия 8.3.17
 4. Операционная система: Windows 7 Pro x64
 5. Путь для воспроизведения: _Сервис_ -> _Обучение_ -> _Показать помощник при первом запуске_
  
 Проблема возникает в процедуре **ЭлементUIAutomationOnboardingПродолжение1()** формы **УправляемаяФорма**:
после вызова метода внешней компоненты `ВнешняяКомпонентаДляСкриншотов.НачатьВызовНайтиЭлементы(ОписаниеОповещения, ОбъектКонтекст._ОтборЭлементов)` управление не возвращается обратно в процедуру **НайтиЭлементыOnboardingПродолжение1Завершение**.
Антивирус отключал - не помогло.
При этом, другой метод компоненты, **НачатьВызовПоказатьНажатиеМыши** - работает, т.е. дело, вроде как, не в компоненте вообще, а в её отдельной части.
Можно как-то собрать лог работы компоненты?
На соседнем компьютере с той же платформой и Win 10 проблема не возникает.

**Comment by Pr-Mex** [comment]
@lo0p3r 
При появлении диалога о подключении компоненты вы можете сказать Нет, и затем включить флаг компоненты в настройках вручную. Тогда Онбординг не будет появляться.

**Comment by Geronimo1984** [comment]
Та же ситуация, только вот диалог о подключении компоненты у меня не отображается (До этого все было нормально, производила начальную настройку и включала эту компоненту).
Запускала как с менеджером тестирования, так и без, пробовала на других базах - результат тот же.
Подскажите пожалуйста, куда копать?
![Screenshot_1](https://github.com/Pr-Mex/vanessa-automation/assets/105367035/dbd5dd3b-308b-4605-98d3-e0a6028f4526)

**Comment by Pr-Mex** [comment]
@Geronimo1984 
По такой информации непонятно что происходит.
1. Нужно попробовать запустить сеанс 1С из под Администратора
2. Посмотреть в отладке

**Comment by lo0p3r** [comment]
@Geronimo1984 не знаю, как именно вы запускаете ванессу, но попробуйте указать путь к файлу конфигурации, в котором настройка ПоказыватьПомощникПриПервомЗапуске будет Ложь, а потом уже в открывшейся ванессе принудительно сохранить настройки, по идее, они потом будут применяться при следующем открытии обработки.
Например, можно запустить 1С с ключом
`/Execute C:\vanessa-automation\vanessa-automation.epf /TESTMANAGER /C"StartFeaturePlayer;VAParams=C:\VAParams.json"`,
где VAParams.json будет состоять из одной настройки: `{"ПоказыватьПомощникПриПервомЗапуске": false}`.
