### ISSUE TITLE
Кнопка "Перезапустить как менеджер тестирования"

### ISSUE THREAD

**Issue by VO28** [Pr-Mex/vanessa-automation#1963]
Предлагаю сделать кнопку для быстрого перезапуска в режиме Менеджер тестирования.
Если запускать 1С **не** в режиме Менеджер тестирования в VA должна появляться кнопка "Перезапустить как менеджер тестирования"
![image](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/9d1c5e19-96b4-4299-9b8c-9e72464aa7f4)
При запуске такой в режиме Менеджер тестирования такою кнопу убирать
![image](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/fc0b3dee-babc-4ca3-a5de-a67c4187ba00)

**Comment by Pr-Mex** [comment]
@VO28 
Да, можно добавить в меню Ещё эту кнопку.
Главное не делать пользователю уведомлений, т.к. он может запустить обработку не для того, чтобы использовать механизм менеджера и клиента тестирования. А, например, использовать UI Automation.

**Comment by Pr-Mex** [comment]
Решено.
