### ISSUE TITLE
Ошибка при использовании переменных в тэгах автовидеоинструкции

### ISSUE THREAD

**Issue by promtechAdmin** [Pr-Mex/vanessa-automation#1966]
При использовании локальных переменных в тэгах видеоинструкций  #[autodoc.groupsteps] #[autodoc.text] при запуске фичи выдается системная ошибка - переменная не определена

Пример кода фичи для воспроизведения ошибки

Переменные:
	пКоличество=5
Сценарий: Создание и проведение документа Потребность с видом АРМ и до 100.000
      	#[autodoc.groupsteps] Текст для озвучки в количестве ["" + пКоличество] 
      	*Текст параметров примера
      		И Пауза 3

**Comment by Pr-Mex** [comment]
@promtechAdmin 
Это не ошибка. Правильный синтаксис такой
#[autodoc.groupsteps] Текст для озвучки в количестве ["" + Контекст.пКоличество]
