### ISSUE TITLE
Шаг "и я сохраняю выпадающий список" всегда добавляет лишнее значение в массив

### ISSUE THREAD

**Issue by TABWorkGit** [Pr-Mex/vanessa-automation#1967]
Укажите:
   1. Версия Vanessa Automation 1.2.040.15
   2. Версия платформы 8.3.20
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система W10

При выполнении шага "и я сохраняю выпадающий список" даже если выпадающий список пустой он все равно записывает одно значение которое заложено в коде в виде структуры с ключами ОтображаемыйТекст и ПредставлениеДанных с аналогичными значениями. Получается при вызове метода Количество будет всегда возвращаться 1 вместо 0, если список пуст, что вводит в заблуждение. 
![image](https://github.com/Pr-Mex/vanessa-automation/assets/102640534/7a4c866f-14cb-41a2-adc7-7b6baf80aa3f)

**Comment by Pr-Mex** [comment]
Решено.
