### ISSUE TITLE
Не считываются настройки Vanessa Automation при использовании экспортного сценария

### ISSUE THREAD

**Issue by Zakharovzvv** [Pr-Mex/vanessa-automation#1969]
Контекст для воспроизведения ошибки:

Фича1, в которой объявлены переменные:
![image](https://github.com/Pr-Mex/vanessa-automation/assets/68952793/ab3283eb-6c52-4da7-ae64-270f5313e825)

Фича2, в которой написан экспортный сценарий:

Есть экспортный сценарий, в котором устанавливаются и читаются настройки Vanessa. В сценарий импортируются переменные из Фича1. В нем все работает переменные читаются и устанавливаются. 
![image](https://github.com/Pr-Mex/vanessa-automation/assets/68952793/bceac926-85e7-44c8-9937-64eead4cb383)

Фича3, в которой вызывается экспортный сценарий:

Этот экспортный сценарий используется в фиче. В сценарий импортируются переменные из Фича1. Здесь уже настройки имеют пустое значение.
![image](https://github.com/Pr-Mex/vanessa-automation/assets/68952793/b0a8d7b1-a596-48db-94e6-f985f7a35062)

**Comment by Pr-Mex** [comment]
@Zakharovzvv 
Приложите, пожалуйста, файлы для воспроизведения проблемы.

**Comment by Pr-Mex** [comment]
Закрываю, т.к. нет ответа.
