### ISSUE TITLE
В шаге И я нажимаю сочетание клавиш "Shift+<Cursor's movement key>"  не приводит к отметке области текста или таблицы

### ISSUE THREAD

**Issue by mrshadow300373** [Pr-Mex/vanessa-automation#1970]
1. 1.2.40.15
   2. 8.3.22.1923, 8.3.21.1775, 8.3.23.1437
   3. 8.3.21
   4. Windows 10

```Gherkin

Функционал: <описание фичи>

Как <Роль> я хочу
<описание функционала> 
чтобы <бизнес-эффект> 

Контекст:
	И Я открыл новый сеанс TestClient или подключил уже существующий
Сценарий: <описание сценария>
	И я нажимаю сочетание клавиш "Ctrl+N"
	Когда открылось окно 'Выбор вида документа'
	И в таблице "" я выбираю текущую строку
	И я эмулирую ввод текста "Привет это простая проверка"
	И я нажимаю сочетание клавиш "ENTER"
	И я эмулирую ввод текста "Привет это простая проверка"
	И я нажимаю сочетание клавиш "ENTER"
	И я эмулирую ввод текста "Привет это простая проверка"
	И я нажимаю сочетание клавиш "ENTER"
	И я нажимаю сочетание клавиш "Ctrl+Home"
	И я нажимаю сочетание клавиш "Shift+Down"
	И я нажимаю сочетание клавиш "Shift+Down"
	И я нажимаю сочетание клавиш "Shift+Down"

```
Последние три шага должны вызвать отметку 3х ранее введённых строк, но не вызывают, хотя и отрабатывают без ошибки
https://github.com/Pr-Mex/vanessa-automation/assets/34220218/9fa20445-a8af-4e6a-877c-27278d25af31
UPD:
Есть радостные новости
Если заменить последние строки на 

```Gherkin
	И я нажимаю сочетание клавиш "LShift+RShift+Down"
	И я нажимаю сочетание клавиш "LShift+RShift+Down"
	И я нажимаю сочетание клавиш "LShift+RShift+Down"
```
То в таком варианте требуемый эффект достигается.

**Comment by Pr-Mex** [comment]
Попробую у себя воспроизвести.

**Comment by mrshadow300373** [comment]
> Попробую у себя воспроизвести.

Получилось? Есть и не радостные с последней комбинацией без режима записи видео все работает стабильно. А вот если включить запись видео, то:
1. В текстовых редакторах работает
2. В редакторе MXL при каких то случаях 2 из 10 срабатывает, а вот 8 из 10 поведение как в изначальном условии, т.е. курсор передвигается по ячейкам, а отметки нет. Пока не смог понять что это за случаи и так потратил много времени. Происходило так, например ставлю запуск сценария с определенной точки - срабатывает (хотя подозреваю, что режим записи видео с определенного шага просто не канает). Ставлю весь тест с начала - доходит до этого места и не отмечает ячейки. В итоге, после отметки в нужных местах понаставил паузы 5 секунд и дождавшись этих моментов отмечал руками то что нужно, а потом удалили паузы из видео...
3. В некоторых случаях перестало срабатывать Ctrl+F, Ctrl+N тоже паузы и руками нажимал на клавиатуре. 
При этом сложилось стойкое ощущение, что не срабатывали комбинации лишь потому, что само приложение (которое должно было реагировать на нажатие символов) было не "в фокусе ввода", несмотря на то, что было "сверху" потому, что когда просто руками пытался комбиинацию нажать на клавиатуре - тоже не срабатывало, и, лишь только после того как ткнул в приложение мышью, получалось нужную комбинацию ввести.
В общем непонятно как, ощущение, то запуск видео переводит саму программу записи видео (не оч. разбираюсь но наверное это сам ffmpeg) в фокус ввода, и именно по этому горячие кнопки в 1С (клиенте тестирования) не срабатывали, либо срабатывали некорректно, а в открытом и 1С WORDе, который оказался "сверху" работало все корректно, но после закрытия WORDа фокус снова возвращался не в 1С.

**Comment by Pr-Mex** [comment]
@mrshadow300373 
Думаю стоит попробовать добавить активизацию окна перед эмуляцией клавиш.

**Comment by mrshadow300373** [comment]
Действительно, в некоторых случаях фокус ввода терялся, тогда я делал так (1я строка):
```Gherkin
		И я активизирую окно текущего клиента тестирования
		И в табличном документе 'SpreadsheetDocument' я перехожу к ячейке "R1C1"
		#И я нажимаю сочетание клавиш "RSHIFT+LSHIFT+CTRL+END"
		И я нажимаю сочетание клавиш "RSHIFT+LSHIFT+RIGHT"
		И я нажимаю сочетание клавиш "RSHIFT+LSHIFT+RIGHT"
		И я нажимаю сочетание клавиш "RSHIFT+LSHIFT+DOWN"
		И я нажимаю сочетание клавиш "RSHIFT+LSHIFT+DOWN"
		И я нажимаю сочетание клавиш "RSHIFT+LSHIFT+DOWN"
		И я нажимаю сочетание клавиш "RSHIFT+LSHIFT+DOWN"
		И я нажимаю сочетание клавиш "RSHIFT+LSHIFT+DOWN"
		И я нажимаю сочетание клавиш "RSHIFT+LSHIFT+DOWN"
```
И если не включать запись то это работает корректно. 
Причем я взял вот этот же кусок сценария, "вырвал из контекста" отвлеченно в отдельный сценарий и он работает как с записью так и нет. Тяжелый случай.

**Comment by Pr-Mex** [comment]
@mrshadow300373 
Бывают нехорошие окна, которые не ловят фокус.
Попробуй добавить клик мышкой по центру экрана перед эмуляцией клавиатуры. Для этого есть шаг.

**Comment by Pr-Mex** [comment]
@mrshadow300373 
Снял метку ошибки. Видимо это особенность эмуляции клавиш.
