### ISSUE TITLE
Незакрытие окна Настройка списка и блокирование выполнения последующих сценариев

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#1976]
Версия Vanessa Automation 1.2.040.15
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

При использовании шага "И я устанавливаю фильтр на список" в случае когда устанавливается отбор на несуществующий элемент выходит ошибка следующего шага, и все последующие шаги, сценарии и фичи завершаются с ошибкой "Недоступный пользователю элемент управления не может выполнять интерактивные действия." , так как форма отбора не закрывается ни шагами закрытия все окон клиента тестирования, ни контекстным шагом "Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий"
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/8c94b7cb-780d-4a26-aef7-6da406454ab8)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/aab24356-04e3-432d-90d9-95a60d0447d9)

база и фича для примера :
[незакрытие окна Настройка списка.zip](https://github.com/Pr-Mex/vanessa-automation/files/11662366/default.zip)

**Comment by Pr-Mex** [comment]
@akademik1986 
Думаешь это ошибка? Тест свою функцию выполнил, нашел место где не работает.

**Comment by Pr-Mex** [comment]
@akademik1986 
А если добавить шаг закрытия клиента тестирования и установить этот флаг?
![image](https://github.com/Pr-Mex/vanessa-automation/assets/8627416/e8d61c76-a326-43f2-bbfb-ca54313c50df)

**Comment by akademik1986** [comment]
@Pr-Mex не совсем понимаю, что ты хочешь этим проверить, но да, такой вариант работает.
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/a6370ee0-6282-488a-9417-8b13c0ed5ac2)

Но ты же не хочешь сказать используй в контексте этот шаг?)

**Comment by Pr-Mex** [comment]
@akademik1986 
По разному бывает )
Вообще конечно лучше разобраться как починить поведение установки фильтра.

**Comment by akademik1986** [comment]
@Pr-Mex а как решено, неужели  изменено поведение установки фильтра?)

**Comment by Pr-Mex** [comment]
Насколько я понимаю, пока исправление не нужно.
