### ISSUE TITLE
Автоматическая генерация фича файлов с дымовыми тестами

### ISSUE THREAD

**Issue by VO28** [Pr-Mex/vanessa-automation#1978]
Сделать возможность генерировать фича файлы при пакетном запуске 1С

С целью не плодить зоопарк дополнительных обработок для VA

Сейчас использую: https://github.com/VO28/VA-SmokeTests
Дорабатывал: https://github.com/Tavalik/VA-SmokeTests

 ![233015973-84c507bb-6ee2-4508-bce9-0dc49fd57844](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/502c2e90-1aad-46c7-ab14-c47b14937893)

![239352497-1391d737-efc8-4e26-9f42-4a0237b7cba4](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/352d10d5-4c6c-4530-b5ee-d259e4299343)

Может сделать что-то подобное в самой VA?
Добавить **отдельную форму** для такой генерации или **доработать существующую**?
![image](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/5cd19bf6-2035-4d0c-a24b-df6e59721c4f)

**Comment by Pr-Mex** [comment]
@VO28 
Существующая форма дымовых тестов в VA "не взлетела". Её смело можно заменить.

Я правильно понимаю, что ты берёшь за основу вот этот проект
https://github.com/Tavalik/VA-SmokeTests
затем, его дорабатываешь и делаешь пулреквест в него?

**Comment by VO28** [comment]
@Pr-Mex да, за основу мною была взята [эта](https://github.com/Tavalik/VA-SmokeTests) обработка. Пулреквест кидал но он не был принят

**Comment by Pr-Mex** [comment]
@VO28 
Тогда я думаю стоит разделить задачу на две части.
1. Сделать так, чтобы Виталий посмотрел твой пул реквест и принял его.
2. Встраивание инструмента в VA. На самом деле мы с Виталием уже обсуждали, что его инструмент надо встроить и решили, что мы оба за это. Так что давай встраивать. То что пулреквест пока не принят нам не мешает

Итого - давай заменять ту форму дымовых тестов что сейчас есть на новый инструмент.
И маякни мне в телеге, пожалуйста.

**Comment by Tavalik** [comment]
> @VO28 Тогда я думаю стоит разделить задачу на две части.
> 
> 1. Сделать так, чтобы Виталий посмотрел твой пул реквест и принял его.
> 2. Встраивание инструмента в VA. На самом деле мы с Виталием уже обсуждали, что его инструмент надо встроить и решили, что мы оба за это. Так что давай встраивать. То что пулреквест пока не принят нам не мешает
> 
> Итого - давай заменять ту форму дымовых тестов что сейчас есть на новый инструмент. И маякни мне в телеге, пожалуйста.

Готов подключиться к проекту и принимать пул-реквесты. Насколько я понял, надо мне обработку в исходные файлы раскладывать и собирать релизную версию? Или как?

**Comment by Pr-Mex** [comment]
@Tavalik
Обсудили устно.
Кажется решили, что обработка будет встроена в VA и будет там развиваться, т.к. без VA не имеет смысла.
Я ничего не  перепутал?

**Comment by Tavalik** [comment]
> @Tavalik Обсудили устно. Кажется решили, что обработка будет встроена в VA и будет там развиваться, т.к. без VA не имеет смысла. Я ничего не перепутал?

Да, все так. Готовлю пул-реквест в основное репо ванессы.

**Comment by Pr-Mex** [comment]
Решено.
