### ISSUE TITLE
Работа с экспортными сценариями

### ISSUE THREAD

**Issue by iamnifed** [Pr-Mex/vanessa-automation#1979]
1. Версия Vanessa Automation 1.2.040.9
   2. Версия платформы 1С:Предприятие 8.3 (8.3.22.1851)
   3. Режим совместимости базы, где запускается Vanessa Automation Серверный
   4. Операционная система Windows server 2019 Standard

Добрый день. Попытаюсь обьяснить проблему с которой столкнулся.

Есть файл с экспортными сценариями, в данном случае идет у меня выбор номенклатуры. Я делаю много файлов по сути с одним функционалом, но с разной номенклатурой. Номенклатуру помечаю разными цифрами на конце (Кислота 2, Кислота 3 и тд). Первый раз когда меняешь сам сценарий в фиче - вроде бы все нормально. Потом после перезапуска файла я заметил, что сценарии которые я не менял поменялись сами. Например, в видео видно что я меняю 2 на 3 в одном месте без редактора, потом меняю с 3 на 2 обратно, но в строках ничего само не меняется. Замечаю такое впринципе только если в конце названия экспортного сценария указана цифра, остальные сценарии так не ломались. 

![image](https://github.com/Pr-Mex/vanessa-automation/assets/131357263/abd176e8-9e61-4869-a4a2-ba65946d3d96)
(например вот, я его уже сохранил, и по идее от должен подтянуть другой, но этого не происходит )

Вследствие чего вопрос, это действительно так работает программа и лучше искать другие варианты записи тестов, или это все-таки ошибка?

Это пример с видео 
https://disk.yandex.ru/i/3UgPTA_Kin3gBA

**Comment by Pr-Mex** [comment]
@iamnifed 
Число 3 воспринимается как параметр подсценария.
Т.е. можно объявить сценарий с одним параметром так:
И мой сценарий "Парам01"
или так
И мой сценарий 1
Во втором примере единица в конце считается первым параметром подсценария.
Если не нужно считать единицу параметром можно объявить подсценарий, например, так
И мой сценарий_1

**Comment by iamnifed** [comment]
А где можно прочитать подробнее об этом функционале? Т.е за что вообще параметр подсценария отвечает

p.s 
![image](https://github.com/Pr-Mex/vanessa-automation/assets/131357263/f0133e28-c03c-4149-b2fe-22d33197f00f)

Еще нашел несоответствие текста и инструкции

**Comment by Pr-Mex** [comment]
@iamnifed 
По описанию шага - поправлю. Спасибо.

**Comment by Pr-Mex** [comment]
@iamnifed 
По подсценариям можно почитать тут
https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/MainHelp/index.MD

**Comment by iamnifed** [comment]
@Pr-Mex Подскажите пожалуйста еще по такому вопросу, если не сложно, я видел что в ванессе можно использовать переменные, а как-то возможно сделать чтобы в 1 переменную записывалось значение которое может изменяться постоянно? Меня интересует курс валюты, ибо если его обновить, то все тесты сразу рушатся

**Comment by Pr-Mex** [comment]
@iamnifed 
Да, сохраните значение курса в глобальную переменную.

**Comment by Pr-Mex** [comment]
@iamnifed 
Попробуйте для начала написать шаг проверки значения ячейки таблицы:
И в таблице "Список" поле "Дата курса" имеет значение "$$ПеременнаяТекущаяДата$$"
Может проблема в том, что у вас не получается найти колонку таблицы. Посмотрите в исследователе формы как правильно она называется. Возможно нужно проверять значение ячейки по внутреннему имени, а не по заголовку.

**Comment by iamnifed** [comment]
Спасибо вам за совет, получилось сделать как я хотел, только немного по-другому

![image](https://github.com/Pr-Mex/vanessa-automation/assets/131357263/1296c028-36fe-4eea-a868-5f7a33bb08c1)
