### ISSUE TITLE
При падении теста прогон замирает на окне Не найден файл, блокируется создание отчета

### ISSUE THREAD

**Issue by XeniyaSKA** [Pr-Mex/vanessa-automation#1980]
Укажите:
   1. Версия Vanessa Automation 1.2.040.15
   2. Версия платформы 1С Предприятие 8.3. (8.3.21.1624)
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система Windows Server 2016 Standard 
   
При падении рандомного теста прогон замирает на окне Не найден файл и блокируется либо дальнейшее прохождение прогона, либо формирование отчета с итогами тестового прогона

> Заполните шаблон обсуждения GIT
![IMG_20230601_095239_012](https://github.com/Pr-Mex/vanessa-automation/assets/135205190/6b16ed59-49bf-4b14-9ee9-e8919b348512)
![IMG_20230601_095250_326](https://github.com/Pr-Mex/vanessa-automation/assets/135205190/0d34fbe5-ea6a-4522-bd11-53a186c75f7c)

**Comment by Pr-Mex** [comment]
@Pr-Mex 
Спасибо, посмотрю.

**Comment by Pr-Mex** [comment]
Решено.
