### ISSUE TITLE
Не корректный пример использования шага в библиотеке шагов

### ISSUE THREAD

**Issue by VO28** [Pr-Mex/vanessa-automation#1989]
Версия Vanessa Automation 1.2.040.20
  
для шага вызова кода 1С 
например "And I execute 1C:Enterprise script at server no context"
![image](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/1059c416-ff5a-4cea-b3df-2f8b8656f120)

 вызов код из примера: | "Message ("Hello world.") " |
 нужно так: | 'Message ("Hello world."); ' |
 т.к. в  примере не правильно расставлены кавычки шаг падает с ошибкой

 ![image](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/64a786b2-c6e4-4f11-b67e-3ff3ee15bef8)

**Comment by Pr-Mex** [comment]
@VO28 
Ага, спасибо. Поправлю.

**Comment by Pr-Mex** [comment]
Решено.
