### ISSUE TITLE
Не в полном объеме выгружаются данные из ПВХ ДополнительныеРеквизитыИСведения

### ISSUE THREAD

**Issue by TrilexTriton** [Pr-Mex/vanessa-automation#1991]
Укажите:
   1. Версия Vanessa Automation 1.2.040.15
   2. Версия платформы 8.3.20
   3. Режим совместимости базы, где запускается Vanessa Automation 8 .3.17
   4. Операционная система Windows Serve 2016 Standart 

При выполнении шага  _И я проверяю или создаю для плана видов характеристик "ДополнительныеРеквизитыИСведения" объекты:_  не выгружается реквизит _ТипЗначения_ . Если дописать реквизит вручную, то сценарий выполниться без учета реквизита.

**Comment by Pr-Mex** [comment]
Решено.
