### ISSUE TITLE
Не хватает варианта асинхронного вызова кнопки открытия

### ISSUE THREAD

**Issue by VO28** [Pr-Mex/vanessa-automation#1995]
1. Версия Vanessa Automation **1.2.040.20**
   2. Версия платформы **8.3.22**
   3. Режим совместимости базы, где запускается Vanessa Automation **8.3.17**
   4. Операционная система **windows 10**

![image](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/352e3750-f268-4c8f-b37c-92c8b46b4b0e)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/434b0c33-2c42-4e79-aa77-7377820f2915)

**Comment by Pr-Mex** [comment]
Решено.
