### ISSUE TITLE
Не открывается тестовый клиент (шаг на английском)

### ISSUE THREAD

**Issue by hawk911** [Pr-Mex/vanessa-automation#1997]
Укажите:
   1. Версия Vanessa Automation: 1.2.040.1  
   2. Версия платформы: 8.3.17.2677  
   3. Операционная система: Windows 10, Windows 11

Не открывается тестовый клиент отличный от текущего на английском языке.

```gherkin
#language: en

@tree

Functionality: <description features>

As <Role>
I want <functional description>
To <business effect>

Scenario: TestClient

And I close current test client session
When Я подключаю клиент тестирования с параметрами:
    | 'Имя'             | 'Синоним'        | 'Тип клиента' |   'Строка соединения'  |  'Дополнительные параметры строки запуска'  |
    | 'ИмяПрофиля'      | 'СинонимПрофиля' | 'Тонкий'      |  'File="D:\data12345";' |  '/Len'                             |
And Delay 5
And I close current test client session 
When I connect TestClient with parameters
	| 'Name' | 'Synonym' | 'Client type' | 'Connection String' |  'Additional command line parameters'  |
	| 'NameOfProfile' | 'SynonymofClient' | 'Thin' | 'File="D:\data12345";'  | '/Len'                             |
```

Первый шаг работает - открывает новый тестовый клиент, второй не работает - открывает текущий тестовый клиент (а должен открывать новый).
Базы использовались пустые.

![image](https://github.com/Pr-Mex/vanessa-automation/assets/11535209/cade606f-9d6a-4006-9aa3-60afb93698ef)

**Comment by Pr-Mex** [comment]
@hawk911 
Проверил на 1.2.040.20
Не воспроизвелось.
Сначала клиент тестирования запустился, потом закрылся, потом запустился новый.

**Comment by hawk911** [comment]
> @hawk911 Проверил на 1.2.040.20 Не воспроизвелось. Сначала клиент тестирования запустился, потом закрылся, потом запустился новый.

Проверил на 1.2.040.20 - ошибка осталась.
