### ISSUE TITLE
Шаг И я записываю документ по навигационной ссылке "НавигационнаяСсылка" в режиме "Проведение"

### ISSUE THREAD

**Issue by VO28** [Pr-Mex/vanessa-automation#2001]
**Предлагаю сделать шаги**
И я записываю документ по навигационной ссылке "НавигационнаяСсылка" в режиме "Проведение"
И я записываю документ по навигационной ссылке "НавигационнаяСсылка" в режиме "Проведение" с вызовом исключения

**сейчас есть аналоги но они работают через переменную внутри которой ссылка на документ**
И я записываю документ "ИмяПеременной" в режиме "Проведение"
И я записываю документ "ИмяПеременной" в режиме "Проведение" с вызовом исключения

**Пример фичи:**
#language: ru

@tree

Функционал: <описание фичи>

Как <Роль> я хочу
<описание функционала> 
чтобы <бизнес-эффект>   

Контекст:
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: <описание сценария>
	И я записываю документ по навигационной ссылке "e1cib/data/Документ.РасходТовара?ref=a1aa086266c6d20f11e70b13d9094c6d" в режиме "Проведение"

**Comment by Pr-Mex** [comment]
@VO28 
Это доработка по подсистеме инициатора данных?

**Comment by VO28** [comment]
Да

**Comment by Pr-Mex** [comment]
Решено.
