### ISSUE TITLE
Переписать открытие навигационных ссылок на режим без модальность

### ISSUE THREAD

**Issue by VO28** [Pr-Mex/vanessa-automation#2003]
Vanessa automation 1.2.40.22
При нажатии Ctrl+ клик левой кнопкой мыши по навигационной ссылке  возникает ошибка
![image](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/81f90b63-8cb0-4556-812d-d953b0711c40)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/91219263/e708014f-dca3-475f-bf40-dcb38a8acb9f)

**Comment by Pr-Mex** [comment]
@VO28 
Там видимо надо использовать асинхронный вариант

**Comment by Pr-Mex** [comment]
Решено.
