### ISSUE TITLE
Все равно пишет ошибки такого рода версия Vanessa 1.20.040.20

### ISSUE THREAD

**Issue by dvissarov** [Pr-Mex/vanessa-automation#2022]
Версия 1С : 1С:Предприятие 8.3 (8.3.22.2106)
Режим совместимости : 8.3.17
Конфигурация. УТ 11.5.13.74
ОС : Windows Server 2016

ИНФОРМАЦИЯ - - Шаг: И в таблице "СписокСтандартныйПоискНоменклатура" я активизирую дополнение формы с именем "СписокСтандартныйПоискНоменклатураСтрокаПоиска"
ИНФОРМАЦИЯ - Pending: Пустой адрес снипета у шага: И в таблице "СписокСтандартныйПоискНоменклатура" я активизирую дополнение формы с именем "СписокСтандартныйПоискНоменклатураСтрокаПоиска"

_Originally posted by @dvissarov in https://github.com/Pr-Mex/vanessa-automation/issues/1558#issuecomment-1660743969_

**Comment by dvissarov** [comment]
При ручном запуске нормально находит СписокСтандартныйПоискНоменклатураСтрокаПоиска
При запуске из командной строки пишет такого рода ошибку.

**Comment by Pr-Mex** [comment]
Опишите подробно как и что вы сейчас запускаете и с какими настройками.

**Comment by dvissarov** [comment]
Запуская через консоль командой
 vrunner vanessa --settings tools\json\vrunner.json

сами json файлы во вложении
[json.zip](https://github.com/Pr-Mex/vanessa-automation/files/12241802/json.zip)

И feature файл теста

[1 Создание заказа на перемещение.zip](https://github.com/Pr-Mex/vanessa-automation/files/12241749/1.zip)

Если еще что то надо то напишите

**Comment by Pr-Mex** [comment]
@dvissarov 
Давайте проверим что будет, если запустить менеджер тестирования под другим пользователем.

**Comment by dvissarov** [comment]
@Pr-Mex  Под другим windows пользователем?
Через консоль и через обработку 1 и тот же пользователь

**Comment by Pr-Mex** [comment]
@dvissarov 
Под другим пользователем в базе менеджера тестирования.

**Comment by dvissarov** [comment]
то же самое. Если правильно понял, то указал в файле vrunner.json другого пользователя.

И в таблице "СписокСтандартныйПоискНоменклатура" я активизирую дополнение формы с именем "СписокСтандартныйПоискНоменклатураСтрокаПоиска" 2 parameters0s
Парам1	СписокСтандартныйПоискНоменклатура
Парам2	СписокСтандартныйПоискНоменклатураСтрокаПоиска
Пустой адрес снипета у шага: И в таблице "СписокСтандартныйПоискНоменклатура" я активизирую дополнение формы с именем "СписокСтандартныйПоискНоменклатураСтрокаПоиска"

**Comment by dvissarov** [comment]
> @dvissarov У вас менеджер тестирования запустился под другим пользователем? 

Ну да запустился

> Можете показать скриншоты менеджера тестирования до изменений и после изменений?

![image](https://github.com/Pr-Mex/vanessa-automation/assets/21277545/2520cdec-23f9-4419-912b-65bbd708a17b)

**Comment by Pr-Mex** [comment]
@dvissarov 
На данном скриншоте не видно под кем запущен сеанс и не видно статистику загрузки шагов, которая находится в правом нижнем углу.

**Comment by dvissarov** [comment]
![Скриншот 07-08-2023 162452](https://github.com/Pr-Mex/vanessa-automation/assets/21277545/984b3e21-e487-429e-be12-b3c340769ce7)

**Comment by Pr-Mex** [comment]
@dvissarov 
А как выглядит проблема при запуске через консоль?

**Comment by Pr-Mex** [comment]
@dvissarov 
Скиньте, пожалуйста, скриншот на котором видно проблему "Пустой адрес снипета у шага"

**Comment by Pr-Mex** [comment]
@dvissarov 
Интересует что в этот момент происходит в менеджере тестирования

**Comment by dvissarov** [comment]
@Pr-Mex  Скриншот консоли? а то при ошибке все клиенты закрываются  и уже саму обработку не видно.

**Comment by dvissarov** [comment]
![image](https://github.com/Pr-Mex/vanessa-automation/assets/21277545/d464b117-48fa-495c-85b0-5491ef5532db)

**Comment by dvissarov** [comment]
![image](https://github.com/Pr-Mex/vanessa-automation/assets/21277545/a2d13a1c-518e-431a-b560-adf8d9dd9e08)

**Comment by Pr-Mex** [comment]
@dvissarov 
1. Можно выставить в настройках не завершать работу после завершения сессии тестирования. Тогда все окна останутся.
2. Приведите полный текст ошибки. Его можно взять из аллюра, если нажать сюда
![image](https://github.com/Pr-Mex/vanessa-automation/assets/8627416/f576a76a-4a91-4845-b3cc-bca817251ebe)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/8627416/3fcf066c-94d6-4fa2-96be-7d2522d0b520)

**Comment by dvissarov** [comment]
![image](https://github.com/Pr-Mex/vanessa-automation/assets/21277545/4400d87d-d297-4edd-a8a3-7b154d04ecbd)
пусто

**Comment by dvissarov** [comment]
![image](https://github.com/Pr-Mex/vanessa-automation/assets/21277545/db4e8bc4-c984-4c74-b18d-427eaab1e4ba)

**Comment by Pr-Mex** [comment]
@dvissarov 
Понятно. У вас из консоли запускается не та обработка. На скриншоте не Vanessa Automation.
Там в файле настроек vrunner где-то надо прописать путь к обработке VA. Это лучше в чате спросить где именно.

**Comment by dvissarov** [comment]
Ок спасибо
