### ISSUE TITLE
При выполнении фичи происходит ошибка парсера - не удается получить следующий шаг для выполнения

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#2027]
Версия Vanessa Automation 1.2.040.20
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

При выполнении фичи происходит ошибка парсера (вероятно), и не удается получить следующий шаг для выполнения
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/b5ef3eb3-40bc-44a5-9d95-cef0191650b1)

**Comment by Pr-Mex** [comment]
@akademik1986 
Нужна база и сценарий, чтобы можно было у себя воспроизвести.

**Comment by akademik1986** [comment]
База и сценарий в личке ТГ, на всякий тут это повторил.

**Comment by Pr-Mex** [comment]
@akademik1986 
Получилось воспроизвести. Починю.

**Comment by Pr-Mex** [comment]
Решено.
