### ISSUE TITLE
При выполнении "Получить проверку текущего элемента формы в виде шагов" по таблице сформированная таблица Gerkin содержит неверный порядок колонок

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#2029]
Версия Vanessa Automation 1.2.040.20
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

При выполнении "Получить проверку текущего элемента формы в виде шагов" по таблице сформированная таблица Gerkin содержит неверный порядок колонок

Фича для демонстрации 
[прикреплена тут](https://github.com/Pr-Mex/vanessa-automation/files/12394709/03.04.060.zip)

База для воспроизведения была дана в личке телеграмма 17.08.2023 

Нужно запустить фичу на выполнение и остановиться на шаге Тогда таблица "Таблица" стала равной по шаблону на строке 75, и выполнить команду "Получить проверку текущего элемента формы в виде шагов". При визуальном анализе порядок колонок в клиенте тестирования и полученный в VA различается.

**Comment by Pr-Mex** [comment]
@akademik1986 
Посмотрел.
Там две колонки с заголовком "Дата". И у обеих стоит признак видимости. Это видно в исследователе формы.
Поэтому алгоритм отказывается упорядочивать колонки.
Я сделаю доработку для этого случая, но она будет работать только начиная с 8.3.25, т.к. там появился метод получить родителя и можно быстро получать родителя элемента формы, чтобы проверить видимость группы элементов в таблице.

**Comment by Pr-Mex** [comment]
Решено.
