### ISSUE TITLE
Крашится тест при раскрытии справочника с номенклатурой одинарным щелчком

### ISSUE THREAD

**Issue by Prorogi** [Pr-Mex/vanessa-automation#2031]
Укажите:
   1. Версия Vanessa Automation - Vanessa Automation ver 1.2.040.20
   2. Версия платформы - 1С:Предприятие 8.3 (8.3.21.1895)
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система - Win 10

> Заполните шаблон обсуждения GIT

```Gherkin
#language: ru

@tree

Функционал: Создать Заказ

Как Администратор я хочу
создать Заказ и провести его
чтобы Заказ был проведен  

Контекст:
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: <описание сценария>
И В командном интерфейсе я выбираю 'Продажи' 'Заказы'
Тогда открылось окно 'Заказы товаров'
И я нажимаю на кнопку с именем 'ФормаСоздать'
Тогда открылось окно 'Заказ (создание)'
И из выпадающего списка с именем "Организация" я выбираю точное значение 'ООО "1000 мелочей"'
И из выпадающего списка с именем "Покупатель" я выбираю точное значение 'Магазин "Бытовая техника"'
И из выпадающего списка с именем "Склад" я выбираю точное значение 'Малый'
И в таблице "Товары" я нажимаю на кнопку с именем 'ТоварыДобавить'
И в таблице "Товары" я нажимаю кнопку выбора у реквизита с именем "ТоварыТовар"
Тогда открылось окно 'Товары'
И в таблице  "Список" я перехожу на один уровень вниз
И в таблице "Список" я перехожу к строке:
	| 'Код'       | 'Наименование' |
	| '000000030' | 'Колбаса'      |
И в таблице "Список" я выбираю текущую строку
Тогда открылось окно 'Заказ (создание) *'
И в таблице "Товары" я завершаю редактирование строки
И я нажимаю на кнопку с именем 'ФормаПровестиИЗакрыть'
И я жду закрытия окна 'Заказ (создание) *' в течение 20 секунд

```

> Прикладывайте файлы скриншотов
![ПричинаОшибки](https://github.com/Pr-Mex/vanessa-automation/assets/125183392/179190eb-c68a-4451-a347-e2c5405bacb1)
![ТекстОшибки](https://github.com/Pr-Mex/vanessa-automation/assets/125183392/3d8e7247-fc66-4907-9b90-7c2720dfcf2e)
![МоментОшибки](https://github.com/Pr-Mex/vanessa-automation/assets/125183392/22ceff2c-29a2-464e-8cbb-427be085858a)
![МестонахождениеНоменклатуры](https://github.com/Pr-Mex/vanessa-automation/assets/125183392/017742c2-0ee0-4cd5-a329-8faca9cdaed5)

**Comment by akademik1986** [comment]
Коллега, все правильно отработала vanessa.
у вас так
Тогда открылось окно 'Товары'
И в таблице  "Список" я перехожу на один уровень вниз

то есть открылась форма списка и сразу выполняется шаг раскрытия списка вниз, но раскрывается то первая строка ,которая активизировалась при открытии.
чтобы заработало вам нужно между этими шагами вставить и я перехожу к строке Продукты

**Comment by Prorogi** [comment]
Вас понял, благодарю.

**Comment by Pr-Mex** [comment]
@akademik1986 
Спасибо за помощь!
