### ISSUE TITLE
Продолжительное выполнение шагов в условии

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#2033]
Версия Vanessa Automation 1.2.040.20
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

База для воспроизведения была дана в личке телеграмма 17.08.2023
Фича для демонстрации
[Пример для issue.zip](https://github.com/Pr-Mex/vanessa-automation/files/12560371/issue.zip)

Обратить внимание на выполнение шагов
Если в таблице "ПоследовательностьШагов" текущая строка равна Тогда
Если элемент "******" присутствует на форме Тогда

![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/a3e90178-36e7-4d6e-a551-3b8ad7973b23)

визуально, когда запускаешь рядом менеджера и клиента тоже видно,что на клиенте строка в ТЧ активизировалась, а менеджер еще висит на на строке  и чего то думает
Если в таблице "ПоследовательностьШагов" текущая строка равна Тогда
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/35e2bf48-dd71-4412-abc3-20b4b5159133)

**Comment by Pr-Mex** [comment]
@akademik1986 
Думаю для начала можно включить замер производительности и выполнить один шаг. Сразу станет понятно на что ушло время.

**Comment by akademik1986** [comment]
Хорошая идея, не пришла в голову, только ЖР анализировал

**Comment by akademik1986** [comment]
по итогу, тормозит следующая комбинация шагов
И я включаю проверку видимости элементов с учётом видимости групп элементов
	Если элемент "ГруппаПользовательскийШагРедактируемыеПараметры" присутствует на форме Тогда
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/89750189-58ea-432a-9556-7b3542baf45f)

я так понимаю с этим ничего не сделать?

**Comment by akademik1986** [comment]
Спасибо.
Если можно, добавить замечание в описание шага.
