### ISSUE TITLE
Выполнение тестов зависает при падении шага в попытке

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#2035]
Версия Vanessa Automation 1.2.040.20
Версия платформы 8.3.20
Режим совместимости базы, где запускается Vanessa Automation 8.3.17
Операционная система windows

Есть таблица значений, сделанная в шаге "Я задаю таблицу строк"
Далее идет обход таблицы и в попытке выполняется экспортный шаг,в исключении стандартный шаг регистрации ошибки. 
И вот такая конструкция на боевом тесте приводит к зависанию всего процесса тестирования когда вся таблица уже обошлась, такое ощущение что начинает его прогонять заново и замирает.
В результате в логах видно, что последним сообщением при зависании находится ошибка
Не найден шаг, упавший в секции Попытка/Исключение.
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/ccdd0e44-a162-44e4-aae6-aa1b72772b7a)

Удалось накидать тестовый пример, но только по получению этой же ошибки, добиться зависания сценария не смог
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/ec1dba87-2da2-4444-9477-d1e8a9de8dcf)

вот ссылка на фичу
[пример ошибки.zip](https://github.com/Pr-Mex/vanessa-automation/files/12595884/default.zip)

Воспроизводится на любой базе, только во второй строке нужно задать реально существующий раздел и команду раздела

**Comment by akademik1986** [comment]
@Pr-Mex  приветствую!
А когда можно ожидать анализ данной ошибки? У меня на стопе уже накопилось много фич, которые ожидают решения по заведенным багам) Понимаю, что времени наверное нет, но мне хотя для понимания и планирования, хотя бы примерно.

**Comment by Pr-Mex** [comment]
@akademik1986 
Пока не получается добраться. Точных сроков назвать не могу.
И я не понял - указанные тестовый пример приводит к зависанию?
Ну и лучше проверять на самой новой версии, а не на 1.2.040.20.

**Comment by akademik1986** [comment]
@Pr-Mex релиз был последний на момент заведения issue. Но и на 41.1 ошибка осталась, поэтому и спросил.
Пример не помню приводит к зависанию или нет, но ошибку содержит точно.

**Comment by Pr-Mex** [comment]
@akademik1986 
Исправил. Спасибо за информацию!
