### ISSUE TITLE
Ошибка сохранения шаблона фичи со структурой сценария

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#2036]
Версия Vanessa Automation 1.2.040.20
Версия платформы 8.3.22
Режим совместимости базы, где запускается Vanessa Automation 8.3.21
Операционная система windows

При сохранении шаблона фичи с пустой структурой сценария выходит ошибка

14.09.2023 15:53:53 {ВнешняяОбработка.VanessaAutomation.Форма.ПарсерGherkin.Форма(573)}: Значение не является значением объектного типа (steps)

![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/49639708-cd83-4d60-95a6-61caacb0c0f2)

```
#language: ru

@tree
@ExportScenarios

Функционал: Управление разрешением

Структура Сценария: Отрицательная ЭПС - первичный расчет
		
Примеры: 
	| 'мВариантРасчетаГрафиков'                          |
	| 'Запретить'                                        |
	| 'Предупреждать' |
	| 'Разрешать'                                        |
```

**Comment by Pr-Mex** [comment]
Решено.
