### ISSUE TITLE
Ошибка при использовании шагов "И в табличном документе ""РеквизитТабличныйДокумент"" я перехожу на ""ЧислоЯчеек"" ячеек вправо/влево/вверх/вниз"

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#2045]
Версия Vanessa Automation 1.2.041.1
Версия платформы 8.3.22
Режим совместимости базы, где запускается Vanessa Automation 8.3.21
Операционная система windows

Ошибка возникает при использовании данного типа шагов, если текущая ячейка именованная
Пример показан на скриншотах
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/a1af688a-bab4-4cd0-a21b-40f979e549e5)

При использовании шага
И в табличном документе "ТабличныйДокумент" я перехожу на "2" ячеек вправо
получаем ошибку
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/550a03a2-7ce6-4031-acb3-666e85ad4224)

{ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(12074)}: Преобразование значения к типу Число не может быть выполнено

Технические данные:
        ЗаголовокАктивногоОкна: Строка 11956 "Активы, приобретаемые для передачи в лизинг", графа "На 31 января 2022 г." - расшифровка значения
        ИмяАктивнойФормы: ОбщаяФорма.РасшифровкаПоказателейРегламентированныхОтчетов
        ИмяФичи: НБО. Расшифровки
        ИмяСценария: НБО. Расшифровки
        НомерСтрокиДерева: 97
        НомерСтрокиФичи: 78
        ПолныйПутьКФиче: C:\jenkins\workspace\job_settings_work\regacc\features\03 Функциональные тесты\90 Последние проверки\03.90.020. Регучет. Настраиваемая бухгалтерская отчетность. Расшифровки.feature
        ИмяФайла: C:/Program Files/OneScript/lib/vanessa-automation/features/Libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом.epf
        ИмяПроцедуры: ВТабличномДокументеЯПерехожуНаЯчеекВправо
        ИмяРаннера: altsrv03
        ИмяКлиентаТестирования: REGACC_Empty_Тонкий
        СинонимКлиентаТестирования: REGACC_Empty_Тонкий
        ТипКлиентаТестирования: Тонкий
        СтрокаСоединения: Srvr="altsrv03";Ref="regacc_test1";
        ДопПараметрыПодключения: /N"Главный Бухгалтер" /UC
        PIDКлиентаТестирования: 16808
        ВерсияVA: ver 1.2.041.1
        ВерсияПлатформы: 8.3.22.2143
        ТипПлатформы: Windows x86-64
        РежимСовместимостиTestManager: Версия8_3_21
        ВремяРаботыСценария: 0:00:02 (ч:м:с)
        ДатаВремяОшибки: 25.09.2023 15:33:42

**Comment by Pr-Mex** [comment]
@akademik1986 
@JaneGlass73
Это не ошибка. В апи платформы метод ПолучитьАдресТекущейОбласти() так работает.
Для именованных ячеек возвращается имя ячейки и по нему нельзя определить реальный адрес в формате RC.



![image](https://github.com/Pr-Mex/vanessa-automation/assets/8627416/8bdeb243-820f-4e81-bdbe-cbdea3ba3f4c)

**Comment by JaneGlass73** [comment]
@Pr-Mex собственно сейчас у Вас есть другой шаг, который ищет значение и возвращает реальный адрес ячейки, в которой это значение есть, вне зависимости именованная она или нет. Этого достаточно. Потому что обычно эти шаги предварял поиск значения в таблице (ну у меня по крайней мере) в потом от найденного значения происходил сдвиг по строке вправо или влево. Например искали аналитику потом получили по ней значение из следующей колонки. Теперь не критично. Кстати когда в релиз отправится этот шаг? А то тестировщики некоторые не такие продвинутые чтобы из исходников собирать.

**Comment by Pr-Mex** [comment]
@JaneGlass73 
Релиз планирую, когда исправлю найденные проблемы. Думаю в течение месяца.
