### ISSUE TITLE
Некорректное выполнение условия в контексте при отсутствии шагов в самом сценарии

### ISSUE THREAD

**Issue by 1cgh** [Pr-Mex/vanessa-automation#2047]
Укажите:
   1. Версия Vanessa Automation 1.2.041.1

```Gherkin
#language: ru

Функционал: <описание фичи>

Контекст:
	Если существует переменная "ИмяПеременной1" Тогда
		И я вывожу значение переменной "ИмяПеременной1"

Сценарий: Сценарий 1

Сценарий: Сценарий 2
	И Пауза 2
```

Странное поведение при выполнении условий в контексте при отсутствии шагов в сценарии.
Условие выполняется, хотя переменной не существует.
Если в сценарии есть шаги (Сценарий 2), то условие отрабатывает корректно.
Если добавить Иначе в условие в контексте, то оно тоже начинает работать корректно.

В целом есть вопрос: если в сценарии нет шагов, то должен ли он выполняться (должны ли выполняться секции Контекст и Переменные для такого сценария)?

![image](https://github.com/Pr-Mex/vanessa-automation/assets/24507052/d87728d1-cd65-4188-8cc5-89b4440ecc22)

**Comment by Pr-Mex** [comment]
Решено.
