### ISSUE TITLE
При использовании шага "И я заполняю таблицу "ИмяТаблицы" данными" ошибка, если колонка содержит многострочный заголовок

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#2053]
Версия Vanessa Automation 1.2.041.1
Версия платформы 8.3.22
Режим совместимости базы, где запускается Vanessa Automation 8.3.21
Операционная система windows

При использовании шага "И я заполняю таблицу "ИмяТаблицы" данными" ошибка, если колонка содержит многострочный заголовок
например,
И я заполняю таблицу "ТаблицаГрафика" данными
		| 'Дата'       | 'Лизинговый\nплатеж' | 'Аванс\nначальный'   | 'Выкуп\nплан' |
		| '15.01.2022' | ''                   | '12 000,00' | ''            |
		| '20.02.2022' | '10 500,00'          | ''          | ''            |
		| '20.03.2022' | '8 500,00'           | ''          | ''            |
		| '20.04.2022' | '8 500,00'           | ''          | ''            |
		| '20.05.2022' | '8 500,00'           | ''          | ''            |
		| '20.06.2022' | '8 500,00'           | ''          | ''            |
		| '20.07.2022' | '8 500,00'           | ''          | ''            |
		| '20.08.2022' | '7 500,00'           | ''          | '1 000,00'    |

**Comment by Pr-Mex** [comment]
Решено.
