### ISSUE TITLE
Не работает функция "Получить проверку текущего элемента формы в виде шагов"

### ISSUE THREAD

**Issue by Tatyana1997** [Pr-Mex/vanessa-automation#2054]
Укажите:
   1. Версия Vanessa Automation 1.2.041.1
   2. 8.3.20.1549
   3. Серверный (сжатие: усиленное, Менеджер тестирования)
   4. Windows 10 Pro

Клиент тестирования подключен, в клиенте тестирования активирую поле ввода, далее в менеджере тестирования нажимаю на "Получить проверку текущего элемента формы в виде шагов".

![image](https://github.com/Pr-Mex/vanessa-automation/assets/142234362/06b61ea4-ca19-48fd-a12b-47df76359498)
При попытке проверить данные текущего элемента формы в виде шагов возникает ошибка:
![image](https://github.com/Pr-Mex/vanessa-automation/assets/142234362/2e0d8eff-d236-45c9-acb2-2fc72326dbca)

Подскажите, пожалуйста, может я что-то делаю не так?

**Comment by Pr-Mex** [comment]
@Tatyana1997 
Обсудили в чате. Надо обновить платформу.

**Comment by Tatyana1997** [comment]
Спасибо за ответ!
