### ISSUE TITLE
Ошибка отображения результатов выполнения в allure отчете при использовании попытки в цикле

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#2058]
Версия Vanessa Automation 1.2.041.1
Версия платформы 8.3.22
Режим совместимости базы, где запускается Vanessa Automation 8.3.21
Операционная система windows

Допустим в тексте фичи используется в цикле попытка/исключение
Пока не встретилось первое исключение в allure отчете все отображается корректно
Когда вышла первая ошибка, тогда все последующие шаги в отчете отображаются попавшими в исключение, хотя шаг в попытке верный и не должен быть упавшим (рис.1). В шапке отчета в фиче указано верное количество найденных ошибок, однако в самом отчете уже после первой ошибки каждый шаг показывает, как будто была ошибка, и столько же прикрепляет файлов к ошибкам шагов.
Затем мы видим несоответствие строк в массиве и отображаемых строк цикла в allure отчет (рис.2). Последний шаг отображается пустым.

![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/a9c4e8f7-964f-41ad-9e2d-25342d616399)

 
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/1f49cec1-7281-4e39-b3d0-872589b938cc)

Текст фичи
`#language: ru
@tree
Функционал: тестирование ошибки в попытке в цикле
Контекст:
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий
Сценарий: тестирование ошибки в попытке в цикле
	Дано Я задаю таблицу строк "НоменклатурныеГруппы"
		| 'Наименование'              | 'РасходыПоНУ' |
		| 'Лизинговая деятельность'   | 'Да'          |
		| 'Продажа предметов лизинга' | 'Нет'         |
		| 'Прочие услуги'             | 'Да'          |
		| 'Остальные услуги'          | 'Нет'         |
		| 'Прочая номенклатура'       | 'Да'          |
		| 'Прочее'                    | 'Да'          |
	И для каждого значения "ЗначениеИзТаблицы" из таблицы в памяти "НоменклатурныеГруппы"
		И Я запоминаю в переменную "ИмяПеременной" значение "$РасходыПоНУ$"
		Попытка
			Тогда переменная "ИмяПеременной" имеет значение "Да"
		Исключение
			И я регистрирую ошибку "Произошла ошибка в попытке" по данным исключения`

**Comment by akademik1986** [comment]
не очень вставило код, попробую еще раз

#language: ru
@tree
Функционал: тестирование ошибки в попытке в цикле
Контекст:
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий
Сценарий: тестирование ошибки в попытке в цикле
	Дано Я задаю таблицу строк "НоменклатурныеГруппы"
		| 'Наименование'              | 'РасходыПоНУ' |
		| 'Лизинговая деятельность'   | 'Да'          |
		| 'Продажа предметов лизинга' | 'Нет'         |
		| 'Прочие услуги'             | 'Да'          |
		| 'Остальные услуги'          | 'Нет'         |
		| 'Прочая номенклатура'       | 'Да'          |
		| 'Прочее'                    | 'Да'          |

	И для каждого значения "ЗначениеИзТаблицы" из таблицы в памяти "НоменклатурныеГруппы"
		И Я запоминаю в переменную "ИмяПеременной" значение "$РасходыПоНУ$"
		Попытка
			Тогда переменная "ИмяПеременной" имеет значение "Да"
		Исключение
			И я регистрирую ошибку "Произошла ошибка в попытке" по данным исключения

**Comment by Pr-Mex** [comment]
@akademik1986 
Проверил на актуальной версии.
Отображается корректно
![image](https://github.com/Pr-Mex/vanessa-automation/assets/8627416/35689d2a-a1e3-4e8f-9d2e-8fdb454d4a64)

**Comment by akademik1986** [comment]
@Pr-Mex а последний скрин тоже проверил? У меня последний шаг цикла в аллюре на последней выпущенной версии все равно пустой без шагов

**Comment by Pr-Mex** [comment]
> @Pr-Mex а последний скрин тоже проверил? У меня последний шаг цикла в аллюре на последней выпущенной версии все равно пустой без шагов

Последний шаг цикла в реальности выполняется ещё раз. Как раз в этот момент принимается решение, что тело цикла выполнять дальше не надо.
