### ISSUE TITLE
При открытии файла Vanessa Automation возникает ошибка "Неизвестный идентификатор формы"

### ISSUE THREAD

**Issue by AleyMih** [Pr-Mex/vanessa-automation#2060]
Укажите:
   1. Версия Vanessa Automation = 1.2.041.1
   2. Версия платформы  = 8.3.22.1709
   3. Режим совместимости базы, где запускается Vanessa Automation = Версия 8.3.17
   4. Операционная система = Windows Server 2019 Standard. Версия 1809. 64-разрядная.

При открытии файла Vanessa Automation возникает ошибка "Неизвестный идентификатор формы"
в форме УправляемаяФорма.
В процедуру ПроверкаВозможностиОптимизацииРаботыСФайлами(ДопПараметры) не заходит.

> Прикладывайте файлы скриншотов
![image](https://github.com/Pr-Mex/vanessa-automation/assets/149932837/1c7af82e-6f1c-4e43-9de1-838c7333947f)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/149932837/0158e111-8cca-4878-beaa-c4b4cf8650b2)

**Comment by Pr-Mex** [comment]
Посмотрите тут
https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/MainHelp/index.MD

![image](https://github.com/Pr-Mex/vanessa-automation/assets/8627416/dd290699-2d97-4853-8ae0-040813c00782)
