### ISSUE TITLE
При переоткрытии экспортного сценария не сохраняются его изменения

### ISSUE THREAD

**Issue by Reheab** [Pr-Mex/vanessa-automation#2080]
Версия Vanessa Automation 1.2.041.1
Версия платформы 8.3.22.2239
Режим совместимости базы, где запускается Vanessa Automation
Операционная система WIndows 10

При переоткрытии экспортного сценария не сохраняются его изменения

Воспроизведение:
1. открыть основную фичу
3. перейти в экспортный сценарий
4. внести в экспортный сценарий любые изменения
5. не сохраняя и не закрывая экспортный сценарий, вернуться во вкладку основной фичи
6. снова открыть экспортный сценарий по кнопке "Открыть подсценарий в новой вкладке"
Результат: внесенные данные в эксп. сценарий не сохранятся

![image](https://github.com/Pr-Mex/vanessa-automation/assets/125824399/b860a4f6-ea90-4c2c-a7ac-6720a7030206)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/125824399/8c102146-866e-4563-9cf0-312eeba124d2)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/125824399/5c038890-23d1-4efe-900c-4dd8a85ab423)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/125824399/a8df9175-54e0-474f-bbf2-67721a2808c8)

По-правильному, нужно просто вернуться в открытую фичу экспортного сценария без потери внесенных данных

**Comment by Pr-Mex** [comment]
@Reheab 
Да, скорее всего нет проверки, что уже есть вкладка.

**Comment by Pr-Mex** [comment]
Решено.
