### ISSUE TITLE
отличается  работа обработки anessa-automation-single.epf если в командной строке ключ StartFeaturePlayer; или нет.

### ISSUE THREAD

**Issue by ilyanet** [Pr-Mex/vanessa-automation#2091]
Укажите:
   1. Версия Vanessa Automation
        ВерсияVA: ver 1.2.041.1
   2. Версия платформы
       1С:Предприятие 8.3 (8.3.18.1616)
   3. Режим совместимости базы, где запускается Vanessa Automation
       Версия 8.3.15
   4. Операционная система
        ТипПлатформы: Windows x86-64
        Windows 10 Pro

Использую vanessa-automation-single.epf
собранную по инструкции https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/MakeVASingle/MakeVASingle.md

Запускаю из командной строки
C:\Program Files\1cv8\8.3.18.1616\bin\1cv8.exe ENTERPRISE /IBConnectionString Srvr=<сервер>;Ref=<база>; Usr=Администратор;
/TestManager /Execute D:\GIT\tools\vanessa-automation\vanessa-automation-single.epf /CStartFeaturePlayer;КаталогФич=D:\GIT\features;ПутьКФайлуДляВыгрузкиСтатусаВыполненияСценариев=D:\GIT\DumpVanessa.r;VAParams=D:\GIT\tools\vanessa-automation\VAParams.json;ИмяКаталогаЛогОшибок=D:\GIT\LogVanessa;КаталогФайловВыводаСлужебныхСообщений=D:\GIT\OutVanessa;ИмяФайлаЛогВыполненияСценариев=D:\GIT\Out.log;ЗагрузкаФичПриОткрытии=4;

Файл параметров
[VAParams.json](https://github.com/Pr-Mex/vanessa-automation/files/14137147/VAParams.json)

**Проблема** заключается в том что работа обработки отличается если в командной строке ключ StartFeaturePlayer; или нет.
с ключом  StartFeaturePlayer; обработка запускается и отрабатывает фичи все ок. 
без ключа StartFeaturePlayer; выскакивают ошибки:
предположение не подхватываются параметры командной строки.

Пример ошибки:
02.02.2024 10:57:21 Ошибка при построении дерева из файла <D:\GIT\features\init_00.feature>
{ВнешняяОбработка.VanessaAutomationsingle.Форма.УправляемаяФорма.Форма(22562)}: Не указано имя файла лога в параметре <ИмяКаталогаЛогОшибок>

ИмяКаталогаЛогОшибок -параметр есть в командной строке

Мое обходное решение:
Исправил СтруктураПараметровКоманднойСтроки на ПараметрыЗапуска
ВнешняяОбработка.VanessaAutomationsingle.Форма.УправляемаяФорма.Форма(50106)
```bsl
//Обработка настроек переданных в командной строке
Если ТипЗнч(ДополнительныеПараметры) = Тип("Структура") И ДополнительныеПараметры.Свойство("СтруктураПараметровКоманднойСтроки") Тогда
	СтруктураПараметровКоманднойСтроки = ДополнительныеПараметры.СтруктураПараметровКоманднойСтроки;
Иначе	
	СтруктураПараметровКоманднойСтроки = Неопределено;
КонецЕсли;
```
на
```bsl
//Обработка настроек переданных в командной строке
Если ТипЗнч(ДополнительныеПараметры) = Тип("Структура") И ДополнительныеПараметры.Свойство("ПараметрыЗапуска") Тогда
	СтруктураПараметровКоманднойСтроки = ДополнительныеПараметры.ПараметрыЗапуска;
Иначе	
	СтруктураПараметровКоманднойСтроки = Неопределено;
КонецЕсли;
```

**Comment by Pr-Mex** [comment]
@ilyanet 
Тут надо разбираться. Пока не понятно.

**Comment by Pr-Mex** [comment]
@ilyanet 
Проверил на текущей версии. Ошибка не воспроизвелась.
Просьба проверить тоже самое у себя.

**Comment by ilyanet** [comment]
@Pr-Mex
Проверил.
Действительно. на новой(1.2.041.18) версии ошибка не воспроизводится.
Все нормально спасибо.
