### ISSUE TITLE
Ошибка ввода текста в HTML документ

### ISSUE THREAD

**Issue by NikitaKazancev** [Pr-Mex/vanessa-automation#2092]
Укажите:
   1. Версия Vanessa Automation - 1.2.041.1
   2. Версия платформы - 8.3.22.1923, но ошибка воспроизводится и на других версиях, например, на 8.3.23.1688, 8.3.24.1368
   3. Режим совместимости базы, где запускается Vanessa Automation - 8.3.21
   4. Операционная система - Windows 10

Шаги "ВПолеЯВвожуТекст", "ВПолеСИменемЯВвожуТекст", "ВПолеЯВвожуТекстИзМакета", "ВПолеСИменемЯВвожуТекстИзМакета" не работают с HTML-документом (по крайней мере в тонком клиенте, за веб-клиент не могу говорить, у меня тут с ним пока другие проблемы).
Если специально самому установить курсор в HTML документ, то ошибка все равно остается (думал, может, курсор не видит).

На самом деле тут для нас это очень важная ошибка, т.к. у нас достаточно много таких HTML-документов, которые надо протестировать. Пожалуйста, ответьте, как сможете, может, просто я что-то делал не так.

Прикладываю скриншот ошибки и описание ошибки:

![2024-02-02_16-51-56](https://github.com/Pr-Mex/vanessa-automation/assets/87575708/5d781792-0969-412e-8337-dc51dc7f52b1)
[Ошибка.txt](https://github.com/Pr-Mex/vanessa-automation/files/14140963/default.txt)

**Comment by Pr-Mex** [comment]
@NikitaKazancev 
Попробуйте вводить не просто текст в поле - а текст в формате HTML

**Comment by NikitaKazancev** [comment]
Да, извиняюсь, что сразу не прикрепил и такой пример. Ошибка при вводе HTML такая же. 
На скрине снизу показал ошибку при попытке ввода одного случая верстки, но она возникает и при остальных 7-и случаях, добавленных там снизу на скрине (не стал для всех скрины прикладывать).

Мне это просто важно, т.к., вероятно, мы постепенно будем вообще отказываться от форматированного документа (вплоть до того, пока его кто-нибудь не улучшит) в пользу HTML. Ну и соответственно да, нам бы хотелось его везде тестировать.

![image](https://github.com/Pr-Mex/vanessa-automation/assets/87575708/b57e3854-76a4-4b4c-bd3f-13a4a1c2be83)

**Comment by NikitaKazancev** [comment]
@Pr-Mex 
Да, извиняюсь, что сразу не прикрепил и такой пример. Ошибка при вводе HTML такая же.
На скрине снизу показал ошибку при попытке ввода одного случая верстки, но она возникает и при остальных 7-и случаях, добавленных там снизу на скрине (не стал для всех скрины прикладывать).

Мне это просто важно, т.к., вероятно, мы постепенно будем вообще отказываться от форматированного документа (вплоть до того, пока его кто-нибудь не улучшит) в пользу HTML. Ну и соответственно да, нам бы хотелось его везде тестировать.

![2024-02-13_12-21-40](https://github.com/Pr-Mex/vanessa-automation/assets/87575708/f367d359-84d7-4521-9173-c149b6b687fe)

**Comment by Pr-Mex** [comment]
@NikitaKazancev 
Посмотрел, ошибки нет. В текущем апи платформы нет метода для установки текста в поле HTML документа.
Но если речь идёт про ДО, то там элемент формы "ТекстПисьмаHTML" связан в реквизитом "ТекстПисьма".
И текст письма легко можно изменить, например вот так
```Gherkin
И я выполняю выражение '_ТекущееОкно.ТекстПисьма = "<h3>333333333333333333333</h3"' в текущем окне (Расширение)
```

Подробнее см тут
https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/VAExtension/VAExtension.md
