### ISSUE TITLE
Добавить шаг очистки таблицы клиентов тестирования

### ISSUE THREAD

**Issue by Reheab** [Pr-Mex/vanessa-automation#2102]
- Версия Vanessa Automation 1.2.041.1
- Версия платформы 8.3.22.2239
- Операционная система Виндовс 10 про

Добавить шаг очистки таблицы клиентов тестирования
![Ошибка загрузки картинки](https://i.postimg.cc/gkkdhKv9/Screenshot-36.png)

Возникла следующая проблема: в базу был загружен dt и запущены тесты, потом оказалось, что в клиентах тестирования уже была подключена другая база, и тесты выполнялись на ней, а не на базе-менеджере тестирования.
Проверять вручную-очищать постоянно возможности нет.

Поэтому хотелось бы добавить шаг, полностью очищающий таблицу клиентов тестирования, кроме текущей базы - менеджера тестирования.
Также было бы удобно если бы аналогичная настройка была для json-файла при запуске тестов

**Comment by Pr-Mex** [comment]
@Reheab 
Посмотрите тут.
Есть параметр, который управляет, чтобы не загружались клиенты тестирования
https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/CommandSetting/CommandSetting.md

**Comment by Reheab** [comment]
Спасибо!
