### ISSUE TITLE
Не переключается на страницу запуска сценариев при нажатии на кнопку "дерево шагов" из любой другой страницы

### ISSUE THREAD

**Issue by alei1180** [Pr-Mex/vanessa-automation#2103]
- Версия Vanessa Automation 1.2.041.1
- Версия платформы 8.3.23
- Режим совместимости базы, где запускается Vanessa Automation 8.3.12
- Операционная система Windows 10 Pro

Находясь на странице запуска сценариев кнопка "дерево шагов" отрабатывает ожидаемо без проблем.

Но если перейти на любую другую страницу и нажать на кнопку "дерево шагов" то панель кнопок меняется на присущую дереву шагов, но не происходит перехода на страницу запуска сценариев для просмотра дерева шагов. 

Прикладываю скришоты:
![image](https://github.com/Pr-Mex/vanessa-automation/assets/43796905/7fbd0ccb-0079-4974-9bf7-4799804a6374)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/43796905/e32e81cd-1118-4225-b0a6-14a2c8f42d41)

Ожидаю что страница при нажатии на кнопку дерево шагов сменится на страницу "запуска сценариев".

**Comment by Pr-Mex** [comment]
Решено
