### ISSUE TITLE
При выполнении экспортного сценария в Контексте, он выполняется 2 раза

### ISSUE THREAD

**Issue by Reheab** [Pr-Mex/vanessa-automation#2108]
Укажите:
   1. Версия Vanessa Automation 1.2.041.1
   2. Версия платформы 8.3.23.2040
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система Windows

При выполнении только одного экспортного сценария (по кнопке F11), расположенного в Контексте, он выполняется 2 раза:
![image](https://github.com/Pr-Mex/vanessa-automation/assets/125824399/347b26fd-ed30-40c3-9224-70653d4fc382)

экспортный сценарий:
![image](https://github.com/Pr-Mex/vanessa-automation/assets/125824399/369b33aa-311d-4e74-bfec-9faaae4a69a2)

Если шаг не в экспортном сценарии, то выполняется 1 раз:
![image](https://github.com/Pr-Mex/vanessa-automation/assets/125824399/433a8d74-e07e-44ac-8982-1ab55b72a054)

**Comment by Pr-Mex** [comment]
Решено.
