### ISSUE TITLE
Переменную из шага "И Я запоминаю случайное число в переменную """ нельзя вставить в текст

### ISSUE THREAD

**Issue by Reheab** [Pr-Mex/vanessa-automation#2115]
Укажите:
   1. Версия Vanessa Automation 1.2.041.1
   2. Версия платформы 8.3.22.2239
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система Windows 10

Переменную из шага "И Я запоминаю случайное число в переменную """ нельзя использовать в сочетании в другим текстом, переменная не подставляется в текст.
![не грузится картинка](https://imgbly.com/ib/8XOS6zouAg.png)
*******
Другие переменные, например из шага "И Я запоминаю в переменную "КодSluch1" значение "123"" отрабатывают корректно:
![не грузится картинка](https://imgbly.com/ib/fHOFtQPD3F.png)

**Comment by Pr-Mex** [comment]
@Reheab 
Числовые переменные не вставлются, когда идёт попытка их вставить в $.
Нужно переменную преобразовать к строке.
