### ISSUE TITLE
Ошибка при открытии файла с помощью шага И я выбираю файл "$ИмяФайла1$" ВК

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#2116]
Задача следующая: нужно проверить формируемые 1C:ФинОтчетность заполненные отчеты, однако на агенте нет Excel.

Проверил - через Файл - Открыть xlsx открывается как mxl и там уже можно организовать поиск нужной информации.
Однако столкнулся с тем, что шаг И я выбираю файл "ИмяФайла" не работает. Попробовал И я выбираю файл "ИмяФайла" ВК, но тоже не работает, во первых открывается какой то пустой файл где просто путь к файлу указан, и еще он модифицируется при выполнении теста, вставляя туда какие то куски текста
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/8bf42f63-354e-4454-aa37-c3a612ec30f8)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/16ba8aa8-dda4-431b-8f0c-220020a6a356)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/faa88d8b-c2f2-4334-82ca-8c6ba3fabc40)

Ниже привожу фичу, которую можно запустить наверное на любой конфигурации, где есть спр. Организации.
Вопрос собственно почему так странно работает открытие файла этими шагами, в них ли ошибка? и как решить задачу, может есть еще решение?

```
#language: ru
@tree
Функционал: ошибка открытия файлов
Переменные:
	СсылкаНаФормуСпискаОрганизации = "e1cib/command/ОбщаяКоманда.Организации"
Контекст:
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий
Сценарий: ошибка открытия файлов

	Дано Я открываю навигационную ссылку "$СсылкаНаФормуСпискаОрганизации$"
	Тогда открылось окно "Организации"

	* Сохраним список и откроем сохраненный эксель (Раз)
		И я нажимаю на кнопку с именем 'ФормаВывестиСписок'
		Тогда открылось окно 'Вывести список'
		И я нажимаю на кнопку с именем 'Ok'
		Тогда открылось окно 'Список'
		И Я запоминаю значение выражения '$КаталогПроекта$\\СписокОрганизаций1.mxl' в переменную "ИмяФайла1"
		И я выбираю файл '$ИмяФайла1$'
		И я сохраняю данные элемента формы с именем 'SpreadsheetDocument' в файл
		И я закрываю текущее окно

		И я активизирую окно текущего клиента тестирования
		И я выбираю файл "$ИмяФайла1$" ВК
		Тогда открылось окно "$ИмяФайла1$"
		Тогда табличный документ "" содержит значения:
			| 'Наименование в программе' |		

	* Сохраним список и откроем сохраненный эксель (Два)
		И Я запоминаю значение выражения '$КаталогПроекта$\\СписокОрганизаций2.mxl' в переменную "ИмяФайла2"
		И я выбираю файл '$ИмяФайла2$'
		И я сохраняю данные элемента формы с именем 'SpreadsheetDocument' в файл
		И я закрываю текущее окно

		И я активизирую окно текущего клиента тестирования
		И я выбираю файл "$ИмяФайла1$" ВК
		Тогда открылось окно "$ИмяФайла1$"
		Тогда табличный документ "" содержит значения:
			| 'Наименование в программе' |			
```

**Comment by Pr-Mex** [comment]
@akademik1986 
Шаг
И я выбираю файл
перехватывает диалог открытия файлов, если он создан программно.
Если нужно просто открыть файл, эмулируя по сути ctrl+O, то данный шаг такое не сделает, т.к. апи платформы такое не поддерживает.
Но можно открыть произвольный файл кодом, а код выполнить расширением
https://github.com/Pr-Mex/vanessa-automation/blob/develop/docs/VAExtension/VAExtension.md

**Comment by akademik1986** [comment]
Там есть шаг, на который я смотрел, но он только для обработок и отчетов (И я открываю внешнюю обработку или отчет "ИмяФайла" (Расширение) ). Не будет ли полезным наличие шага, открывающего любой файл по имени?

**Comment by akademik1986** [comment]
@Pr-Mex помоги пожалуйста, уже пару часов бьюсь, не пойму как добиться открытия файла
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/d0747ebe-a433-4632-b3d6-00601c77a2fd)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/2caacd53-e5fa-47d3-af43-094c4832d39e)

не пойму как победить, чтобы это не было связано с реквизитом формы...

**Comment by akademik1986** [comment]
В итоге плюнул, в расширение добавил форму и кнопку открытия) 
Вопрос для себя решил, задачу можно закрывать, если только не решишь ее оставить для добавления шага по открытию произвольного файла

**Comment by Pr-Mex** [comment]
@akademik1986 
Да, добавлю шаг для открытия файлов макетов и текстовых файлов.
