### ISSUE TITLE
Возможность сохранения текста фичи при редактировании

### ISSUE THREAD

**Issue by marmyshev** [Pr-Mex/vanessa-automation#212]
Хотелось бы иметь возможность открывать-редактировать-сохранять файл фичи.

На текущий момент не понятно, что именно загружено в редактор (текстовое поле) а что за фича находится в дереве.

Полагаю, что было бы логичнее при открытии фича-файла загружать его редактор, если там находится текст, предлагать сохранять (если модифицирован). Или хотя бы спрашивать, стоит ли загрузить в редактор...

С учетом того что Платформа может упасть, было бы удобно текст который редактируешь в ВА можно было бы сохранять.

**Comment by Pr-Mex** [comment]
Закрываю, т.к. выходит новый редактор для VA.
