### ISSUE TITLE
Полноценный редактор на платформе 8.3.14

### ISSUE THREAD

**Issue by marmyshev** [Pr-Mex/vanessa-automation#213]
С учетом возможностей 8.3.14 - было бы удобно редактировать файлы и запускать их сразу же в одном окне.

Подсветку синтаксиса и контент-ассист для шагов (подключаемых из библиотек) и терминов геркина 1С - очень нужны!
Может быть @atridis сделает фичу?

**Comment by Pr-Mex** [comment]
Закрываю, т.к. выходит новый редактор для VA.
