### ISSUE TITLE
Каталоги библиотек не загружаются из переменных среды или параметра запуска.

### ISSUE THREAD

**Issue by smilut** [Pr-Mex/vanessa-automation#2132]
1. Версия Vanessa Automation: 1.2.041.15  
2. Версия платформы: 8.3.24.1342  
3. Режим совместимости базы: 8.3.21  
4. Операционная система: Windows Server 2022 Standart  
  
Проблема возникает в двух случаях при указании списка каталогов библиотек в переменных среды и при передаче списка в параметре запуска, при этом из файла настроек список каталогов библиотек загружается корректно.  

Отладкой VA single выявлено, что при обработке значений параметров запуска в функции 
модуля объекта СтруктураОбщихНастроек(...) для параметра КаталогиБиблиотек установлен тип Строка. При этом для параметров с аналогичным функционалом, например СписокТеговИсключений, установлен тип Массив. Замена типа решает проблему загрузки настройки из параметра запуска.  
  
Проблема при загрузке через переменные среды несколько сложнее.   
При обработке данных переменных среды используется функция ОбщегоНазначенияVA.КоллекцияКомандЗапуска() для получения сопоставления англоязычных имен параметров.   
Коллекция команд строится на базе структуры возвращаемой функцией ОбщегоНазначенияVA.СтруктураПараметровЗапуска().  
Функция СтруктураПараметровЗапуска() в качестве кеша использует глобальную переменную модуля формы ОбщегоНазначенияVA ПлоскаяСтрутураПараметровЗапуска, которая после создания структуры параметров возвращается функцией для создания структуры сопоставления имен команд.  
Т.к. структуры между функциями передаются по ссылке, то при заполнении коллекции команд происходит перезапись данных переменной ПлоскаяСтрутураПараметровЗапуска и далее, т.к. тип свойства КаталогиБиблиотек меняется с Массива (в исправленном варианте) на Структуру, обработка параметра КаталогиБиблиотек выполняется не корректно.  

Для исправления необходимо при формировании коллекции команд создавать копию структуры параметров запуска и уже на базе копии формировать коллекцию команд.

Вопрос в том нужно ли делать форк и исправление? Потому что функция КоллекцияКомандЗапуска отмечена как устаревшая и возможно в следующем релизе  данной функции уже не будет.

Скрины:
![2024-05-07_12-08](https://github.com/Pr-Mex/vanessa-automation/assets/41290917/65a8d3c9-45f9-4774-87c0-26a6790d8dae)
![2024-05-07_12-12](https://github.com/Pr-Mex/vanessa-automation/assets/41290917/2ce5509b-253b-4c96-b3dc-3d9ffab88021)

**Comment by Pr-Mex** [comment]
@smilut 
1. Как вы задаёте переменную среды, чтобы задать каталоги библиотек?
2. Как вы передаёте каталоги библиотек через параметр запуска?
Нужны примеры.

**Comment by smilut** [comment]
через переменные среды: VANESSA_librarycatalogs
![image](https://github.com/Pr-Mex/vanessa-automation/assets/41290917/729fef52-fd1e-4820-946a-0c097625f2c5)

и через параметр запуска: КаталогиБиблиотек=C:\_ERP\ExportScenarios

**Comment by Pr-Mex** [comment]
@smilut 
Разобрался. Да, ПлоскаяСтрутураПараметровЗапуска передавалась по ссылке.
Поправлю.

**Comment by Pr-Mex** [comment]
Решено.
