### ISSUE TITLE
"Продолжить с текущего шага с продолжением" в структуре сценария отрабатывает неверно

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#2145]
Версия Vanessa Automation 1.2.041.15
Версия платформы 8.3.22
Режим совместимости базы, где запускается Vanessa Automation 8.3.21
Операционная система windows

Если поставить точку останова на шаге структуры сценария и потом выбрать "Продолжить с текущего шага с продолжением", то выполнение фичи начнется с первого примера структуры сценария и с его налача.
Например, поставим точку останова на шаге "Допустим в окне сообщений пользователю нет сообщений" , очистим окно сообщений в ванессе, и запустим  "Продолжить с текущего шага с продолжением", то в сообщениях будет перечислены все примеры, хотя должны были только со второго
```
$_НомерДоговора$ = один
28.05.2024 14:38:57 Выполняется сценарий: <тест (Пример №1)>.
28.05.2024 14:38:57 Выполняется сценарий: <тест (Пример №2)>.
$_НомерДоговора$ = два
28.05.2024 14:38:57 Выполняется сценарий: <тест (Пример №3)>.
$_НомерДоговора$ = три
28.05.2024 14:38:57 Выполняется сценарий: <тест (Пример №4)>.
$_НомерДоговора$ = четыре
28.05.2024 14:38:58 Выполнение сценариев закончено. Ошибок не было.
```

И еще момент, что больше на этой точке останова VA не остановится.

```1c-enterprise

#language: ru
@tree
Функционал: пример структуры сценария
Контекст:
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Структура Сценария: тест

	И я запоминаю строку <мНомерДоговора> в переменную "_НомерДоговора"
	И я вывожу значение переменной "$_НомерДоговора$"
	Допустим в окне сообщений пользователю нет сообщений
	И я запоминаю количество окон в переменную "ИмяПеременной"

Примеры:
	| 'мНомерДоговора' |
	| 'один'           |
	| 'два'            |
	| 'три'            |
	| 'четыре'         |


```

**Comment by Pr-Mex** [comment]
@akademik1986 
Посмотрел как сделано в дереве шагов.
Если нужно продолжить с конкретной строки конкретного примера - надо включить отображение строк подсценариев/примеров и выполнять сценарий с нужной строки.

**Comment by akademik1986** [comment]
Спасибо!
