### ISSUE TITLE
"Выполнить с текущего шага..." отрабатывает некорректно для экспортных сценариев, начинающихся с Попытки-Исключения

### ISSUE THREAD

**Issue by Reheab** [Pr-Mex/vanessa-automation#2147]
Укажите:
   1. Версия Vanessa Automation 1.2.041.15
   2. Версия платформы 8.3.22.2239
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система Windows 10

Скорее всего часть ошибки [#2150](https://github.com/Pr-Mex/vanessa-automation/issues/2150)

Если в экспортном сценарии есть "Попытка-Исключение" в начале сценария, то при запуске экспортного сценария через "Выполнить с текущего шага" и "Выполнить с текущего шага с продолжением" сценарий начинает отрабатывать не с выбранного экспортного сценария, а с начала сценария вообще.

В примере был запущен с шага "тестирование экспортный1", а выполнился весь сценарий

![картинка](https://imgbly.com/ib/AtLH6f9iVJ.png)

Если Попытки-Искл нет в начале сценария или она не в начале, то отрабатывает корректно с выбранного экспортного сценария

![картинка](https://imgbly.com/ib/2mcMUreiki.png)

**Comment by Pr-Mex** [comment]
Решено.
