### ISSUE TITLE
Избавиться от Сообщений пользователю в работе VA - перейти на оповещения

### ISSUE THREAD

**Issue by marmyshev** [Pr-Mex/vanessa-automation#215]
Читать оповещения более удобно, т.к. они не съедают экранное место, можно кликабельные ссылки делать. Просматривать их удобнее чем то что выводится через `Сообщить();`

Платформа считает - что выводить сообщения можно не больше 2х шт. Если оно изначально больше - лучше использовать для этого соответствующий механизм.

Возможно, следует учесть если VA работает на старых платформах (8.1, 8.2,...) или в режиме обычных форм - то там можно поведение не менять.

**Comment by Pr-Mex** [comment]
Решено.
