### ISSUE TITLE
При выполнении шагов экспортного сценария через F11 выполняются совсем другие экспортные сценарии

### ISSUE THREAD

**Issue by Reheab** [Pr-Mex/vanessa-automation#2150]
Укажите:
   1. Версия Vanessa Automation 1.2.041.15
   2. Версия платформы 8.3.23.2040, 8.3.22.2239
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система Windows 10

Ошибка воспроизвелась на разных базах с разными платформами.

Файлы внутри:
[Main.zip](https://github.com/user-attachments/files/15737396/Main.zip)

Если открыть файлы Тест и Тест2, включить отображение экспортных и выполнить только шаги "И я перехожу к предыдущему реквизиту" экспортного сценария Эксп1, то будет происходить перепрыгивание на предыдущие экспортные сценарии. Ошибка воспроизводится только при наличии тега @tree.

Опытным путем выяснено, что строка самого первого экспортного сценария в фиче (в Тесте  = 19, в Тесте2 = 16) соответствует строке в экспортном сценарии, когда происходит перепрыгивание. И порядок следующих экспортных сценариев соответствует порядку "перепрыгивающих" шагов в экспортном сценарии.

Выходит, что строка шага экспортного сценария связана со строкой самой фичи, чего быть не должно.

![image](https://imgbly.com/ib/KcikCgUCNV.png)
![image](https://imgbly.com/ib/LOvwXplmlv.png)

**Comment by Pr-Mex** [comment]
Решено
