### ISSUE TITLE
Ошибка сравнения таблицы с переменной, если в заголовке колонки есть пробелы

### ISSUE THREAD

**Issue by wolfery666** [Pr-Mex/vanessa-automation#2151]
Vanessa Automation v1.2.041.15
Версия платформы 8.3.22.2283
Операционная система Windows 10

При сохранении таблицы в переменную (ЯЗапоминаюЗначениеТаблицыКак) из значения в структуре шапки убираются запрещенные символы, как для ключа, в том числе пробелы, а при сравнении таблицы с переменной (ТаблицаСталаРавной) значения из структуры шапки используются для сопоставления колонок, и поскольку в заголовке колонок таблицы пробелы есть, а в шапке таблицы из переменной нет, возвращается ошибка отсутствия колонок. 
https://github.com/Pr-Mex/vanessa-automation/blob/8a814e91bf3b254ee9e8bfa566f19c91d8bf5be4/features/Libraries/UITestRunner/step_definitions/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%A1%D0%98%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81%D0%BE%D0%BC/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L15663

**Comment by Pr-Mex** [comment]
Решено.
