### ISSUE TITLE
Запуск сценария из фичи по тэгу отрабатывает без контекста

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#2161]
Версия Vanessa Automation 1.2.041.15
Версия платформы 8.3.22
Режим совместимости базы, где запускается Vanessa Automation 8.3.21
Операционная система windows

Если вызывать сценарий фичи по тэгу - в этом случае не отрабатывают шаги из секции контекст.
Фича с тэгом только у сценария
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/0bb92785-69a2-4015-9239-68a741ea4e89)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/fe897df0-4922-4be8-a7f3-78c745c1720d)
![image](https://github.com/Pr-Mex/vanessa-automation/assets/19662685/f49d6d44-4820-4a94-9bbf-54e85ce9e13e)

пример
```
#language: ru
@tree
Функционал: Расширения конфигурации
Контекст:
	И я подключаю TestClient "ЭтотКлиент" логин "Главный бухгалтер" пароль ""
Сценарий: Сбросить флаги у расширений
	И пауза 1
Сценарий: Настроить использование расширения Менеджер потоков
	И пауза 1
@REGACC_Demo_Buh1
Сценарий: Настроить профиль пользователя
	Дано Я открываю основную форму обработки "АктивныеПользователи"
@REGACC_Demo_Buh1
Сценарий: Закрытие клиента тестирования после настройки
	И я закрываю сеанс текущего клиента тестирования
```

**Comment by Pr-Mex** [comment]
Решено.
