### ISSUE TITLE
Вопрос, как открыть навигационную ссылку в менеджере тестирования?

### ISSUE THREAD

**Issue by oompaloomp** [Pr-Mex/vanessa-automation#2166]
1. Версия Vanessa Automation - vanessa-automation-single.1.2.041.22
   2. Версия платформы - 8.3.25.1286
   3. Режим совместимости базы, где запускается Vanessa Automation - совместима
   4. Операционная система - Windows Server 2019, 1809

Как в сценарии перейти по навигационной ссылке до запуска клиента тестирования?
Сейчас отрабатывает проверка запуска клиента тестирования.

Фича: 

Сценарий: Открыть настройки пользователя в менеджере тестирования

Дано я перехожу по навигационной ссылке "ссылка"

**Comment by Pr-Mex** [comment]
@oompaloomp 

Шаг предполагает, что он будет открывать навссылку в клиенте тестирования. Если нужно изменить настройки пользователя в менеджере тестирования - это надо делать как-то по-другому.

**Comment by oompaloomp** [comment]
Понял, спасибо
