### ISSUE TITLE
Разное поведение шага И для каждого значения "ЗначениеИзТаблицы" из таблицы в памяти "Коллекция" в версии 1.2.041.1 и 1.2.041.22

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#2180]
Версия Vanessa Automation 1.2.041.22
Версия платформы 8.3.24
Режим совместимости базы, где запускается Vanessa Automation 8.3.21
Операционная система windows

Есть фича, которая использует сохранение списка в переменную и обход потом этой переменной и после обновления на релиз 1.2.041.22 эта фича стала падать.
Ниже привожу скрин ошибка выполнения на 1.2.041.22  с таблом переменных и  выполнение на 1.2.041.1.
Отличие в том. что в в версии 1.2.041.1 была переменная "Представление", в версии 1.2.041.22 теперь только соответствие, в котором есть эта переменная. 
![image](https://github.com/user-attachments/assets/4a684e84-14e3-4a46-9291-60b5977f6444)
![image](https://github.com/user-attachments/assets/5df91913-6c44-4d65-af07-ef6e92126cb0)

Это теперь штатное поведение?

```
Сценарий: Создание реализации по правой кнопке
	* Проверяем создание документа по правой кнопке мыши
		И В командном интерфейсе я выбираю 'Продажи' 'Реализация (акты, накладные, УПД)'
		Тогда открылось окно 'Реализация (акты, накладные, УПД)'
		И я выбираю пункт контекстного меню с именем 'СписокКонтекстноеМенюСоздать' на элементе формы с именем "Список"
		И таблица 'СписокВидовОпераций' содержит строки:
			| 'Представление'   |
			| 'Лизинговые услуги' |
			| 'Выкуп с баланса лизингополучателя' |
		И я запоминаю значение таблицы "СписокВидовОпераций" как "ПерСписок"
		И я закрываю текущее окно		
		И для каждого значения "Стандартный" из таблицы в памяти "ПерСписок"
			И я выбираю пункт контекстного меню с именем 'СписокКонтекстноеМенюСоздать' на элементе формы с именем "Список"
			Тогда открылось окно 'Форма документа'
			И в таблице "СписокВидовОпераций" я перехожу к строке
					| 'Представление' |
					| '$Представление$' |
			И в таблице "СписокВидовОпераций" я выбираю текущую строку
			И я закрываю текущее окно
```

**Comment by akademik1986** [comment]
![image](https://github.com/user-attachments/assets/a224587a-44e9-4cdc-9cd0-9f6bb5df793d)

**Comment by Pr-Mex** [comment]
@akademik1986 

>Это теперь штатное поведение?

Да
