### ISSUE TITLE
Запуск тест клиента не учитывает настройку "Тип клиента"

### ISSUE THREAD

**Issue by tsukanov-as** [Pr-Mex/vanessa-automation#220]
VA Single ver. 1.2.020

Не могу дать ссылку на строку кода, т.к. гитхаб не может отобразить модуль управляемой формы :)

В общем обнаружили что в гитлабе на раннере у нас тест клиент запускается как толстый несмотря на настройку.
Отладчиком я выяснил что запуск происходит этой строкой: https://i.imgur.com/UUCGls7.png

Трабл в том, что такой подход игнорит настройку, которая задана для тест клиента, и запускает его с тем же типом клиента что и у тест менеджера. Кажется это не вполне верно.

**Comment by Pr-Mex** [comment]
@tsukanov-as 
У вас ТестМенеджер запущен как тонкий или как толстый клиент?

**Comment by tsukanov-as** [comment]
Как толстый

**Comment by Pr-Mex** [comment]
Решено.
@tsukanov-as 
Просьба проверить.
