### ISSUE TITLE
Добавить шаг "И таблица 'Список' содержит только строки"

### ISSUE THREAD

**Issue by Reheab** [Pr-Mex/vanessa-automation#2203]
Укажите:
   1. Версия Vanessa Automation 1.2.041.22
   2. Версия платформы
   3. Режим совместимости базы, где запускается Vanessa Automation
   4. Операционная система

Добавить шаг:
И таблица 'Список' содержит только строки
        | 'ИмяКолонки1' | 'ИмяКолонки2' |
	| 'Значение1' | 'Значение2' |
по аналогии с шагом "И в логе сообщений TestClient есть сообщения только из списка"

**Comment by Pr-Mex** [comment]
@Reheab 

Это видимо уже сделано
https://github.com/Pr-Mex/vanessa-automation/issues/2189
