### ISSUE TITLE
VARIABLES при отладке сценариев

### ISSUE THREAD

**Issue by zeegin** [Pr-Mex/vanessa-automation#221]
```Gherkin
Функционал: VARIABLES при отладке сценариев
   Как разработчик сценариев
   Я хочу при отладке сценариев видеть и редактировать переменные контекста

Сценарий: Я выполняю построчную отладку сценария с шагами с переменными
  Допустим: Я остановил выполнение на брейкпоинте
  Когда: Я открываю дополнительное окно WATCH
  Тогда: Я виду все текущие переменные контекста
            И могу их редактировать для отладки шага в нескольких вариантах переменной

```
Например в VSCode
![изображение](https://user-images.githubusercontent.com/729213/54452441-3c92ca00-4766-11e9-9b9e-7d95807ff32a.png)

**Comment by nixel2007** [comment]
любопытная идея. можно оперативно накостылить обычной строкой с "выполнить", но отдельное окно было бы полезно

**Comment by zeegin** [comment]
@nixel2007 Было бы интересно реализовать DAP в виде HTTP сервиса в расширении с ванессой и попробовать его подружить с VSCode - вот это была бы бомба)

**Comment by nixel2007** [comment]
@zeegin это настолько охренительная идея, что мне даже хочется это дело напилить. Вопрос только что делать со скоростью отладки - есть ли кроме системы взаимодействия варианты получения информации на клиент быстрее, чем опрос сервера раз в 1 секунду?

**Comment by zeegin** [comment]
@nixel2007 Я думаю опрос раз в секунду это нормально. Учитывая разные механики ожидания окон и элементов просадка будет незаметка.
Например так:
Реквизит и параметр запуска "ВнешнийДебаггер" который блокирует на форме все элементы управления встроенным дебаггером. Он же включает обработчик серверного вызова раз в секунду.
Нужно хранилище состояний внешнего дебаггера (регистр сведений в расширении и константа с хранилищем значений со структурой), и функция адаптер в реквизиты формы, которая доступна из ванессы в режиме серверного вызова.
В режиме внешний дебаггер дергается это самое сохраненное значение, адаптируется в реквизиты ванессы, затем на клиенте дергается тик запуска сценария.
Внешнее хранилище управляется http сервисом по протоколу DAP.
При получении запроса на изменение он сохранится, потом тиком ванессы обновятся сначала реквизиты затем выполнится тик сценария.

**Comment by zeegin** [comment]
@nixel2007 а LSP для геркина же есть?

**Comment by zeegin** [comment]
Другой вариант это http поднимать отдельным процессом внутри самого vscode и обмениваться с помощью какого-нибудь файла с состоянием, типо watch на изменение файла будет событием. Но сильных плюсов от такой реализации не вижу.

**Comment by Pr-Mex** [comment]
Да. Тоже периодически сталкиваюсь тем, что нужно посмотреть переменные контекста.

**Comment by nixel2007** [comment]
@zeegin, lsp для геркина не гуглится. 

Хттп сервисы на стороне 1с как минимум требуют веб сервера для публикации. Надо покурить способы взаимодействия у dap. Lsp например, может использовать два (любых) потока для взаимодействия, в том числе stdin/stdout. Если получится с клиента работать с потоками напрямую через файл, например, то это Во-первых упростит 1сное клиент-серверное взаимодействие, а во-вторых, позволит шуршать всему этому намного быстрее.

**Comment by zeegin** [comment]
@nixel2007

Поковырял https://github.com/Microsoft/vscode-mock-debug

Пришел к тому же выводу. Обмен через файлы проще. Надо посмотреть как @Pr-mex сделал загрузку и обновление фичи из сппр, можно попробовать этот механизм расширить, там тоже через временную папку.

**Comment by Pr-Mex** [comment]
Решено в новом редакторе VAEditor. При наведении мышки на шаг показываются значения переменных.
