### ISSUE TITLE
Vanessa Automation не разворачивает структуру доступных полей в отборах

### ISSUE THREAD

**Issue by i-saitgalin** [Pr-Mex/vanessa-automation#2223]
Укажите:
   1. Версия Vanessa Automation : vanessa-automation.1.2.041.30, так же делал на vanessa-automation.1.2.041.1
   2. Версия платформы: 8.3.19.1522
   3. Режим совместимости базы, где запускается Vanessa Automation 8.3.12
   4. Операционная система Windows 10

> Заполните шаблон обсуждения GIT

```Gherkin
#language: ru

@tree

Функционал: <описание фичи>

Как <Роль> я хочу
<описание функционала> 
чтобы <бизнес-эффект>   

Переменные:

ОрганизацияЗВП	= "Андромеда Плюс"
ПодразделениеЗВП = "Коммерческая служба"
Код_подразделенияЗВП = "00-000005"
ОрганизацияКодЗВП = "00-000008"

Контекст:
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: <описание сценария>

#language: ru

И я закрыл все окна клиентского приложения


Когда В панели разделов я выбираю 'Главное'
И Я нажимаю кнопку командного интерфейса 'Заказы на внутреннее потребление'
Когда открылось окно 'Заказы на внутреннее потребление'
И в таблице "Список" я нажимаю на кнопку с именем 'СписокСоздать'

Когда открылось окно 'Заказ на внутреннее потребление (создание)'

И из выпадающего списка с именем "Организация" я выбираю точное значение "ОрганизацияЗВП"

И я нажимаю кнопку выбора у поля с именем "Подразделение"

Тогда открылось окно 'Структура предприятия'
И я нажимаю на кнопку 'Список'

И я устанавливаю фильтр на список
		| 'Код'                           | Равно | "Код_подразделенияЗВП" |
        | 'Вышестоящее Подразделение.Код' | Равно | "ОрганизацияКодЗВП"    |
		| 'Наименование'                  | Равно | "ПодразделениеЗВП"     |

//И я нажимаю на кнопку с именем 'ФормаНастройкаСписка'
//Тогда открылось окно 'Настройка списка'
//И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0ДоступныеПоляТаблица" я перехожу к строке:
//	| 'Доступные поля'            |
//	| 'Вышестоящее подразделение' |

//И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0ДоступныеПоляТаблица" я разворачиваю текущую строку
//
//И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0ДоступныеПоляТаблица" я разворачиваю текущую строку
//И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0ДоступныеПоляТаблица" я перехожу к строке:
//	| 'Доступные поля' |
//	| 'Код'            |
//И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0ДоступныеПоляТаблица" я выбираю текущую строку
//И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0Отбор" я активизирую поле с именем "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0ОтборВидСравнения"
//И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0Отбор" я выбираю текущую строку
//И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0Отбор" из выпадающего списка с именем "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0ОтборВидСравнения" я выбираю точное значение 'Равно'
//И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0Отбор" я активизирую поле с именем "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0ОтборПравоеЗначение"
//И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0Отбор" в поле с именем 'КомпоновщикНастроекПользовательскиеНастройкиЭлемент0ОтборПравоеЗначение' я ввожу текст '00-000008'
//И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0Отбор" я завершаю редактирование строки
//И я нажимаю на кнопку с именем 'ФормаЗакончитьРедактирование'


И в таблице "Список" я выбираю текущую строку

Тогда открылось окно 'Заказ на внутреннее потребление (создание) *'
И я нажимаю кнопку выбора у поля "Склад"
Тогда открылось окно 'Склады и магазины'


```

С демо базой 1С:ERP Управление предприятием 2 (2.4.7.107)  не удается установить отбор Вышестоящее Подразделение.Код, пробовал разными способами (в комментариях), не разворачивается ветка

Выдается ошибка:
{ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(17282)}: Не получилось перейти к строке фильтра <Вышестоящее Подразделение>

Технические данные:
        ЗаголовокАктивногоОкна: Настройка списка
        ИмяАктивнойФормы: DynamicListSettings
        ИмяФичи: <описание фичи>
        ИмяСценария: <описание сценария>
        НомерСтрокиДерева: 15
        НомерСтрокиФичи: 42
        ПолныйПутьКФиче: C:\Users\saitgalin\Documents\Автотесты\ДляДемо.feature
        ИмяФайла: C:/Users/saitgalin/Documents/Автотесты/vanessa-automation.1.2.041.1/vanessa-automation/features/Libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом.epf
        ИмяПроцедуры: ЯУстанавливаюФильтрНаСписок
        ИмяРаннера: ***
        ИмяКлиентаТестирования: Этот клиент
        СинонимКлиентаТестирования: 
        ТипКлиентаТестирования: Тонкий
        СтрокаСоединения: Srvr="***";Ref="***";
        ДопПараметрыПодключения: /N"Администратор (ОрловАВ)" 
        PIDКлиентаТестирования: 15316
        ВерсияVA: ver 1.2.041.30
        ВерсияПлатформы: 8.3.19.1522
        ТипПлатформы: Windows x86-64
        РежимСовместимостиTestManager: Версия8_3_12
        ВремяРаботыСценария: 0:00:10 (ч:м:с)
        ДатаВремяОшибки: 29.10.2024 17:32:28

> Прикладывайте файлы скриншотов

![Снимок1](https://github.com/user-attachments/assets/f3d21a7e-bc83-4a06-8f7a-82680c42b143)
![Снимок2](https://github.com/user-attachments/assets/4deac5ab-211b-451f-baf7-3a899067776b)

**Comment by Pr-Mex** [comment]
@i-saitgalin 
Попробуйте записать действия для установки данного фильтра не используя шаг
И я устанавливаю фильтр на список

Этот шаг не предполагает универсальности на все случаи жизни. Он позволяет устанавливать стандартные отборы.

**Comment by i-saitgalin** [comment]
Я так пробовал,  в коде первоначальном закомментировано. Вот скриншот ошибки и код.

Выдается на шаге:

И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0ДоступныеПоляТаблица" я разворачиваю текущую строку



![Снимок](https://github.com/user-attachments/assets/08b225c6-7375-4906-a6c6-8406495e00c5)

{ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(3438)}: Ошибка при вызове метода контекста (Развернуть): Неподходящее состояние элемента управления для вызванного действия.

```Gherkin
#language: ru

@tree

Функционал: <описание фичи>

Как <Роль> я хочу
<описание функционала> 
чтобы <бизнес-эффект>   

Переменные:

ОрганизацияЗВП	= "Андромеда Плюс"
ПодразделениеЗВП = "Коммерческая служба"
Код_подразделенияЗВП = "00-000005"
ОрганизацияКодЗВП = "00-000008"

Контекст:
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: <описание сценария>


#language: ru

И я закрыл все окна клиентского приложения


Когда В панели разделов я выбираю 'Главное'
И Я нажимаю кнопку командного интерфейса 'Заказы на внутреннее потребление'
Когда открылось окно 'Заказы на внутреннее потребление'
И в таблице "Список" я нажимаю на кнопку с именем 'СписокСоздать'

Когда открылось окно 'Заказ на внутреннее потребление (создание)'

И из выпадающего списка с именем "Организация" я выбираю точное значение "ОрганизацияЗВП"

И я нажимаю кнопку выбора у поля с именем "Подразделение"

Тогда открылось окно 'Структура предприятия'
И я нажимаю на кнопку 'Список'

И я устанавливаю фильтр на список
		| 'Код'                           | Равно | "Код_подразделенияЗВП" |
//        | 'Вышестоящее Подразделение.Код' | Равно | "ОрганизацияКодЗВП"    |
		| 'Наименование'                  | Равно | "ПодразделениеЗВП"     |

И я нажимаю на кнопку с именем 'ФормаНастройкаСписка'
Тогда открылось окно 'Настройка списка'
И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0ДоступныеПоляТаблица" я перехожу к строке:
	| 'Доступные поля'            |
	| 'Вышестоящее подразделение' |

И в таблице "КомпоновщикНастроекПользовательскиеНастройкиЭлемент0ДоступныеПоляТаблица" я разворачиваю текущую строку

```

**Comment by Pr-Mex** [comment]
@i-saitgalin 

То что равернуть не срабатывает скорее всего связано с этим
>Режим совместимости базы, где запускается Vanessa Automation 8.3.12

В 8.3.13 была доработка в платформе связанная с тем как разворачиваются узлы дерева.
Попробуйте поднять режим совместимости.

**Comment by i-saitgalin** [comment]
да, в режиме совместимости 8.3.13 ошибки нет
