### ISSUE TITLE
Вложенность tree шагов в отчете allure

### ISSUE THREAD

**Issue by asosnoviy** [Pr-Mex/vanessa-automation#228]
```Gherkin
Функционал: Вложенные tree шаги в отчете allure
   Как пользователь VA
   Я хочу в отчете аллюр видеть родительские и вложенные tree шаги 

Контекст:

Сценарий:  Формирование отчета аллюр с вложенными tree шагами
  Допустим:  Есть сценарий с тегом tree И вложенными шагами
  Когда:  формируется отчет allure
  Тогда:  В отчете есть родительский шаг и вложенные в него выполняемые шаги

```
![image](https://user-images.githubusercontent.com/15638529/54676616-1b3d2f80-4b12-11e9-8386-a99e89648c3b.png)

**Comment by 1cgh** [comment]
@Pr-Mex @asosnoviy это вроде уже работает?
![image](https://user-images.githubusercontent.com/24507052/213987825-53ae014b-f542-418e-b779-5119980dbfcf.png)
![image](https://user-images.githubusercontent.com/24507052/213987874-1ed510d5-70a0-4cb8-a27a-5747aa22e313.png)

**Comment by Pr-Mex** [comment]
@asosnoviy 
@1cgh 
Да, это давно сделано. Я забыл закрыть issue.
