### ISSUE TITLE
Шаг ввода текущей даты не работает на английской конфе

### ISSUE THREAD

**Issue by tsukanov-as** [Pr-Mex/vanessa-automation#229]
VA Single ver. 1.2.020

Имеется шаг (ну вообще семейство шагов): 
```И в поле с именем "ИмяПоля" я ввожу текущую дату```

В реализации захардкожен формат для преобразования в текст: "ДФ=dd.MM.yyyy"
Из-за этого шаг не работает на английской конфе (запуск с параметрами /Len /VLen), т.к. формат даты там другой.
Да и вообще в принципе формат ведь может быть любым.

Может быть имеет смысл хранить формат в рантайме Ванессы и сделать настроечный шаг типа: `И я задаю формат "Формат" для ввода дат` ?

**Comment by Pr-Mex** [comment]
@hawk911 вы это как-то решали?

**Comment by hawk911** [comment]
@Pr-Mex на следующей неделе напишу.

**Comment by tsukanov-as** [comment]
Для связи: #152

**Comment by hawk911** [comment]
@Pr-Mex Да, есть в планах все даты перевести к формату который в базе. Я убираю время с помощью функции `ДатаБезВремениСтрока`. Это тоже переделаю. 
@tsukanov-as Да, проходил это. Выше описал как сделал.

**Comment by tsukanov-as** [comment]
@hawk911 Формат даты может быть в конфе для конкретного поля персонально выставлен. Это как-то учесть нужно.

**Comment by Pr-Mex** [comment]
Наверное нужно в Ванессе добавить поле
ФорматДаты
Также нужно добавить шаг, который его может изменить.
Это видится максимально универсальным.

**Comment by nixel2007** [comment]
И настройку в json!

**Comment by Pr-Mex** [comment]
> И настройку в json!

Это само собой )

**Comment by Pr-Mex** [comment]
Переехало в https://github.com/Pr-Mex/vanessa-automation/issues/732
