### ISSUE TITLE
Добавить в API ванессы

### ISSUE THREAD

**Issue by zeegin** [Pr-Mex/vanessa-automation#248]
Из `ЗапускПриложений`

1. `ВыполнитьКомандуСПотокомВывода`
2. `ПолучитьДанныеКлиентаТестирования`
3. `ОбновитьДанныеКлиентовТестирования`
4. `УдалитьЭлементПодключенныеTestClient`
5. `ВычислитьTestClientPID`

Отрефакторить код универсально для `РаботаСTestClient` - задействовать API.

**Comment by Pr-Mex** [comment]
Решено.
