### ISSUE TITLE
Лишняя " в шагах проверки командного интерфейса

### ISSUE THREAD

**Issue by asosnoviy** [Pr-Mex/vanessa-automation#261]
В библиотеке известных шагов, для шагов проверки командного интерфейса:
 "И панель разделов равна"
 "И панель разделов не содержит пункты меню"
 "И панель функций равна"
 итд

Выводится лишний символ `"`

![image](https://user-images.githubusercontent.com/15638529/56290572-1b8a1400-612c-11e9-87a9-5364296b4d2a.png)

VA 1.2.0.22

**Comment by Pr-Mex** [comment]
Понял. Спасибо!

**Comment by Pr-Mex** [comment]
Решено.
