### ISSUE TITLE
Для шага "...каждой строки таблицы отбора я устанавливаю отбор в списке" реализовать работу с переменной

### ISSUE THREAD

**Issue by lelikanet** [Pr-Mex/vanessa-automation#263]
1.2.023
Пример: 
И для каждой строки таблицы отбора я устанавливаю отбор в списке
|ИмяФильтр|ТипСравнения|"$ИмяПеременной$"|
Сейчас фактически в "Значение" пишется строкой $ИмяПеременной$
А не значение из переменной.
![image](https://user-images.githubusercontent.com/45041332/56499090-8319d800-650d-11e9-8a66-a3fe03ee6481.png)

**Comment by Pr-Mex** [comment]
Сделано.
