### ISSUE TITLE
"Научить" шаг "И Я устанавливаю фильтр на список" раскрывать подчиненные узлы дерева

### ISSUE THREAD

**Issue by lelikanet** [Pr-Mex/vanessa-automation#264]
версия 1.2.023
Сейчас описанный шаг этого делать не умеет. Показывает ошибку:
Текст ошибки при этом: {ВнешняяОбработка.ФильтрФормыСпискаЭкспорт.Форма.Форма.Форма(114)}: Не смог перейти к строке фильтра <Договор.Вид элемента. ...>
![image](https://user-images.githubusercontent.com/45041332/56756920-97730480-679b-11e9-8d7e-58735b0ae0e8.png)

**Comment by Pr-Mex** [comment]
Сделано.
