### ISSUE TITLE
Изменить в шаге описание "Дано Я открываю основную форму регистра сведений "РегистрСведений1"

### ISSUE THREAD

**Issue by lelikanet** [Pr-Mex/vanessa-automation#265]
В шаге "Дано Я открываю основную форму регистра сведений "РегистрСведений1"" Есть несоответствие в описании.
Сейчас оно "Открывает основную форму регистра накопления по его имени в метаданных"
Должно быть "Открывает основную форму регистра сведений по его имени в метаданных"
![image](https://user-images.githubusercontent.com/45041332/56976916-ae8b6b00-6b7c-11e9-8567-5aad7b9df4af.png)

**Comment by Pr-Mex** [comment]
Сделано.
