### ISSUE TITLE
Запуск тестового клиента в зависимости от языка фичи 

### ISSUE THREAD

**Issue by hawk911** [Pr-Mex/vanessa-automation#267]
```Gherkin
Функционал: Я запускаю тестовый клиент под необходимой локалью
   Как Тестировщик
   Я хочу запускать тестовый клиент под нужной мне локалью

Сценарий: Когда я переключаю язык Геркина добавляется языковой параметр
  Допустим:  Я переключил язык фич на английский
  Когда: Я запускаю тестовый клиент 
  Тогда: Запускается предприятие на английском языке

```

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
Ты хочешь безусловно добавлять параметр /L в зависимости от языка фичи?

**Comment by hawk911** [comment]
Да, а как по другому решить вопрос запуска нужного языка в конфигурации? Если ты пишешь на английском фичи - значит проверяешь на английском языке конфигурацию.

**Comment by Pr-Mex** [comment]
Как считаешь, может получиться ситуация, когда я пишу в основном фичи на английском для английского интерфейса, а потом ещё сделаю пару фич на английском, но для вьетнамского интерфейса? В целом может быть такое?

**Comment by Pr-Mex** [comment]
@1C-Romania 
Как считаешь?

**Comment by hawk911** [comment]
> Как считаешь, может получиться ситуация, когда я пишу в основном фичи на английском для английского интерфейса, а потом ещё сделаю пару фич на английском, но для вьетнамского интерфейса? В целом может быть такое?

Так и думал, что будет охота на лис :)  У нас такого не может быть.

**Comment by Pr-Mex** [comment]
> > Как считаешь, может получиться ситуация, когда я пишу в основном фичи на английском для английского интерфейса, а потом ещё сделаю пару фич на английском, но для вьетнамского интерфейса? В целом может быть такое?
> 
> Так и думал, что будет охота на лис :) У нас такого не может быть.

Тут дело такое. С одной стороны предполагается сделать автоперевод фич на нужный язык для тестов интерфейсов под другими языками.
С другой стороны обрубается возможность запустить фичу на одном языке, а интерфейс на другом. 
@hawk911 Может всё-таки создать настройку, которая управляет этим?

**Comment by hawk911** [comment]
@Pr-Mex Ничего я не обрубаю 😸 Я лишь частую операцию автоматезировал - какой процент, что ты пишешь фичу на английском, а запускаешь конфигурацию на русском?

**Comment by Pr-Mex** [comment]
Ок. А если пользователь явно указал другое значение параметра /L - оно сохранится?

**Comment by hawk911** [comment]
А какой порядок действия в этом случае будет?

**Comment by Pr-Mex** [comment]
> А какой порядок действия в этом случае будет?

Пользователь открыл вкладку клиентов тестирования и указал своё значение для /L руками или через json. Это значение будет оставлено?
![image](https://user-images.githubusercontent.com/8627416/57351566-a9bd4d00-7162-11e9-9a35-0ea8fc69e1d6.png)

**Comment by hawk911** [comment]
Добавление параметра только при смене языка. Язые меняется при начале работы с фичей. Так что, если пользователю необходимо запустить фичу под другим языком он поменят параметр или впишет его, если не менял язык Геркина.

**Comment by Pr-Mex** [comment]
Ок. Понял.

**Comment by Pr-Mex** [comment]
Сделано.

**Comment by ekaruk** [comment]
Не совсем поняла это изменение.
У нас язык Геркина русский. При этом тесты выполняются в украинском интерфейсе.
Для этого в файле настройки указан параметр запуска
 "--additional": "/DisplayAllFunctions /VLuk /Luk  /Debug",
Запуск пакетно через "call runner vanessa" 
В 1.2.20 всё работало корректно.
После обновления с 1.2.20 на 1.2.25 клиент тестирования стал всегда запускаться с русским интерфейсом.
Возникает вопрос, как теперь правильно указать язык интерфейса, отличающийся от языка Геркин?

**Comment by Pr-Mex** [comment]
@ekaruk 

Привет!
1. Ты видимо имела ввиду 1.2.024? 25 ещё не выходил.
2. Дай json, который вы отдаёте VA для запуска. Посмотрю что происходит.

**Comment by hawk911** [comment]
@ekaruk Это скорей всего связано с изменением запуска тестового клиента. Данная настройка не берёт настройки из json.

**Comment by ekaruk** [comment]
{
    "$schema": "https://raw.githubusercontent.com/silverbulleters/vanessa-runner/develop/vanessa-runner-schema.json",
    "default": {
        "--db-user": "Федоров (адміністратор)",
        "--db-pwd": "",
        "--v8version":"8.3.14",
        "--additional": "/DisplayAllFunctions /VLuk /Luk  /Debug",
    },
    "vanessa": {
        "--vanessasettings": "C:/ADD/features/bddRunnerAutostartSettings.json",
        "--pathvanessa": "C:/ADD/vanessa_ukr_v1_2_020/vanessa-automation.epf"
    },
    "xunit": {
        "--xddConfig": "$workspaceRoot/Настройки.json",
        "testsPath": "$workspaceRoot",
        "--workspace_": "C:/ADD/features/dm",
        "--reportsxunit": "ГенераторОтчетаAllureXML{$workspaceRoot/allure_result/allure-testsuite.xml}",
        "--additional": "/DisplayAllFunctions /L ru /VL ru /Debug",
        "--db-user":"Fedorov"
    }

}

**Comment by ekaruk** [comment]
При такой настройке ранее клиент тестирвоания запускался на украинском.
На 1.2.24 стал запускаться на русском.
Сам менеджер тестирования остался на украинском. А клиента внутри себя запускает на русском.
Что еще может на него влиять?

**Comment by nixel2007** [comment]
Коллег больше вот этот файл интересует
C:/ADD/features/bddRunnerAutostartSettings.json

**Comment by Pr-Mex** [comment]
> Коллег больше вот этот файл интересует
> C:/ADD/features/bddRunnerAutostartSettings.json

Это VBParams, который передаётся VA?

**Comment by nixel2007** [comment]
@Pr-Mex да.

**Comment by Pr-Mex** [comment]
@ekaruk 
Да, нужен файл, про который говорит @nixel2007.
