### ISSUE TITLE
Пропала группировка по фичам в отчетах Allure

### ISSUE THREAD

**Issue by ingenergari** [Pr-Mex/vanessa-automation#281]
Контекст:
После перехода на версию ванессы 1.2.0.23 с 1.2.0.21 в отчетах allure перестала производится группировка по фичам.
В приложенных скриншотах видно поведение при формировании отчетов до обновление и после. Сама структура тестов не менялась между двумя скриншотами.

> Прикладывайте файлы скриншотов
![issue](https://user-images.githubusercontent.com/5244597/57615278-644ab680-758c-11e9-810d-700b8d931ef0.png)
![normal](https://user-images.githubusercontent.com/5244597/57615279-644ab680-758c-11e9-8b24-1f0695e56f6f.png)

**Comment by Pr-Mex** [comment]
@ingenergari 
Погрузился в проблему - не понял что именно изменилось.
У меня на тестовых примерах получается одинаково.
Приложи, пожалуйста, фичи, на которых получается данный эффект.

**Comment by freddy121** [comment]
А раздел behaviors поменчлся?

**Comment by ingenergari** [comment]
Доброго дня.
Смог повторить разницу между отчетами как на моих скринах.
Итак, на версии 1.2.021 группировки нет, а вот на 1.2.020 группировка есть.

Структура каталогов с фичами которую испльзовал в тесте: **корень репозитория**\features\User Rights\\**файлы фич**
Ниже код самих фич на которых смог воспроизвести (использовал два разных файла).

**test1.feature**
```
#language: en
Feature: Test1

As Developer
I want to break free

Background:
    Given I launch TestClient opening script or connect the existing one

Scenario: Close All Start
    And I close all client application windows

Scenario: Escape1
    And I set "Test1" synonym to the current TestClient
```

**test2.feature**
```
#language: en

Feature: Test2

As Developer
I want to break free

Background:
    Given I launch TestClient opening script or connect the existing one

Scenario: Close All Start
    And I close all client application windows

Scenario: Escape2
    And I set "Test2" synonym to the current TestClient
```

**Comment by pzhgulev** [comment]
+1, не удобно стало.

**Comment by tsukanov-as** [comment]
@Pr-Mex Есть понимание из-за чего это?

**Comment by Pr-Mex** [comment]
@tsukanov-as произошла смена формата формирования отчёта allure с xml на json. И где-то перестало что-то заполняться. Я с ходу не нашёл.

**Comment by Pr-Mex** [comment]
Решено.
