### ISSUE TITLE
Ошибка генерации сценария "кнопконажималкой"

### ISSUE THREAD

**Issue by theshadowco** [Pr-Mex/vanessa-automation#288]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Запись действий пользователя
   Как пользователь
   Я хочу хочу воспроизводить записанные действия пользователя без доработки

Контекст:
  Дано: 1.2.0.24
  И 8.3.11.3034
  и демо база из поставки


Сценарий: Выполняю запись действий
  Допустим: выполняю запись действий и получаю сгенерированный текст сценария
  Когда: запускаю этот сценарий на выполнение
  Тогда: не находит форму по записанному имени

```

> Прикладывайте файлы скриншотов
[features.zip](https://github.com/Pr-Mex/vanessa-automation/files/3217545/features.zip)

Файл demo.feature - сценерированный
Файл demo.correct.feature - исправленный

**Comment by Pr-Mex** [comment]
@theshadowco 
Для расследования такого нужно приложить xml, который отдала платформа.
Он находится здесь
![image](https://user-images.githubusercontent.com/8627416/58342247-d78bdc80-7e58-11e9-88bf-51645acafd5f.png)

**Comment by theshadowco** [comment]
[demo.xml.zip](https://github.com/Pr-Mex/vanessa-automation/files/3217784/demo.xml.zip)

**Comment by Pr-Mex** [comment]
@theshadowco 
Из xml берётся заголовок окна. Он лежит в 
<ClientApplicationWindow caption="Исходящее письмо (Создание)">

В данном случае платформа не отдаёт дополнительной информации, что по ходу дела у окна поменялся заголовок.

**Comment by theshadowco** [comment]
принято
