### ISSUE TITLE
Генерация Файла профиля запуска обработки из обработки

### ISSUE THREAD

**Issue by theshadowco** [Pr-Mex/vanessa-automation#290]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Генерация файла профиля запуска обработки
   Как пользоатель VA
   Я хочу иметь возможность сохранять и загружать настройки из интерфейса обработки

Контекст:
  Дано: latest
  И other
  и other

Сценарий: Сохранение конфигурационного файла
  Допустим: я открыл VA и настроил как мне надо
  Когда: вызываю команду "Сохранить настройки в файл"
  Тогда: VA предлагает указать путь для сохранения настроек
  И Я указываю путь для сохранения
  Тогда VA сохраняет в файл все настройки
  И я могу использовать его для пакетного запуска VA


```

> Прикладывайте файлы скриншотов

**Comment by asosnoviy** [comment]
Где то был такой же ишуз про загрузку настроек... Но найти не смог.

**Comment by theshadowco** [comment]
@asosnoviy 
Тоже поискал и не нашел.

Задача родилась из необходимости дебажить дабы понять, что и как передать в VA

**Comment by theshadowco** [comment]
как дополнение (круто было бы) генерация доки с описанием параметров при выпуске нового релиза VA.

**Comment by Pr-Mex** [comment]
Принято.

**Comment by Golovanoff** [comment]
Раз уж зашла речь про отладку, есть предложение заодно в генераторе epf заменить создание процедур на создание функций. функции можно вызывать как процедуры, ничего не сломается, при этом функцию всегда и в любой момент можно дернуть отладчиком, а вот богопротивную процедуру - нельзя.

**Comment by Pr-Mex** [comment]
@Golovanoff 
Ты прав. Все процедуры шагов и так помечены "Экспорт".
Я за. Создашь новую задачу для этого?

**Comment by theshadowco** [comment]
> Раз уж зашла речь про отладку, есть предложение заодно в генераторе epf заменить создание процедур на создание функций. функции можно вызывать как процедуры, ничего не сломается, при этом функцию всегда и в любой момент можно дернуть отладчиком, а вот богопротивную процедуру - нельзя. если надо - могу попробовать мерж-реквест сразу сделать, там пара строчек.

Я думаю стоит это отдельной ишузой оформить

**Comment by Golovanoff** [comment]
> 
> 
> @Golovanoff
> Ты прав. Все процедуры шагов и так помечены "Экспорт".
> Я за. Создашь новую задачу для этого?

Я тут новенький. Запилил, как смог. Если чо не так - ткните носом :)

https://github.com/Pr-Mex/vanessa-automation/issues/291#issue-448878237

**Comment by Pr-Mex** [comment]
> > @Golovanoff
> > Ты прав. Все процедуры шагов и так помечены "Экспорт".
> > Я за. Создашь новую задачу для этого?
> 
> Я тут новенький. Запилил, как смог. Если чо не так - ткните носом :)
> 
> [#291 (comment)](https://github.com/Pr-Mex/vanessa-automation/issues/291#issue-448878237)

Всё отлично!

**Comment by Pr-Mex** [comment]
Решено.
