### ISSUE TITLE
генерация шагов в виде функций

### ISSUE THREAD

**Issue by Golovanoff** [Pr-Mex/vanessa-automation#291]
```Gherkin
Функционал: 
   Как программист 1с
   Я хочу иметь возможность отладки шагов, которые сгенерировала vanessa

Контекст:
  Дано: 1.2.024
  И любая версия 1с
  и любая конфигурация запуска

Сценарий: генерация шагов как функций
  Допустим: у меня есть ванесса
  Когда: я перехожу на вкладку "Генератор EPF"
  И я нажимаю кнопку "Создать шаблоны обработок"
  Тогда: в сгенерированном EPF шаги сформировались как экспортные функции

```

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
@Golovanoff 
Будешь делать реквест?

**Comment by Golovanoff** [comment]
@Pr-Mex 
Пардон за такой вопрос,  но в https://github.com/Pr-Mex/vanessa-automation/blob/develop/.github/CONTRIBUTING.md ничего про это не нашел. Как сделать мерж-реквест? Мне же для этого как-то надо свой код в репозитарий залить, а прав лить в develop у меня, есстно,  нет (да и не должно быть . по крайней мере, на первых порах :)). Свою отдельную ветку я тоже залить не могу. Где почитать про то, как предлагать свои патчи?

**Comment by asosnoviy** [comment]
Форкаешь себе 
![image](https://user-images.githubusercontent.com/15638529/58485804-635d7b80-816d-11e9-82dc-47a3d21b4db2.png)

Клонишь свою репу на комп. Создаешь новую ветку, дорабатываешь. Пушишь в свой форк. Из него делаешь пул реквест.

**Comment by Golovanoff** [comment]
>Пушишь в свой форк
Вот где собака порылась. Спасибо :)

**Comment by asosnoviy** [comment]
@pr-mex есть предложение Возвращать Истину. Для порядка, функция должна же что-то возвращать)))

**Comment by Pr-Mex** [comment]
> @Pr-Mex есть предложение Возвращать Истину. Для порядка, функция должна же что-то возвращать)))

Оно по идее вернёт Неопределено ))) Если будет не хватать - можно будет доработать.

**Comment by Pr-Mex** [comment]
Решено.
