### ISSUE TITLE
Просьба вместо одной кнопки запуска/остановки сценария сделать две

### ISSUE THREAD

**Issue by tsukanov-as** [Pr-Mex/vanessa-automation#297]
Просьба вместо одной кнопки запуска/остановки сценария сделать две.
С одной кнопкой постоянная проблема остановить сценарий, т.к. слишком легко повторно запустить.

![image](https://user-images.githubusercontent.com/17392154/58898220-c9647880-8702-11e9-973b-8233abbfe53d.png)

**Comment by asosnoviy** [comment]
Тоже впарывался не раз)

**Comment by Pr-Mex** [comment]
+1 )))

**Comment by Pr-Mex** [comment]
Решено.
