### ISSUE TITLE
Просьба добавить кнопки для перехода к следующей/предыдущей ошибке в дереве

### ISSUE THREAD

**Issue by tsukanov-as** [Pr-Mex/vanessa-automation#298]
В GUI ванессы после прогона сценариев в дереве не очень удобно искать ошибки.
Во-первых группировки не подсвечиваются красным, во-вторых нет способа прыгать по ошибкам.

**Comment by Pr-Mex** [comment]
@tsukanov-as 
Строка сценарий разве не подкрашивается красным?
Или ты именно про группы шагов?

**Comment by tsukanov-as** [comment]
про группы, да

**Comment by Pr-Mex** [comment]
ок

**Comment by fenixnow** [comment]
не очень понимаю реализацию, просто вверх/вниз на ошибочные строки дерева?

**Comment by tsukanov-as** [comment]
Да

**Comment by fenixnow** [comment]
реализована в develop

**Comment by Pr-Mex** [comment]
Решено.

**Comment by tsukanov-as** [comment]
Кнопка делает не то что нужно. Она прыгает по сценариям. А нужно было прыгать именно туда где ошибка возникла.

**Comment by fenixnow** [comment]
Спасибо, по этому поводу мы соберём группу, расследуем проблему, поймём куда она должна прыгать, повторим ваше поведение и поправим.

**Comment by tsukanov-as** [comment]
@fenixnow пардон, если в моем сообщении видится претензия.
Я написал совершенно нейтрально по факту.

**Comment by fenixnow** [comment]
Чтобы помочь тебе, мне нужны более конкретные проблемы, скрины, кусочек видео. Воспользуйся например nimbus для записи описания проблемы.

**Comment by nixel2007** [comment]
Так вон же ссылка на видео...

**Comment by tsukanov-as** [comment]
Я же скинул видео. Этого недостаточно?

**Comment by fenixnow** [comment]
Так ее же небыло

**Comment by tsukanov-as** [comment]
Согласен, надо было сразу скинуть. Мне просто показалось что проблема понятна.
Пардон еще раз )
