### ISSUE TITLE
Не открывается обработка vanessa-automation

### ISSUE THREAD

**Issue by Benony0** [Pr-Mex/vanessa-automation#3]
```Gherkin
Функционал: Открыть обработку Ванесса
   Как Администратор
   Я хочу Открыть обработку в пользовательском режиме

Контекст:
  Дано: Обработка версии 1.2.008
  И 1С версии 8.3.10.2466
  и Управляемая не типовая конфигурация на БСП

Сценарий: Отрыть обработку Ванесса
  Допустим: У меня есть обработка И Я запускаю 1С в пользовательском режиме
  Когда: Вызываю меню Файл-Открыть И выбираю файл внешней обработки
  Тогда: Появляется ошибка и обработка не открывается

```
Текст ошибки:

{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(2347)}: Получение элемента по индексу для значения не определено
	РасшифровкаСлужебногоСообщения = Объект.ТекстСообщенийПользователю[Сообщение];

**Comment by kuzyara** [comment]
Чет не воспроизводится...

**Comment by Pr-Mex** [comment]
@Benony0 
Видимо неверно указан "каталог инструментов". Из-за этого не загружается epf с локализацией.

**Comment by Pr-Mex** [comment]
@Benony0 
Проверь пожалуйста.

**Comment by Benony0** [comment]
Коллеги, прошу прощения, ошибки нет. Ну как.... скорее тех.долг: после превращения ВБ в ВА, сильно мешаются сохраненные кэши. Вчера по этому поводу писал в гиттере, помогла смена пользователя. Ишью можно закрыть, а над тех.долгом предлагаю подумать )))
