### ISSUE TITLE
Ошибка формирования отчета allure

### ISSUE THREAD

**Issue by theshadowco** [Pr-Mex/vanessa-automation#312]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Формирование отчета в формате allure
   Как пользователь
   Я хочу получать отчет в формате allure

Контекст:
  Дано: 1.2.024
  И 8.3.10.2580
  и любая

Сценарий: Формирование отчета allure после выполнения сценария
  Допустим: Загружен сценарий
   И указаны настройки формирования отчета allure
  И VA уставлена через opm
  Когда: Выполнение сценария завершилось
  Тогда: Возникает ошибка 

```

> Прикладывайте файлы скриншотов
![image](https://user-images.githubusercontent.com/9591731/59769193-50425500-92ae-11e9-8bb8-be0bff3340cb.png)

Причина в том, что в пакете не указан каталог vendor

![image](https://user-images.githubusercontent.com/9591731/59769233-62bc8e80-92ae-11e9-9231-53f30f1dc27d.png)

**Comment by Pr-Mex** [comment]
Да. Файл надо добавить.

**Comment by 1cgh** [comment]
туда же:
24.06.2019 17:27:16 Запись действий пользователя начата.
24.06.2019 17:30:41 Запись действий пользователя закончена.
Не смог обработать XML в UILogToScript.
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(20520)}: Ошибка при вызове конструктора (ДвоичныеДанные): Каталог не обнаружен 'C:\Program Files (x86)\OneScript\lib\vanessa-automation\vendor\1C\UILogToScript.epf'

VA 1.2.024
при завершении записи в "Работа с UI"
VA установлена через opm

**Comment by Pr-Mex** [comment]
Да. Тот же каталог.

**Comment by Pr-Mex** [comment]
Решено.
