### ISSUE TITLE
Ошибка шага "Я делаю паузу <Пауза> секунды"

### ISSUE THREAD

**Issue by theshadowco** [Pr-Mex/vanessa-automation#314]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Использование паузы
   Как пользователь
   Я хочу Использовать стандартный шаг с паузой и он должен работать верно

Контекст:
  Дано: 1.2.024
  И 8.3.10.2580
  и Любая

Сценарий: Использую шаг паузы и он работает верно
  Допустим: я хочу приостановить выполнение на 40 секунд
  Когда: я вызываю шаг "И Я Делаю паузу 40 секунды"
  Тогда: пауза 1 секунду

```

Причина ошибки в том, что не устанавливается значение «ДатаНачалаОбработкиОжидания»

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
Ты пишешь про ОФ или УФ?

**Comment by theshadowco** [comment]
УФ

**Comment by Pr-Mex** [comment]
@theshadowco 
Сейчас (и раньше) процедура выглядит вот так.
ДатаНачалаОбработкиОжидания заполняется.
Покажи что у тебя в модуле?
![image](https://user-images.githubusercontent.com/8627416/59995671-a58cb680-9660-11e9-94ff-72f71e7bf0a3.png)

**Comment by theshadowco** [comment]
Здесь разговор про другой метод "И Я Делаю паузу "" секунды"

**Comment by Pr-Mex** [comment]
Решено.
