### ISSUE TITLE
Ошибка установки значения в ТекстовйДокумент посредством "ВвестиТекст"

### ISSUE THREAD

**Issue by theshadowco** [Pr-Mex/vanessa-automation#317]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Ввод текста в "ТекстовыйДокумент"
   Как пользователь
   Я хочу Использовать ввод текста в реквизит "ТекстовыйДокумент" который работает правильно

Контекст:
  Дано: 1.2.024
  И 8.3.10.2580
  и Любая

Сценарий: Ввод текста в поле "ТекстовыйДокумен"
  Допустим: я имею форму со строковым реквизитом, который отображен на форме как "ТекстовыйДокумент"
  Когда: вызываю шаг установки значения
  Тогда:  не обновляется значение связанного реквизита

```

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
@theshadowco 
Нужен пример воспроизведения.

**Comment by Pr-Mex** [comment]
@theshadowco 
Учти, что в новых версиях платформы это может работать по разному.
Я помню, что регистрировал ошибку на такое и это исправлялось.

**Comment by theshadowco** [comment]
@Pr-Mex 

Возможно в новых версиях и работает, здесь именно 8.3.10.

**Comment by Pr-Mex** [comment]
@theshadowco 
Если проблема на стороне платформы - то надо использовать более новые версии платформы.
Приложи пример для воспроизведения, проверим.

**Comment by theshadowco** [comment]
Повторить не удается, похоже на локальный глюк
