### ISSUE TITLE
Ошибка при использовании Lang=En

### ISSUE THREAD

**Issue by hawk911** [Pr-Mex/vanessa-automation#318]
VA: 1.2.0.24
Был добавлен новый элемент `ДанныеАллюрМеток` и при поиске синонима появлялась ошибка, потому что элемент имеет значение `Неопределено`.
![image](https://user-images.githubusercontent.com/11535209/60259799-4352e080-9902-11e9-8b94-8447e02da99d.png)

**Comment by Pr-Mex** [comment]
Решено.
