### ISSUE TITLE
Невсегда корректно запускается клиент тестирования из фичи

### ISSUE THREAD

**Issue by Lopner** [Pr-Mex/vanessa-automation#326]
Запускаю Vanessa Automation (single edition 24 версия) с подготовленными тестами. 
Так как только знакомлюсь с данной технологией, возможно чего то не знаю 

При подключении к TestClient с прописанными параметрами (база, пользователь, пароль) подключение происходит не всегда, так как база иногда открывается более 25 секунд. И соответственно остальные фичи пролетают мимо. Открывать на каждой фиче новое подключение и закрывать его в конце - это + (1-2) минуты * N фич. 

Есть какой-то более стабильный вариант подключения клиента тестирования? 

Один день работает нормально, другой не отрабатывает. Отчет в Allure2 скачет туды-сюды

**Comment by Pr-Mex** [comment]
@Lopner 
Укажите в json параметр, который определяет таймаут на запуск клиента тестирования.
Пример
https://github.com/Pr-Mex/vanessa-automation/blob/develop/tools/JSON/VBParams8313UF_FastCheck.json#L55

**Comment by Lopner** [comment]
Спасибо!
