### ISSUE TITLE
Ошибка установки пакета из хаба

### ISSUE THREAD

**Issue by theshadowco** [Pr-Mex/vanessa-automation#332]
Не удается установить актуальную версию из хаба

```
λ opm install vanessa-automation
ИНФОРМАЦИЯ - Скачиваю файл: vanessa-automation.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет vanessa-automation
ПРЕДУПРЕЖДЕНИЕ - Обрабатываю возникшую ошибку...
{Модуль C:\reps\fork\opm\src\core\Классы\МенеджерУстановкиПакетов.os / Ошибка в строке: 120 / {Модуль C:\reps\fork\opm\src\core\Классы\УстановкаПакета.os / Ошибка в строке: 173 / Внешнее исключение (Ionic.Zip.BadReadException): bad read of entry tools/ServiceBases/v82ServiceBase82/1Cv8.1CD from compressed archive.}}
```

```
λ opm install vanessa-automation@1.2.022
ИНФОРМАЦИЯ - Скачиваю файл: vanessa-automation-1.2.022.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет vanessa-automation
ИНФОРМАЦИЯ - Установка завершена
```

**Comment by Pr-Mex** [comment]
Решено.

**Comment by alkoleft** [comment]
На версии 1.2.026 проблемы исчезла, но на 27 опять появилась

```bash
opm install vanessa-automation@1.2.027
ИНФОРМАЦИЯ - Скачиваю файл: vanessa-automation-1.2.027.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет vanessa-automation
ПРЕДУПРЕЖДЕНИЕ - Обрабатываю возникшую ошибку...
{Модуль C:\Program Files (x86)\OneScript\lib\opm\src\core\Классы\МенеджерУстановкиПакетов.os / Ошибка в строке: 120 / {Модуль C:\Program Files (x86)\OneScript\lib\opm\src\core\Классы\УстановкаПакета.os / Ошибка в строке: 173 / Внешнее исключение (Ionic.Zip.BadReadException): bad read of entry tools/ServiceBases/v82ServiceBase82/1Cv8.1CD from compressed archive.}}
```

**Comment by Pr-Mex** [comment]
@alkoleft 
Перезалил пакет. Проверь, пожалуйста.

**Comment by Pr-Mex** [comment]
Решено.

**Comment by ErmochenkoMA** [comment]
Не устанавливается версия 1.2.041.22, хотя версия 1.2.041.1 установилась без ошибок.

06:31:35  ИНФОРМАЦИЯ - Скачиваю файл: vanessa-automation-1.2.041.22.ospx
06:31:35  ИНФОРМАЦИЯ - Ошибка подключения к хабу ОсновнойСерверПакетов <404>
06:31:35  ИНФОРМАЦИЯ - Ошибка подключения к хабу ЗапаснойСерверПакетов <404>
06:31:35  {Модуль C:\Program Files (x86)\OneScript\lib\opm\src\core\Классы\МенеджерПолученияПакетов.os / Ошибка в строке: 49 / Ошибка установки пакета vanessa-automation: Нет соединения}

**Comment by Pr-Mex** [comment]
@ErmochenkoMA 
А другие пакеты скачиваются?

**Comment by ErmochenkoMA** [comment]
Да, устанавливал версии 1.2.038 и 1.2.041.1. Мне в группе testspro1c подсказали, что для последней версии можно использовать SNAPSHOT вместо указания конкретной версии, использовал его помогло.
