### ISSUE TITLE
при выполнении сценария курсор мыши перемещается в правую нижнюю точку экрана

### ISSUE THREAD

**Issue by gidrest** [Pr-Mex/vanessa-automation#334]
Добрый день !
Пробую делать авто-инструкцию в VanessaBehavior - при выполнении сценария курсор мыши перемещается в правую нижнюю точку экрана и не перемещается к активному элементу ,соответственно рамку обрисовывает на весь размер активного окна . Подскажите что не так ?

**Comment by Pr-Mex** [comment]
> Добрый день !
> Пробую делать авто-инструкцию в VanessaBehavior - при выполнении сценария курсор мыши перемещается в правую нижнюю точку экрана и не перемещается к активному элементу ,соответственно рамку обрисовывает на весь размер активного окна . Подскажите что не так ?

Инструмент называется Vanessa Automation )))
Перемещение курсора мыши перестало работать начиная с 8.3.12.
Об  этих и других особенностях записи видео написано тут
https://github.com/Pr-Mex/vanessa-automation/blob/develop/MakeAutoVideo.md

**Comment by Pr-Mex** [comment]
Решено.
