### ISSUE TITLE
Нужно придумать так, чтобы не вставлять везде "Я"

### ISSUE THREAD

**Issue by fenixnow** [Pr-Mex/vanessa-automation#339]
Научить систему сопоставлять шаги с отсуствующим "я" по тексту
![image](https://user-images.githubusercontent.com/13418562/61277311-9b229000-a7ba-11e9-805e-502d57971e35.png)

**Comment by fenixnow** [comment]
Посмотрел, поиск шагов происходить по "СтрокаДляПоиска", также есть "IDИзStepDefinition"
при правильном формировании этих задача реализуемая :)

**Comment by asosnoviy** [comment]
[Якорь в телеге](https://t.me/testspro1c/11037)

**Comment by fenixnow** [comment]
1. Да
2. Да
3. Да
В технической реализации она мне кажется не сильно сложной. Ведь есть у нас выпиливание буквы "И" из начала строки. В идеале, да, как говорил Дмитрий Мармышев и Никита Грызлов, хорошо иметь контекстную подсказку внутри обработки и не заморачиваться с вариантами написания шагов.

**Comment by Pr-Mex** [comment]
Не понимаю как это улучшит читаемость, т.к. кажется наоборот, это «я» добавляет  читаемости.
Убыстрение написания, на мой взгляд, надо через удобные редакторы, контекстные подсказки и подобное.
Может голосовалку откроем?

**Comment by fenixnow** [comment]
Мы уходим в сторону от идеи, не нужно избавляться от Я навсегда.
Посмотрите на первый скрин, в трех первых строчках используется Я, но сопоставление с шагом не происходит.
Идея в том, чтобы дать возможность не учитывать Я в переменной СтрокаДляПоиска

**Comment by fenixnow** [comment]
Почитав шаги думаю, что я не прав по отношению к Я 😄

**Comment by Pr-Mex** [comment]
Думаешь можно оставить как есть?

**Comment by fenixnow** [comment]
Да
