### ISSUE TITLE
Новые картинки для строк дерева шагов

### ISSUE THREAD

**Issue by fenixnow** [Pr-Mex/vanessa-automation#343]
Прошу заменить картинки на более свежие :)

![image](https://user-images.githubusercontent.com/13418562/61394087-0eb3c280-a8cb-11e9-94f9-de69b9c9ca61.png)

![КолекцияШагов](https://user-images.githubusercontent.com/13418562/61394201-46bb0580-a8cb-11e9-9205-291777eb692f.png)

Или через Пулл?

**Comment by Pr-Mex** [comment]
Здорово! Нравится! ))))
Вопрос по зеленой букве K.
Я бы оставил зелёный цвет за успешно выполненными шагами. Может синиц для неё выбрать или другой какой-нибудь?

**Comment by fenixnow** [comment]
![КолекцияШагов1](https://user-images.githubusercontent.com/13418562/61395655-9ea73b80-a8ce-11e9-8a56-7788d58948af.png)

**Comment by Pr-Mex** [comment]
Ага. Я за.

**Comment by fenixnow** [comment]
@Pr-Mex ты затянешь картинку?

**Comment by Pr-Mex** [comment]
Давай лучше реквестом.
