### ISSUE TITLE
ПолучитьПолноеИмяФайла

### ISSUE THREAD

**Issue by fenixnow** [Pr-Mex/vanessa-automation#346]
Предлагаю добавить метод получения абсолютных путей к файлу
Сейчас мы используем конструкцию 

`ИмяФайла = ДополнитьСлешВПуть(Объект.ВерсияПлатформыДляГенерацииEPF) + "1cv8.exe";`

`ИмяФайла = ДополнитьСлешВПуть(Объект.КаталогИнструментов) + "lib/Video/РаботаСВидео.epf";`

во второй строке слеши не учитывают специфику операционной системы

`Функция ПолучитьПолноеИмяФайла(Знач ИмяКаталога, Знач ИмяФайла)

	СистемнаяИнформация = Новый СистемнаяИнформация;
	ЭтоWindows = СистемнаяИнформация.ТипПлатформы = ТипПлатформы.Windows_x86 
				Или СистемнаяИнформация.ТипПлатформы = ТипПлатформы.Windows_x86_64;
	
	Слэш = "";
	Если (Прав(ИмяКаталога, 1) <> "\") И (Прав(ИмяКаталога, 1) <> "/") Тогда
		Слэш = ?(СтрНайти(ИмяКаталога, "\") = 0, "/", "\");
	КонецЕсли;
	
	ПолноеИмяФайла = ИмяКаталога + Слэш + ИмяФайла;		
	Если ЭтоWindows Тогда 
		ПолноеИмяФайла = СтрЗаменить(ПолноеИмяФайла, "/", "\");
	Иначе 
		ПолноеИмяФайла = СтрЗаменить(ПолноеИмяФайла, "\", "/");
	КонецЕсли;
	
	Возврат ПолноеИмяФайла;
	
КонецФункции`

Думается мне, читаемость кода улучшится.
Что скажите?

**Comment by zeegin** [comment]
Лучше сделать 
```bsl
ОбъединитьПути(Объект.КаталогИнструментов, "1cv8.exe")
```
по примеру с NodeJs: https://nodejs.org/api/path.html#path_path_join_paths
```js
path.join([...paths])
path.join('/foo', 'bar', 'baz/asdf', 'quux', '..'); // Returns: '/foo/bar/baz/asdf'
path.normalize(path)
```
Python: https://docs.python.org/2/library/os.path.html#os.path.join

```python
os.path.join(path, *paths)
os.path.join("c:", "foo")
os.path.normpath(path)
# up-level references so that A//B, A/B/, A/./B and A/foo/../B all become A/B
```

**Comment by fenixnow** [comment]
Ну у нас названия переменных по коду называться "имяФайла" я руководствовался еще этим

**Comment by zeegin** [comment]
Ну и получится
```bsl
ИмяФайла = ОбъединитьПути(Объект.ВерсияПлатформыДляГенерацииEPF, "1cv8.exe");
ИмяФайла = ОбъединитьПути(Объект.КаталогИнструментов, "lib/Video/РаботаСВидео.epf");
```

Реализация есть в OneScript https://github.com/EvilBeaver/OneScript/blob/d9bf73f7c5b9887b687544be8fe819765346c3d3/src/ScriptEngine.HostedScript/Library/FileOperations.cs хочется такое же.

В add сделано так: https://github.com/silverbulleters/add/blob/2e7fe8e2e9291d6f3fad2bd270e564134de3b685/features/libraries/%D0%A4%D0%B0%D0%B9%D0%BB%D1%8B/step_definitions/%D0%A4%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D1%8B%D0%B5_%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8/%D0%A4%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D1%8B%D0%B5_%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D0%B8/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L450

**Comment by fenixnow** [comment]
@zeegin прошу прокоментировать такую реализацию

`// Возвращает полный путь к файлу или каьалогу
// 
&НаКлиенте
Функция ОбъединитьПути(ИмяКаталога, Знач Часть1 = "", Знач Часть2 = "", Знач Часть3 = "", Знач Часть4 = "", Знач Часть5 = "", Знач Часть6 = "")

	ПолныйПуть = ИмяКаталога;
	
	РазделительПути = ПолучитьРазделительПути();
	
	Если РазделительПути = "\" Тогда
		СлешДо = "/";
	Иначе
		СлешДо = "\";
	КонецЕсли;
	
	ПолныйПуть = СтрЗаменить(ИмяКаталога, СлешДо, РазделительПути);
	
	Если Прав(ПолныйПуть, 1) <> РазделительПути Тогда
		ПолныйПуть = ИмяКаталога + РазделительПути;
	КонецЕсли;
	
	Для НомерЧасти = 1 По 6 Цикл
		ЧастьПути = Вычислить("Часть" + НомерЧасти);
		Если Не ПустаяСтрока(ЧастьПути) Тогда
			ЧастьПути = СтрЗаменить(ЧастьПути, СлешДо, РазделительПути);
			ПолныйПуть = ПолныйПуть + ЧастьПути + РазделительПути;
		КонецЕсли;
	КонецЦикла;

	Возврат ПолныйПуть;
	
КонецФункции`

**Comment by zeegin** [comment]
@fenixnow 

https://its.1c.ru/db/v8std#content:669:hdoc
https://its.1c.ru/db/v8std#content:770:hdoc

Лучше избегать метода `Вычислить` если это возможно. Тут кажется возможно, например собрать части в массив и обойти массив.

Надо посмотреть нужно или нет делать `СокрЛП` и как ведут себя аналоги на других языках - т.е. проверить конкатенацию путей `часть1`. `    часть2   `, ` /часть3/ `

Здесь врядли будут проблемы с производительностью, слишком мало кода, но все же строки лучше так не конкатиниривать `ПолныйПуть = ПолныйПуть + `. См. https://its.1c.ru/db/v8std#content:782

**Comment by fenixnow** [comment]
Наверное итоговый мой вариант.
Включил в окончание имя файла

`// Возвращает полный путь к файлу или каталогу
//
// Параметры:
//  ИмяКаталога	 - Строка	 - Начальный путь
//  Часть1 - 4	 - Строка	 - Части путей
//  ИмяФайла	 - Строка	 - Имя конечного файла
// 
// Возвращаемое значение:
//  Строка - Итоговый полный путь
//
&НаКлиентеНаСервереБезКонтекста
Функция ОбъединитьПути(ИмяКаталога, Знач Часть1 = "", Знач Часть2 = "",	Знач Часть3 = "", Знач Часть4 = "", Знач ИмяФайла = "")

	ПолныйПуть = ИмяКаталога;

	РазделительПути = ПолучитьРазделительПути();

	Если РазделительПути = "\" Тогда
		СлешДо = "/";
	Иначе
		СлешДо = "\";
	КонецЕсли;

	ПолныйПуть = СтрЗаменить(ИмяКаталога, СлешДо, РазделительПути);

	Если Прав(ПолныйПуть, 1) <> РазделительПути Тогда
		ПолныйПуть = ИмяКаталога + РазделительПути;
	КонецЕсли;

	МассивЧастейПути = Новый Массив;
	МассивЧастейПути.Добавить(Часть1);
	МассивЧастейПути.Добавить(Часть2);
	МассивЧастейПути.Добавить(Часть3);
	МассивЧастейПути.Добавить(Часть4);

	Для Каждого ЧастьПути Из МассивЧастейПути Цикл
		Если Не ПустаяСтрока(ЧастьПути) Тогда
			ЧастьПути = СтрЗаменить(СокрЛП(ЧастьПути), СлешДо, РазделительПути);
			ПолныйПуть = ПолныйПуть + ЧастьПути + РазделительПути;
		КонецЕсли;
	КонецЦикла;

	Если Не ПустаяСтрока(ИмяФайла) Тогда
		ПолныйПуть = ПолныйПуть + ИмяФайла;
	КонецЕсли;

	Возврат ПолныйПуть;

КонецФункции`

**Comment by fenixnow** [comment]
влито
