### ISSUE TITLE
Где взять документацию по проекту?

### ISSUE THREAD

**Issue by forsaled** [Pr-Mex/vanessa-automation#369]
Пытаюсь начать работать с ВА. Никакой документации по проекту, что это, как пользоваться, быстрый старт, сквозной пример - ничего этого не нашёл. На главной странице - только фак с более продвинутыми вопросами, и ссылки на несколько статей, которые больше похожи на описание возможностей. А видеоинструкции описывают создание видеоинструкций) Если всё-таки это где-то есть - буду очень благодарен за ссылки.

Соответственно, включаю обработку, жму "Добавить известный шаг" - библиотека пустая. И на сингле, и на не сингле. Куда идти, что читать, как понять, что делать - ума не приложу. Неужели в код лезть?

**Comment by Pr-Mex** [comment]
Для начала прочтите статьи на инфостарте Владимира Литвиненко
https://infostart.ru/public/969637/
Они написаны на примере ADD, но всё тоже самое справедливо и для VA.

**Comment by forsaled** [comment]
Статьи прочёл, спасибо за ссылку. Но вот уткнулся в пустые известные шаги, в АДД тоже была проблема такая, но в новой версии проблема ушла, шаги стали появляться всегда. О том, куда лезть, чтобы найти шаги, в статьях ничего не написано, там предполагается, что это работает.

Также статьи, это, конечно, хорошо, но неужели у такого титанического труда нет нормальной документации? Я от АДД полез в ВА потому, что вижу, что работа с не1Сными объектами есть, т.е. можно открывать сторонние приложения и т.п. Для меня это очень важно и именно это преимущество заставило разбираться именно с ВА. Но без документации это, получается, нужно весь код самому анализировать!

**Comment by nixel2007** [comment]
> Но вот уткнулся в пустые известные шаги

откройте любую фичу на первой вкладке и нажмите Перезагрузить. Шаги появятся. Ишуз на доработку этого неудобства уже висит буквально тремя строками ниже https://github.com/Pr-Mex/vanessa-automation/issues/364

**Comment by nixel2007** [comment]
Остальная имеющаяся документация доступна либо по f1, либо в каталоге docs, либо в каталоге features этого репа. Остальная имеющаяся документация доступна либо по f1, либо в каталоге docs, либо в каталоге features этого репа.

**Comment by Pr-Mex** [comment]
Документация наполняется медленно. Если есть желание поучаствовать - добро пожаловать!

**Comment by forsaled** [comment]
Да я бы с радостью, только знаний сейчас - ноль по этой теме. Я думаю, что для того, чтобы контрибьюторов было больше, была большая заинтересованность в продукте, нужно отцам-основателям, тем, кто знает, как это работает, сделать хотя бы какие-то видео или даже аудиорассказы, чтобы быстрее, своими словами. Дальше уже в том числе я могу по ним написать хоть какие-то доки. После того, как будет хоть видео, хоть аудио, хоть какие-то материалы, люди потянутся охотнее. Именно поэтому у любого маломальски серьёзного проекта за бугром всё с документации начинается. Например, я изучал электрон - там очень сильно всё задокументировано, хотя проект тоже активно развивается. Но документация даёт толчок интересоваться, говорить о продукте, появляется сообщество, часть которого обязательно будет контрибьютить.

А сейчас я зашёл, потолкался тут, ничё не понятно. Ну поплачу тихонько и уйду, как и многие. Образно, конечно, и не в упрёк кому-то - я же вижу, труд титанический проведён. Но проблема видна, и из-за этой проблемы, как мне кажется, и контрибьюторов мало. И каждому ковыряться в коде - ну это не наш метод.

**Comment by Pr-Mex** [comment]
Создание автоинструкций упрощает задачу. Но сначала пришлось переработать движок для создания автоинструкций. Это было совсем недавно. Дело движется, но рук не хватает.
