### ISSUE TITLE
HOST при формировании отчета Allure

### ISSUE THREAD

**Issue by zeegin** [Pr-Mex/vanessa-automation#371]
https://github.com/Pr-Mex/vanessa-automation/blob/6296546ac53991398d9bf96debe805da06788eb6/VanessaAutomation/Ext/ObjectModule.bsl#L1736

```bsl
СписокМеток =  СтруктураВыгрузки.labels;
ДобавитьМетку2(СписокМеток, "host", СисИнформация.ВерсияОС, СписокМетокПереопределяемый);
```

Здесь в `host` должно быть имя компьютера а не версия ОС, это нужно для того, чтобы на вкладке `Timeline` можно было видеть распределение времени выполнения по разным раннерам.

**Comment by Pr-Mex** [comment]
Ок.

**Comment by Pr-Mex** [comment]
Решено.
