### ISSUE TITLE
Отсутствует английский синоним у шага "я набираю текст"

### ISSUE THREAD

**Issue by pzhgulev** [Pr-Mex/vanessa-automation#379]
Функционал: английский синоним у шага 
   Я хочу чтобы шаг "я набираю текст" имел английский синоним

Контекст:
  Дано: VA 1.2.025

**Comment by Pr-Mex** [comment]
@pzhgulev 
Интересно. Вообще он должен быть. Посмотрю.

**Comment by Pr-Mex** [comment]
Решено.
