### ISSUE TITLE
Возможность указывать Intro и Outro видео файлы для автоинструкций

### ISSUE THREAD

**Issue by pzhgulev** [Pr-Mex/vanessa-automation#380]
Функционал: добавить к авто инструкции возможность указывать Intro и Outro видео файлы.
   Как Пользователь VA
   Я хочу чтобы была возможность в настройках указать видео файлы, которые при сборке авто-инструкций VA подставит в Intro и Outro, при этом музыка для сценария на них накладываться либо не будет, либо это будет опционально.

Контекст:
  Дано: VA 1.2.025
  И Платформа 1С версии 8.3.14.1779
  И Самописная конфигурация

**Comment by Sv-Vik** [comment]
Взяла в работу

**Comment by Pr-Mex** [comment]
Решено.
