### ISSUE TITLE
Лишние паузы между шагами видео

### ISSUE THREAD

**Issue by pzhgulev** [Pr-Mex/vanessa-automation#381]
Функционал: Создавать более плавные видео, без искусственных пауз
   Как пользователь VA
   Я хочу избавиться от лишних пауз между шагами, которые сейчас появляются в автоинструкциях

Контекст:
  Дано: VA 1.2.025
  И Платформа 1С версии 8.3.14.1779
  и Демо конфигурация во вложении

Во вложении архив с демо конфигурацией, фичей, скриншотами для кликов и получившейся автоинструкцией.
Хочется иметь возможность управлять паузами, которые возникают между шагами. 
Например между фактическим кликом "Given click "Accounting" picture" и началом произношения *Click on entities, from master data operational panel...

[_CaseForIssue.zip](https://github.com/Pr-Mex/vanessa-automation/files/3466156/_CaseForIssue.zip)

**Comment by Pr-Mex** [comment]
Ок. Буду смотреть.
