### ISSUE TITLE
Не загружаются настройки JSON файла (EN)

### ISSUE THREAD

**Issue by hawk911** [Pr-Mex/vanessa-automation#386]
```Gherkin
Контекст:
  Дано: Текущая VA с develop
  
Сценарий: Загрузился JSON с английскими представлениями полей
  Допустим: У меня есть JSON файл с английскими представлениями полей
  Когда: Я загружают этот файл 
  Тогда: Ничего не происходит

```
Более подробная информация тут: 

https://github.com/Pr-Mex/vanessa-automation/pull/105

Пример, JSON файла: 

```JSON
{
    "buildname":"TestBase",
    "featurepath": "./tests",
    "directorytobuildhierarchy": "./tests",
    "reportlevel1": "#report.epic=;catalog1",
    "reportlevel2": "#report.feature=;catalog2",
    "reportlevel3": "#report.story=;scenarioname",
    "vanessarun": "True",
    "Lang":"en",
    "vanessashutdown": "True",
    "projectpath": "",
     "testclienttable":[
        {
            "name": "this client",
            "pathtoinfobase": "/F.\\ServiceBases\\v83ServiceBase8314",
            "additionalparameters": "/N admin /L en ",
            "clienttype": "Thin",
            "computermame": "localhost",
            "porttestclient": "1538",
            "activatestring": "True"
        }
    ],
    "closetestclient": "False",
     "logtogr": "False",
    "gherkinlanguage": "en",
    "allurecreatereport": "True",
    "junitcreatereport": "True",
    "cucumbercreatereport": "False",
    "logtotext": "True",
    "logstepstotext": "True",
    "allurepathbase": "D:/rep/log/allure",
    "junitpath": "D:/rep/log/jUnit",
    "cucumberreportpath": "./tools/ServiceBases/cucumber",
    "createsubfolderforbuild": "True",
    "onerrorscreenshot": "True",
    "onerrorscreenshoteverywindow": "False",
    "outputscreenshot": "./tools/ServiceBases/ScreenShots",
    "textlogname": "D:/rep/log/steps/test.txt",
    "logerrorstotext": "True",
    "texterrorslogname": "D:/rep/log/errors_json",
    "commandscreenshot": "\"C:/Program Files (x86)/IrfanView/i_view32.exe\" /capture=1 /convert=",
    "createlogs": "True",
    "addtofeaturefilter": "True",
    "logpath": "D:/rep/log/test_BuildStatus.log",
    "platformversiongenerateepf": "C:/Program Files/1cv8/8.3.14.1533/bin",
    "testclienttimeout": 30,
    "filtertags":[
    "Init"
    ],
    "makestepsasync":"False"
 }
 ```

**Comment by fenixnow** [comment]
нужно подумать, как дать понять при загрузке что в файле EN названия.
При загрузке из файла нет параметров, как при загрузке из командной строки, хотя есть в структуре JSON параметр ОсновнойЯзык

**Comment by fenixnow** [comment]
параметр ОсновнойЯзык - это что то не используемое

**Comment by Pr-Mex** [comment]
@fenixnow 
В коде 1.2.025 использовался этот параметр
![image](https://user-images.githubusercontent.com/8627416/62618272-7b473d80-b91c-11e9-88d6-ade4fb74164a.png)

**Comment by fenixnow** [comment]
ок, я сделаю механизм локализации через внешний файл с локализацией, 
нужно будет только дописать туда свежие параметры

**Comment by hawk911** [comment]
Добавил в пример JSON файла информацию о `testclienttable` на английском.

**Comment by fenixnow** [comment]
> ЗавершитьРаботуСистемы

Это реквизиты запуска из командной строки и не учавствуют в выгрузке/загрузке настроек обработки.
на lang, version, versionVA убрал отображение сообщений

**Comment by fenixnow** [comment]
Можно конечно и это включить в Функция СтруктураОбщихНастроек
как раз я закладывал туда область с описание этих переменных

**Comment by Pr-Mex** [comment]
@fenixnow 
Какие-то из перечисленных сообщений останутся?

**Comment by fenixnow** [comment]
> @fenixnow
> Какие-то из перечисленных сообщений останутся?

Останутся для всех параметров, которые не удалось подсунуть в реквизиты объекта. Немного просто поменяю представление сообщения

**Comment by Pr-Mex** [comment]
Решено.

**Comment by hawk911** [comment]
Дошли руки до версии 1.2027 :) 
Загрузка параметров на английском не работает - через параметр "lang=En". Загружал json, что выше написан.  Строка запуска: 
`СтрокаПараметров = "StartFeaturePlayer;VBParams=D:\rep\Test\Settings.json;Lang=En";`

**Comment by Pr-Mex** [comment]
Параметр вроде должен быть внутри Json сейчас.

**Comment by fenixnow** [comment]
Фикс лежит в пуле

**Comment by hawk911** [comment]
> Фикс лежит в пуле

Класс. Жду 👍

**Comment by hawk911** [comment]
> Параметр вроде должен быть внутри Json сейчас.

В Json есть параметр `"Lang":"en"`

**Comment by hawk911** [comment]
![image](https://user-images.githubusercontent.com/11535209/65619151-d840a500-dfe9-11e9-9d83-252bb509fbdc.png)
Не работает.

**Comment by fenixnow** [comment]
Я так понимаю что это загрузка через командную строку?

**Comment by fenixnow** [comment]
Да, точно, выше же написано. Правил загрузку выгрузку через дискетку

**Comment by hawk911** [comment]
Создал новый issue, чтобы разделить проблемы ✈️
