### ISSUE TITLE
Не устанавливается через opm

### ISSUE THREAD

**Issue by PashaMak** [Pr-Mex/vanessa-automation#394]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Запуск тестов
   Как разработчик
   Я хочу писать качественный код

Контекст:
  Дано: onescript версии 1.1.1
  И 1С:Предприятие 8.3 (8.3.14.1630)

Сценарий: Компиляция исходников
  Допустим: Вызываю команду opm install vanessa-automation
  Когда: Командная строка запущена под администратором
  Тогда: Получаю ошибку вместо установки

```

> Прикладывайте файлы скриншотов
![Скриншот 12-08-2019 210833](https://user-images.githubusercontent.com/24808007/62871637-0de54380-bd46-11e9-9aa0-7b279f85980a.png)

**Comment by Pr-Mex** [comment]
Дубль
https://github.com/Pr-Mex/vanessa-automation/issues/332
Будет исправлено с 1.2.026.
