### ISSUE TITLE
Открытие любой формы

### ISSUE THREAD

**Issue by GlavD** [Pr-Mex/vanessa-automation#405]
Предлагаю реализовать механизм открытия форм.
Назвать шаг к примеру "Открыть произвольную форму".

**И я открываю произвольную форму "CommonForm.Test"**

Когда такой шаг встречается в фиче, VA генерит внешнюю обработку, у которой в процедуре "ПриОткрытии" код

Процедура ПриОткрытии(Параметр1)
      ОткрытьФорму([Параметр1]);
      ЭтаФорма.Закрыть();
КонецПроцедуры

**Comment by nixel2007** [comment]
Из коробки уже есть открытие по навигационной ссылке. Делает почти тоже самое.

**Comment by GlavD** [comment]
у общей формы нет навигационной ссылки

**Comment by GlavD** [comment]
Еще, в такой метод можно реализовать передачу параметров

**Comment by Pr-Mex** [comment]
@GlavD 
Если выполнить такой код, тогда форма откроется на стороне TestManager. Если нужно открытие формы в TestClient - тогда нужно делать расширение.

**Comment by Pr-Mex** [comment]
Закрываю.
