### ISSUE TITLE
Шаг открытия основной формы списка РС открывает форму записи

### ISSUE THREAD

**Issue by igostv** [Pr-Mex/vanessa-automation#434]
Раньше шаг открывал форму списка, теперь открывает форму записи
https://github.com/Pr-Mex/vanessa-automation/blob/c757e574b5fe2ad118f17b9a55761c03b07e5b2a/features/Libraries/VB/step_definitions/%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%D0%A4%D0%BE%D1%80%D0%BC%D1%83%D0%A7%D0%B5%D1%80%D0%B5%D0%B7%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%83/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L184

Но теперь есть другой шаг, шаг для открытия списка, но он тоже открывает форму записи, т.к. вызывает не ту функцию 
https://github.com/Pr-Mex/vanessa-automation/blob/c757e574b5fe2ad118f17b9a55761c03b07e5b2a/features/Libraries/VB/step_definitions/%D0%9E%D1%82%D0%BA%D1%80%D1%8B%D1%82%D1%8C%D0%A4%D0%BE%D1%80%D0%BC%D1%83%D0%A7%D0%B5%D1%80%D0%B5%D0%B7%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%83/Forms/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/Ext/Form/Module.bsl#L37

related to #433

**Comment by fenixnow** [comment]
Воспользуйтесь пока версией 26,
этот функционал похоже попал в основную ветку намного раньше

**Comment by fenixnow** [comment]
постарался исправить в коммите b037f3dffae1f814349d74656e5360fb8815461c
