### ISSUE TITLE
Генератор кода gherkin игнорирует настройку языка

### ISSUE THREAD

**Issue by tsukanov-as** [Pr-Mex/vanessa-automation#435]
Если в настройках Ванессы указан английский язык, то при записи сценария код генерируется на английском языке. Но если воспользоваться кнопками получения состояния формы/элемента, то код сгенерируется на русском:
![image](https://user-images.githubusercontent.com/17392154/65327036-86e48000-dbbb-11e9-947e-f26a53cbedc5.png)

**Comment by Pr-Mex** [comment]
Ок. Понял.

**Comment by Pr-Mex** [comment]
Решено.
