### ISSUE TITLE
Ошибка с переменной в таблице 

### ISSUE THREAD

**Issue by MJIbIu** [Pr-Mex/vanessa-automation#436]
VA 1.2.027
И я запоминаю строку 'Сообщить("Hellow world.")' в переменную "Переменная"
И я выполняю код встроенного языка на сервере 
|'$Переменная$'|

Падает с ошибкой
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(6946)}: Ошибка компиляции при вычислении выражения или выполнении фрагмента кода: {(1,1)}: Ожидается последовательность операторов

**Comment by Pr-Mex** [comment]
Сделана обработка таблиц Gherkin с автоподстановкой значений переменных.
