### ISSUE TITLE
TestClient запускается не под тем пользователем, который указан в сценарии

### ISSUE THREAD

**Issue by ovcharenko-di** [Pr-Mex/vanessa-automation#439]
Есть две фичи:

———
Фича 1.feature:

Сценарий: сценарий 1
Когда Я открыл сеанс TestClient от имени "Администратор" с паролем "" или подключаю уже существующий
#шагисценария
И я закрываю сеанс TestClient
Когда Я открыл сеанс TestClient от имени "Пользователь" с паролем "" или подключаю уже существующий
#шагисценария
———
Фича 2.feature:

Сценарий: сценарий 2
Когда Я открыл сеанс TestClient от имени "Администратор" с паролем "" или подключаю уже существующий
#шагисценария
———

При выполнении этих фич в CI сценарий 2 почему-то запускается под Пользователем, а не под Администратором. Возможно, проблему решит добавление в фичу 1 еще одного шага "И я закрываю сеанс TestClient", в самый конец. Но это способ обхода, а не решение.

**Comment by Pr-Mex** [comment]
@ovcharenko-di 
Это скорее всего особенность работы шага, что когда есть подключенный клиент - то он переиспользуется, т.к. шаг всегда использует один и тот же профиль "Этот клиент".

Вот такой код точно работает без проблем:
``` Gherkin
Когда Я открыл сеанс TestClient от имени "Администратор" с паролем "" или подключаю уже существующий
И я закрываю сеанс TestClient
Когда Я открыл сеанс TestClient от имени "Пользователь" с паролем "" или подключаю уже существующий
И я закрываю сеанс TestClient
Когда Я открыл сеанс TestClient от имени "Администратор" с паролем "" или подключаю уже существующий
```

**Comment by Pr-Mex** [comment]
Закрываю.
