### ISSUE TITLE
Не сохраняются настройки "Клиенты тестирования"

### ISSUE THREAD

**Issue by MJIbIu** [Pr-Mex/vanessa-automation#440]
VA27 
Настроил несколько Клиентов тестирования. Нажимаю Выгрузить настройки в файл. в json нет настроенных клиентов.
![2019-09-24](https://user-images.githubusercontent.com/20815801/65518300-c3321c00-deec-11e9-82dd-9054fd77b352.jpg)

**Comment by MJIbIu** [comment]
не загружаются КлиентыТестирования
Пример      
"КлиентыТестирования":[
     {
       "Имя": "Тест001",
       "ПутьКИнфобазе": "/SSPDAPP\\main_release",
       "ДопПараметры": "/NПользователь /P123",
       "ТипКлиента": "Тонкий",
       "ИмяКомпьютера": "localhost",
       "ПортЗапускаТестКлиента": "1538",
	   "АктивизироватьСтроку": "Истина"
     }
   ]
Информация: Параметр клиентытестирования не загружен.

**Comment by Pr-Mex** [comment]
Сейчас это проектное решение.
Были вопросы - как лучше загружать клиентов тестирования и выгружать.
Предлагаю простой вариант. При загрузке добавлять записи. При этом старые записи остаются. При выгрузке - выгружать всё.

**Comment by Pr-Mex** [comment]
@fenixnow 
что скажешь?

**Comment by fenixnow** [comment]
Скажу, ок, сегодня-завтра сделаю

**Comment by fenixnow** [comment]
я вот подумал, значения
![image](https://user-images.githubusercontent.com/13418562/65713005-e1407d80-e0a0-11e9-9324-0375fcbb612e.png)
тоже нужно переводить?

**Comment by Pr-Mex** [comment]
Думаю да.

**Comment by Pr-Mex** [comment]
Решено.

**Comment by DarinaSa** [comment]
подскажите пожалуйста, всякий раз как пререлизную 1с базу затираем для тестов новых задач перед внедрением в рабочую базу, слетают настройки клиентов тестирования (как и в принципе настройки ванессы)
как это предотвратить?

**Comment by Pr-Mex** [comment]
@DarinaSa 
Настройки хранятся в разрезе хранилище настроек под конкретным пользователем.
Видимо пользователь создаётся/удалется.

**Comment by DarinaSa** [comment]
@Pr-Mex всё так. Жаль, что это никак не отладить.

**Comment by Pr-Mex** [comment]
@DarinaSa 
Это всё происходит в коде и поддаётся отладке.
