### ISSUE TITLE
Реализовать отключение финального слайда при записи видео

### ISSUE THREAD

**Issue by Sv-Vik** [Pr-Mex/vanessa-automation#453]
Функционал: Отключение финального слайда
   Как Пользователь
   Я хочу включать/отключить финальный слайд при записи видео

Сценарий:  Флаг Отключить слайд сценария установлен
  Когда: Установлен флаг Отключить слайд сценария
  Тогда: В видео инструкцию не попадает финальный слайд

Сценарий:  Флаг Отключить слайд сценария снят
  Когда: Снят флаг Отключить слайд сценария
  Тогда: В видео инструкцию попадает финальный слайд

**Comment by Pr-Mex** [comment]
Решено.
