### ISSUE TITLE
Вызов ассерта приводит к ошибке

### ISSUE THREAD

**Issue by KrapivinAndrey** [Pr-Mex/vanessa-automation#454]
https://github.com/Pr-Mex/vanessa-automation/blob/7bedcd0fb0dcec37a1fa84cd2bb3fe48c4c8c43d/VanessaAutomation/Ext/ObjectModule.bsl#L3178

Переменная Параметры связна с ДаннымиФормы и переопределять ее нельзя

![image](https://user-images.githubusercontent.com/586025/66108448-0a4e9a00-e5dc-11e9-87fc-4f7e32ed4e5e.png)

**Comment by KrapivinAndrey** [comment]
Вызов выглядел вот так

![image](https://user-images.githubusercontent.com/586025/66108516-30743a00-e5dc-11e9-81ce-c493bce3632b.png)

Нигде не сказано что так делать нельзя

**Comment by KrapivinAndrey** [comment]
Вызов выглядел вот так
![image](https://user-images.githubusercontent.com/586025/66108577-4da90880-e5dc-11e9-824a-051bcb2d7893.png)

**Comment by KrapivinAndrey** [comment]
Никто ж не говорит что так делать нельзя. Более того - второй параметр по умолчанию Неопределено - так что тоже упадет

**Comment by Pr-Mex** [comment]
@KrapivinAndrey привет. Дай больше данных, пожалуйста, о том что ты делаешь и что ты хочешь получить.

**Comment by KrapivinAndrey** [comment]
Пробую тесты для edt. Ребята написали тест на 2ом скриншоте. Вторым параметром передали Неопределено. *На клиенте* это приведет к ошибке. Потому что Данным формы "Параметры" будет присвоено Неопределено и va single закроется с неочевидной ошибкой

**Comment by KrapivinAndrey** [comment]
Фуф. Добрался до компа, проще писать. Итак. Я решил попробовать тесты в edt. Работают они через VA single. Что интересно - тест на скриншоте работает в edt. Настроил Jenkins на прогон тестов. И этот же тест (проверить открытие списка формы заявок) падает с ошибкой: Нельзя изменять данные формы.

Выяснил что падает при обращении к процедуре ПроверитьВыполнилось НаКлиенте. Из-за того что переменной Параметры присвается Неопределено. А это ошибка

**Comment by Pr-Mex** [comment]
@KrapivinAndrey 
Понял что происходит. Спасибо за инфо.

**Comment by Pr-Mex** [comment]
Решено.
