### ISSUE TITLE
Загрузка глобальных переменных из Consul-а

### ISSUE THREAD

**Issue by Wadus16** [Pr-Mex/vanessa-automation#455]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: <Загрузка глобальных переменных из Consul-а>
   Как <разработчиков тестов>
   Я хочу <иметь развернутую key-value базу Consul
   в которую я запишу все плавающие
   пользовательские переменные (имена баз, строки подключений, логины, пароли) 
   чтобы не влезать в фичи каждый раз, если я хочу их поменять>

Контекст:
  Дано: <Vanessa>
  И <8.3.14.1694>
  и <1С:ERP Управление предприятием 2 (2.4.7.151)>

Сценарий: <Я перехожу в Ванессе на закладку Сервис
И Я указываю в настройке "ПоставщикПользовательскихНастроек" значение "Consul"
И Я указываю в настройке "АдресПользовательскихНастроек" http адрес к Consul
Тогда Подтягивается контекст глобальных переменных.
 И в любой части теста я могу обращаться к этим переменным с помощью шагов, 
 которые поддерживают работу с ними, например: 
 И в поле 'ИмяПоля' я ввожу значение глобальной переменной 'ИмяПеременной' >

Сценарий: <Я перехожу в Ванессе на закладку Сервис
И Я указываю в настройке "ПоставщикПользовательскихНастроек" значение "File"
И Я указываю в настройке "АдресПользовательскихНастроек" путь к файлу user_settings.json
Тогда Подтягивается контекст глобальных переменных.
 И в любой части теста я могу обращаться к этим переменным с помощью шагов, 
 которые поддерживают работу с ними, например: 
 И в поле 'ИмяПоля' я ввожу значение глобальной переменной 'ИмяПеременной' >

**Comment by Wadus16** [comment]
В рамках #60  была сделана функциональность загрузки глобальных переменных из внешнего файла user_settings.json. Но нам этого уже недостаточно. Мы решили хранить все конфиги проекта во внешнем key-value хранилище, а не в текстовых файлах. А глобальные переменные сейчас можно загружать только из текстового файла внутри репозитория с проектом.

Для этого предлагается вывести дополнительный реквизит "ПоставщикПользовательскихНастроек" в котором можно выбрать вариант либо "File" (нужен для использования имеющегося функционала по задаче #60) либо Consul, а также дополнительный реквизит "АдресПользовательскихНастроек", в котором можно указать либо путь к файлу user_settings.json, либо http путь к Consul.

Функционал предлагается реализовать в виде отдельного плагина с названием "ЗагрузчикПользовательскихНастроек", хранить в папке "plugins".

Изначально эту доработку делал пользователь "ripreal" из нашей команды для репозитория silverbulleters/add, с его разрешения решено эту же доработку перенести и адаптировать сюда, так как планируем перейти именно на Vanessa-autimation.

**Comment by asosnoviy** [comment]
Ничего не понял, но звучит круто!

**Comment by fenixnow** [comment]
Думается мне, нужно делать это в отдельный плагин, как и обсуждалось ранее. Функционал специфичен

**Comment by Wadus16** [comment]
> Ничего не понял, но звучит круто!

старался сжато и понятно объяснить )) можно более детально посмотреть обсуждение задачи в add https://github.com/silverbulleters/add/pull/400

**Comment by Wadus16** [comment]
> Думается мне, нужно делать это в отдельный плагин, как и обсуждалось ранее. Функционал специфичен

Согласен, так я и предлагаю реализовать в виде плагина, то есть в планин будет перенесен текущий функционал из задачи  #60, а так же добавлен новый по consul. Этот плагин уже есть готовый на add, фактически я его адаптирую

**Comment by Pr-Mex** [comment]
@Wadus16 
Приветствую! Добро пожаловать в клуб!

**Comment by Pr-Mex** [comment]
Решено.
