### ISSUE TITLE
Новый механизм передвижения мышки на экране к элементам формы

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#462]
1. Без сохранения картинки заранее.
2. Без ручного написания шагов.
3. Без регистрации.
4. Без смс.

**Comment by fenixnow** [comment]
Что это? Объясни. Что за такой анонс?

**Comment by Pr-Mex** [comment]
@fenixnow 
Сейчас для создания красивого автовидео нужно снимать картинки с экрана. 
Данный ишуз решает этот вопрос.
Мышка будет перемещаться по экрану к нужному элементу формы.

**Comment by asosnoviy** [comment]
Почекал, огонь! С беду с основной конопкой формы уже решал?

**Comment by Pr-Mex** [comment]
> Почекал, огонь! А беду с основной конопкой формы уже решал?

@asosnoviy 
Расскажи подробнее что за проблема?

**Comment by asosnoviy** [comment]
> > Почекал, огонь! А беду с основной конопкой формы уже решал?
> 
> @asosnoviy
> Расскажи подробнее что за проблема?

Предполагаю, что проблема в цвете фона основной кнопки. Соответственно шаг `я нажимаю на кнопку "Записать и закрыть"` не работает.

**Comment by Pr-Mex** [comment]
@asosnoviy 
Ок. Посмотрю.

**Comment by Pr-Mex** [comment]
@asosnoviy 
Я тут прикинул. Ты ведь можешь просто переснять один раз ту картинку, которая не нашлась на экране и заменить файл на диске. После этого всё заработает.

**Comment by asosnoviy** [comment]
Сложно как то =( 
`Я нажимаю на основную кнопку формы "Записать и закрыть"` 

Через АПИ тестклиента можно понять какая кнопка "Основная" на форме?

**Comment by 1cgh** [comment]
ТестируемаяФорма (TestedForm)
НайтиКнопкуПоУмолчанию (FindDefaultButton)

**Comment by Pr-Mex** [comment]
> НайтиКнопкуПоУмолчанию

Спасибо! Совершенно забыло про это.

**Comment by Pr-Mex** [comment]
Решено.
