### ISSUE TITLE
Произношение текста по умолчанию 

### ISSUE THREAD

**Issue by fenixnow** [Pr-Mex/vanessa-automation#467]
При пустом тексте в поле тестирования голоса, хотелось произносить текст по умолчанию. Например  "Приет, я Ванесса!"
![image](https://user-images.githubusercontent.com/13418562/66418195-3ae26980-ea0a-11e9-8d3f-65631522b6d8.png)

**Comment by Pr-Mex** [comment]
@fenixnow 
Да, ты прав.

**Comment by Pr-Mex** [comment]
Решено.
