### ISSUE TITLE
шаг "Я устанавливаю фильтр на список" может ложно падать если в списке есть предопределенные отборы

### ISSUE THREAD

**Issue by PavelVir** [Pr-Mex/vanessa-automation#472]
Функционал:  Более универсальный алгоритм
   Как тестировщик
   Я хочу стабильной работы шагов

Контекст:
  Дано:  va 27
  И 8.3.13

Сценарий:  Я устанавливаю фильтр на список
  Допустим: в конфигурации для списка документов  есть предопределенный отбор
  Когда: открывается настройка списка
  Тогда: закладка по умолчанию не "Отбор" и шаг падает

> Прикладывайте файлы скриншотов

![image](https://user-images.githubusercontent.com/40602668/66704512-3200d900-ed25-11e9-9a49-e236350169e4.png)

**Comment by Pr-Mex** [comment]
Решено.
