### ISSUE TITLE
Команды и горячие клавиши для комментирования и выделения как кода 1C выделенных строк сценария

### ISSUE THREAD

**Issue by VladimirLitvinenko84** [Pr-Mex/vanessa-automation#474]
Цель данного запроса - упрощение отладки сценариев с использованием штатных средств Vanessa-Automation.

Вкладка "**Работа с UI** → **Сценарий поведения**" часто используется не только для получения результата записи действий пользователя, но и для отладки записанных шагов. 

В процессе отладки часто проверяется, как поведет себя сценарий, если будет временно отключена часть шагов. Для этого применяется комментирование строк, но сейчас каждую строку на вкладке с "Сценарий поведения" приходится комментировать отдельно, либо использовать для этого внешний редактор. Было бы удобно иметь возможность закомментировать/раскомментировать выделенную часть строк одной командой и горячей клавишей непосредственно в поле сценария.

Также есть шаги, которые позволяют исполнять код на встроенном языке платформы 1С: "**И я выполняю код встроенного языка**" , " **И я выполняю код встроенного языка на сервере**". Эти шаги принимают код как параметр-таблицу и поэтому каждая строка кода должна быть обрамлена в символы: **|' код '|**. 

При отладке сценария такой код часто переносится из конфигуратора или EDT в текст на вкладке "Сценарий поведения". При ручном наборе он часто также набирается сначала без обрамления символами |' и '|. Было бы удобно иметь команду и горячую клавишу для преобразования строк кода на языке платформы в вид, приемлемый для этих шагов.

Предлагаемые горячие клавиши:
  - Для комментирования строк можно применять горячую клавишу Ctrl + Num / , как это принято в конфигураторе.
  - Для выделения строк как кода встроенного языка (как параметра шагов выполнения кода) применять горячую клавишу Ctrl + Shift + C.
  - Оба этих сочетания в данный момент не используются в Vanessa Automation.
 
Желаемое поведение при комментировании строк продемонстрировано на следующей анимации:

![1_commenting](https://user-images.githubusercontent.com/24396934/66706137-edcb0400-ed37-11e9-85f3-a9bfc3ee349d.gif)

Желаемое поведение при выделении строк как кода 1С продемонстрировано на следующей анимации:

![2_code](https://user-images.githubusercontent.com/24396934/66706141-f3284e80-ed37-11e9-9c38-aae676fb3a6d.gif)
 
Уже после записи gif-ки внес изменения, чтобы выравнивание закрывающих символов '| при преобразовании к коду платформы выполнялось более ровно в случае, когда экранирование спецсимволов приводит к увеличению максимальной длины строки:

![image](https://user-images.githubusercontent.com/24396934/66713556-f31a6400-edb4-11e9-9e7f-6648ac057d8d.png)

**Comment by VladimirLitvinenko84** [comment]
@Pr-Mex  Если возможности заинтересуют, то готов отправить пул-реквест с этими изменениями.

Изменений в существующем коде не требуется, за исключением того, что директиву компиляции метода **ЭкранироватьСпецСимволыДляЗначенияШага** необходимо поменять с &НаКлиенте  на &НаКлиентеНаСервереБезКонтекста, что вполне согласуется назначением этой функции.

**Comment by fenixnow** [comment]
Интересная фича, интерфейсно вывев бы команды в виде кнопок на панель для привлечения внимания к ним.

**Comment by VladimirLitvinenko84** [comment]
Да, можно было бы вывести непосредственно на панель. Но тогда нужно сократить заголовки команд до чего-то вроде **#** и  **|' '|**. Сейчас показалось что целесообразнее сэкономить место на основной панели через размещение в небольшом подменю. Ведь на этой панели размещается еще одна, обычно скрытая, команда "Перевести". Это также позволяет сохранить понятные заголовки и указывать напротив них соответствующие горячие клавиши.

**Comment by nixel2007** [comment]
Может поиграться с пиктограммами?

**Comment by VladimirLitvinenko84** [comment]
@nixel2007  
Если @Pr-Mex  подтвердит востребованность этих команд, то изменения в интерфейсе можно сделать любые )) Пиктограммы качественные боюсь сам нарисовать не смогу. Возможно имеет смысл поработать над пиктограммами при увеличении количества команд в подменю работы с кодом. 

Например сейчас чувствуется нехватка команд для работы с таблицами в целом (параметрами шагов-таблицами). Хотелось бы например задать их в произвольном виде, соблюдая только правила синтаксиса, а затем одной командой выровнять, чтобы ширина каждой колонки была одинаковой. Или вставить содержимое CSV и вызвать команду преобразования к параметру-таблице. Можно было бы потом такие штуки в эту группу команд добавить.

**Comment by Pr-Mex** [comment]
@VladimirLitvinenko84 
Да. Это полезные фичи. 
Ждём Вашего реквеста!

**Comment by VladimirLitvinenko84** [comment]
@Pr-Mex 
Отправил: https://github.com/Pr-Mex/vanessa-automation/pull/479
Дифф смотреть неудобно так как длины некоторых строк превышают 120 символов. Если не критично, оставлю так, если нужно - переделаю.
