### ISSUE TITLE
Не работает Запись видео если путь к каталогу temp пользователя содержит пробел

### ISSUE THREAD

**Issue by asosnoviy** [Pr-Mex/vanessa-automation#481]
При нажатии на кнопку проверить, что запись видео будет доступна, не найден ffmpeg или convert. т.к. происходит  `-version > папка темп` 
 И "папка темп" требует оборачивания в ""

Аналогичная история в командах записи.

**Comment by Pr-Mex** [comment]
Решено.

**Comment by Pr-Mex** [comment]
> Аналогичная ошибка присутствует в команде "Показать отчет Allure". Если в пути к папке Temp присутствуют пробелы.

Можно скрин кода, который имеется ввиду?

**Comment by fdimok** [comment]
![image](https://github.com/user-attachments/assets/988d69a6-f0b1-4aa2-bcce-46f411e45afa)
Выделены желтым. Если в переменной ИмяВременногоФайла указан путь с пробелами (например имя пользователя ОС состоит из двух слов разделенных пробелом формата "C:\Users\Name Family\AppData\Local\Temp"), то обе команды не выполняются
