### ISSUE TITLE
Представление команд работы с текстом фичи в виде картинок

### ISSUE THREAD

**Issue by fenixnow** [Pr-Mex/vanessa-automation#498]
Хочу, чтобы кнопки отображались в виде картинок.

![image](https://user-images.githubusercontent.com/13418562/67039301-b4c0d400-f129-11e9-96ac-483129cfed59.png)

**Comment by Pr-Mex** [comment]
@fenixnow 
Да, отличная тема!

**Comment by Pr-Mex** [comment]
Решено.
