### ISSUE TITLE
Отладка внешних обработок в УФ

### ISSUE THREAD

**Issue by kuzyara** [Pr-Mex/vanessa-automation#5]
Почему в ОФ отладка теста работает, а в УФ - нет?
![2018-06-28_16-00-09](https://user-images.githubusercontent.com/2604430/42024885-6ba1816a-7aed-11e8-84cc-513b7454a5ea.png)

**Comment by nixel2007** [comment]
https://github.com/Pr-Mex/vanessa-automation/blob/develop/F.A.Q.MD
пункт 10

**Comment by kuzyara** [comment]
Да уж... 0_о
