### ISSUE TITLE
Ошибка доступа к файлам сценариев когда клиент и сервер 1С работают на одной машине и пользователь сервера 1С ограничен в правах на доступ к файлам других пользователей

### ISSUE THREAD

**Issue by VladimirLitvinenko84** [Pr-Mex/vanessa-automation#525]
Если клиент и сервер (служба) 1С расположены на одной машине и при этом пользователь сервера 1С ограничен в правах на чтение "чужих" фалов, в том числе созданных пользователем от имени которого работает клиент, то возникает ошибка доступа к файлам фич. Как ко временным файлам фич, так и загружаемых из каталога пользователя, от имени которого работает клиент 1С.

Это критично для Linux систем, в которых такое разграничение прав подразумевается изначально и ошибка возникает "из коробки". В этом случае права на чтение каталогов и права на чтение и модификацию файлов в этом каталоге часто отличаются. Также можно воспроизвести на Windows, если запускать сервер 1С не от имени системной учетной записи или из под неограниченного в правах администратора. Но в Windows это будет скорее нехарактерное разделение прав, так как права на каталог обычно совпадают с правами на хранящиеся в нем файлы.

Демонстрация поведения:
![va_access_error](https://user-images.githubusercontent.com/24396934/67516969-3f657e00-f6aa-11e9-9e04-a80013660bc1.gif)

Аналогичное поведение наблюдается и с произвольными каталогами фич:

![image](https://user-images.githubusercontent.com/24396934/67517017-5b691f80-f6aa-11e9-8504-fc5442d0134f.png)

Точка возникновения ошибки - модуль обработки vbFeatureReader.epf - момент чтения на стороне сервера файла, который был ранее создан на стороне клиента:
![image](https://user-images.githubusercontent.com/24396934/67517122-8bb0be00-f6aa-11e9-813d-462e600bfa63.png)

Как загружаемые из каталогов фичи, так и файл временной фичи после записи действий пользователя при этом создается с клиента:
![image](https://user-images.githubusercontent.com/24396934/67517189-b3a02180-f6aa-11e9-902a-4be691e933d0.png)

Создаваемый с клиента файл и каталог при этом имеют владельцем пользователя, от имени которого запущен клиент 1С:
![image](https://user-images.githubusercontent.com/24396934/67517292-f82bbd00-f6aa-11e9-9570-bf2a18bb7cb6.png)

Обходным, но неверным путем решения, является включение пользователя, от которого запущен сервер 1С, в группу, к которой относится пользователь, от имени которого запускается менеджер тестирования. Данный обходной путь требует перезапуска сервера 1С или перезагрузки сервера, если просто перезапуска оказалось недостаточно и где-то в памяти висят серверные процессы 1С. 

![image](https://user-images.githubusercontent.com/24396934/67517361-1abdd600-f6ab-11e9-8699-2a2e563ed90a.png)

После этого фича загружается: 

![image](https://user-images.githubusercontent.com/24396934/67517385-2ad5b580-f6ab-11e9-8252-302ac9c251ce.png)

Этот способ кажется некорректным не только потому, что требует неочевидного вмешательства администратора системы и расследования этой проблемы пользователем VA, но и потому, что может помешать тестированию с помощью Vanessa Automation сценариев, предполагающих проверку прав доступа и возможности чтения файлов. Выдача серверу 1С лишних прав может исказить результаты тестов.

Причина ошибки в том, что Vanessa-Automation принимает решение о возможности оптимизированного доступа к файлу (без создания на стороне сервера временных файлов) на основе только существования файла , а не возможности прочитать или записать его на стороне сервера. Это решение сохраняется в реквизите "**ВозможнаОптимизацияРаботыСФайлами**". Если реквизит принимает значение Ложь (например при расположении клиента и сервера на разных машинах) , то перед загрузкой фич на стороне сервера в методе **ПроверитьФичуНаКорректностьСинтаксисаИЗагрузитьСценарии** создаются новые файлы и в них помещаются двоичные данные фич, переданные с клиента:
![image](https://user-images.githubusercontent.com/24396934/67517718-ded74080-f6ab-11e9-9f56-ef3defb282e1.png)

Если же эта переменная равна Истина, то вместо создания новых файлов читаются существующие, к которым у службы 1С может не быть доступа. 

Для устранения ошибки достаточно проверять доступность файлов со стороны сервера не только на проверку существования, но и на чтение/запись. На скриншоте выделен исправляющий код, после внесения которого доступность файла начинает определяться корректно:

![image](https://user-images.githubusercontent.com/24396934/67518018-86ed0980-f6ac-11e9-81ca-3817f000fa1d.png)
и фичи загружаются:

![image](https://user-images.githubusercontent.com/24396934/67518083-af750380-f6ac-11e9-838e-6e95b37f7941.png)

Если же дать полные права пользователю, от имени которого работает сервер 1С, или включить его в группу пользователя, от имени которого работает тест-менеджер 1С и перезагрузить сервер/перезапустить службу 1С, то возможность применения оптимизации при работы с файлами восстанавливается, и фичи загружаются без создания дополнительных временных файлов на сервере:

![image](https://user-images.githubusercontent.com/24396934/67518219-fbc04380-f6ac-11e9-97a4-6e9e9c26b020.png)

**Comment by VladimirLitvinenko84** [comment]
Отправил пул-реквест.

Проверка доступа не только на чтение, но и на на запись выполняется поскольку это соответствует смыслу устанавливаемой переменной **ВозможнаОптимизацияРаботыСФайлами** проверка значения которой может применяться не только для приятия решения о возможности чтения файла, но и о возможности его модификации. В этом случае в будущем придется вносить меньше изменений в код и сталкиваться с неожиданными ошибками доступа.

Также введена переменная для упрощения отладки "ОписаниеОшибкиДляОтладки", которая в коде не используется, но позволит диагностировать ошибки в будущем, в случае их возникновения.

Если покажется излишним то можно удалить строки.

**Comment by Pr-Mex** [comment]
@VladimirLitvinenko84 
Спасибо за детальное описание проблемы!

**Comment by Pr-Mex** [comment]
Решено.

**Comment by asosnoviy** [comment]
Это же целая статья )))
