### ISSUE TITLE
Возможность выводить лог выполнения сценариев в /dev/stdout (Linux)

### ISSUE THREAD

**Issue by VladimirLitvinenko84** [Pr-Mex/vanessa-automation#536]
При выполнении длительных сценариев в Vanessa-Automation необходимо оперативно получать информацию о ходе выполнения сценариев. В настоящий момент получение промежуточной информации о выполнении сценариев в Vanessa-Automation возможно через чтение файла лога выполнения сценариев. При этом **необходимо запускать параллельно работающий процесс**, который читает файл одновременно с работой тест-менеджера. 

Одним из таких инструментов является Vanessa-Runner , но при его использовании с Vanessa-Automation возникают сложности с передачей дополнительных параметров командной строки. На Linux возникают и другие сложности этой связки. Другим вариантом решения является запуск параллельного процесса читающего файл, вроде **tail** и его принудительное завершение после окончания работы Vanessa-Automation. Принудительное завершение может оказаться сложной задачей и вносит дополнительный риск получить ошибки на CI-сервере. В любом случае это всё осложняет настройку CI. 

В то же время CI-сервера (например Jenkins) самостоятельно выводят в логи информацию из стандартного потока вывода stdout и необходимости в отдельном файле в этом случае просто нет. Файл в ряде вариантов использования оказывается ненужным посредником и служит только для того, чтобы прочитать его и вывести в stdout, отобразив тем самым в логах CI-сервера. Возможность выводить напрямую в stdout в этом случае позволяет значительно облегчить вывод логов Vanessa-Automation в логи CI-сервера и получать их уже в ходе выполнения сценариев.

В данный момент при попытке указания stdout в качестве файла вывода возникает ошибка:
![image](https://user-images.githubusercontent.com/24396934/67886091-e4c09c00-fb59-11e9-92f3-83290e24fd65.png)

Она возникает из-за попытки удаления этого файла перед началом исполнения сценариев:
![image](https://user-images.githubusercontent.com/24396934/67886158-0cafff80-fb5a-11e9-9a31-d90243a06ab4.png)

Если не удалять файл, если в качестве него задан /dev/stdout , то  при следующей настройке:
![image](https://user-images.githubusercontent.com/24396934/67886198-24878380-fb5a-11e9-974b-c0231771a7c4.png)

сценарий выполняется и успешно завершается, при этом логи без дополнительных сложностей и привлечения сторонних программ оказываются доступны уже в процессе  выполнения сценариев:

![va-stdout](https://user-images.githubusercontent.com/24396934/67886426-7a5c2b80-fb5a-11e9-8e8e-5e30286977c2.gif)

Вариантов решения видится два. Первый - это решение в одну-две строки кода. Просто проверка типа ОС и имени файла перед его удалением:
![image](https://user-images.githubusercontent.com/24396934/67887201-e7bc8c00-fb5b-11e9-8803-1f7cdcac549f.png)

Второй вариант - это создание новой настройки, например 
   **НеУдалятьФайлЛогаВыполненияСценариевПриНачалеЛогирования**
![image](https://user-images.githubusercontent.com/24396934/67887710-d9bb3b00-fb5c-11e9-8ffd-5fac0fc6d3c2.png)

Вариант с настройкой потребует вмешательства в большее число участков кода, предварительно в четыре участка в одном модуле. Но при этом он более универсален.

**Comment by VladimirLitvinenko84** [comment]
@Pr-Mex  
Будет ли принято это изменение, и если да, то каким образом лучше его реализовать? Через небольшое изменение с проверкой имени файла, или через добавление новой настройки?

Очень хотелось бы упростить текущую настройку запуска на Linux, так как сейчас например приходится использовать параллельные шаги в Jenkins с запуском **tail -f**  и командой **kill** для этого процесса в параллельной ветке, где запускается Vanessa-Automation. Выглядит громоздко и кроме того может привести к ошибкам, если одновременно в системе запускается несколько процессов tail.

Подозреваю, что есть и обходные пути, но возможность использовать stdout кажется самым простым и логичным решением.

**Comment by nixel2007** [comment]
vanessa-runner уже умеет выводить онлайн лог. Действительно ли необходимо переносить это в ядро?

**Comment by asosnoviy** [comment]
> vanessa-runner уже умеет выводить онлайн лог. Действительно ли необходимо переносить это в ядро?

Имхо если можно без прослойки, лучше без прослойки.

>  Первый - это решение в одну-две строки кода. Просто проверка типа ОС и имени файла перед его удалением:

+1

**Comment by Pr-Mex** [comment]
@VladimirLitvinenko84 

Я за похожий вариант
![image](https://user-images.githubusercontent.com/8627416/67927223-1c1a6180-fbc9-11e9-8784-8c9aa236adda.png)

но только с проверкой только имени файла. Без проверки ОС. Под маком такое тоже будет работать?
Т.е. я за вариант проверки только имени файла. Если это файл "/dev/stdout", то его не удаляем.

Собственно я и не знал что под Linux так можно выводить данные в консоль вывода. Спасибо!

**Comment by VladimirLitvinenko84** [comment]
@nixel2007  Vanessa-Runner при установки из репозиториев One Script  (через opm) и через релизы со страницы релизов в репозитории на Github с мая выдает вот эту ошибку: https://github.com/silverbulleters/vanessa-runner/pull/301
![image](https://user-images.githubusercontent.com/24396934/67928352-dca14480-fbcb-11e9-9f8c-a9662437543b.png)
Собирать прямо на CI из ветки develop репозитория Раннера кажется решением, которое может привести к нестабильности всей системы. На Windows не встречался с нестабильным поведением, но на Linux риск встретиться с ним гораздо выше. Эта та причина, по которой сейчас задействовал parallel-шаги в Jenkins совместно с tail. 


@Pr-Mex    
>>  Без проверки ОС. Под маком такое тоже будет работать?

Переменная **ЭтоLinux** в модуле основной управляемой формы Vanessa-Automation сейчас устанавливается в **Истина** в том случае если операционная система либо Linux либо MacOS. Поэтому проверка на операционную систему в приведенной строке - это только гарантия, что при задании этого файла на Windows будет стандартная попытка удалить файл и соответствующее сообщение пользователю.

Под MacOS /dev/stdout тоже доступен для обращения к нему, но как будет в этом случае работать Vanessa-Automation не проверял. Думаю что поведение будет таким же как на Linux. Раньше выходных не буду иметь возможности настроить стенд для проверки, но думаю это не является ограничением для внесения изменений. В конце концов если для MacOS это не будет работать, то достаточно просто не указывать на нем такой файл для лога ))

С учетом этого, можно ли оставить проверку на ОС в приведенной строке кода? Хотел сегодня пул-реквест отправить.

**Comment by nixel2007** [comment]
@VladimirLitvinenko84 спасибо, про падение VR я как-то пропустил.

**Comment by Pr-Mex** [comment]
@VladimirLitvinenko84 
Согласен. Давайте сделаем как вы предложили.

**Comment by VladimirLitvinenko84** [comment]
@Pr-Mex  
Отправил пул-реквест.
