### ISSUE TITLE
Ошибка: Команда ОстановитьЗаписьВидео вернула код возврата = 1

### ISSUE THREAD

**Issue by Svinaug** [Pr-Mex/vanessa-automation#544]
```Gherkin
Функционал:  Я хочу делать автовидеоинструкции, но выходит ошибка  "ОстановитьЗаписьВидео вернула код возврата = 1"

Контекст:
  Дано ver 1.2.028
  И Платформа 1С 8.3.12.1685
  И Конфигурация БИТ.ФИНАНС 3.2

Сценарий: Я запускаю сценарий с включенной настройкой "Создавать видеоинструкцию"
  Когда Я сделал все настройки для записи видео без звука
  И нажал на кнопку "Проверить что запись видео будет работать"
  Тогда появились сообщения об успешной проверке Screenshot_1.png
```
![Screenshot_1](https://user-images.githubusercontent.com/57498465/68412494-625d5b00-019d-11ea-8701-6b3267e9ff25.png)
```Gherkin
  Тогда я запускаю сценарий на выполнение
  И появилось сообщение об ошибке Screenshot_2.png
``` 
![Screenshot_2](https://user-images.githubusercontent.com/57498465/68412951-46a68480-019e-11ea-8d1d-22dafafa4bef.png)

```Gherkin
 И я сохранаю полный текст с ошибкой:
``` 
07.11.2019 20:17:54 КомандаОстановитьЗапись=oscript "C:\Users\u1006\Downloads\vanessa-automation\tools\onescript\StopVideoRec.os" "127.0.0.1:8082"
07.11.2019 20:17:30 Ищу снипеты в каталоге \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\2. Документы\8. Заказ покупателя\
07.11.2019 20:17:30 Ищу снипеты в каталоге C:\Users\u1006\Downloads\vanessa-automation\features\Libraries
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\SikuliX\SikuliXServer.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\Smoke\Smoke_InputBasedOn.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\TestClients\step_definitions\НесколькихКлиентовТестирования.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\TestClients\step_definitions\РаботаСTestClient.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\UITestRunner\step_definitions\ОткрытьTestClient.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\UITestRunner\step_definitions\ПодключениеНесколькихКлиентовТестированияБиблиотека.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\UITestRunner\step_definitions\ПроверкаЗначенияМакета.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\UITestRunner\step_definitions\ПроверкаИсключенияШага.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсомДополнительный.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСОкномСообщений.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\UITestRunner\step_definitions\РаботаСТаблицами.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\UITestRunner\step_definitions\СохранитьМакетИзОбработкиВФайл.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\UITestRunner\step_definitions\ФильтрФормыСписка.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\UITestRunner\step_definitions\ФильтрФормыСпискаЭкспорт.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\Load1000ItemsfromMxl.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\VBForm.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\VBManager.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\ВыводТекста.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\Док-ГененерацияEPF.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\Док-ЗагрузкаФич.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\Док-ОткрытиеФормы.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\Док-ПередачаПараметровВСценарий.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\Док-ПримерНаписанияФичи.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\Док-ПроверитьЕстьЛиОкноСОшибкой.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\Док-РаботаСПеременнымиКонтекстИКонтекстСохраняемый.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\ЗагрузкаФичи.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\ЗаполнитьНастройкиЗаписиВидео.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\ЗапускПростогоСценарияTestClient.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\ИнтервалВыполненияШага.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\Константы.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\ОстановитьВыполнениеШагов.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\ОткрытьФормуЧерезКоманду.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\Плагины.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\РазвернутьВеткиДереваVB.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\СозданиеFixtures.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\СозданиеFixturesПоМакетуОбработкиФичи.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\СозданиеЗаписейРС.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\СуществованиеЭлементов.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\ТестированиеVA.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\VB\step_definitions\УстановкаСистемныхПараметров.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\ВстроенныйЯзык\ВстроенныйЯзык.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\ЗамерПроизводительности\ШагиПолученияЗамеров.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\ЗапускПриложений\ЗапускПриложений.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\Лог\Логирование.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\Нумерация\step_definitions\Обновление нумерации объектов.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\ОбычныеФормы\step_definitions\КнопкаНажималкаОбычныйИнтерфейс.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\ПакетныйРежим\ПакетныйРежим.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\Пауза\step_definitions\СделатьПаузу.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\Пауза\step_definitions\СделатьПаузуОФ.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\ПеременныеОкружения\ПеременныеОкружения.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\РаботаСФайлами\ДобавлениеФайлаКШагу.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\РаботаСФайлами\РаботаСФайлами.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\Роли\step_definitions\ДоступнстьРоли.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\Условие\step_definitions\Условие.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\Цикл\step_definitions\ПереборМассива.epf
07.11.2019 20:17:30 Загрузил снипеты из кеш: C:\Users\u1006\Downloads\vanessa-automation\features\Libraries\Цикл\step_definitions\Цикл.epf
07.11.2019 20:17:30 Ищу снипеты в каталоге \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии
07.11.2019 20:17:33 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ВызыватьИсключение.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ЕслиВПримереИстина.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ЕслиВПримереЛожь.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ЕслиВсплывающееОкноПоявилосьТогда.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ЕслиВшагеОшибка.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ЕслиВыражениеИзПримера.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ЕслиОткрыласьФорма.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ЕслиПоле.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\НастройкаСпискаСпривязкойПроверкиОкна.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ПО - 1. Шапка.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ЭлементЕстьввыпадающемспискеТогда.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ЭтоПолеЗаполнено.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ЭтоПолеНеЗаполнено.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ЯВывожуСообщенияПользователю.epf
07.11.2019 20:17:34 Загрузил снипеты из кеш: \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\0. Библиотека\Для работы\EPF (дополнительные шаги)\ЯЗапоминаюЗначениеТаблицыПоляБезПробеловКак.epf
07.11.2019 20:17:34 Ищу сценарии в каталоге \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\2. Документы\8. Заказ покупателя\
07.11.2019 20:17:34 Ищу сценарии в каталоге C:\Users\u1006\Downloads\vanessa-automation\features\Libraries
07.11.2019 20:17:34 Ищу сценарии в каталоге \\192.168.2.16\1c-site-exch$\Толокнов\Сценарии
07.11.2019 20:17:48 "D:\ImageMagick-7.0.9-Q16\ImageMagick-7.0.9-Q16\convert.exe" -version > "C:\Users\u1006\AppData\Local\Temp\v8_674A_50.txt" 2>&1
07.11.2019 20:17:51 Инициализация записи видео...
07.11.2019 20:17:51 "D:\VLC_2.1.5\VLC\vlc.exe" screen://  -I rc --rc-quiet --rc-host=127.0.0.1:8082 --nommx :screen-mouse-image="C:\Users\u1006\Downloads\vanessa-automation\tools\VideoTools\mouse.png" :screen-fps=20 :screen-width=1680 :screen-height=1050 :screen-top=0 :screen-left=0 :screen-caching=100 :sout=#transcode{vcodec=mp4v,vb=400,fps=20,scale=1,width=1680,height=1050,acodec=none}:duplicate{dst=std{access=file,mux=mp4,dst=D:\\init.mp4}}
07.11.2019 20:18:02 Команда ОстановитьЗаписьВидео вернула код возврата = 1
07.11.2019 20:18:02 Ошибка при построении дерева из файла <\\192.168.2.16\1c-site-exch$\Толокнов\Сценарии\2. Документы\8. Заказ покупателя\ЗК 3  Проведение - (цикл).feature>
{ВнешняяОбработка.РаботаСВидео.Форма.Форма.Форма(3594)}: Команда ОстановитьЗаписьВидео вернула код возврата = 1

**Comment by Pr-Mex** [comment]
Добавлен вывод лога выполнения команды.
