### ISSUE TITLE
Выделение исключений, являющиеся ассертами.

### ISSUE THREAD

**Issue by zeegin** [Pr-Mex/vanessa-automation#550]
Если при вызове исключения текст исключения начинается с тега `[AssertError]` тогда этот текст исключения воспринимается как ассерт, прочие исключения определяются как неопределенные исключения.

Если текст исключения начинается с тега `[AssertError]` то в нем могут содержаться тексты ожидаемого и актуального проверяемых значений. Например:

или
```
[AssertError]
[Expected]
1
[Actual]
2
[Message]
Что-то тут не так
```
или
```
[AssertError]
[Expected]
Timeout exceeded
[Actual]
Internet error
Timeout exceeded
```
или
```
[AssertError]
Какой-то
непонятный текст
исключения
```

- Если одновременно удалось найти блоки `[Expected]` и `[Actual]` то они извлекаются в специальную ассертную структуру.
- Если одного из блоков нет, то весь текст исключения кроме заголовка `[AssertError]` попадает в текст ассерта.
- Если есть блоки  `[Expected]` и `[Actual]` и дополнительно есть блок `[Message]` то первые извлекаются отдельно, дополнительный текст отдельно.

**Comment by Pr-Mex** [comment]
@zeegin Да, давай. Полезная штука.
