### ISSUE TITLE
Результаты в JUnit и Allure форматах, отделение ассертов от исключений

### ISSUE THREAD

**Issue by zeegin** [Pr-Mex/vanessa-automation#551]
Состояния в отчетах по ошибкам и ассертам:

| JUnit   | Allure  | Когда вызывается                                                                                                                                                                                      |
| ------- | ------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| error   | broken  | Произошло исключение в программе при выполнении теста. Это или ошибка при запуске теста или ошибка при вызове метода программы, это не ошбка ассерта, это при попытке выполнить тест упала программа. |
| failure | failure | Программа отработала без исключений, но при проверке ассертом результата оказалось, что результат не верный.                                                                                          |

**Comment by Pr-Mex** [comment]
@zeegin 
Не совсем понял. Это нужно доработать?

**Comment by zeegin** [comment]
Записал, чтобы не забыть, надо убедиться, что это работает так.

**Comment by zeegin** [comment]
Исправил JUnit
Allure не проверял
