### ISSUE TITLE
Вопрос. Как правильно организовать последовательность тестов

### ISSUE THREAD

**Issue by Lopner** [Pr-Mex/vanessa-automation#557]
Есть тест, который открывает например 5 форм по очереди. (В рамках одной проверяемой задачи)

Как это выглядит:
1. Подключение к базе
2. Открытие форму 1
....
6. Открывает форму 5

Получается что если если "Форма 1" не откроется, то тест остановится.

Я понимаю что есть вариант написать 5 отдельных тестов на открытие каждой формы,
но вдруг есть какая то опция, которая позволяет продолжить выполнение теста при ожидаемом некорректном поведении предыдущего независимого шага.

**Comment by fenixnow** [comment]
Воспользуйтесь формой генератора дымовых тестов, она решит вашу проблему. Механизм не доработан, но даст представление, как должны сформироваться тесты

**Comment by Pr-Mex** [comment]
Вы также можете оформить работу с каждой формой отдельным сценарием. Тогда каждый из них точно выполнится.
