### ISSUE TITLE
Настройка для отображения/скрытия сообщений об изменившемся порте тестклиента

### ISSUE THREAD

**Issue by chEEzys** [Pr-Mex/vanessa-automation#558]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Галочка отображения скрытия сообщений о портах тестклиента
   Как автоматизатор тестирования который использует в одном сценарии множество запусков разных тестклиентов
   Я хочу Иметь возможность скрытия сообщений об изменившемся порту тестклиента, т.к. они не несут для меня смысловой нагрузки

Контекст:
  Дано: 1.2.028 single
  И 8.3.10.2309
  и не типовая 1С предприятие

Сценарий: ставим галку и сообщения о смене порта не появляются
  Допустим: Имеем сценарий со множеством вызовов клиентов тестивраония под разными пользвоателями
  Когда: я ставлю галку в настройках вида "Отключить сообщения о портах тестклиента"
  И запускаю сценарий на выполнение
  Тогда: В логе сообщений находятся только полезные сообщения, отсутствуют сообщения вида "%ДатаВремя% Порт 48000 занят или находится вне указанного диапазона, порт подключения изменен на 48 ххх"

**Comment by Pr-Mex** [comment]
Решено.

**Comment by chEEzys** [comment]
@Pr-Mex где искать настройку? в Сингл версии ничего похожего на подобную галочку не увидел на вкладке Сервисы.

**Comment by asosnoviy** [comment]
https://github.com/Pr-Mex/vanessa-automation/commit/989cc8d725e5bd14c8c8b7c576d647149a2552f2

**Comment by Pr-Mex** [comment]
@chEEzys 
@asosnoviy правильно указал

**Comment by asosnoviy** [comment]
![image](https://user-images.githubusercontent.com/15638529/72346017-1cb19700-36e6-11ea-9853-7033b9e40554.png)

**Comment by chEEzys** [comment]
Спасибо за развернутый ответ, проблема в том что у меня лыжи не едут на 1.2.029 single.
Сообщения вида:
14.01.2020 15:57:54 TestClient подключен на 48 001 порту.
14.01.2020 15:58:22 TestClient подключен на 48 002 порту.
Продолжают генерироваться при снятой галочке.
![image](https://user-images.githubusercontent.com/52081206/72346525-399a9a00-36e7-11ea-8a90-5cc30d4e194e.png)

**Comment by Pr-Mex** [comment]
@chEEzys 
Может какое-то ещё сообщение не обернуто в отладку.
Можешь посмотреть какая строка кода выдаёт это сообщение?

**Comment by asosnoviy** [comment]
@chEEzys соль в том, что в исходном ихузе говорилось про 
%ДатаВремя% Порт 48000 занят или находится вне указанного диапазона, порт подключения изменен на 48 ххх =)))

Согласен, что  TestClient подключен на 48 002 порту. тоже надо в отладочные убрать

**Comment by chEEzys** [comment]
Точно.
Эх.
Сделать еще один ишью? )

**Comment by asosnoviy** [comment]
> Точно.
> Эх.
> Сделать еще один ишью? )

Может сразу ПР? =)

**Comment by chEEzys** [comment]
хоть и подозреваю что там все несложно, я не умею кодить и не умею работать с гитхабом :( к ванессе я из ручного тестирования пришел...

**Comment by Pr-Mex** [comment]
Ок. Сделаю.

**Comment by asosnoviy** [comment]
@Pr-Mex ПР уже прилетел =)

**Comment by asosnoviy** [comment]
> хоть и подозреваю что там все несложно, я не умею кодить и не умею работать с гитхабом :( к ванессе я из ручного тестирования пришел...

Тогда огромное спасибо за ишузы!!!
