### ISSUE TITLE
Не все настройки ВА обрабатывают параметр workspaceRoot, переданный через runner run

### ISSUE THREAD

**Issue by MironovDmitry** [Pr-Mex/vanessa-automation#559]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: При запуске тестов через runner run
   Как фичапис
   Я хочу передать параметр wokrspaceRoot, относительно которого должны строиться все относительные пути в настройках ВА

Контекст:
  Дано: команда запуска тестов runner run --v8version 8.3.12 --execute "./vanessa-automation/vanessa-automation.epf" --command "StartFeaturePlayer;workspaceRoot=D:\projectRootFolder;VBParams=D:\projectRootFolder\tools\JSON\VBParams.json"
 и пустая конфигурация запускаемая в режиме тестменеджера

Сценарий: Все настройки ВА, в параметрах которых в файле VBParams.json указаны пути пипа "$workspaceRoot/folder" корректно обработаны ВА
  Допустим: В фале VBParams.json параметр указан как "КаталогВыгрузкиAllure": "$workspaceRoot/build/out/allure"
  Когда: запускаю команду runner run ....
  Тогда: В настройках ВА параметр КаталогВыгрузкиAllure равен "D:\projectRootFolder\build\out\allure"

также не работает для параметров:
"КаталогВыгрузкиJUnit"
"КаталогВыгрузкиCucumberJson"
"КаталогВыгрузкиСкриншотов"
"КаталогПроекта": "$workspaceRoot"

```

> Прикладывайте файлы скриншотов
![image](https://user-images.githubusercontent.com/7125926/68742570-8c7da580-0601-11ea-82cf-81666b2e4f3e.png)
![image](https://user-images.githubusercontent.com/7125926/68742598-9e5f4880-0601-11ea-9585-72df55b0be63.png)

**Comment by fenixnow** [comment]
Вместо $workspaceRoot нужно использовать ./ 
поведение изменилось в 29 версии.
@Pr-Mex

**Comment by Pr-Mex** [comment]
@fenixnow 
Нужно вернуть совместимость со старым поведением.

**Comment by VladimirLitvinenko84** [comment]
@fenixnow   @Pr-Mex  
Коллеги, хотелось бы обратить внимание, что сейчас в разных методах модуля управляемой формы VA точка в начали путей и шаблон $workspaceRoot  интерпретируется по разному. 

Это приводит не только к несовместимости со старым поведением (до релиза 1.0.28 включительно), но и к тому, что нельзя задавать пути в файле настроек единообразно. 

В методе "ЗагрузитьНастройкиНаСервере" вызывается не общий метод "ПреобразоватьПутьСТочкамиКНомальномуПути" , а происходит обработка точки в начале пути по собственному алгоритму:
![image](https://user-images.githubusercontent.com/24396934/74145814-c6664400-4c10-11ea-9e6a-2081664dcfc5.png)

В итоге при обработке каталогов библиотек в версии 1.0.29 точка преобразуется к каталогу проекта (в версии 1.028 преобразовывалась к каталогу VA - каталогу инструментов).

В то же время в методе "ПреобразоватьПутьСТочкамиКНомальномуПути" указано, что ради сохранения совместимости точка по прежнему воспринимается как каталог инструментов (каталог, в которой находится обработка  VA):

![image](https://user-images.githubusercontent.com/24396934/74146123-78057500-4c11-11ea-8b98-d0133084f3dd.png)


Также при указании путей к библиотекам корректно воспринимается как шаблон **$workspaceRoot**  так и шаблон $instrumentsRoot.  А при указании пути к каталогу фич **$workspaceRoot** более не работает.

Поэтому сейчас приходится использовать такую настройку:

![image](https://user-images.githubusercontent.com/24396934/74146305-e21e1a00-4c11-11ea-8fed-45efecde7dbc.png)

Имеет смысл не только вернуть совместимость со старым поведением, когда параметр $workspaceRoot можно было указывать в путях к фичам, но и унифицировать поведение методов  "ЗагрузитьНастройкиНаСервере" и "ПреобразоватьПутьСТочкамиКНомальномуПути" , в идеале оставив один метод, отвечающий за обработку путей.

Замена точки в начале пути на путь к каталогу проекта - это удобно. Но тогда нужно это и в методе "ПреобразоватьПутьСТочкамиКНомальномуПути" сделать.

**Comment by Pr-Mex** [comment]
@VladimirLitvinenko84 
Можете проверить на версии из develop?
Я вернул обработку $workspaceRoot. И добавил на это тест.

**Comment by VladimirLitvinenko84** [comment]
Да, в ветке **develop** работает как с точкой, так и с $workspaceRoot. 
Точка действительно намного удобнее для указания пути к каталогу проекта, чем к каталогу инструментов.  $instrumentsRoot по практике обычно указывается в файле настроек запуска только один раз - для загрузки стандартной библиотеки шагов.

**Comment by Pr-Mex** [comment]
Решено.
