### ISSUE TITLE
Неверно парсит фичу

### ISSUE THREAD

**Issue by pumbaEO** [Pr-Mex/vanessa-automation#56]
Согласно документации https://docs.cucumber.io/gherkin/reference/#keywords 
точнее в поле 
```
Descriptions

Free-form descriptions (as described above for Feature) can also be placed underneath Example, Background, Scenario and Scenario Outline.

You can write anything you like, as long as no line starts with a keyword.
``` 
ожидаем, что после слова Сценарий, Структура сценария все последующие строки до первого ключевого слова относятса к описанию сценария в произвольной форме.  Фактически для feautereader считается, что фича неверна, что не есть правильно. 

Например для фичи 
```
Функционал: Продажа товара

  Сценарий: Продажа товара менеджером
        * формируем остаток товара на складе
        * эмулируем создание заказа из интернет магазина
     Когда у меня существует остатоток
     Тогда менеджер продает товар
 ```
Сейчас для такой фичи выводит сообщение, не удалось прочитать feature файл.

**Comment by 1cto** [comment]
@pumbaEO давай уже свой патч. Не держи в себе ;-)
