### ISSUE TITLE
Ошибка в тесте. Не русский а English

### ISSUE THREAD

**Issue by fenixnow** [Pr-Mex/vanessa-automation#562]
https://github.com/Pr-Mex/vanessa-automation/blob/99514bcc4b12176654969410fb7afda57fc7b006/features/Core/CommandLine/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0%D0%9F%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2%D0%98%D0%B7%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D0%BE%D0%B9%D0%A1%D1%82%D1%80%D0%BE%D0%BA%D0%B8.feature#L235

и строка задвоена

**Comment by Pr-Mex** [comment]
Решено.
