### ISSUE TITLE
не оптимальный вариант

### ISSUE THREAD

**Issue by fenixnow** [Pr-Mex/vanessa-automation#563]
https://github.com/Pr-Mex/vanessa-automation/blob/99514bcc4b12176654969410fb7afda57fc7b006/features/Core/CommandLine/files/TestEN.json#L6

При такой ссылке в тесте, и флаге "загружать фичи при открытии" происходит большой "зависон", и в сценарии не отрабатывает таймаут 30 сек.
Предлагаю убрать или не грузить фичи.

**Comment by Pr-Mex** [comment]
@fenixnow 
У меня это происходит за пару секунд. Можешь сделать замер производительности, чтобы посмотреть куда уходит время?

**Comment by fenixnow** [comment]
Я могу видос записать как происходит загрузка

**Comment by fenixnow** [comment]
отправил в личку

**Comment by Pr-Mex** [comment]
Разобрались.
