### ISSUE TITLE
Вопрос. Можно ли как-то сохранять печатную форму в pdf

### ISSUE THREAD

**Issue by Lopner** [Pr-Mex/vanessa-automation#564]
Надо протестировать печатные формы. Установлен виртуальный принтер, который конвертирует в pdf то, что на печать отправляется.
Есть какое-то решение, с помощью которого можно было бы сохранять при каждом тесте печатную форму как будто я ее отправил на печать, но сохранять ее в pdf в каталоге?

(предпросмотр из 1С и скрин предпросмотра не подходит, так как он не соответствует тому что в итоге выходит на печать)

**Comment by Pr-Mex** [comment]
@Lopner 
При отправке на печать в вашем варианте - появляются какие-то дополнительные окна или диалоги? Можете записать видео как это происходит с точки зрения пользователя?

**Comment by Lopner** [comment]
@Pr-Mex  Попробую скриншотами объяснить:
1. При Нажатии на кнопку "печать" в 1С вылезает стандартное окно с выбором принтера
и я Выбираю эмулятор принтера "Pdf creator"
![image](https://user-images.githubusercontent.com/23383979/69135559-58572880-0aca-11ea-890f-1da6423f25e3.png)
2. Нажимаю кнопку печать
Вылезает окно сохранения "Pdf Creator"
![image](https://user-images.githubusercontent.com/23383979/69135783-b97efc00-0aca-11ea-85e3-2a2d13b0433f.png)
3. Сохраняю pdf в выбранный каталог


Возможно есть какие-то и другие решения.

 Конечная цель - после теста получать набор артефактов в виде pdf файлов этих печатных форм.

**Comment by Pr-Mex** [comment]
@Lopner 
Чтобы нажимать на кнопки в таких окнах сторонних приложений понадобятся дополнительные инструменты. Я обычно использую эмуляцию движения мышки с помощью SikuliX - это java приложение.
VA умеет хорошо интегрироваться с SikuliX.

**Comment by Lopner** [comment]
Спасибо, по разбираюсь с SikuliX
