### ISSUE TITLE
Изменен формат сравнения даты

### ISSUE THREAD

**Issue by hawk911** [Pr-Mex/vanessa-automation#565]
Сейчас почти все шаги используют формат времени, где явно приводится к формату с точками. У нас формат даты американский через `/` из-за этого с датами большая проблема. 
[Тут](https://github.com/Pr-Mex/vanessa-automation/pull/159) я уже начинал делать.

**Comment by Pr-Mex** [comment]
Переехало в https://github.com/Pr-Mex/vanessa-automation/issues/732
