### ISSUE TITLE
Необходимо создать парный шаг для <Затем Если появилось окно диалога я нажимаю на кнопку "Заголовок кнопки"> с поиском по имени

### ISSUE THREAD

**Issue by gatinv** [Pr-Mex/vanessa-automation#570]
```Gherkin
# language: ru
@tree

Функционал: Если на экране появилось диалоговое окно - нажимает на нужную кнопку (находит по имени).
   Как Тестировщик
   Я хочу использовать шаг "Затем Если появилось окно диалога я нажимаю на кнопку с именем "Имя кнопки""
   Чтобы уметь нажимать в ходе тестирования кнопки без Заголовка

Контекст:
  Дано: ver 1.2.028 Vanessa Automation single
  И 1С:Предприятие 8.3 (8.3.14.1694)
  и файловая база, тонкий клиент

Сценарий: Я создаю пользователя с ролью "Интерактивное открытие внешних отчетов и обработок"
	Открываем справочник пользователей
		Когда В панели разделов я выбираю 'Администрирование'
		И В панели функций я выбираю 'Настройки пользователей и прав'
		Тогда открылось окно 'Настройки пользователей и прав'
		И я нажимаю на кнопку 'Пользователи'    
		Тогда открылось окно 'Пользователи'
	Создаем пользователя
		И я нажимаю на кнопку с именем 'СоздатьПользователя'
		Тогда открылось окно 'Пользователь (создание)'
		И в поле 'Полное имя' я ввожу текст TEST_USER
		И в поле с именем 'ПользовательИБИмя1' я ввожу текст TEST_USER
	Назначаем роли
		И в таблице "Роли" я перехожу к строке:
		| 'Пометка' | 'Разрешенное действие (роль)'                        |
		| 'Нет'     | 'Интерактивное открытие внешних отчетов и обработок' |
		И в таблице "Роли" я изменяю флаг 'Пометка'
		Тогда открылась форма "Предупреждение безопасности"
		Затем Если появилось окно диалога я нажимаю на кнопку с именем 'Продолжить5'
		И в таблице "Роли" я завершаю редактирование строки
	Завершаем создание пользователя
		И я нажимаю на кнопку 'Записать и закрыть'
    		И я жду закрытия окна 'Пользователь (создание) *' в течение 20 секунд
```

Уже существующий шаг не нажимает на кнопку но при этом и не возвращает ошибки
![1](https://user-images.githubusercontent.com/58205151/69608142-d457f000-1037-11ea-8af4-c033973491fd.jpg)

**Comment by gatinv** [comment]
Судя по всему есть проблема на этапе определения окна.

	Процедура ЕслиПоявилосьОкноДиалогаЯНажимаюНаКнопку(ИмяКнопки) Экспорт
		ОкноПредупреждения  = Ванесса.НайтиОкноМодальногоДиалога();
		ТекстСообщения = Ванесса.ПолучитьТекстСообщенияПользователю("Всё дело в окне!");
		ВызватьИсключение ТекстСообщения;
		Если ОкноПредупреждения = Неопределено Тогда
			Возврат;
		КонецЕсли;	

		Кнопка = ОкноПредупреждения.НайтиОбъект(Тип("ТестируемаяКнопкаФормы"),ИмяКнопки);
		Если Кнопка = Неопределено Тогда
			ТекстСообщения = Ванесса.ПолучитьТекстСообщенияПользователю("Кнопка/команда с заголовком <%1> не найдена.");
			ТекстСообщения = СтрЗаменить(ТекстСообщения,"%1",ИмяКнопки);
			ВызватьИсключение ТекстСообщения;
		КонецЕсли;	 

		Кнопка.Нажать();
		Ванесса.ОбработатьСменуАктивногоОкна();
	КонецПроцедуры

![image](https://user-images.githubusercontent.com/58205151/69697347-3a557d80-10f3-11ea-8e29-fdf436be0fba.png)

Можно добавить заголовок "Предупреждение безопасности" в функцию НайтиОкноМодальногоДиалога?

**Comment by Pr-Mex** [comment]
@gatinv 
>Можно добавить заголовок "Предупреждение безопасности" в функцию НайтиОкноМодальногоДиалога?

Да. Надо так сделать. Сделаете реквест?

**Comment by gatinv** [comment]
@Pr-Mex 
Леонид, посмо́трите, не напортачил ли

**Comment by Pr-Mex** [comment]
@gatinv 
Да, всё ок. Запустил тесты.

**Comment by Pr-Mex** [comment]
Решено.
