### ISSUE TITLE
Программное изменение заголовка кнопки

### ISSUE THREAD

**Issue by fenixnow** [Pr-Mex/vanessa-automation#584]
Допустим, у нас на форме есть кнопка с заголовком "Заголовок 1". На кнопку повешен обработчик, если нажать на кнопку заголовок изменится:
`Элементы.ИмяКнопки.Заголовок = "Новый заголовок"`

Суть проблемы в том, что если обратиться к тестируемой формы и НайтиОбъект(), то кнопка вернется с заголовком который у нее установлен по умолчанию, а не с заголовком который был установлен программно.

Через исследователь формы заголовок кнопки возвращается верный.

**Comment by Pr-Mex** [comment]
@fenixnow 
Лучше сразу регистрировать ошибку на платформу.

**Comment by fenixnow** [comment]
Не является ошибкой, это я сам накосячил.
