### ISSUE TITLE
ВОткрытойФормеЯНажимаюНаКнопкуСЗаголовком - теряется сообщение когда кнопка не найдена

### ISSUE THREAD

**Issue by fenixnow** [Pr-Mex/vanessa-automation#585]
В методе ВОткрытойФормеЯНажимаюНаКнопкуСЗаголовком в обработке РаботаСИнтерфейсом
Теряется сообщение об ошибке если на форме не была найдена кнопка по заголовку

`ТекстОшибки = Ванесса.ПолучитьТекстСообщенияПользователю("Кнопка/команда с заголовком <%1> не найдена. ТекущееОкно=%2");`
мы получаем сам текст ошибки и заполняем его параметрами, но в клиенте он не выводится.

**Comment by Pr-Mex** [comment]
@fenixnow 
Нужен алгоритм воспроизведения проблемы.

**Comment by Pr-Mex** [comment]
@fenixnow 
Проблема актуальна?

**Comment by Pr-Mex** [comment]
Закрываю.
