### ISSUE TITLE
Настройки размера окна тест клиента для написания HTML инструкций

### ISSUE THREAD

**Issue by ViktorErmakov** [Pr-Mex/vanessa-automation#586]
Функционал: <Необходимый эффект>
   Как Аналитик
   Я хочу что бы записывались HTML инструкции с картинками активного окна нужного размера.
   Размеры должны быть типизированы по стандартам изображений. Тогда мне не придется открывать
   каждую картинку на редактирование в редакторе и инструкция станет более читаемой.

Контекст:
  Дано: 1.2.028 Vanessa Automation
  И платформа 1С:Предприятие 8.3 (8.3.13.1690)
  и Демонстрационная конфигурация "Управляемое приложение" (1.0.22.2) 

Сценарий: запустить тест клиент с запущенной обработкой изменения размера окна
  Допустим: Я запускаю конфигурацию, и открываю Vanessa Automation
  Когда: я перехожу на вкладку "клиенты тестирования"
  И рядом с кнопкой подключения я вижу кнопку "При подключении тест клиента запустить обработку размера экрана"
  И я помечаю эту кнопку
  Тогда: запустился тест клиент, а в нем запущена обработка по настройки экрана
  И там я выбираю необходимый мне размер экрана
  Тогда: экран изменил размер
```

**Comment by ViktorErmakov** [comment]
![2019-12-08_22-00-43](https://user-images.githubusercontent.com/39617680/70394436-43edb800-1a06-11ea-93ff-a41fdbe47720.png)
![2019-12-08_22-01-46](https://user-images.githubusercontent.com/39617680/70394447-5962e200-1a06-11ea-94f7-b2475d981710.png)

**Comment by Pr-Mex** [comment]
@ViktorErmakov 
У меня есть ощущение, что эти Настройки не нужно задавать для каждого клиента тестирования. А достаточно задать их один раз сразу для всех. Ты как считаешь?

**Comment by ViktorErmakov** [comment]
Леонид, как ты посмотришь на то, что бы добавить команду сюда?
![изображение](https://user-images.githubusercontent.com/39617680/70462547-2e42c600-1acc-11ea-988d-db9747fb6a2d.png)

**Comment by ViktorErmakov** [comment]
назвать ее что то типа "подобрать размер окна". И больше никуда ее не выводить, тут как Бы и шаги пишутся..

**Comment by Pr-Mex** [comment]
Я за название:
Задать размер окна клиента тестирования.
Кто как думает?

**Comment by Pr-Mex** [comment]
@ViktorErmakov 
Насчёт расположения - да, ок.

**Comment by ViktorErmakov** [comment]
Как эта задача будет принята, буду делать известные шаги, которые будут изменять размер окна.

**Comment by ViktorErmakov** [comment]
А вообще идея такая, когда пользователь подбирает размер окна, нажимает на кнопки в клиенте тестирования, то в текст фичи добавляется шаг с тем размера что он нажал последний, как то так.

**Comment by Pr-Mex** [comment]
> А вообще идея такая, когда пользователь подбирает размер окна, нажимает на кнопки в клиенте тестирования, то в текст фичи добавляется шаг с тем размера что он нажал последний, как то так.

Да, такое было бы полезно.
