### ISSUE TITLE
Отказ от русских значений в переменных. В json должна быть возможность передать цифры вместо русских значений полей.

### ISSUE THREAD

**Issue by hawk911** [Pr-Mex/vanessa-automation#615]
```Gherkin
   Функционал:  Я хочу загружать json файл и понимать параметры
   Как иностранец, который не знает русского языка
   Я хочу чтобы параметры были английскими или имели аналоги на английском языке
```
Вот от [такого ](https://github.com/Pr-Mex/vanessa-automation/blob/develop/features/Core/CommandLine/files/TestEN1.json#L9) надо уходить. 
Помимо нерусскоговорящих, на сервере не стоит русский язык и обработка json файла будет проблемой (Например, прочитать файл, поменять пути и сохранить - очень много времени потерял на кодировках). 

Для [этого](https://github.com/Pr-Mex/vanessa-automation/blob/develop/features/Core/CommandLine/files/TestEN1.json#L57-L59) я делал 

```json
     "reportlevel1": "#report.epic=;catalog1",
    "reportlevel2": "#report.feature=;catalog2",
    "reportlevel3": "#report.story=;scenarioname"
```
Основная мысль: учитывать, что в английском json файле не должно быть русских переменных и значений.

**Comment by Pr-Mex** [comment]
@hawk911 
Сколько проблемных русских слов осталось в json?

**Comment by hawk911** [comment]
> @hawk911
> Сколько проблемных русских слов осталось в json?

Одно. Я бы сказал, что оно появилось :)

**Comment by fenixnow** [comment]
Если не ошибаюсь, у нас появилась возможность сопоставлять не только значения ключей, но и их значения.

**Comment by Pr-Mex** [comment]
@fenixnow 
Ты предлагал в английском json вместо русских строк использовать цифры. Вполне это можно сделать.

**Comment by fenixnow** [comment]
Да, и это тоже, ранее мы с тобой обсуждали этот подход. Тогда не придется заботиться о переводе и сопоставлении для json. Придется где-то в доках описать за что отвечает каждая цифра.
У нас по такому признаку работает IrfanViewer

**Comment by Pr-Mex** [comment]
Решено.
