### ISSUE TITLE
Не могу найти шаг который формирует в разделе Links в Allure произвольную ссылку

### ISSUE THREAD

**Issue by Lopner** [Pr-Mex/vanessa-automation#618]
Не могу найти шаг который формирует в разделе Links в Allure произвольную ссылку

Видел вот такой вариант:
`И Я устанавливаю ссылку 'http://test/issue' с именем 'SUP-222'`
в статье https://infostart.ru/public/1010127/

Подскажите есть что то такое? 
Очень хочется ссылкой на задачу провязывать тест

**Comment by Pr-Mex** [comment]
@freddy121 
Это ваш шаг?

**Comment by freddy121** [comment]
Это @pumbaEO в адд делал,  а мы оттуда руками перетаскивали в конкретный проект. Мы хотим переделать формирование этой ссылки по тегам. Но это уже в феврале.
