### ISSUE TITLE
Шаг проходит как успешный (открытие формы списка), хотя в конфигурации нет такого документа

### ISSUE THREAD

**Issue by Lopner** [Pr-Mex/vanessa-automation#622]
```Gherkin
Функционал: Открытие основной формы списка документа или справочника

Контекст:
  Дано: VA 1.2.027
  Платформа 8.3.10.2639

Сценарий: Ошибка при открытии несуществующей формы списка несуществующего документа
Дано Я открываю основную форму списка документа "МойДокумент1"

```
Такой шаг проходит как успешный, хотя в конфигурации нет такого документа

**Comment by GenVP** [comment]
@Lopner
Формы списка документа как и другие (справочники, регистры) открываются через переход по навигационной ссылке. Пример "e1cib/list/Документ.Документ1"
Если добавлять в каждую процедуру открытия форм списка/объектов проверку метаданных, нужно будет делать вызов сервера.

Например, можно использовать шаги чтобы тест падал:
```
Когда Я открываю основную форму списка документа "АвансовыйОтчет"
Тогда не появилось окно предупреждения системы
```
или
```
Когда Я открываю основную форму списка документа "АвансовыйОтчет"
Тогда я жду открытия окна "Авансовые отчеты" в течение 5 секунд
```

**Comment by Pr-Mex** [comment]
@GenVP 
А, точно. Если форма указано не правильно - то появляется предупреждение.

**Comment by Pr-Mex** [comment]
Закрываю.
