### ISSUE TITLE
Некорректное имя сценария в отчете Cucumber при генерации фича-файлов из СППР

### ISSUE THREAD

**Issue by azheval** [Pr-Mex/vanessa-automation#624]
В отчете Cucumber при формировании фича-файлов генерацией из СППР (обработка сборки сценариев) в поле "name" секции "elements""keyword":"scenario" попадает наименование настройки запуска сценариев, а не наименование сценария.

**Comment by Pr-Mex** [comment]
@azheval 
Расскажи подробнее как у себя такое воспроизвести.

**Comment by azheval** [comment]
Сценарии из сппр, на ci формируется cucumber, в нем клик по сценарию (в действительности это настройка сценария, но не важно), клик по коду сценария (отбор) и, если для сценария было выполнено несколько настроек, то видим все эти настройки, но в поле scenario прописано название настройки, а не сценария

**Comment by Pr-Mex** [comment]
@azheval 
Я что-то в тексте не понимаю.
Дай видео или скрины, плиз.

**Comment by azheval** [comment]
![2020-01-27_7-00-15](https://user-images.githubusercontent.com/14293358/73149569-ef47ee80-40d2-11ea-96df-c4e80f88d2d0.png)

**Comment by Pr-Mex** [comment]
Неактуально.
