### ISSUE TITLE
Ошибка работы с EPF, если в клиент-сервере есть доступ к EPF?

### ISSUE THREAD

**Issue by GenVP** [Pr-Mex/vanessa-automation#628]
Дано
VA 1.2.029
Клиент и сервер 1С на одной машине. У пользователя сервера 1С нет доступа к файлам тестов.
После генерации обработок фич и выполнение тестов выдается ошибка о невозможности подключения обработок фич.

Проверил в отладчике - падает в форме VA в "ПолучитьОбработкуИзФайлаЧерезМетодСоздать" из-за ошибки доступа к файлу обработки фичи на чтение при попытке создания обработки из файла на сервере.
Это из-за того, что проверка контекста подключения выполняется через Файл.Существует(). А в этом случае будет истина даже, если у пользователя сервера 1С нет доступа на чтение.

Пример когда работает:
`&НаСервереБезКонтекста
Функция ПолучитьОбработкуИзФайлаЧерезМетодСоздать(ДополнительныеПараметры,ИмяОбработки)
	Обработка = Неопределено;
	Если ТипЗнч(ДополнительныеПараметры) = Тип("Структура") Тогда
		Если ДополнительныеПараметры.Свойство("ИмяФайла") Тогда
			Файл = Новый Файл(ДополнительныеПараметры.ИмяФайла);
			Если Файл.Существует() Тогда
				**//+ Проверка доступа к обработке на чтение**
				Попытка
					ЧтениеДанных = Новый ЧтениеДанных(ДополнительныеПараметры.ИмяФайла);
				Исключение
					Возврат Обработка;
				КонецПопытки;
				ЧтениеДанных.Закрыть();
				**//- Проверка доступа к обработке на чтение**
				Обработка = ВнешниеОбработки.Создать(ДополнительныеПараметры.ИмяФайла, Ложь);
				ИмяОбработки = Обработка.Метаданные().Имя;
			КонецЕсли;	 
		КонецЕсли;	 
	КонецЕсли;	 
	
	Возврат Обработка; 
КонецФункции	 
`

**Comment by Pr-Mex** [comment]
@GenVP 
Это интересная ситуация.
Когда сервер на том же компе - специально включена оптимизация, чтобы быстрее подключить обработки.
Получается сервер файл видит, но не может прочитать.

**Comment by Pr-Mex** [comment]
@GenVP 
А почему не обернуть в попытку строку

Обработка = ВнешниеОбработки.Создать(ДополнительныеПараметры.ИмяФайла, Ложь);

?

**Comment by GenVP** [comment]
@Pr-Mex 
Да, по-молчанию 1С создает пользователя сервера 1С без доступа на чтение к папкам. Но видеть он их может. В принципе, такая ошибка также может возникнуть, если файл обработки будет в сетевой папке к которой нет доступа на чтение под пользователем сервера, но есть под пользователем клиента.

Не стал заключать в попытку внешнюю обработку, так как в этом случае будет попытка создания файла на сервере и выход без ошибке при неудаче. Он может, например, быть заблокирован. Я же хотел исключить только ошибку доступа на чтение. Но, как говориться, можно и так ) Будет не зависеть от платформы.

**Comment by Pr-Mex** [comment]
@GenVP 
Если файл заблокирован, то нам наверное всё равно, т.к. всё равно не можем его прочитать напрямую и надо подключать epf длинным путём.

**Comment by Pr-Mex** [comment]
Решено.
