### ISSUE TITLE
Добавить вариант снятия скриншотов - не использовать компоненту

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#632]
Сейчас, если включить компоненту - то скрины всегда будут сниматься только с помощью неё. Нужен вариант - когда компонента используется, но скрины снимаются чем-то другим.

**Comment by ViktorErmakov** [comment]
@ViktorErmakov

**Comment by ViktorErmakov** [comment]
пора закрывать задачу думаю. Леонид?)

**Comment by Pr-Mex** [comment]
@ViktorErmakov 

Да

**Comment by ViktorErmakov** [comment]
> 
> 
> @ViktorErmakov
> 
> Да

Ну если что я этого сделать не могу!)
