### ISSUE TITLE
 "ТаблицаИзвестныхStepDefinition" не заполняется шагами при первом запуске

### ISSUE THREAD

**Issue by Lopner** [Pr-Mex/vanessa-automation#634]
Если первый раз запускать VA-single, и не загружать подготовленные тесты(шаги),
если перейти в раздел "работа с UI"->"Сценарий поведения" и нажать на кнопку "Добавить известный шаг" то список известных шагов будет пустой. 
(При таких условиях таблица "ТаблицаИзвестныхStepDefinition" не заполняется шагами)

**Comment by asosnoviy** [comment]
Дубль https://github.com/Pr-Mex/vanessa-automation/issues/364

**Comment by Pr-Mex** [comment]
@asosnoviy 
Видишь в этом знак? )))

**Comment by asosnoviy** [comment]
я честно пытался, не вышло =(

**Comment by Pr-Mex** [comment]
Решено.
