### ISSUE TITLE
Снимать скриншоты новой компонентой 1WinCtr если стоит необходимый флаг

### ISSUE THREAD

**Issue by ViktorErmakov** [Pr-Mex/vanessa-automation#637]
Во всех местах вызова сделать скриншот, адаптировать под новую компоненту 1cWinCtrl

**Comment by ViktorErmakov** [comment]
Решили что в рамках этой задачи делаем снимок основного экрана клиента тестирования, в дальнейшем сделаем опционально снимок дочернего окна, либо снимок экрана.

**Comment by Pr-Mex** [comment]
Решено.
