### ISSUE TITLE
При снятии скриншотов компонентой 1cWinCtrl делать ктивным окно клиента тестирования

### ISSUE THREAD

**Issue by ViktorErmakov** [Pr-Mex/vanessa-automation#638]
Либо в начале запуска фичи, либо перед каждым снимком скриншота
Кто за что голосует?

**Comment by Pr-Mex** [comment]
@ViktorErmakov 
Насколько я понял, компонента снимает скрин окна, даже когда оно не активно. Поэтому наверное не нужно специально для скриншота активизировать окно.

**Comment by ViktorErmakov** [comment]
это да, но например мне что бы запустить запись инструкций после настройки окна через компоненту, приходится писать первый шаг "И Пауза 5" что бы было время переключиться на экран клиента тестирования, который был запущен ранее для настроек. Это косяк.

**Comment by ViktorErmakov** [comment]
можно один раз при старте фичи сделать активным основное окно клиента тестирования

**Comment by Pr-Mex** [comment]
> это да, но например мне что бы запустить запись инструкций после настройки окна через компоненту, приходится писать первый шаг "И Пауза 5" что бы было время переключиться на экран клиента тестирования, который был запущен ранее для настроек. Это косяк.

@ViktorErmakov 
Я не понял этот случай. Расскажи подробнее, пожалуйста.

**Comment by ViktorErmakov** [comment]
погоди, что то я нагнал да.

**Comment by ViktorErmakov** [comment]
запутался.. ладно дома все еще раз проверю и закрою ишью
