### ISSUE TITLE
Просмотр лога Out при ошибке генерации EPF

### ISSUE THREAD

**Issue by GenVP** [Pr-Mex/vanessa-automation#640]
При генерации epf файлов на основании фич, если возникла ошибка при разборке/сборке обработки (например, кончились локальные лицензии) выводятся логи файлов Out и std. Но лог Out 1С в windows генерирует в кодировке windows-1251, а все логи сейчас выводятся в UTF-8. В результате ошибку из лога Out прочитать нельзя.

Кто использует в linux там Out то же в UTF-8 генерируется?

Необходимо указывать кодировку в ВывестиТекстФайлаЛога в зависимости от типа выводимого лога и ОС. Можно оставить по умолчанию UTF-8, но для Out и windows передавать windows-1251.

**Comment by GenVP** [comment]
На eng windows не проверял какая кодировка будет. Может стоит для Оut файла оставить автоматическое определение кодировки?

**Comment by Pr-Mex** [comment]
@GenVP 
Как просто получить ошибку генерации epf, чтобы проверить по живому?

**Comment by GenVP** [comment]
Я проверял на серверной базе, выдача лицензий сервером 1С, на клиенте лицензии по сети не доступны.
В принципе, если все на одном компе, лицензии для баз выдает сервер 1С и у клиента в настройках отключена галка "Использовать аппаратную лицензию", то тоже не сработает )

Будет сообщение наподобие:
`23.01.2020 20:42:47 Проверьте работу команды <"C:\Program Files\1cv8\8.3.14.1976\bin\1cv8" DESIGNER /F "C:\Windows\Temp\v8_543A_38.tmp" /LoadExternalDataProcessorOrReportFromFiles "C:\Windows\Temp\v8_543A_36.tmp/temp.xml" "C:\Windows\Temp\v8_543A_37.epf" /out "C:\Windows\Temp\v8_543A_3d.txt" > "C:\Windows\Temp\v8_543A_3c.txt">
23.01.2020 20:42:44 Запускаю генерацию epf.
23.01.2020 20:42:44 Работаю по фиче: C:\Windows\Temp\vanessa-behavior\temp.feature
23.01.2020 20:42:47 Файл EPF не создан.
23.01.2020 20:42:47
23.01.2020 20:42:47 �� ������� ��������. �� ��������� ���� ������ ��������� ��� ���������� ����������� ��������!
23.01.2020 20:42:47 Создание epf по фичам закончено.`

**Comment by Pr-Mex** [comment]
> На eng windows не проверял какая кодировка будет. Может стоит для Оut файла оставить автоматическое определение кодировки?

Подскажи, что ты имеешь ввиду под автоматически?

**Comment by Pr-Mex** [comment]
@GenVP

**Comment by GenVP** [comment]
@Pr-Mex Не задавать кодировку для `ЧтениеТекста.Открыть`. Тогда кодировка должна определяться автоматически. Проверил - выводит сообщение правильно.

> Если параметр не задан, формат текста будет определен автоматически по сигнатуре BOM в начале файла; если сигнатура BOM в файле отсутствует, файл будет открыт в кодировке ANSI.

**Comment by Pr-Mex** [comment]
@GenVP 
Понял. Зареквестишь?

**Comment by GenVP** [comment]
@Pr-Mex 
Дв

**Comment by Pr-Mex** [comment]
> @Pr-Mex
> Да

@GenVP 
Ок. Ждём.

**Comment by Pr-Mex** [comment]
Решено.
