### ISSUE TITLE
Ошибка при копирование основного клиента тестирования

### ISSUE THREAD

**Issue by GenVP** [Pr-Mex/vanessa-automation#652]
При копировании основного клиента тестирования "Этот клиент" в таблице клиентов сохраняется невидимый флаг "ЭтотКлиент" (у него то же отображается звездочка в первой колонке) и поэтому новый клиент не выгружается в файл настроек JSON.

Исправлю.

**Comment by GenVP** [comment]
Заодно вопрос: должен ли выгружаться в настройки основной клиент с заданными доп параметрами? А то получается, что для него можно задать пользователя и пароль, но он не выгрузиться в файл для пакетного запуска?

**Comment by Pr-Mex** [comment]
@GenVP 
На CI сервере путь скорее будет всего другой, а запись "Этот клиент" всегда соответствует базе TestManager. Поэтому было принято решение не выгружать эту строку.
Считаешь что её надо выгружать?

**Comment by GenVP** [comment]
@Pr-Mex 
Если клиент один, то да. Раньше колонка ЭтотКлиент ("звездочка") в таблице клиентов использовалась для идентификации "Этот клиент" или для исключения клиентов из выгрузки?

 Сейчас колонка "ЭтоКлиент" в таблице клиентов используется:
1. При добавлении клиента "Этот клиент" - заполняется Истина
2. При выгрузке для исключения "ЭтотКлиент" = Истина.
3. В "РаботаСTestClient.ЯКопируюТекущийПрофильTestClientСУстановкойПараметров" - сбрасывается, если не "Этот клиент".

В остальных случаях проверка "Этот клиент" выполняется по имени.

**Comment by GenVP** [comment]
Можно оставить на выбор пользователя, переключая звездочку по двойному щелчку

**Comment by Pr-Mex** [comment]
@fenixnow 
Напомни, плиз, ты какой смысл закладывал в поле со звёздочкой? Чтобы отказаться от поиска по имени?

**Comment by fenixnow** [comment]
Если не ошибаюсь, то мы не выгружаем "этот клиент". Это предопределенный элемент списка.

**Comment by fenixnow** [comment]
> @fenixnow
> Напомни, плиз, ты какой смысл закладывал в поле со звёздочкой? Чтобы отказаться от поиска по имени?

Поле со звездочкой это для красоты, оно сокращает ширину колонки....

**Comment by fenixnow** [comment]
> Можно оставить на выбор пользователя, переключая звездочку по двойному щелчку

Не врубился, что это нам даст? Признак вызгузки в json? 
Если идея сводится к тому, что в json должен быть "Этот клиент" доп настроками авторизации и тд, то думаю это лучше добавить руками в json
Могу ошибаться.

**Comment by GenVP** [comment]
@fenixnow 
Если это признак только для исключения выгрузки в json, то лучше сделать его выбираемым, а по-умолчанию установленным. Если можно не редактировать файл настроек вручную - это, по-моему, хорошо.
Если это признак предопределеннного клиента, тогда пусть остается как есть. Только убирать при копировании. Можно только переделать в коде проверку клиента по имени на признак при рефакторинге.

**Comment by fenixnow** [comment]
> Можно только переделать в коде проверку клиента по имени на признак при рефакторинге.
Не возражаю, если Леонид не против.

**Comment by Pr-Mex** [comment]
> > Можно только переделать в коде проверку клиента по имени на признак при рефакторинге.
> 
> Не возражаю, если Леонид не против.

@GenVP  @fenixnow 
Я за.

**Comment by Pr-Mex** [comment]
Решено.
