### ISSUE TITLE
Поиск картинки(рисунка) в табличном документе 

### ISSUE THREAD

**Issue by Lopner** [Pr-Mex/vanessa-automation#655]
VA - Single  27

Есть табличный документ, в котором есть ячейка, в которой расположена картинка не на всю область ячейки.
Расшифровка стоит только на картинке

Если эту область выводить в макет, то кликнуть можно только на картинку.
Но если перейти на ячейку через шаг установки ячейки в табличном документе, то фокус на картинку не попадет и нажать тестом не получается.

Как то можно искать картинки в Табличном документе по имени и их выделять и нажимать?

По идее туда можно попасть если "TAB" нажимать, но я тоже не понял как это можно сделать без Sikulix

Нет случайно такого шага который имитирует вот это:
```
ОбъектShell = Новый COMОбъект("Wscript.Shell");
ОбъектShell.SendKeys("{TAB}"); 
```

**Comment by Pr-Mex** [comment]
@Lopner 
Код приведенный вами можно выполнить и напрямую с помощью шага
И я выполняю код встроенного языка
    | 'Мой код' |

Насчет клика на картинку - это проще сделать с помощью расширения, которое будет принимать имя картинки и кликать на неё.

**Comment by Lopner** [comment]
Попробовал запихнуть код в этот шаг:
```
И я выполняю код встроенного языка
	| 'ОбъектShell = Новый COMОбъект("Wscript.Shell");' |
	| 'ОбъектShell.SendKeys("{TAB}"); ' |
```
но ожидаемого результата не получил, такое ощущение что эта команда отрабатывает в менеджере тестирования а не в клиенте

**Comment by Pr-Mex** [comment]
> @Pr-Mex
> Попробовал запихнуть код в этот шаг:
> 
> ```
> И я выполняю код встроенного языка
> 	| 'ОбъектShell = Новый COMОбъект("Wscript.Shell");' |
> 	| 'ОбъектShell.SendKeys("{TAB}"); ' |
> ```
> 
> но ожидаемого результата не получил, такое ощущение что эта команда отрабатывает в менеджере тестирования а не в клиенте

@Lopner 
Да, этот код будет выполняться на стороне TestManager.
Но если активным окном является клиент тестирования, то команда SendKeys должна уйти ему, разве не так?

**Comment by Lopner** [comment]
@Pr-Mex
Да вы правы, код отрабатывает, оказывается дело  в некорректной установке фокуса на ячейке.
Переход к ячейке работает, ячейка открывается по двойному клику (расшифровка), но при этом фокус на ней не активный.

Мне нужно выполнить что то такое.
`ТабличныйДокумент.ТекущаяОбласть = ТабличныйДокумент.Область("R10C10");`

Как такой шаг выполнить?

**Comment by Pr-Mex** [comment]
@Lopner 
Для обычной ячейки надо сделать так
``` Gherkin
И в табличном документе 'РеквизитТабличныйДокумент' я перехожу к ячейке "R10C10"
```

**Comment by Lopner** [comment]
@Pr-Mex
К сожалению такой шаг не выделяет ячейку, точнее он ее выделяет, но не как активную (такая желтая рамка должна появляться).

Если во время теста и перехода от ячейки к ячейки один раз кликнуть мышкой по табличной части, то фокус начинает нормально устанавливаться. И вот этот шаг работает корректно

**Comment by Lopner** [comment]
Ну собственно получилось решить сей момент опять через
`И я выполняю код встроенного языка
	| 'ОбъектShell = Новый COMОбъект("Wscript.Shell");' |
	| 'ОбъектShell.SendKeys("{TAB}"); ' |`

Чтоб фокус перекинуть на табличный документ. Наверное это решение не очень :) но работает! :)
