### ISSUE TITLE
Адаптация feature-файлов проекта VA для использования в StoryMapper

### ISSUE THREAD

**Issue by 1cto** [Pr-Mex/vanessa-automation#667]
Функционал: Структурирование feature-файлов VA в виде карты пользовательских историй
   Как владелец продукта VA
   Я хочу я хочу структурировать feature-файлы VA  в виде карты пользовательских историй
   Чтобы информация о функционале VA стала более прозрачна контрибьюторам

Контекст:
  Дано: VA 1.2.0.29

Сценарий: Простановка тегов привязки конкретной фичи к UA/UF
  Допустим: существует фича docs/VSL/Create new step/Док-Создать новый шаг.feature 
![image](https://user-images.githubusercontent.com/15178930/73852368-183d5180-4840-11ea-9e71-124c8e232185.png)

  Когда: Когда фиче файл в StoryMapper привязывается к соотв. UA/UF

  Тогда: тогда шапка feature-файла меняется на
![image](https://user-images.githubusercontent.com/15178930/73852523-60f50a80-4840-11ea-9996-734e17ded150.png)

**Comment by Pr-Mex** [comment]
Решено.
