### ISSUE TITLE
Шаг я запоминаю случайное число в переменную

### ISSUE THREAD

**Issue by asosnoviy** [Pr-Mex/vanessa-automation#684]
Шаг я запоминаю случайное число в переменную
Чтобы вставлять значения в новые элементы

**Comment by Pr-Mex** [comment]
@asosnoviy 
Разве не было такого?

**Comment by asosnoviy** [comment]
@Pr-Mex посмотрю на девелопе

**Comment by asosnoviy** [comment]
@Pr-Mex поискал, не нашел.
