### ISSUE TITLE
Проверка на задвоение имен сценариев

### ISSUE THREAD

**Issue by pumbaEO** [Pr-Mex/vanessa-automation#687]
```Gherkin
Функционал: проверка на дубли сценариев
   Как администратор feature файлов
   Я хочу выводить удобные сообщения одублях сценариев в разных фичах

Контекст:
  Дано: 1,0,28
  И 8.3.16.1148
  и конфигурация запуска = оучной запуск

Сценарий: вывод сообщения о дублях при загрузке feature файлов
  Допустим: запустили vanessу
  Когда: выбрали каталог с feature файлами
  Тогда: после загрузки фич в случаии наличия дублей выводить краткий отчег где и какой сценарий задублировался

```

**Comment by Pr-Mex** [comment]
@pumbaEO 
Я использую сценарии с одинаковым именем.
Например
Закрыть клиент тестирования.

И мне не нужны Сообщения о том, что имя сценария задублировалось. Как такое предлагаешь решать?

**Comment by pumbaEO** [comment]
вопрос не использования шагов одних и тех же в разных сценариях, а в том что предупредить пользователей что есть названия сценариев одинаковые в разных фичах, т.е. тот же `Сценарий: Я открываю и закрываю TestClient` только один раз встречаетса а не в какой нибудь еще фиче было бы определение другое для этого наименоваеия.

Плюс возникает неразбериха в отчетах о прохождении тестов, например есть 2 разные фичи с названием одинаковым сценариев в отчете допустим первый будет passed, а второй failure...

**Comment by freddy121** [comment]
Женя прав. В отчете в формате cucumber(что является стандартом отчетов в bdd во нормальном мире) такие штуки будут задваиваться и неоднозначно трактоваться. В specflow , например, проект не компилится если сценарии называются одинаково. Ну и документацию непонятно как вести. А переиспользование экспортных сценариев это же не дублирование. Это шаг в другом сценарии.

**Comment by Pr-Mex** [comment]
Решено.
