### ISSUE TITLE
Поддержка статуса Test broken для отчета Allure

### ISSUE THREAD

**Issue by ThargoN** [Pr-Mex/vanessa-automation#696]
Сейчас всем упавшим тестам в Allure присваивается статус "Test failed". Необходимо добавить поддержку статуса "Test broken" который тоже присваивается упавшим тестам.

Выбор между этими статусами определяется шагом, на котором произошло падение теста:
* Любой шаг теста, начинающиеся с ключевого слова "**Тогда**"  => статус "**Test failed**".
* Любые другие шаги => статус "**Test broken**".

**Зачем:**
Мы в тексте теста разделим все шаги на 2 группы:
* важные для проверки конкретного поведения и отвал теста на этих шагах означает ошибку в тестируемом функционале (результат теста отличается от ожидаемого)
* "инфраструктурные", падение на которых означает (почти наверняка), что сам тест требует доработки, т.к. он не смог проверить НУЖНЫЙ функционал

**Пример фича-файла:**
```
        И В командном интерфейсе я выбираю 'Продажи' 'Договоры с клиентами'
        ...
        И в поле 'Номер' я ввожу текст '23 С'
        ...
        Тогда переменная "recieved" имеет значение "$reference$"
```
В этом примере только последний шаг начинается с "Тогда" и падение теста на нем и будет результатом проверки функционала в разработке: test failed, необходима работа разработчика.  
Если же в типовой конфигурации поменяется название команды или поля "Номер", что приведет к неработоспособности теста - то это явно требует корректировки самого теста, который стал неактуален, поэтому тут статус test broken лучше отразит ситуацию.

**Comment by NikitaMikhaylovSB** [comment]
Очень ждем...

**Comment by Pr-Mex** [comment]
1. Нужно добавить опцию в параметрах Allure, которая включает данный режим.
2. Поправить формирование самого отчета Allure.

@NikitaMikhaylovSB 
возьмётесь?

**Comment by Pr-Mex** [comment]
Решено.
