### ISSUE TITLE
Ошибка в VA-Single 1.2.030 при скрине всех окон 1С

### ISSUE THREAD

**Issue by Filippal** [Pr-Mex/vanessa-automation#718]
Ошибка появляется при скриншоте окна 1с после падения теста

Файл <C:\Program Files (x86)\OneScript\lib\vanessa-automation-single/tools/Sikuli/GetAll1CWindowsCoordinates.sikuli> не найден.
{ВнешняяОбработка.VanessaAutomationsingle.Форма.УправляемаяФорма.Форма(6031)}:			ВызватьИсключение ПодставитьПараметрыВСтроку(
{ВнешняяОбработка.VanessaAutomationsingle.Форма.УправляемаяФорма.Форма(23748)}:	Рез = ВыполнитьSikuliСкрипт(Объект.КаталогИнструментов + "/tools/Sikuli/GetAll1CWindowsCoordinates.sikuli > """ 
{ВнешняяОбработка.VanessaAutomationsingle.Форма.УправляемаяФорма.Форма(23839)}:		МассивКоординатОкон1С = ПолучитьМассивКоординатОкон1С();

**Comment by Pr-Mex** [comment]
@Filippal 
В 1.2.030 для снития скринов всех окон используется SikuliX. В 1.2.031 планируется отказаться от этого и использовать компоненту. Чтобы сейчас заработало надо скачать из репо каталог скриптов SikuliX.

**Comment by Pr-Mex** [comment]
Не актуально. Теперь используется компонента для снятия всех окон.
