### ISSUE TITLE
Ошибка загрузки фич по тегу

### ISSUE THREAD

**Issue by hawk911** [Pr-Mex/vanessa-automation#731]
```Gherkin

Контекст:
  Дано: VA 1.2.0.29

```

Если загружать фичи по определённому тегу из папки, в которой есть сценарий с ошибкой (компиляций), тогда эта фича тоже попадает в список загруженный фич, хотя у этой фичи нет данного тега.

**Comment by Pr-Mex** [comment]
@hawk911 
Можешь прикрепить файл фичи, которая не компилируется?

**Comment by hawk911** [comment]
> @hawk911
> Можешь прикрепить файл фичи, которая не компилируется?

Зачем, там была синтаксическая ошибка. Было:
```Gherkin
3And ...
```
Хотели закомментировать, но не сработало и так запушили.

**Comment by Pr-Mex** [comment]
Решено.
