### ISSUE TITLE
Ошибка при заполнении табличной части

### ISSUE THREAD

**Issue by Akhmedova1** [Pr-Mex/vanessa-automation#738]
**Контекст**:
   Дано: vanessa-automation 1.2.030
  1С:Предприятие 8.3 (8.3.14.1976)
  Управление холдингом, редакция 1.2 (1.2.8.100)

**Сценарий**: Создание документа Заявка на операцию
  Когда: Заполнение статьи ДДС в табличной части документа 
  Тогда: Генерируется код 
И в таблице "ТаблицаДвижений" я активизирую поле "Статья движения денежных средств"
И в таблице "ТаблицаДвижений" я выбираю текущую строку
И в таблице "ТаблицаДвижений" из выпадающего списка "Статья движения денежных средств" я выбираю по строке [СтатьяДДС]

**Но** при запуске сценария с данным кодом из СППР выдается ошибка:

![image](https://user-images.githubusercontent.com/63597874/79129481-f3200e80-7dad-11ea-8d7e-c7d2dc5728b0.png)

Ошибка возникает при установке связей параметров выбора, а точнее в этих строчках (ОперативноеПланированиеФормыУХ.УстановитьСвязиПараметровВыбора()):
![image](https://user-images.githubusercontent.com/63597874/79129643-42fed580-7dae-11ea-9fec-8276ae4a0f46.png)
Ожидается, что в качестве Текущего элемента формы будет передаваться _табличная часть_. Однако по факту - реквизит шапки _Сумма документа,_ в следствии чего невозможно выполнение метода НайтиПоИдентификатору().
Помогите, пожалуйста, разобраться в чем проблема.

**Comment by Pr-Mex** [comment]
@Akhmedova1 
Вы нашли ошибку в тестируемой конфигурации. В данном случае в УХ.
Такие ошибки нужно регистрировать на v8@1c.ru
