### ISSUE TITLE
Как можно перечислить несколько значений реквизитов в конструкции Если не существует элемент справочника "Справочник1" с реквизитами Тогда ?

### ISSUE THREAD

**Issue by JVorobyeva** [Pr-Mex/vanessa-automation#739]
Контекст:
 Дано: vanessa-automation 1.2.030
  И 1С:Предприятие 8.3 (8.3.14.1976)
  и Управление холдингом, редакция 1.2 (1.2.8.100)

Сценарий: Необходимо проверить есть ли элемент справочника по значению нескольких реквизитов. 
  Допустим: 
Если не существует элемент справочника "ДоговорыКонтрагентов" с реквизитами [НаименованиеДоговора] И [Контрагент] Тогда 

Но при запуске сценария с данным кодом из СППР выдается предупреждение: 

Пустой адрес снипета у шага: Если не существует элемент справочника "ДоговорыКонтрагентов" с реквизитами "Тест1304" И "ОЛИВЕР ВАЙМАН" Тогда

Как можно перечислить несколько значений реквизитов?

**Comment by Pr-Mex** [comment]
@JVorobyeva 
Данного шага нет в библиотеке шагов.
Вы можете написать его сами, или создать подсценарий, который будет выполнять эту проверку.
