### ISSUE TITLE
Ошибка при импорте сценария на английском языке

### ISSUE THREAD

**Issue by hawk911** [Pr-Mex/vanessa-automation#74]
Функционал: 
   Как  Разработчик 
   Я хочу импортировать сценарий в Vanessa на английском языке

Контекст:
  Дано: Vanessa Simple 1.2.014
  И  8.3.12.1567

Сценарий:  Испорт шага с параметром на английском языке
  Когда:  Импортирую шаг с параметром на английском языке
  Тогда:  Vanessa не видит мой импортированный шаг с параметром на английском языке

**Comment by Pr-Mex** [comment]
Решено.
