### ISSUE TITLE
Передача параметров между шагами процесса

### ISSUE THREAD

**Issue by Leonsiya25** [Pr-Mex/vanessa-automation#741]
Добрый день!
Подскажите, пожалуйста, в чем у меня может быть ошибка при передаче параметров между шагами процесса?
Создала процесс с 2 шагами: 
1. Создание пользователя
2. Настройка прав пользователя.
В каждом шаге указан соответствующий одноименный сценарий. 
В сценарии "Создание пользователя" есть параметр "ИмяПользователя" со значением по-умолчанию ("Казначей") и флагом "Возвращает данные".
В сценарии "Настройка прав пользователя" тоже есть параметр "ИмяПользователя", но значение по-умолчанию я для него не указываю, т.к. хочу получить его из предыдущего шага.
Для этого в шаге процесса "Настройка прав пользователя" на закладке "Параметры" я указала для параметра "Имя пользователя" значение по ссылке "Создание пользователя.ИмяПользователя".
Запускаю тест, падает с ошибкой: "{ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(2911)}: Не удалось перейти к нужной строке в таблице <ПользователиСписок>. 
		| 'Полное имя'                              | 
		| '$Создание пользователя.ИмяПользователя$' | "
Возможно, неправильно понимаю механизм работы с параметрами между шагами процесса?
На ИТС не нашла.

**Comment by Pr-Mex** [comment]
Это вопрос по СППР. Попробуйте его задать тут
https://t.me/testspro1c

**Comment by Leonsiya25** [comment]
> https://t.me/testspro1c

Леонид, ссылка точно рабочая?
![image](https://user-images.githubusercontent.com/63595103/79460216-2a382f00-7ffd-11ea-8539-ab67c58e5c0e.png)
