### ISSUE TITLE
Версия компоненты 1cWinCtr содержит не допустимый символ XML 

### ISSUE THREAD

**Issue by DmitriyKorotovskih** [Pr-Mex/vanessa-automation#764]
САБЖ

Версия попадает в контекст формы:
![image](https://user-images.githubusercontent.com/34188696/80362989-fbdc0e80-889c-11ea-9f29-64011cd428e5.png)

Любой контекстный серверный вызов на форме:
```
{ВнешняяОбработка.VanessaAutomation.Форма.УправляемаяФорма.Форма(12734)}: Ошибка при вызове метода контекста (ЗаполнитьДеревоЗначенийПоМассивуСервер): Ошибка передачи данных между клиентом и сервером. Значение недопустимого типа.: Ошибка преобразования данных XDTO:      
Запись значения свойства 'str':
        форма: Элемент
        имя: {http://v8.1c.ru/8.2/managed-application/logform}str: Ошибка при записи XDTO: Текст XML содержит недопустимый символ в позиции 15 :
Версия: 1.0.0.0
```
Компонента(1cWinCtrlLin64_1_0_0_0) возвращает строку значения версии, содержащую лишний символ, воспроизводится на Ubuntu 16.04, предыдущие версии компоненты не проверял.

Версия ВА: https://github.com/Pr-Mex/vanessa-automation/tree/4e754b31f38445b78fdf49ec4f2d7ab7c813f7be

@lintest @Pr-Mex

**Comment by lintest** [comment]
Ошибка воспроизводится, в том числе на предыдущих версиях. 
Будут внесены исправления в компоненту. Быстрый патч:
```bsl
Заголовок = "Управление окнами, версия " + СтрЗаменить(Значение, Символ(0), "");
```

**Comment by Pr-Mex** [comment]
Решено.
