### ISSUE TITLE
Не создаются шаблоны обработки для новых шагов

### ISSUE THREAD

**Issue by PiskunovSS** [Pr-Mex/vanessa-automation#794]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Проверка генерации EPF
   Как разработчик
   Я хочу генерировать шаблоны обработок для программирования шагов

Контекст:
  Дано: 1.2.031
  И платформа 8.3.14.1854
  и собственная конфигурация
  и синхронные вызовы разрешены
  и модальность разрешена
  и режим совместимости "не использовать"
  и режим совместимости интерфейса "8.2. Разрешить такси"
  и пользовательский сеанс запущен в "такси"

Сценарий: Генерация шаблона обработки для нового шага
  	Допустим я запускаю обработку "C:\Program Files\OneScript\lib\vanessa-automation\vanessa-automation.epf"	
	Когда открылось окно 'ver 1.2.031: Vanessa Automation'
	И в поле 'СгенерированныйСценарий' я ввожу текст 
		|'#language: ru'|
		|''|
		|'Функционал: <описание фичи>'|
		|''|
		|'Как <Роль>'|
		|'Я хочу <описание функционала> '|
		|'Чтобы <бизнес-эффект> '|
		|''|
		|'Контекст: '|
		|' Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий'|
		|''|
		|''|
		|'Сценарий: <описание сценария>'|
		|' И новый несуществующий шаг'|
	И я нажимаю на кнопку 'Подготовить сценарий к выполнению'
	И я перехожу к закладке "Генератор EPF"
	И я устанавливаю флаг 'Генерировать управляемую форму'
	И я нажимаю на кнопку 'Создать и обновить шаблоны обработок'
	Тогда файл с шаблоном обработки не создается

```

> Прикладывайте файлы скриншотов
![image](https://user-images.githubusercontent.com/10277115/81899800-b160ce80-95cc-11ea-86a8-f487d1ff040f.png)

Отладчиком нашел, что в процедуре СделатьGenerateEpf() получается, что в ПомещаемыеФайлы попадает один файл "C:\Program Files\OneScript\lib\vanessa-automation\features\Core\FeatureReader\step_definitions\ПроверкаМетодаШагОФ.epf" и из-за этого пропускается вызов СделатьGenerateEpfПродолжение();

**Comment by PiskunovSS** [comment]
У меня был путь к библиотеке C:\Program Files\OneScript\lib\vanessa-automation\features
Если меняю на C:\Program Files\OneScript\lib\vanessa-automation\features\Libraries, то проблема уходит. Если так и задумано, то проблема снимается.

Но костыль тот еще:

```bsl
Если ИмяОбработки = Неопределено ИЛИ ИмяОбработки = "ПроверкаМетодаШагОФ" Тогда
	Возврат Ложь;
КонецЕсли;
```

**Comment by PiskunovSS** [comment]
База файловая. На серверной не успел проверить. Может тут gif прокатит 
![Генерация EPF](https://user-images.githubusercontent.com/10277115/81914692-ad3fab80-95e2-11ea-9dd2-21959a205455.gif)

**Comment by PiskunovSS** [comment]
Как я понял проблему:
Есть процедура СделатьGenerateEpf(). В ней происходит чтение всех epf из каталога библиотеки. В массив файлов попадает ПроверкаМетодаШагОФ.epf, который на стадии загрузки файлов из библиотеки был пропущен, потому что в коде затычка именно на эту обработку. А в СделатьGenerateEpf() получается, что подгружены не все файлы бибилиотеки, поэтому пропускается вызов СделатьGenerateEpfПродолжение() и нигде далее по коду повторный вызов СделатьGenerateEpfПродолжение() не происходит:

```bsl
Если ПомещаемыеФайлы.Количество() = 0 Тогда
	СделатьGenerateEpfПродолжение();
	Возврат;
КонецЕсли;
```

Какая здесь заложена логика, чтобы самому поправить, я не знаю) Может нужно тупо не указывать в качестве каталога библиотек весь каталог features?)

**Comment by Pr-Mex** [comment]
@PiskunovSS 
Проблема в epf ПроверкаМетодаШагОФ.
Видимо в ней нет управляемой формы, поэтому была сделана заглушка.
Сейчас понимаю, что надо просто добавить управляемую форму в epf со стандартным набором процедур и убрать заглушку.

**Comment by Pr-Mex** [comment]
Решено.
