### ISSUE TITLE
Аттачменты allure на русском, надо на английском

### ISSUE THREAD

**Issue by DitriXNew** [Pr-Mex/vanessa-automation#797]
Все окружение на инглише, однако, отчеты для аллюра берут русские наименования:
![image](https://user-images.githubusercontent.com/11927866/82046672-00386200-96ba-11ea-89e8-0e13be8ce6a7.png)
И внутри отчетов тоже все на русском, а надо на инглише, раз уж все на инглише

**Comment by Pr-Mex** [comment]
Решено.
