### ISSUE TITLE
Не работает создание каталога при нажатии Сравнить таблицы в окне ошибки

### ISSUE THREAD

**Issue by akademik1986** [Pr-Mex/vanessa-automation#803]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: Сравнение табличных документов в окне ошибки шага
   Как разработчик
   Я хочу видеть отличия при сравнении табличных документов, которые отличаются друг от друга при выполнении шага "Дано Табличный документ "Таб1" равен макету "МакетЭталон.mxl""

http://joxi.ru/l2ZQ8z1hEvP6jm

**Comment by akademik1986** [comment]
> > Заполните шаблон обсуждения GIT
> 
> ```
> Функционал: Сравнение табличных документов в окне ошибки шага
>    Как разработчик
>    Я хочу видеть отличия при сравнении табличных документов, которые отличаются друг от друга при выполнении шага "Дано Табличный документ "Таб1" равен макету "МакетЭталон.mxl""
> 
> 
[http://joxi.ru/l2ZQ8z1hEvP6jm](url)
> ```

**Comment by Pr-Mex** [comment]
Решено.
