### ISSUE TITLE
Шаг, сохраняющий навигационную ссылку активного окна в переменную

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#809]
```Gherkin
И я сохраняю навигационную ссылку текущего окна в переменную "ИмяПеременной"
```

**Comment by Pr-Mex** [comment]
Это подходит для окон, которые находятся в панели открытых.

**Comment by Pr-Mex** [comment]
Решено.

**Comment by drobilna121** [comment]
Добрый день! шаг отрабатывает, возвращая пустую строку в переменную. текущее окно находится в панели открытых.

**Comment by Pr-Mex** [comment]
@drobilna121 попробуйте на новой версии платформы

**Comment by drobilna121** [comment]
@Pr-Mex, Да, действительно, дело было в платформе. Спасибо большое!
