### ISSUE TITLE
Нужен пример теста Печатных форм или подход

### ISSUE THREAD

**Issue by Lopner** [Pr-Mex/vanessa-automation#819]
Есть печатная форма, в ней в зависимости от выбранных документов в области параметров макета подставляются какие-то значения (ну обычное дело кароче)

Как можно протестировать корректность формирования параметров макета?
Есть эталонные документы, есть ожидаемые значения, но как все это запихнуть в тест в VA я не соображу. Вариант с поиском области(конкретной ячейки) в макете и проверке его на ожидаемое значение не подходит, так как печатных форм куча, и они меняются(строчку добавили, строчку убрали, соответственно тест слишком трудоемко будет адаптировать), а вот состав параметров не меняется.

Хотелось бы проверять только эти параметры на ожидаемые значения

**Comment by Pr-Mex** [comment]
@Lopner 
Если в макете есть именованные области, то можно использовать

И Табличный документ "ИмяТабДок" содержит строки в областях
| ИмяОбласти | Подстрока |


Проверяет что в табличном документа содержатся значения, перечисленные в таблице. Таблица состоит из двух колонок: "ИмяОбласти" и "Подстрока".
