### ISSUE TITLE
Не сохраняется отчёт для СППР при запуске из командной строки

### ISSUE THREAD

**Issue by BarinovIN** [Pr-Mex/vanessa-automation#824]
Контекст:
  Дано: Версия 1.2.032: Vanessa Automation
  И 1С:8.3.14.1993
  И запуск из командной строки с завершением после выполнения всех сценариев 

Сценарий: Формирование отчёта в формате СППР
  Когда: Возникает ошибка при выполнении сценария
  Тогда: В каталоге отчёта СППР есть файл снимка экрана
             И **нет xml файла отчёта**.

  Когда: Тот же сценарий выполнялся на 1.2.031
  Тогда: В каталоге отчёта СППР формировался файл отчёта.

  Когда: Тот же сценарий выполняется на 1.2.032 без завершения сразу после выполнения сценариев
  Тогда: В каталоге отчёта СППР формируется файл отчёта, но при запуске из командной строки необходимо завершать работу системы.

**Comment by Pr-Mex** [comment]
@BarinovIN 
Нужен файл настроек, с которым вы запускаете VA в пакетном режиме.

**Comment by BarinovIN** [comment]
Приложил файл с настройками и сценарием.
[Настройки.zip](https://github.com/Pr-Mex/vanessa-automation/files/4691112/default.zip)

**Comment by Pr-Mex** [comment]
@BarinovIN 
Это должно быть исправлено в новых версия. Проверь, плиз.

**Comment by BarinovIN** [comment]
Проверил. Исправлено. Спасибо.
