### ISSUE TITLE
Вопрос о программном создании элемента справочника.

### ISSUE THREAD

**Issue by Mikadzy** [Pr-Mex/vanessa-automation#825]
> Заполните шаблон обсуждения GIT

```Gherkin
#language: ru
@tree
@ExportScenarios
@IgnoreOnCIMainBuild

Функционал: Проверка функционала создания Тестового справочника  

Как Администратор
Я хочу запустить сценарий тестирования 
Чтобы проверить функционал создания Тестового справочника

Контекст: 
	Дано Я открыл сеанс TestClient от имени "ТестовыйПользователь" с паролем "" или подключаю уже существующий


Сценарий: Проверяется функционал создания Тестового справочника
	
	Закрываем все окна и очищаем сообшения пользователю
		И я закрыл все окна клиентского приложения	
		И я очищаю окно сообщений пользователю
		
	И Я запоминаю значение выражения '"ТестовыйСправочник" + Формат(ТекущаяДата(), "ДФ=дд.ММ")' в переменную "ТестовыйОбъект"
	И Создается тестовый справочник с параметром "ТестовыйОбъект"

    		
```
Здравствуйте. Заранее скажу, что работаю с Ванессой совсем недавно, поэтому вопрос может показаться для Вас простым
Также, разумеется, вместе с данным сценарием был создан собственный шаг, который содержит в себе создание элемента справочника("ТестовыйСправочник"). При выполнении выпадает ошибка  "поле объекта "ТестовыйСправочник" не обнаружено". Проще говоря не видит справочник в системе. 
Не подскажите есть ли какая-то возможность создавать элемент справочника программно?
Для интерактивного добавления кнопка "Создать" не доступна. Заранее спасибо за ответ! 
> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
@Mikadzy 
Вы всегда можете создать элемент программно, если TestManager и TestClient открыты в одной базе.

Либо через расширение вы можете выполнить произвольный код на стороне TestClient.

**Comment by Mikadzy** [comment]
Угу, уже разобрался, пересмотрев урок на канале 1С ещё раз с: Большое спасибо за ответ!
