### ISSUE TITLE
Добавить оставшиеся параметры из json на форму

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#837]
"ВыполнитьСценарии": true,
  "ЗавершитьРаботуСистемы": true,
  "ЗакрытьTestClientПослеЗапускаСценариев": true,

также параметры BuilStatusLog.

**Comment by Pr-Mex** [comment]
Решено.

**Comment by Pr-Mex** [comment]
@nixel2007 
Теперь при сохранении параметров из VA в json должны быть все параметры, необходимые для запуска на CI,

**Comment by nixel2007** [comment]
Супер, спасибо!
