### ISSUE TITLE
Не всегда отрабатывают шаги выделения областей в браузере

### ISSUE THREAD

**Issue by 32960** [Pr-Mex/vanessa-automation#841]
Vanessa Automation Single ver. 1.2.032.4

При записи видео с помощью компоненты VanessaExt шаг: И я показываю подсказку "ТекстПодсказки" EnjoyHint у элемента "ИмяЭлемента" отрабатывает не каждый раз. 
А шаг: И я рисую рамку вокруг нескольких элементов в браузере не отрабатывает.

Ссылка на фича- файл: https://cloud.mail.ru/public/4tRq/3RHdF3joh
Ссылка на видео: https://cloud.mail.ru/public/keLq/25eV3JFo6

**Comment by Pr-Mex** [comment]
@32960 
Проблема ещё актуальна?
