### ISSUE TITLE
Не работает генерация собственных шагов на платформе 8.3.17.1496

### ISSUE THREAD

**Issue by Filippal** [Pr-Mex/vanessa-automation#846]
Vanessa full 1.2.032
Платформа 8.3.17.1496

Не работает генерация собственных шагов.
Не получается ни вывести текст получаемого модуля, ни сгенерировать epf.
Никаких ошибок не вываливается, просто ничего не происходит.

На платформе 8.3.15.1700 и с этой же версией ванессы работает без проблем.

**Comment by Pr-Mex** [comment]
Ок. Проверю у себя на этой же платформе.

**Comment by Pr-Mex** [comment]
@Filippal 
Проверил. Всё работает на 8.3.17.1496.
Возможно у вас не установлена полная версия платформы.

**Comment by Filippal** [comment]
Понял, у меня в конфигурации стоит совместимость с 8.3.12, скорее всего в этом проблема, так как на совместимости 8.3.14 работает создание обработки

**Comment by Pr-Mex** [comment]
Проверил на этих режимах совместимости. У меня также работает. 
@Filippal можете посмотреть в отладка что у вас происходит?

**Comment by Filippal** [comment]
Нашел проблему. Ванесса начала видеть другие обработки, которые лежали в директории и пыталась получить из них сниппеты, но там не было функции ПолучитьСписокТестов. Поэтому в конструкции: 
"Если ПомещаемыеФайлы.Количество() = 0 Тогда
	СделатьGenerateEpfПродолжение();
	Возврат;
КонецЕсли;"
всегда было больше 0.
Решил проблему добавлением функции ПолучитьСписокТестов в те обработки с возвратом пустого массива.
Неясно почему это проявилось на новой платформе

**Comment by Pr-Mex** [comment]
@Filippal 
Можете уточнить что именно вы правили?

**Comment by Filippal** [comment]
В ванессу изменения не вносил.
В КаталогеФич лежит обработка ЗагрузкаВыгрузкаДанныхXML
Я добавил в модуль обработки(которая не собственные шаги) следующий код:

&НаКлиенте
Перем Ванесса;

&НаКлиенте
Функция ПолучитьСписокТестов(КонтекстФреймворкаBDD) Экспорт
	Ванесса = КонтекстФреймворкаBDD;
	ВсеТесты = Новый Массив;
	Возврат ВсеТесты;
КонецФункции

**Comment by Pr-Mex** [comment]
Понятно.
