### ISSUE TITLE
При закрытии клиента тестирования ждать исчезновения процесса по PID

### ISSUE THREAD

**Issue by Pr-Mex** [Pr-Mex/vanessa-automation#852]
Сейчас есть шаг
И я жду когда завершится процесс с ИД процесса "PID" в течение 10 секунд

Но его тогда придётся добавлять после каждого закрытия клиента тестирования.
Лучше сделать ожидание закрытия клиента на уровне движка VA.

**Comment by KrapivinAndrey** [comment]
Интересная задача. Я бы добавил: добивать тестклиент по PID. А то бывает зависнут другие окна на диалогах и тестклиент остается висеть

![image](https://user-images.githubusercontent.com/586025/94516878-3c6ef800-0240-11eb-9c83-2cabaadb8c62.png)

**Comment by Pr-Mex** [comment]
Решено.
