### ISSUE TITLE
Ошибка при генерации epf без управляемой формы

### ISSUE THREAD

**Issue by unichkin** [Pr-Mex/vanessa-automation#857]
> Заполните шаблон обсуждения GIT

```Gherkin
Функционал: генерация epf по фиче с кодом в модуле объекта
   Как Программист
   Я хочу иметь возможность проверки серверной логики, без интерактива

Контекст:
  Дано:  v.1.2.032
  И 1С:Предприятие 8.3 (8.3.14.1854)
  и произвольная конфигурация, тонкий клиент, УФ

Сценарий: требуется проверять только серверную логику
  Допустим: проверяется исполнение шагов бизнес процесса
  Когда: создаю обработку без упр. формы
  Тогда: выдается ошибка "Каталог не обнаружен <ИмяВременногоКаталога>" 

В управляемой форме ванессы добавил условие в стр. 21439:
		Если Объект.ГенерироватьУФ Тогда
			ЗаменитьUIDФайлеОбработки(ПутьКИсходникам + "/" + ИмяОбработки + "/Forms/Форма.xml", "<Form uuid=", Строка(Новый УникальныйИдентификатор));
		КонецЕсли;	

Я ожидал, что после этого для исполнения фичи будет задействован лишь модуль объекта. Но обработка в раннер не подтянулась. Скажите, может я чего не понимаю - можно ли использовать ванессу как аналог xUnit? С упр. формой же будут сплошные вызовы сервера - создать бизнес процесс, стартовать, выполнить задачи. И это только один простой кейс. Все кэширование в клиент-сервере - это неудобно, т.к. надо учитывать сериализацию. А мне допустим захочется внутри сценария одну таблицу значений иметь. И все это гораздо дольше отработает из-за постоянных вызовов сервера.
Повторюсь: я здесь не проверяю интерактив, а хочу некий аналог теста в xUnit.

**Comment by Pr-Mex** [comment]
@unichkin 
Дело в том, что  в подключаемой обработке всё равно должна быть управляемая форма (если мы говорим о запуске VA в УФ), пусть и без шагов.
Я не совсем понимаю что вы хотите получить.
Ведь и так есть возможность вызывать серверный код внутри формы полученной обработки.

**Comment by unichkin** [comment]
"Ведь и так есть возможность вызывать серверный код внутри формы полученной обработки." - это породит кучу КС вызовов, а также добавит приключений по сохранению сериализации контекста. "Массив структур" и т.п. - всего этого можно избежать, если ввести в фреймворк некую режимность: исполнять код только из модуля формы, или исполнять его только из модуля объекта. Возможно, с некой параметризацией. 
Однако, я уже сам пришел к тому, что это видимо невозможно, ибо интерактив... Каждый шаг должен исполняться с клиента, чтобы отобразить прогресс выполнения.
Давайте закроем задачу?

**Comment by Pr-Mex** [comment]
@unichkin Да, итерратор выполнения шагов находится на клиенте. И тогда для вызова серверного кода будут постоянные вызовы сервера.
С другой стороны мы с @DoublesunRUS  обсуждали, что нужна возможность выполнить несколько шагов на сервере за один вызов. Это бы решило вашу задачу?

**Comment by unichkin** [comment]
Я думаю было бы лучше, если в дереве фич была возможность указать контекст исполнения шага. Какую-нибудь галочку "НаСервере", это бы несколько упростило разработку, и сократило объем кода теста. А задача в гите есть? Можете ссылку на ваше обсуждение скинуть? Интересно было бы почитать.

**Comment by DoublesunRUS** [comment]
Сейчас перед сценарием можно указать @OnServer и тогда весь сценарий будет выполняться на сервере.

**Comment by unichkin** [comment]
"сократило объем кода теста." - хотя нет, вызов с клиента все-равно останется, нет, это плохое решение такая галка. Породит новые проблемы с обновлением кода epf, лучше уж как сейчас..
Вот если бы вся фича исполнялась только на сервере, или только на клиенте - было бы лучше. Но как шаги в таком случае обновлять непонятно. Фоновое исполнение отметается, т.к. внешняя обработка, независимая от конфы. В рамках БСП был какой-то хак, для исполнения методов обработки в фоне с отображением этапов в обработке ожидания, но здесь не тот случай.
Несколько шагов на сервере - если в одном серверном вызове, тогда вероятно это имеет смысл. У меня пока хорошего опыта нет, чтобы для себя определиться в этом вопросе.

**Comment by unichkin** [comment]
> Сейчас перед сценарием можно указать @onserver и тогда весь сценарий будет выполняться на сервере.

- т.е. будет использоваться код модуля объекта, а не УФ? Шаги будут обновляться не последовательно, а при окончании теста?

**Comment by unichkin** [comment]
Извините, вопрос не в тему немного. 
Сейчас падает тест при запуске, посомтрел в код - там ищется форма активного приложения. Подскажите пожалуйста - обязательно надо тестовый клиент подключать? Мне ведь не нужен интерактив совершенно, я только логику на сервере проверяю.

**Comment by Pr-Mex** [comment]
> Сейчас перед сценарием можно указать @onserver и тогда весь сценарий будет выполняться на сервере.

Насколько я помню мы с тобой этот тег сделали заранее, и сейчас он не меняет поведение.

**Comment by Pr-Mex** [comment]
> > Сейчас перед сценарием можно указать @onserver и тогда весь сценарий будет выполняться на сервере.
> 
> * т.е. будет использоваться код модуля объекта, а не УФ? Шаги будут обновляться не последовательно, а при окончании теста?

@unichkin 
Да. Обновления состояние дерева не будет пока шаги идут на сервере.
Где расположен текст таких шагов - надо думать отдельно. Наверное да, в модуле объекта обработки.
