### ISSUE TITLE
Пожелание: вывести поле описания известного шага по текущей строке

### ISSUE THREAD

**Issue by unichkin** [Pr-Mex/vanessa-automation#858]
Добрый день. Предлагаю в форме "Известные шаги" добавить ниже таблицы просмотровое поле от узла описания:
![image](https://user-images.githubusercontent.com/10799597/86902023-0d9c2680-c116-11ea-96d5-8aa547ce5cf9.png)

Возможно также стоит сделать и с полем "ИмяФайла". Я бы его выводил перед описанием, а в самой колонке оставлял бы только имя файла, без каталога.

**Comment by Pr-Mex** [comment]
@unichkin 
Да, выводить текст снизу - хорошая идея.!
Насчет имени файла - если его выводить внизу после описания, тогда эту колонку вообще можно скрыть.

Сделаете реквест?

**Comment by unichkin** [comment]
Вы вероятно предлагаете мне поместить эти изменения, но я пока сильно плаваю как в сленге, так и в механике. Ближайшие несколько месяцев буду плотно работать с ванессой, потому уделю этому вопросу время на выходных. Насколько на тек. момент раскопался, многое еще сыровато.. По возможности буду дорабатывать.

**Comment by Pr-Mex** [comment]
@unichkin 
Вот тут описано как поместить изменения в VA. Там всё просто.
https://infostart.ru/public/1092009/

**Comment by Pr-Mex** [comment]
Решено.
