### ISSUE TITLE
Некорректная передача таблиц в экспортные сценарии

### ISSUE THREAD

**Issue by CryptKat** [Pr-Mex/vanessa-automation#859]
VA 1.2.032
При передаче таблиц в экспортный сценарий, они копируются начиная с самого нижнего уровня иерархии, тогда как нужно с верхнего уровня экспортного сценария.

Сделаю PR.

[ВызовЭкспортногоСценария.txt](https://github.com/Pr-Mex/vanessa-automation/files/4890312/default.txt)
[Экспортный.txt](https://github.com/Pr-Mex/vanessa-automation/files/4890313/default.txt)

![photo_2020-07-08_14-20-25](https://user-images.githubusercontent.com/21363661/86912868-65428e00-c126-11ea-88a3-8e10eae7d960.jpg)

**Comment by Pr-Mex** [comment]
Решено.
