### ISSUE TITLE
Пожелание- видеть комментарии в дереве сценариев

### ISSUE THREAD

**Issue by unichkin** [Pr-Mex/vanessa-automation#863]
Ванесса 1.2.032. 
Сейчас загрузил фичу с большим комментарием (текст после #), однако в самом дереве коммент не отобразился.

**Comment by Pr-Mex** [comment]
@unichkin 
Я думаю в свете нового редактора это уже не актуально
https://www.youtube.com/watch?v=cntKcYDRU98&feature=youtu.be
