### ISSUE TITLE
Экранирование любого символа Unicode на клиенте

### ISSUE THREAD

**Issue by Wadus16** [Pr-Mex/vanessa-automation#864]
```Gherkin
Функционал: Экранирование любого символа Unicode
   Как тестировщик
   Я хочу при написании тестов для проверка маркировки использовать в строковых переменных любой символ Unicode

Контекст:
  Дано: <Vanessa Automation 1.2.032>
  И <1C 8.3.16.1063>
  и <1С:ERP Управление предприятием 2 (2.4.11.56)>

Сценарий: я сохраняю в текстовую переменную значение с символами Unicode, которые запрещены в XML
  Допустим: я записываю в текстовую переменную значение "{U+001D}010460081800729921<nY?ZDA{U+001D}8005100000{U+001D}93SFN5{U+001D}24014501206"
  Когда: я сохраненной текстовой переменной заполняю элемент формы 
  Тогда: в этом элементе формы символы {U+001D} переведены в символ Unicode с кодом 001D

```

> Прикладывайте файлы скриншотов

**Comment by Wadus16** [comment]
@Pr-Mex  могу я сделать такой функционал? Мне кажется может другим пригодиться

**Comment by Pr-Mex** [comment]
@Wadus16 
Привет! Опиши подробнее свою проблему?
У тебя в поля надо вставлять нестандартный текст?

Насколько я помню, VA местами использует функцию XMLСтрока(), которая убирает такие символы.

Ты хочешь переделать несколько шагов?

**Comment by Wadus16** [comment]
@Pr-Mex 
есть мобильное приложение на 1С для сканирования штрих-кодов, при сканировании заполняется поле ввода текста, в этом поле ввода могут быть символы, которые запрещены в XML. 
Стоит задача написать тест, который будет имитировать сканирование, т.е. в тесте будет уже готовая строка как-будто отсканированного штрих-кода, в частности Символ(29) (в Unicode 001D). Если в тексте фичи будет текст с таким символом, фича даже не сможет загрузиться, будет ошибка разбора XML.
Т.е. надо сделать так, чтобы в фичах была нужная строка штрих-кода, чтобы фича могла загрузиться без проблем, и чтобы  в результате работы теста в нужное поле ввода могла вставляться строка, в котором есть этот запрещенный символ.
У нас я сделал доработку в функции ванессы 

&НаКлиенте
Функция ПолучитьКорректныйТекстДляВставкиВПоле(Знач Текст) Экспорт
 

перед возвратом вызывается новая функция

Текст = ОбработатьЭкранированныеСимволыUnicode(Текст);

Получается в фичах мы использует строку вида "{U+001D}010460026601339221E28t%Qq{U+001D}8005122000{U+001D}93P37X{U+001D}24010086588{U+001D}"

а потом на клиенте перед самой вставкой этой строки в поле ввода происходит подмена строки {U+001D} на реальный Символ(29). Так у нас все работает как мы ожидаем.

**Comment by Wadus16** [comment]
@Pr-Mex 
функция ОбработатьЭкранированныеСимволыUnicode написана универсально, там просто вырезается шестнадцатеричный код, напимер тот же 001D, переводится в десятичный и подставляется в функцию Символ().

**Comment by Pr-Mex** [comment]
@Wadus16 
Да, давай добавим.

**Comment by Wadus16** [comment]
@Pr-Mex на наших тестах столкнулись с проблемой при включенной настройки эмулировать нажатие кнопок клавиатуры для заиси видеороликов. Проанализировал в отладчике, в типовом коде происходит запись вводимого текста в текстовые файлы с кодировкой windows-1251 и ANSI, в результате чего наши Unicode символы "теряются". Я так понял эти перекодировки в ANSI нужны для удаления BOM символов. Как лучше всего побороть проблему с потерей Unicode? или это будет такая "особенность"?

**Comment by Pr-Mex** [comment]
@Wadus16 
Какую эмуляцию ввода клавиатуры используете? Их есть две.
Через приложение и с помощью компоненты.

**Comment by Wadus16** [comment]
@Pr-Mex  
Мы устанавливаем сервисные утилиты и ставим галку "Эмулировать ввод с клавиатуры"
https://prnt.sc/tto1rd

Я так понял в этом случае используется приложение, так как в отладчике видно, что формируется путь к *.exe файлу.

**Comment by Pr-Mex** [comment]
@Wadus16 
Попробуйте эмуляцию клавиатуры с помощью компоненты.

**Comment by Wadus16** [comment]
@Pr-Mex 
а как ей воспользоваться?

**Comment by Pr-Mex** [comment]
@Wadus16 
![image](https://user-images.githubusercontent.com/8627416/89275083-76f65300-d64a-11ea-9128-1f0e5c3bb0eb.png)
