### ISSUE TITLE
Не работает шаг: "Если элемент "ИмяЭлементаФормы" не присутствует на форме Тогда".

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#868]
Не работает шаг: "Если элемент "ИмяЭлементаФормы" не присутствует на форме Тогда". 

Шаг "Если элемент "ИмяЭлементаФормы" присутствует на форме Тогда" работает.

VA 1.2.032

**Comment by Pr-Mex** [comment]
@egorovsergio 
Нужен DT и сценарий, чтобы это воспроизвести.
Можно скинуть в личку и дать ссылку сюда.

**Comment by KrapivinAndrey** [comment]
Подозреваю что тут 8.3.17+ Сталкивался с таким. Попробую воспроизвести и пришлю данные

**Comment by Pr-Mex** [comment]
> Подозреваю что тут 8.3.17+ Сталкивался с таким. Попробую воспроизвести и пришлю данные

Ок
