### ISSUE TITLE
Внедрение плагина "ИнициаторДанных"

### ISSUE THREAD

**Issue by unichkin** [Pr-Mex/vanessa-automation#895]
Функционал: Внедрение плагина "ИнициаторДанных"
Как Разработчик
Я Хочу: 	
- программно создавать ссылочные объекты при работе сценария
- использовать имена переменных, а также идентификаторы предопределенных данных в качестве указателей на ссылку, при написании сценария
- выполнять проверку заполненности реквизитов, движений, табличных частей, описывая эталон в теле скрипта

Согласовано с @Pr-Mex

**Comment by Pr-Mex** [comment]
Решено.
