### ISSUE TITLE
Не выполняется шаг "И я запоминаю значение таблицы "Таблица1" как "ИмяПеременной"

### ISSUE THREAD

**Issue by egorovsergio** [Pr-Mex/vanessa-automation#909]
Если заголовок колонки таблицы состоит из двух и более слов, то эти слова "склеиваются" и в дальнейшем поиск значений по этой колонке в цикле не выполняется.

Пример сценария
![Screenshot_1](https://user-images.githubusercontent.com/68432407/89801784-4b3b0780-db39-11ea-91a2-da43f209b6a6.png)
 (воспроизводится на демо УТ 11, которую я тебе передавал раньше или https://trade.demo.1c.ru/trade/ru_RU/):

И В командном интерфейсе я выбираю 'Склад и доставка' 'Отгрузка'
Тогда открылось окно 'Отгрузка товаров со склада'
И из выпадающего списка с именем "Склад" я выбираю по строке 'Центральный склад'
И я перехожу к следующему реквизиту
И из выпадающего списка с именем "Помещение" я выбираю точное значение 'Коммерческие товары'
И я перехожу к следующему реквизиту
И в таблице "ПулНоменклатурыОтгрузка" я перехожу к первой строке

И я запоминаю значение таблицы "ПулНоменклатурыОтгрузка" как "ПулНоменклатурыОтгрузка"
        | 'Товар'    |
        | 'Ед. изм.' |

Цикл И для каждого значения "ЗначениеИзТаблицы" из таблицы в памяти "ПулНоменклатурыОтгрузка"
        
        И в таблице "ПулНоменклатурыОтгрузка" я перехожу к строке:
                | 'Товар'   | 'Ед. изм.'   |
                | '$Товар$' | '$Ед. изм.$' |
        
КонецЦикла

**Comment by Pr-Mex** [comment]
@egorovsergio 
Ок, посмотрю.

**Comment by Pr-Mex** [comment]
Решено.

**Comment by Pr-Mex** [comment]
Решено в 1.2.035
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.035
