### ISSUE TITLE
Шаг с датой на конец месяца от определенной даты

### ISSUE THREAD

**Issue by Hupmu** [Pr-Mex/vanessa-automation#913]
Подскажите, пожалуйста, как правильно задать шаг с приводом определенной даты к концу месяца этой даты?
И в поле 'Срок погашения' я ввожу значение выражения "Строка(КонецМесяца('$$Data$$'))"
Как указано выше - не работает
Хотя если ввожу
И в поле 'Срок погашения' я ввожу значение выражения "Строка(КонецМесяца(ТекущаяДата()))" работает, но вводится конец месяца текущей даты, а нужно от конкретной даты.

**Comment by CryptKat** [comment]
Посморти в режиме отладки шаг "я ввожу значение выражения". Посмотри в Shift+F9 значение частей твоего выражения (в частности $$Data$$) на момент его вычисления. Может быть что-то с типом, что КонецМесяца получает НЕ дату, хотя одинарные кавычки есть... Тут только смотреть в отладчике надо.

**Comment by Hupmu** [comment]
Хотелось бы понять, правильно ли так это реализовывать.
Может правильней было бы через:
И затем я выполняю код встроенного языка
	|newdate="$Data$";|
	|Контекст.Вставить("NewData",Строка(КонецМесяца(newdate)));|

**Comment by Hupmu** [comment]
А как зайти в отладку?
Выше у меня уже использовалась подстановка в поле дата документа данная дата и там дата подставилась корректно - 22.06.2020

**Comment by CryptKat** [comment]
> А как зайти в отладку?
> Выше у меня уже использовалась подстановка в поле дата документа данная дата и там дата подставилась корректно - 22.06.2020

https://infostart.ru/1c/articles/974944/#%D0%9E%D1%82%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0_%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B5%D0%B2

**Comment by Hupmu** [comment]
Спасибо за статью.
По отладке, когда идет вычисление выражения, у меня приходит:
Строка(КонецМесяца( ||ПараметрСтрокаА|| ))

**Comment by Pr-Mex** [comment]
Можно так
Строка(КонецМесяца(Контекст.Data))
или
Строка(КонецМесяца(КонтекстСохраняемый.Data))

**Comment by Hupmu** [comment]
Если ввожу 
Строка(КонецМесяца(Контекст.Data))
или
Строка(КонецМесяца(КонтекстСохраняемый.Data))
то выдает - Преобразование значения к типу Дата не может быть выполнено

**Comment by Hupmu** [comment]
Не правильно было введен параметр Data. Теперь выдает, что
Поле объекта не обнаружено (Date)
Смотрю по отладке, где идет определение Контекст, там у меня следующее:
![Контекст](https://user-images.githubusercontent.com/69621332/90238100-0f9c8800-de2e-11ea-857d-2ff76833fe4d.png)
![Выражение](https://user-images.githubusercontent.com/69621332/90238104-10cdb500-de2e-11ea-8590-10670d3c3295.png)

**Comment by Pr-Mex** [comment]
@Hupmu 
Откуда у вас берётся переменная, которую вы хотите использовать?
Или вы не хотите использовать переменные?

**Comment by Hupmu** [comment]
Переменная берется из опер.дня (ОД  в тестовой базе не совпадает с текущим днем)
```
И В командном интерфейсе я выбираю 'Операции' 'Установка Операционного дня'
	Тогда открылось окно 'Установка Операционного дня'
	И из выпадающего списка "Организация" я выбираю точное значение '$UserOrganization$'
	И я запоминаю значение поля 'Текущий' как "Date" 
```

Далее я эту дату использую при создании СЗ, и в поле Дата она проставляется нормально
`И в поле с именем 'Дата' я ввожу текст '$$Date$$  0:00:00'`

а в поле "Срок погашения" нужен последний день месяца от этой даты.
`И в поле 'Срок погашения' я ввожу значение выражения "Строка(КонецМесяца('$$Date$$'))"`
но не работает (

**Comment by CryptKat** [comment]
Без отношения конкретно к вашей проблеме, просто, может помочь:
```
И я запоминаю значение поля с именем "Дата" как "Перем_ДатаДокумента"
И Я запоминаю значение выражения 'Формат(Дата(Сред(Контекст.Перем_ДатаДокумента, 7, 4) + Сред(Контекст.Перем_ДатаДокумента, 4, 2) + Сред(Контекст.Перем_ДатаДокумента, 1, 2)), "Л = ro; ДФ=\'MMMM yyyy\'")' в переменную "Перем_ДатаДокументаДляПечати"
И я вывожу значение переменной "Перем_ДатаДокументаДляПечати"
```

**Comment by CryptKat** [comment]
И зачем используйте по два доллара? Нужно по одному.

**Comment by CryptKat** [comment]
Попробуйте 
`И в поле 'Срок погашения' я ввожу значение выражения 'Строка(КонецМесяца(Дата(Сред(Контекст.Date, 7, 4) + Сред(Контекст.Date, 4, 2) + Сред(Контекст.Date, 1, 2))))'`

**Comment by Hupmu** [comment]
По одному доллару - ошибка та же:
Ошибка компиляции при вычислении выражения или выполнения фрагмента кода.
в указанную строку у меня приходит вместо Строка(КонецМесяца('$$Date$$'))
`Строка(КонецМесяца( ||ПараметрСтрокаА|| ))`

Если вставить, как вы указали выше, то ошибка:
Поле объекта не обнаружено (Date)

То есть он не может определить Контекст.Date. ЧТо у меня туда приходит - выложен скрин выше.

**Comment by Pr-Mex** [comment]
@Hupmu 
Скиньте полный текст сценария, плиз.

**Comment by Hupmu** [comment]
`# ---------------------получаем данные пользователя-----------------------------------
	И В панели разделов я выбираю 'Главное'
	И Я нажимаю кнопку командного интерфейса 'Персональные настройки'
	Тогда открылось окно 'Персональные настройки'
	И я запоминаю значение поля 'Учетная запись' как "UserName" 
	И я запоминаю значение поля 'Основная организация' как "UserOrganization"
	И я запоминаю значение поля 'Основное подразделение' как "UserDepartment" 
	И Я закрываю окно 'Персональные настройки'
	# --------------------------------------------------------------------------
	
	# ----------------получаем текущий операционный день------------------------------
	И В командном интерфейсе я выбираю 'Операции' 'Установка Операционного дня'
	Тогда открылось окно 'Установка Операционного дня'
	И из выпадающего списка "Организация" я выбираю точное значение '$UserOrganization$'
	И я запоминаю значение поля 'Текущий' как "Date" 
	И Я закрываю окно 'Установка Операционного дня'
	И Я запоминаю строку "$Date$" как переменную "Date" глобально
	# -----------------------------------------------------------------------------

# -------------------------создаем СЗ методом копирования----------------------------------
	И В командном интерфейсе я выбираю 'Банк и касса' 'Служебные записки на оплату'
	Тогда открылось окно 'Служебные записки на оплату'
	И в таблице "Список" я активизирую поле "Номер"
	И я нажимаю на кнопку с именем 'ФормаНайти'
	Тогда открылось окно 'Найти'
	И в поле '&Что искать' я ввожу текст '5'
	И я нажимаю на кнопку '&Найти'
	И я выбираю пункт контекстного меню с именем 'СписокКонтекстноеМенюСкопировать' на элементе формы с именем "Список"
	Тогда открылось окно 'Служебная записка на оплату (создание)'
	И в поле с именем 'Дата' я ввожу текст '$$Date$$  0:00:00'
	#И в поле 'Срок погашения' я ввожу значение выражения "Строка(КонецМесяца(Контекст.Date))"
	#И в поле 'Срок погашения' я ввожу значение выражения "Строка(КонецМесяца('$Date$'))"
	И в поле 'Срок погашения' я ввожу значение выражения 'Строка(КонецМесяца(Дата(Сред(Контекст.Date, 7, 4) + Сред(Контекст.Date, 4, 2) + Сред(Контекст.Date, 1, 2))))'`

**Comment by Pr-Mex** [comment]
@Hupmu 
Ок.
Скажите, пожалуйста, на каком шаге в приведённом сценарии происходит падение и дайте полный текст ошибки, пожалуйста.

**Comment by Hupmu** [comment]
Странно, сейчас заработало со строчкой
`И в поле 'Срок погашения' я ввожу значение выражения 'Строка(КонецМесяца(Дата(Сред(Контекст.Date, 7, 4) + Сред(Контекст.Date, 4, 2) + Сред(Контекст.Date, 1, 2))))'`
Спасибо.
А как ее преобразовать, что бы значение бралось не из Контекст.Date, а из 
`И Я запоминаю строку "$Date$" как переменную "Date" глобально`?
Потому что в первом случае надо сценарий начинать сначала, так как, если начинать сразу с этого шага, то он не находит переменную Date в Контексте.

**Comment by Pr-Mex** [comment]
@Hupmu 
Надо заменить
Контекст.
на
КонтекстСохраняемый.

**Comment by Hupmu** [comment]
И как тогда будет? Вот так? Это не одно и тоже?
`И в поле 'Срок погашения' я ввожу значение выражения 'Строка(КонецМесяца(Дата(Сред(КонтекстСохраняемый.Date, 7, 4) + Сред(КонтекстСохраняемый.Date, 4, 2) + Сред(КонтекстСохраняемый.Date, 1, 2))))'`
Или надо где-то раньше определить этот КонтекстСохраняемый?

**Comment by Pr-Mex** [comment]
> И как тогда будет? Вот так? Это не одно и тоже?
> `И в поле 'Срок погашения' я ввожу значение выражения 'Строка(КонецМесяца(Дата(Сред(КонтекстСохраняемый.Date, 7, 4) + Сред(КонтекстСохраняемый.Date, 4, 2) + Сред(КонтекстСохраняемый.Date, 1, 2))))'`
> Или надо где-то раньше определить этот КонтекстСохраняемый?

Да. Так. 
КонтекстСохраняемый - это структура, которая всегда определена.
Когда вы сохраняете переменную "глобально" - то она помещается в эту структуру.
Тоже самое происходит когда вы пишите
И я сохраняю в переменную "$$МояПеременная$$"
