### ISSUE TITLE
Ошибка подключения тест клиента в WEB, если имя подключения содержит скобки

### ISSUE THREAD

**Issue by sergey-dubinin-work** [Pr-Mex/vanessa-automation#915]
Если тест-клиент имеет скобки в имени подключения - то при попытке подключения такого клиента с режиме веб-клиента возникает ошибка:
8/20/2020 11:42:45 AM The session must be launched with the TESTMANAGER key.{(1)}: Error calling constructor (ТестируемоеПриложение): Invalid parameter value (parameter number '3') (Client ID must comply with the name generation rule)

Воспроизводится в vanessa-automation 1.2.033

![image](https://user-images.githubusercontent.com/57937645/90749130-bb851e00-e2db-11ea-9a1b-49c503a0c438.png)

**Comment by Pr-Mex** [comment]
Решено.
