### ISSUE TITLE
Ошибка при выполнении ванесса.sleep(n), вечное ожидание, если в тест клиенте вызван блокирующий интерфейс метод.

### ISSUE THREAD

**Issue by AlexanderNiMo** [Pr-Mex/vanessa-automation#919]
Платформа 8.3.14.1993

Выявлено при запуске sikulix сервера, для подтверждения подписания в сторонней программе, вызванной из 1С блокирующим вызовом.

**Comment by Pr-Mex** [comment]
@AlexanderNiMo 
Можете подробно описать как такое воспроизвести?

**Comment by AlexanderNiMo** [comment]
```
#language: ru

Функционал: Демонстрация ошибки sleep

Как Разработчик
Я хочу чтобы ожидание работало вне зависимости от состояния тест клиента 
Чтобы Иметь возможность корректно использовать функцияю sleep при блокировке сеанса тест клиента

Контекст: 
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: Выполнение блокирующего метода
	
	Когда В панели разделов я выбираю 'Подсистема1'
	И В панели функций я выбираю 'Обработка1'
	Тогда открылось окно 'Обработка1'
	И я нажимаю на кнопку 'Блокирующий метод' 
	Дано я нажимаю ENTER
```


В настройках должно быть включено использование sikulix сервера, для 100% вызова sleep


[Конфа](https://yadi.sk/d/2p5H4XrvFXBr4A) для демонстрации  приложена.

**Comment by Pr-Mex** [comment]
@AlexanderNiMo 
Скажи ещё, пожалуйста, какая версия VA используется?
Проверял это поведение на 8.3.17?

**Comment by AlexanderNiMo** [comment]
VA 1.2.033
На 8.3.17 не проверял.

**Comment by Pr-Mex** [comment]
@AlexanderNiMo можешь проверить на 8.3.17?

**Comment by AlexanderNiMo** [comment]
К сожалению у меня нету в доступе 8.3.17

**Comment by Pr-Mex** [comment]
Добавил опцию, которая регулирует как выполняется sleep()

**Comment by AlexanderNiMo** [comment]
Спасибо!
