### ISSUE TITLE
Не формируется видеоинструкция с шагом - И видеовставка картинки "ИмяКартинки" "ТекстДиктора"

### ISSUE THREAD

**Issue by alk213** [Pr-Mex/vanessa-automation#935]
Добрый день!
Версия используемой Vanessa - 1.2.033
Записываю видеоинструкцию с помощью компоненты - VanessaExt (версия 1.0.9.0). Инструмент для записи использовался VLC и FFmpeg
При использовании шага в фиче - И видеовставка картинки "ИмяКартинки" "ТекстДиктора" - тест успешно выполняется, но видеоинструкция до конца не формируется и нет конечного файла в сборке. (1С работала часов 12 - видеофайл не сформировался)
При закрытии 1С - формируется видеофайл, но только до этого шага.
Пытаюсь запустить заново тест, Vanessa не может удалить временные файлы расположенные по пути \vanessa-automation\tools\VideoTemp
В процессах висит приложение ffmpeg
![image](https://user-images.githubusercontent.com/55937884/92882185-59ba5e80-f418-11ea-9811-e5556ce8ab1c.png)

**Comment by Pr-Mex** [comment]
@alk213 
Скиньте ваше сценарий, пожалуйста.

**Comment by Pr-Mex** [comment]
Не понял что могло работать 12 часов при формировании видео. Это очень много. Должно быть что-то в районе 5 минут.

**Comment by TexnaRRR** [comment]
@Pr-Mex 
Вот такой например сценарий
Контекст:
	И я устанавливаю настройки пользовательского интерфейса и подключаюсь к TestClient
		
		И я подключаю TestClient "ТЕСТ" логин "" пароль ""
		И я активизирую браузер и устанавливаю полноэкранный режим
		И пауза 5
Сценарий: Как найти нужный документ

	#[autodoc.ignorestep]
	И я рисую рамку вокруг элемента панели разделов "Документы и файлы" в браузере
			|'color'  |'red' |
			|'size'   |'3'   |
			|'timeout'|'2000'|	
	#[autodoc.text] В панеле разделов, переходим в раздел документы и файлы	
	И В панели разделов я выбираю 'Документы и файлы'
	
	#[autodoc.text] Открываем внутренние документы 
	И В панели функций я выбираю 'Документы внутренние'
	#[autodoc.text] Первый способ поиска нужного документа  
	И видеовставка картинки "СкринЕще" "Первый способ поиска нужного документа"   

Видеофайл до конца не формируется. А если закрыть 1С-ку то сразу файл сформирован, но до этого шага обрезает все

**Comment by Pr-Mex** [comment]
@TexnaRRR 
Сравните разрешение вашей картинки "СкринЕще" и разрешение, с котором происходит запись видео.
Полагаю проблема в том, что они разные.

**Comment by TexnaRRR** [comment]
@Pr-Mex 
Запись видео - полный экран. Сейчас сделал скриншот в 2 раза меньше и проблема все так же осталась.
Или скриншот нужен с точным разрешением как в видео?

**Comment by Pr-Mex** [comment]
@TexnaRRR 
Скриншот должен в точности совпадать с разрешением, в котором идёт запись видео.
