### ISSUE TITLE
Шаг "И видеоставка картинки"

### ISSUE THREAD

**Issue by TexnaRRR** [Pr-Mex/vanessa-automation#975]
Перед проявлением картинки, появляется темная заставка.
Добавьте пожалуйста параметр, которым можно будет управлять вставкой картинки,
Спасибо!

**Comment by Pr-Mex** [comment]
@TexnaRRR 
Решено.
Для отключения затемнения надо передавать в шаг таблицу
```Gherkin
И видеовставка картинки "ИмяКартинки" "ТекстДиктора"
    |'FadeIn' |'Нет'|
    |'FadeOut'|'Нет'|
```

**Comment by Pr-Mex** [comment]
Решено в 1.2.035
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.035
