### ISSUE TITLE
Не отрабатывает шаг проверки на исключение на английском языке

### ISSUE THREAD

**Issue by Severnity** [Pr-Mex/vanessa-automation#977]
На английском языке не отрабатывает шаг проверки на исключение - выполняется успешно в любом случае. 
Версия VA 1.2.034

When I Check the steps for Exception
        |'In the field named "Name2" I enter the text "TestItem"'|

При запуске на русском языке работает нормально.

**Comment by Pr-Mex** [comment]
@Severnity 
Приложите, пожалуйста, сценарий и базу для воспроизведения ошибки.

**Comment by Pr-Mex** [comment]
@Severnity
Пока закрываю. Приложите пример воспроизведения ошибки, когда он будет.
