### ISSUE TITLE
Невозможно получить состояние формы в веб-интерфейсе, если она генерируется программно

### ISSUE THREAD

**Issue by sergey-dubinin-work** [Pr-Mex/vanessa-automation#978]
```Gherkin
Функционал: Получить состояние формы в веб-клиенте
   Как Тестировщик
   Я хочу Я хочу получить состояние формы в веб клиенте, если она генерируется программно


Контекст:
  Дано: Vanessa Automation 1.2.034
  И 1С:Предприятие 8.3.15.1869 / 8.3.17.1549
  и 1C: Drive

Сценарий: Я открываю Исследователь формы и получаю состояние формы, которая генерируется программно в веб интерфейсе
  Допустим: Приложенная база публикуется на веб-сервере apache
В качестве клиента тестирования используется веб-клиент (браузер Chrome)
  Когда: Я создаю документ Debit note (подсистема Purchases - Return), в реквизите Operation выбираю Purchase return, затем нажимаю на кнопку выбора у реквизита Base
  Тогда: Открывается форма, состояние которой я не могу получить с помощью инструмента Исследователь формы

Объект не имеет собственной формы. Генерируется список значений, форма генерируется программно

```
База: https://drive.google.com/file/d/1g4GlRBzLtzxe0huZHVZoPMylWLsoTX1G/view?usp=sharing
доступ открою по запросу

Скриншот:

![image](https://user-images.githubusercontent.com/57937645/95453867-4a292980-0974-11eb-9d82-5723a6657745.png)
![image](https://user-images.githubusercontent.com/57937645/95453923-6200ad80-0974-11eb-88f6-1bf59b5f01cc.png)

```Gherkin
Также возникают проблемы со взаимодействием с такими формами. 
Например кнопка "ОК" на форме имеет синоним "Button2"

В ходе выполнения сценария некорректно выполняются шаги:

Если элемент "Button2" присутствует на форме Тогда
If "Button2" attribute is present on the form Then
```

**Comment by Pr-Mex** [comment]
@sergey-dubinin-work 
Попробуйте использовать шаг. Платформа должна быть обязательно новая начиная с 8.3.16.
```Gherkin
И я выбираю из списка "Значение"
```

**Comment by sergey-dubinin-work** [comment]
> @sergey-dubinin-work
> Попробуйте использовать шаг. Платформа должна быть обязательно новая начиная с 8.3.16.
> 
> ```
> И я выбираю из списка "Значение"
> ```

Увы, не помогло

![image](https://user-images.githubusercontent.com/57937645/95716312-f2d8d100-0c73-11eb-824c-e64c283f3d74.png)

**Comment by Pr-Mex** [comment]
@sergey-dubinin-work 
У вас в исключении написано, что клиент тестирования не подключен.
Попробуйте с подключенным клиентом тестирования.

**Comment by sergey-dubinin-work** [comment]
> @sergey-dubinin-work
> У вас в исключении написано, что клиент тестирования не подключен.
> Попробуйте с подключенным клиентом тестирования.

![image](https://user-images.githubusercontent.com/57937645/95790994-1ab64c00-0ce9-11eb-84c8-838ffbf1761e.png)

**Comment by Pr-Mex** [comment]
@sergey-dubinin-work 
Написал обход. Доступно в ветке develop. Проверьте, пожалуйста.
Использовать нужно шаг:
И я выбираю из списка "Значение"

**Comment by sergey-dubinin-work** [comment]
@Pr-Mex Есть несколько вопросов
1) Будет ли это работать на 8.3.15 ?
2) Можно ли добавить это исправление в VA 1.2.029 ?
3) Если на последний вопрос ответ да, достаточно ли будет перести вот эти изменения себе?
![image](https://user-images.githubusercontent.com/57937645/96412082-37271c80-11f2-11eb-93dc-f7304e1e3639.png)

**Comment by Pr-Mex** [comment]
@sergey-dubinin-work 
1. Насчёт 8.3.15 - надо проверять.
2 и 3. Да, вы можете попробовать перенести этот код. Но лучше перейти на новую версию. После 1.2.029 было много изменений и исправлений.

**Comment by sergey-dubinin-work** [comment]
Перенёс исправления в VA 1.2.029, на платформе 8.3.15.1869 выбор значения заработал
Искренне благодарю!

**Comment by Pr-Mex** [comment]
@sergey-dubinin-work 
Отлично!
P.S. Вы планируете обновляться?

**Comment by sergey-dubinin-work** [comment]
@Pr-Mex Пока что не планируем, у нас в пайплайне используется VA 1.2.029 и мы не хотели бы вносить изменения в стабильно работающий контур

**Comment by Pr-Mex** [comment]
@sergey-dubinin-work 
Всё же рекомендую запланировать обновление.
Мы перед обновлением прогоняем спец сборку на новой версии VA, чтобы убедиться, что ничего не сломалось.

**Comment by Pr-Mex** [comment]
Решено в 1.2.035
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.035
