### ISSUE TITLE
Не выполняется шаг "I remove checkbox" в веб интерфейсе

### ISSUE THREAD

**Issue by sergey-dubinin-work** [Pr-Mex/vanessa-automation#980]
```Gherkin
Функционал: Убрать чекбокс с формы
   Как тестировщик
   Я хочу иметь возможность снимать чекбокс с формы

Контекст:
  Дано: Vanessa Automation 1.2.034
  И 1С:Предприятие 8.3.15.1869
  и 1C: Drive

Сценарий: Шаг "I remove checkbox"
  Допустим: Приложенная база публикуется на веб-сервере apache
В качестве клиента тестирования используется веб-клиент (браузер Chrome)
  Когда: Я открываю отчёт Stock statement (Warehouse - > Reports) и  выполняю шаг "I remove checkbox "Movement document""
  Тогда: Не снимается галочка с чекбокса

Пробовал "I remove checkbox named..." - результат аналогичный
```

База: https://drive.google.com/file/d/1g4GlRBzLtzxe0huZHVZoPMylWLsoTX1G/view?usp=sharing
доступ открою по запросу

![image](https://user-images.githubusercontent.com/57937645/95568190-9afc5900-0a2c-11eb-8104-b8ae70727d9f.png)

**Comment by Pr-Mex** [comment]
@sergey-dubinin-work 
Попробуйте искать элемент формы по имени, а не по заголовку.

**Comment by sergey-dubinin-work** [comment]
> @sergey-dubinin-work
> Попробуйте искать элемент формы по имени, а не по заголовку.

Пробовал "I remove checkbox named..." - результат аналогичный

**Comment by Pr-Mex** [comment]
@sergey-dubinin-work 
Написал обход. Доступно в ветке develop. Проверьте, пожалуйста.

**Comment by sergey-dubinin-work** [comment]
Перенёс точечно исправления в VA 1.2.029, на платформе 8.3.15.1869 установка флага заработала
Благодарю!

**Comment by Pr-Mex** [comment]
Решено в 1.2.035
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.035
