### ISSUE TITLE
Ошибка при сверке печатной формы с ранее сохраненным макетом

### ISSUE THREAD

**Issue by LexxArh** [Pr-Mex/vanessa-automation#989]
Изначально ошибка появилась в тонком клиенте при сверке выведенного на печать документа с ранее сохраненным макетом при проверке шагом "И Табличный документ "РеквизитТабличныйДокумент" равен макету "ИмяМакета" по шаблону"
![image](https://user-images.githubusercontent.com/54675016/96144177-8e846e80-0f0c-11eb-81b9-44446cc72cef.png)
Однако даже если открыть в 1С ранее сохраненный макет и попробовать сравнить его с самим собой с помощью того же шага - возникает та же самая ошибка

В приложенных файлах имеется как макет, так и короткий сценарий для воспроизведения ошибки.
Необходимо только указать путь к проекту в VA и заменить пути к макету в сценарии
[ОшибкаСравненияМакетов.zip](https://github.com/Pr-Mex/vanessa-automation/files/5385586/default.zip)

Воспроизводится на версии VA 1.2.034
Версия платформы: 8.3.15.1958

**Comment by Pr-Mex** [comment]
@LexxArh 
Начал разбираться.
Зарегистрировал ошибку платформы.

**Comment by Stepa86** [comment]
У меня или аналогичная или даже эта же ошибка. 8.3.17.1851 VA 1.2.035

В `Функция ПолучитьТабличныйДокументTestClient(` происходит попытка получить mxl во временный файл через 

```bsl
ОбъектКонтекстСохраняемый.ТестовоеПриложение.УстановитьРезультатДиалогаВыбораФайла(Истина, ИмяВременногоФайла);
ЭлементФормы.ЗаписатьСодержимоеВФайл();
```

Попытка не успешная. Хотя из тест клиента я могу сохранить из этого элемента табличный документ (но не с первого раза, может в этом причина).

Потом уходит в метод `Функция ТабличныйДокументTestClientПоЯчейкам(` где есть код определения размеров:

```bsl
ПлатформаКорректноОпределяетРазмерМакетаВТонкомКлиенте = Ложь;
	
РазмерОбластиДанныхДокументаПоВертикали   = Неопределено;
РазмерОбластиДанныхДокументаПоГоризонтали = Неопределено;
	
ОпределятьГраницыМакетаWebКлиентаЧерезПереходКОбласти = Истина;
Если ТекущийTestclientЭтоWebКлиент Тогда
	Если Версия8312ИлиВыше И НЕ Версия8313ИлиВыше Тогда
		ОпределятьГраницыМакетаWebКлиентаЧерезПереходКОбласти = Ложь;
	КонецЕсли;	 
	
	Если Версия8313ИлиВыше Тогда
		ОпределятьГраницыМакетаWebКлиентаЧерезПереходКОбласти = Ложь;
		РазмерОбластиДанныхДокументаПоВертикали   = ЭлементФормы.ПолучитьРазмерОбластиДанныхДокументаПоВертикали();
		РазмерОбластиДанныхДокументаПоГоризонтали = ЭлементФормы.ПолучитьРазмерОбластиДанныхДокументаПоГоризонтали();
	КонецЕсли;	 
Иначе	
	Если ПлатформаКорректноОпределяетРазмерМакетаВТонкомКлиенте Тогда
		РазмерОбластиДанныхДокументаПоВертикали   = ЭлементФормы.ПолучитьРазмерОбластиДанныхДокументаПоВертикали();
		РазмерОбластиДанныхДокументаПоГоризонтали = ЭлементФормы.ПолучитьРазмерОбластиДанныхДокументаПоГоризонтали();
	КонецЕсли;	 
КонецЕсли;
```
Причем переменная ПлатформаКорректноОпределяетРазмерМакетаВТонкомКлиенте всегда ложь, т.к. ей ничего не присваивается. А если выполнить `ЭлементФормы.ПолучитьРазмерОбластиДанныхДокументаПоВертикали()` и `ЭлементФормы.ПолучитьРазмерОбластиДанныхДокументаПоГоризонтали()`, то цифры вернутся верные.

Дальше идет заполнение таблицы по ячейкам и по ощущениям там просто идет перебор строк ограниченный значением 100. А в исходном ТаблДоке 53 заполненных строки. И вот все строки с 54 до 100 - пустые. Потом эта таблица уходит на сравнение и в эталоне 53 строки, а в полученной из тестклиента - 100 и вызывается исключение

**Comment by Pr-Mex** [comment]
@Stepa86 
Да, ПлатформаКорректноОпределяетРазмерМакетаВТонкомКлиенте пока выставлено в Ложь, т.к. ещё есть неисправленные проблемы в тонком клиненте. Скоро это будет решено.

**Comment by Pr-Mex** [comment]
Решено для платформ:
8.3.15.2122
8.3.16.1831
8.3.17.1886
8.3.18.1243
и более новых.
