### ISSUE TITLE
Реализация шагов по работе с окном сообщений

### ISSUE THREAD

**Issue by fenixnow** [Pr-Mex/vanessa-automation#996]
Я хочу иметь два шага
1. Помещает текст из окна сообщений в исключение. Пример, в отчете аллюр можно реализовать отображение текста сообщения в тексте исключения. Например, когда текст сообщения не влазиет в окно сообщений. На скрине в таком варианте не видно.
2. Помещать текст сообщения в тепеременную, для того, чтобы можно также было выдавать это в виде исключения но с доп. данными.

**Comment by Pr-Mex** [comment]
Решено в 1.2.035
https://github.com/Pr-Mex/vanessa-automation/releases/tag/1.2.035
